/-
  Consumer specification for the `ds-head` differential / ramification tail.

  WHAT THIS FILE IS
  -----------------
  A written-down *use* of the three ported `ds-head` modules. It is a deliverable
  measure, not a proof obligation, and it is deliberately **not part of any
  library**: nothing globs `spec/`, so it cannot break the verified port's green
  build. Run it by hand:

      cd lean
      lake env lean -DmaxHeartbeats=4000000 -DautoImplicit=false spec/DsHeadConsumer.lean 2>&1 | grep -c error

  The error count is the metric (target 0). No `#check`, no `sorry`.

  HOW TO READ IT
  --------------
  One zone per module/claim. Every zone is a real, executed application, so
  deleting any one of `Differential/Hurwitz.lean`,
  `Differential/Generation.lean` or `Genus/RatFunc.lean` makes this file fail to
  elaborate:

    [hurwitz]      the two headlines of the duplicated pin pair, composed with each
                   other (the `KaehlerDifferential.map` nonvanishing discharges the
                   Hurwitz formula's `hω₀'` hypothesis) and instantiated at the
                   concrete `ℙ¹` differential `dX K`.
    [generation]   the Ω-generation headline at the concrete `P1` place
                   `placeInfty K`.
    [ratfunc]      the `ℙ¹` genus headline and its degree half at the same place
                   `placeInfty K`, consuming `Hurwitz`'s `KaehlerDifferential.map`
                   API in the headline's type.
-/

import FLTForHuman.AlgebraicCurve.Differential.Hurwitz
import FLTForHuman.AlgebraicCurve.Differential.Generation
import FLTForHuman.AlgebraicCurve.Genus.RatFunc
import FLTForHuman.AlgebraicCurve.Defs.KaehlerTranscendental

open AlgebraicCurve
open AlgebraicCurve.RationalFunctionField
open KaehlerDifferential

noncomputable section

/-! ## Zone `[hurwitz]` — the duplicated pair, written once

`Differential/Hurwitz.lean` carries both headlines. The first example is the
`KaehlerDifferential.map` nonvanishing statement; the second composes the two:
the map-nonvanishing headline is exactly the `hω₀'` hypothesis the Hurwitz
formula names, so the pair is applied as one engine. -/

example {K F F' : Type*} [Field K] [Field F] [Field F']
    [Algebra K F] [Algebra K F'] [Algebra F F'] [IsScalarTower K F F']
    [Algebra.IsIntegral F F']
    [IsCurveOver K F] [∀ v : Place K F, v.DCoordGenerates]
    [IsCurveOver K F'] [∀ w : Place K F', w.DCoordGenerates]
    (hreg : ∀ (w : Place K F') (u : F'), u ≠ 0 → w.ord u = 0 →
      w.differentialCoeff (KaehlerDifferential.D K F' u) = 0
        ∨ 0 ≤ w.ord (w.differentialCoeff (KaehlerDifferential.D K F' u)))
    (htame : ∀ w : Place K F', ((w.ramificationIndex F : ℕ) : F') ≠ 0)
    (w₀ : Place K F') {ω₀ : Ω[F⁄K]} (hω₀ : ω₀ ≠ 0) :
    KaehlerDifferential.map K K F F' ω₀ ≠ 0 :=
  map_ne_zero_of_tame hreg htame w₀ hω₀

example {K F F' : Type*} [Field K] [Field F] [Field F']
    [Algebra K F] [Algebra K F'] [Algebra F F'] [IsScalarTower K F F']
    [Algebra.IsIntegral F F']
    [IsCurveOver K F] [∀ v : Place K F, v.DCoordGenerates]
    [IsCurveOver K F'] [∀ w : Place K F', w.DCoordGenerates]
    [HasCanonicalDivisor (K := K) (F := F)] [HasCanonicalDivisor (K := K) (F := F')]
    [FiniteDimensional F F'] [Algebra.IsSeparable F F']
    (hreg : ∀ (w : Place K F') (u : F'), u ≠ 0 → w.ord u = 0 →
      w.differentialCoeff (KaehlerDifferential.D K F' u) = 0
        ∨ 0 ≤ w.ord (w.differentialCoeff (KaehlerDifferential.D K F' u)))
    (htame : ∀ w : Place K F', ((w.ramificationIndex F : ℕ) : F') ≠ 0)
    (w₀ : Place K F') {ω₀ : Ω[F⁄K]} (hω₀ : ω₀ ≠ 0)
    (hK : Divisor.degree (canonicalDivisorOf (K := K) hω₀) = 2 * (genus K F : ℤ) - 2)
    (hK' : Divisor.degree (canonicalDivisorOf (K := K)
        (show KaehlerDifferential.map K K F F' ω₀ ≠ 0
          from map_ne_zero_of_tame hreg htame w₀ hω₀)) = 2 * (genus K F' : ℤ) - 2) :
    2 * (genus K F' : ℤ) - 2
      = (Module.finrank F F' : ℤ) * (2 * (genus K F : ℤ) - 2)
        + ∑ᶠ w : Place K F', ((w.ramificationIndex F : ℤ) - 1) * (w.deg : ℤ) :=
  two_mul_genus_sub_two_eq_of_degree_canonical hreg htame hω₀
    (map_ne_zero_of_tame hreg htame w₀ hω₀) hK hK'

/-! The engine at the concrete `ℙ¹` differential `dX K`: the tame engine's
`differentialCoeff_D_uniformizer_pow` machinery is applied to the uniformizer of a
`RatFunc` place, and the Hurwitz headline's type uses `dX` from `P1/UnitNormalForm`. -/

example (K : Type*) [Field K] :
    (KaehlerDifferential.D K (RatFunc K)) RatFunc.X = dX K := rfl

/-! ## Zone `[generation]` — Ω generated by `dπ` at a concrete `P1` place -/

example (K : Type*) [Field K] [PerfectField K] [DecidableEq (RatFunc K)]
    [Algebra.EssFiniteType K (RatFunc K)] [IsCurveOver K (RatFunc K)]
    {π : RatFunc K} (hπ : (placeInfty K).ord π = 1) {x : RatFunc K}
    (hx : x ∈ (placeInfty K).toValuationSubring) :
    ∃ c : RatFunc K, c ∈ (placeInfty K).toValuationSubring ∧
      KaehlerDifferential.D K (RatFunc K) x
        = c • KaehlerDifferential.D K (RatFunc K) π :=
  exists_mem_D_eq_smul_D_of_isCurveOver (placeInfty K) hπ hx

/-! ## Zone `[ratfunc]` — the `ℙ¹` genus headline

The headline at its wrapper hypotheses, plus its degree half applied to the
concrete `dX K`. -/

example (K : Type*) [Field K] [PerfectField K] [IsCurveOver K (RatFunc K)]
    [HasCanonicalDivisor (K := K) (F := RatFunc K)] : genus K (RatFunc K) = 0 :=
  genus_ratFunc_eq_zero_of_perfectField K

example (K : Type*) [Field K] [PerfectField K] [IsCurveOver K (RatFunc K)]
    {ω : Ω[(RatFunc K)⁄K]} (hω : ω ≠ 0) :
    Divisor.degree (canonicalDivisorOf hω) = -2 :=
  degree_canonicalDivisorOf_ratFunc_of_perfectField_s17 K hω

example (K : Type*) [Field K] [PerfectField K] [IsCurveOver K (RatFunc K)]
    [HasCanonicalDivisor (K := K) (F := RatFunc K)] :
    Divisor.degree (canonicalDivisorOf (K := K) (dX_ne_zero K)) = -2 :=
  degree_canonicalDivisorOf_ratFunc_of_perfectField_s17 K (dX_ne_zero K)

/-! ## Zone `[riders]` — the two small deferred nodes folded in

`Genus/RatFunc.lean` gains the `CharZero` form (a char-zero field is perfect);
`Defs/KaehlerTranscendental.lean` gains the uniqueness of the differential
generator. Each example applies a declaration that exists in exactly one of those
modules. -/

example (K : Type*) [Field K] [CharZero K] [IsCurveOver K (RatFunc K)]
    [HasCanonicalDivisor (K := K) (F := RatFunc K)] : genus K (RatFunc K) = 0 :=
  genus_ratFunc_eq_zero K

example (K : Type*) [Field K] {F : Type*} [Field F] [Algebra K F]
    (x : F) (hx : Transcendental K x)
    [Algebra.IsSeparable (IntermediateField.adjoin K ({x} : Set F)) F]
    (ω : KaehlerDifferential K F) :
    ∃! c : F, ω = c • KaehlerDifferential.D K F x :=
  KaehlerDifferential.exists_unique_smul_D_of_transcendental K x hx ω

/-! ## Zone `[genusff]` — the geometric genus of `ℙ¹` at its closure

`genusFF_ratFunc_eq_zero_of_isAlgClosed` is the deepest node of this set: it
composes the closure landed in `ResidueTheorem/RRAssembly.lean`
(`functionFieldRiemannRoch_of_isAlgClosed_of_isCurveOver`,
`constantsAreBase_of_isAlgClosed`, `genus_eq_genusFF`) with the landed
`genus_ratFunc_eq_zero_of_perfectField`. It takes no hypotheses beyond
`[IsAlgClosed K]`, so the `ℂ` instance is a fully concrete application. -/

example (K : Type*) [Field K] [IsAlgClosed K] : genusFF K (RatFunc K) = 0 :=
  genusFF_ratFunc_eq_zero_of_isAlgClosed K

example : genusFF ℂ (RatFunc ℂ) = 0 :=
  genusFF_ratFunc_eq_zero_of_isAlgClosed ℂ

end
