/-
Equal `j`-invariants of the odd Vélu quotients by `Q` and `Q'` force the cyclic
subgroups generated by `Q` and `Q'` to be equal.

Statement transcribed verbatim from the pinned FLT `aa2d8b3` wrapper
`Theorems/Thm_WeierstrassCurve_zmultiples_eq_of_veluQuotient_j_eq_of_forall_isogenyEndDatum_exists_int.lean`
(28 lines); the proof follows
`P2M/Sol/S_WeierstrassCurve_zmultiples_eq_of_veluQuotient_j_eq_of_forall_isogenyEndDatum_exists_int.lean`
(525 lines; `cmm5_dp_natCard_ker_comp` at 39, `normFormulaAlong_of_elliptic` at 106,
`charZero_addMonoidEnd_point` at 127, `intCast_addMonoidEnd_point_injective` at 155,
`kw_point_infinite` at 162, `kw_nat_card_ker_of_zsmul` at 190, `kw_eq_zero_of_zsmul_eq_zero`
at 211, `Pic0_pushforwardAlongHom_comp` at 230, `pointMapOfPushforward_comp` at 248,
`finrankAlong_eq_one_of_bijective` at 273, `pointMapOfPushforward_injective_of_bijective`
at 287, `kw_veluOddQuotientJInjOnCyclic_of_isogenyEndInt` at 314, `solution` at 510).
Every helper stays `private` at the pin's leaf names; only the headline is public.

The mathematics: over the Hahn-series curve with `[IsAlgClosed]` and `[CharZero]`, every
`IsogenyEndDatum` endomorphism is assumed to be an integer multiple (`hEnd`).  The odd
Vélu quotient maps `φ : W → W/⟨Q⟩` and `φ' : W → W/⟨Q'⟩` have kernels `ℤQ` and `ℤQ'`, and
`hΔ`/`hΔ'` make the quotients elliptic.  Equal `j`-invariants give a variable change, hence
an isomorphism `τ` of function fields; the composite `β = φ ∘ τ` has the same kernel as `φ`.
A dual `ψ'` of `φ'` exists by the `IsogenyHomDatum` factorisation theorem, and the
endomorphism `ψ' ∘ β` of `W` is a scalar `m` by `hEnd`.  A two-sided kernel count forces
`|m| = 2n+1`, and then `β = ±φ'` on the kernel, so `ℤQ = ℤQ'`.

**Substitutions (the four public port-identical rows), imported and not re-proved:**
`normFormulaAlong_of_elliptic` from `IsogenyEndDatum/Engine.lean` (the `[IsAlgClosed F]
[CharZero F]`, `hsep`-free copy — *not* the newly renamed character-free
`normFormulaAlong_of_elliptic_cf` in `Velu/RestrictAlong.lean`),
`charZero_addMonoidEnd_point` and `intCast_addMonoidEnd_point_injective` from
`IsogenyEndDatum/CharPolySquare.lean` (namespace `Ws13S7`), and `kw_point_infinite` from
`Isogeny/NatCard.lean`.  The remaining eight pin helpers are re-derived `private` here,
since no counterpart exists anywhere in the port.

**Proof adaptations, recorded.**  (i) The pin's `S_` file writes the four substituted
helpers inline; here they are the imported declarations above.  (ii) The pin's
`set_option maxHeartbeats 6400000` and `synthInstance.maxHeartbeats 1600000` are dropped;
the port's global cap is `4,000,000` and the node closes under it.  (iii) The pin's
attribute block is not transcribed — none of its names is in the port's cone.  The three
linter suppressions the pin carries (`autoImplicit false`, `linter.unusedVariables false`,
`linter.unusedSectionVars false`) are transcribed, and nothing else.

References (public mirror, pinned):
<https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Theorems/Thm_WeierstrassCurve_zmultiples_eq_of_veluQuotient_j_eq_of_forall_isogenyEndDatum_exists_int.lean>
<https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_WeierstrassCurve_zmultiples_eq_of_veluQuotient_j_eq_of_forall_isogenyEndDatum_exists_int.lean>
-/
import FLTForHuman.AlgebraicCurve.WeilExchange.Transport
import FLTForHuman.WeierstrassCurve.Isogeny.ConditionalCurrency
import FLTForHuman.WeierstrassCurve.Isogeny.NatCard
import FLTForHuman.WeierstrassCurve.Isogeny.PointMapSurjective
import FLTForHuman.WeierstrassCurve.Isogeny.VariableChangeAlgEquiv
import FLTForHuman.WeierstrassCurve.Isogeny.KernelBaseChange
import FLTForHuman.WeierstrassCurve.IsogenyEndDatum.Engine
import FLTForHuman.WeierstrassCurve.IsogenyEndDatum.CharPolySquare
import FLTForHuman.WeierstrassCurve.IsogenyEndDatum.Vocabulary
import FLTForHuman.WeierstrassCurve.GenusOnePlaceGateCentred
import FLTForHuman.WeierstrassCurve.PrincipalDivisors
import FLTForHuman.WeierstrassCurve.Velu.PointMapOddOrder
import FLTForHuman.WeierstrassCurve.Velu.MapEquation
import Mathlib.AlgebraicGeometry.EllipticCurve.IsomOfJ
import Mathlib.RingTheory.HahnSeries.Basic
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.Tactic

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false

noncomputable section

open WeierstrassCurve.Affine AlgebraicCurve

namespace WeierstrassCurve

/-! ### The kernel cardinality of a composite (pin 39–85) -/

private theorem cmm5_dp_natCard_ker_comp {A B C : Type*} [AddCommGroup A] [AddCommGroup B]
    [AddCommGroup C] (f : A →+ B) (g : B →+ C) (hf : Function.Surjective f) :
    Nat.card (AddMonoidHom.ker (g.comp f))
      = Nat.card (AddMonoidHom.ker g) * Nat.card (AddMonoidHom.ker f) := by

  have hmem : ∀ x : AddMonoidHom.ker (g.comp f),
      (f.domRestrict (AddMonoidHom.ker (g.comp f))) x ∈ AddMonoidHom.ker g := by
    intro x
    have hx := x.2
    rw [AddMonoidHom.mem_ker] at hx
    rw [AddMonoidHom.mem_ker]
    exact hx

  have hle : AddMonoidHom.ker f ≤ AddMonoidHom.ker (g.comp f) := by
    intro x hx
    rw [AddMonoidHom.mem_ker] at hx
    rw [AddMonoidHom.mem_ker, AddMonoidHom.comp_apply, hx, map_zero]
  have hφker : Nat.card (AddMonoidHom.ker
        (AddMonoidHom.codRestrict (f.domRestrict (AddMonoidHom.ker (g.comp f)))
          (AddMonoidHom.ker g) hmem))
      = Nat.card (AddMonoidHom.ker f) := by
    rw [AddMonoidHom.ker_codRestrict, AddMonoidHom.ker_domRestrict]
    exact Nat.card_congr (AddSubgroup.addSubgroupOfEquivOfLe hle).toEquiv

  have hφsurj : Function.Surjective
      (AddMonoidHom.codRestrict (f.domRestrict (AddMonoidHom.ker (g.comp f)))
        (AddMonoidHom.ker g) hmem) := by
    intro y
    have hy : g (y : B) = 0 := by
      have h := y.2
      rwa [AddMonoidHom.mem_ker] at h
    obtain ⟨x, hx⟩ := hf (y : B)
    have hxK : x ∈ AddMonoidHom.ker (g.comp f) := by
      rw [AddMonoidHom.mem_ker, AddMonoidHom.comp_apply, hx]
      exact hy
    exact ⟨⟨x, hxK⟩, Subtype.ext hx⟩
  calc Nat.card (AddMonoidHom.ker (g.comp f))
      = Nat.card (AddMonoidHom.ker (g.comp f) ⧸ AddMonoidHom.ker
            (AddMonoidHom.codRestrict (f.domRestrict (AddMonoidHom.ker (g.comp f)))
              (AddMonoidHom.ker g) hmem))
          * Nat.card (AddMonoidHom.ker
            (AddMonoidHom.codRestrict (f.domRestrict (AddMonoidHom.ker (g.comp f)))
              (AddMonoidHom.ker g) hmem)) :=
        AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup _
    _ = Nat.card (AddMonoidHom.ker g) * Nat.card (AddMonoidHom.ker f) := by
        rw [Nat.card_congr
          (QuotientAddGroup.quotientKerEquivOfSurjective _ hφsurj).toEquiv, hφker]

/-! ### Torsion helpers (pin 120–218) -/

section Torsion

universe u

variable {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
variable (W : Affine F) [W.IsElliptic]

variable {W} in

private theorem kw_nat_card_ker_of_zsmul {f : W.Point →+ W.Point} {N : ℤ}
    (hN : N ≠ 0) (hf : ∀ P, f P = N • P) : Nat.card f.ker = N.natAbs ^ 2 := by
  have hsets : ∀ P : W.Point,
      P ∈ f.ker ↔ P ∈ Submodule.torsionBy ℤ W.Point (N.natAbs : ℤ) := by
    intro P
    rw [AddMonoidHom.mem_ker, hf, Submodule.mem_torsionBy_iff]
    constructor
    · intro hP
      rcases Int.natAbs_eq N with h | h
      · rwa [h] at hP
      · rwa [h, neg_zsmul, neg_eq_zero] at hP
    · intro hP
      rcases Int.natAbs_eq N with h | h
      · rw [h]; exact hP
      · rw [h, neg_zsmul, neg_eq_zero]; exact hP
  rw [Nat.card_congr (Equiv.subtypeEquivRight hsets)]
  exact card_torsionBy_eq_sq_of_isAlgClosed W (n := N.natAbs)
    (Nat.cast_ne_zero.mpr (Int.natAbs_ne_zero.mpr hN)) two_ne_zero

variable {W} in

private theorem kw_eq_zero_of_zsmul_eq_zero {N : ℤ} (hN : N ≠ 0) {G : Type*} [AddCommGroup G]
    (δ : W.Point →+ G) (hδ : ∀ P, N • δ P = 0) : δ = 0 := by
  refine AddMonoidHom.ext fun P => ?_
  obtain ⟨R, hR⟩ : ∃ R : W.Point, N • R = P :=
    WeierstrassCurve.Affine.Point.exists_zsmul_eq_of_isAlgClosed W hN P
  rw [← hR, map_zsmul]; exact hδ R

end Torsion

/-! ### Functoriality of the Picard pushforward (pin 220–262) -/

section Functoriality

universe u

variable {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
variable {A B C : Affine F}
  [A.IsElliptic] [GenusOnePlaceGate A] [AbelTheorem A]
  [B.IsElliptic] [GenusOnePlaceGate B] [AbelTheorem B]
  [C.IsElliptic] [GenusOnePlaceGate C] [AbelTheorem C]

private theorem Pic0_pushforwardAlongHom_comp
    (f : B.FunctionField →ₐ[F] A.FunctionField) (hf : f.toRingHom.IsIntegral)
    (hfinf : FiniteAlong F f) (hNf : NormFormulaAlong F f hfinf)
    (g : C.FunctionField →ₐ[F] B.FunctionField) (hg : g.toRingHom.IsIntegral)
    (hfing : FiniteAlong F g) (hNg : NormFormulaAlong F g hfing)
    (hfg : (f.comp g).toRingHom.IsIntegral) (hfinfg : FiniteAlong F (f.comp g))
    (hNfg : NormFormulaAlong F (f.comp g) hfinfg)
    (x : Pic0 F A.FunctionField) :
    Pic0.pushforwardAlongHom g hg hfing hNg (Pic0.pushforwardAlongHom f hf hfinf hNf x)
      = Pic0.pushforwardAlongHom (f.comp g) hfg hfinfg hNfg x := by
  obtain ⟨D, rfl⟩ := Pic0.mk_surjective x
  rw [Pic0.pushforwardAlongHom_mk, Pic0.pushforwardAlongHom_mk, Pic0.pushforwardAlongHom_mk]
  congr 1
  refine Subtype.ext ?_
  rw [Pic0.coe_pushforwardAlongDegZero, Pic0.coe_pushforwardAlongDegZero,
    Pic0.coe_pushforwardAlongDegZero]
  exact Divisor.pushforwardAlong_pushforwardAlong g f hg hf hfg (D : Divisor F A.FunctionField)

private theorem pointMapOfPushforward_comp
    (f : B.FunctionField →ₐ[F] A.FunctionField) (hf : f.toRingHom.IsIntegral)
    (hfinf : FiniteAlong F f) (hNf : NormFormulaAlong F f hfinf)
    (g : C.FunctionField →ₐ[F] B.FunctionField) (hg : g.toRingHom.IsIntegral)
    (hfing : FiniteAlong F g) (hNg : NormFormulaAlong F g hfing)
    (hfg : (f.comp g).toRingHom.IsIntegral) (hfinfg : FiniteAlong F (f.comp g))
    (hNfg : NormFormulaAlong F (f.comp g) hfinfg) (P : A.Point) :
    pointMapOfPushforward (f.comp g) hfg hfinfg hNfg P
      = pointMapOfPushforward g hg hfing hNg (pointMapOfPushforward f hf hfinf hNf P) := by
  have key : ∀ x : Pic0 F B.FunctionField, pointClass (genusOnePic0Equiv B x) = x := fun x => by
    rw [← genusOnePic0Equiv_symm_apply, AddEquiv.symm_apply_apply]
  rw [pointMapOfPushforward_apply, pointMapOfPushforward_apply, pointMapOfPushforward_apply, key,
    Pic0_pushforwardAlongHom_comp f hf hfinf hNf g hg hfing hNg hfg hfinfg hNfg]

end Functoriality

/-! ### Injectivity from bijectivity (pin 264–300) -/

section IsoInjective

universe u

variable {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
variable {A B : Affine F}
  [A.IsElliptic] [GenusOnePlaceGate A] [AbelTheorem A]
  [B.IsElliptic] [GenusOnePlaceGate B] [AbelTheorem B]

private theorem finrankAlong_eq_one_of_bijective (τ : B.FunctionField →ₐ[F] A.FunctionField)
    (hτ : Function.Bijective τ) : finrankAlong F τ = 1 := by
  let := algebraAlong τ
  let σ : B.FunctionField ≃+* A.FunctionField := RingEquiv.ofBijective τ hτ
  let e : A.FunctionField ≃ₗ[B.FunctionField] B.FunctionField :=
    { σ.symm.toAddEquiv with
      map_smul' := fun b x => by
        show σ.symm (b • x) = b * σ.symm x
        rw [Algebra.smul_def, map_mul]
        congr 1
        exact σ.symm_apply_apply b }
  show Module.finrank B.FunctionField A.FunctionField = 1
  rw [e.finrank_eq, Module.finrank_self]

private theorem pointMapOfPushforward_injective_of_bijective
    (τ : B.FunctionField →ₐ[F] A.FunctionField) (hτ : τ.toRingHom.IsIntegral)
    (hfin : FiniteAlong F τ) (hN : NormFormulaAlong F τ hfin) (hbij : Function.Bijective τ) :
    Function.Injective (pointMapOfPushforward τ hτ hfin hN) := by
  have hcard : Nat.card (pointMapOfPushforward τ hτ hfin hN).ker = 1 := by
    rw [natCard_ker_pointMapOfPushforward_eq_finrankAlong A B τ hτ hfin hN,
      finrankAlong_eq_one_of_bijective τ hbij]
  have : Finite (pointMapOfPushforward τ hτ hfin hN).ker :=
    Nat.finite_of_card_ne_zero (by rw [hcard]; exact one_ne_zero)
  have hbot : (pointMapOfPushforward τ hτ hfin hN).ker = ⊥ :=
    AddSubgroup.eq_bot_of_card_eq _ hcard
  exact (AddMonoidHom.ker_eq_bot_iff _).mp hbot

end IsoInjective

/-! ### The engine (pin 314–501) -/

universe u

private theorem kw_veluOddQuotientJInjOnCyclic_of_isogenyEndInt
    {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
    (W : WeierstrassCurve F) [W.IsElliptic]
    [GenusOnePlaceGate W.toAffine] [GenusOnePlaceGate.IsCentred W.toAffine]
    [AbelTheorem W.toAffine]
    (hNs : ∀ D : IsogenyEndDatum W.toAffine, NormFormulaAlong F D.ι D.hfin)
    (hEnd : ∀ D : IsogenyEndDatum W.toAffine, ∃ m : ℤ, ∀ P : W.toAffine.Point,
      D.pointEnd (hNs D) P = m • P)
    (n : ℕ) (Q Q' : W.toAffine.Point)
    (hQ : addOrderOf Q = 2 * n + 1) (hQ' : addOrderOf Q' = 2 * n + 1)
    (hΔ : (W.veluQuotient (W.oddOrderSummingSet Q n)).Δ ≠ 0)
    (hΔ' : (W.veluQuotient (W.oddOrderSummingSet Q' n)).Δ ≠ 0)
    (hj : haveI : (W.veluQuotient (W.oddOrderSummingSet Q n)).IsElliptic :=
        ⟨isUnit_iff_ne_zero.mpr hΔ⟩
      haveI : (W.veluQuotient (W.oddOrderSummingSet Q' n)).IsElliptic :=
        ⟨isUnit_iff_ne_zero.mpr hΔ'⟩
      (W.veluQuotient (W.oddOrderSummingSet Q n)).j
        = (W.veluQuotient (W.oddOrderSummingSet Q' n)).j) :
    AddSubgroup.zmultiples Q = AddSubgroup.zmultiples Q' := by
  classical

  have hell : (W.veluQuotient (W.oddOrderSummingSet Q n)).IsElliptic :=
    ⟨isUnit_iff_ne_zero.mpr hΔ⟩
  have hell' : (W.veluQuotient (W.oddOrderSummingSet Q' n)).IsElliptic :=
    ⟨isUnit_iff_ne_zero.mpr hΔ'⟩
  have : IsDedekindDomain (W.veluQuotient (W.oddOrderSummingSet Q n)).toAffine.CoordinateRing :=
    CoordinateRing.isDedekindDomain (W.veluQuotient (W.oddOrderSummingSet Q n))
  have : IsDedekindDomain (W.veluQuotient (W.oddOrderSummingSet Q' n)).toAffine.CoordinateRing :=
    CoordinateRing.isDedekindDomain (W.veluQuotient (W.oddOrderSummingSet Q' n))
  obtain ⟨gV, hcV, haV⟩ := exists_genusOnePlaceGate_isCentred_and_abelTheorem
    (W := (W.veluQuotient (W.oddOrderSummingSet Q n)).toAffine)
  obtain ⟨gV', hcV', haV'⟩ := exists_genusOnePlaceGate_isCentred_and_abelTheorem
    (W := (W.veluQuotient (W.oddOrderSummingSet Q' n)).toAffine)
  let := gV
  let := gV'
  have := hcV
  have := hcV'
  have := haV
  have := haV'

  obtain ⟨ι, hι, hfin, -, hkerQ⟩ :=
    WeierstrassCurve.exists_veluFunctionFieldHom_pointMapOfPushforward_ker_eq_zmultiples hQ hΔ
  obtain ⟨ι', hι', hfin', -, hkerQ'⟩ :=
    WeierstrassCurve.exists_veluFunctionFieldHom_pointMapOfPushforward_ker_eq_zmultiples hQ' hΔ'

  obtain ⟨C, hC⟩ := WeierstrassCurve.exists_variableChange_of_j_eq
    (W.veluQuotient (W.oddOrderSummingSet Q n))
    (W.veluQuotient (W.oddOrderSummingSet Q' n)) hj
  obtain ⟨σ⟩ : Nonempty ((W.veluQuotient (W.oddOrderSummingSet Q n)).toAffine.FunctionField
      ≃ₐ[F] (W.veluQuotient (W.oddOrderSummingSet Q' n)).toAffine.FunctionField) :=
    hC ▸ WeierstrassCurve.nonempty_functionField_algEquiv_of_variableChange
      (W.veluQuotient (W.oddOrderSummingSet Q n)) C

  set τ : (W.veluQuotient (W.oddOrderSummingSet Q' n)).toAffine.FunctionField
      →ₐ[F] (W.veluQuotient (W.oddOrderSummingSet Q n)).toAffine.FunctionField :=
    σ.symm.toAlgHom with hτ_def
  have hτbij : Function.Bijective τ := σ.symm.bijective
  have hτint : τ.toRingHom.IsIntegral := RingHom.isIntegral_of_surjective _ hτbij.2
  have hτfin : FiniteAlong F τ := finiteAlong_of_surjective τ hτbij.2
  have hNτ : NormFormulaAlong F τ hτfin := normFormulaAlong_of_elliptic τ hτfin

  have hNι : NormFormulaAlong F ι hfin := normFormulaAlong_of_elliptic ι hfin
  have hNι' : NormFormulaAlong F ι' hfin' := normFormulaAlong_of_elliptic ι' hfin'

  have hιτint : (ι.comp τ).toRingHom.IsIntegral := RingHom.IsIntegral.trans _ _ hτint hι
  have hιτfin : FiniteAlong F (ι.comp τ) := finiteAlong_comp τ ι hτfin hfin
  have hNιτ : NormFormulaAlong F (ι.comp τ) hιτfin := normFormulaAlong_of_elliptic _ hιτfin
  set φ := pointMapOfPushforward ι hι hfin hNι with hφ_def
  set φ' := pointMapOfPushforward ι' hι' hfin' hNι' with hφ'_def
  set β := pointMapOfPushforward (ι.comp τ) hιτint hιτfin hNιτ with hβ_def
  have hβ_comp : ∀ P, β P = pointMapOfPushforward τ hτint hτfin hNτ (φ P) := fun P =>
    pointMapOfPushforward_comp ι hι hfin hNι τ hτint hτfin hNτ hιτint hιτfin hNιτ P
  have hτinj := pointMapOfPushforward_injective_of_bijective τ hτint hτfin hNτ hτbij
  have hkerφ : φ.ker = AddSubgroup.zmultiples Q := hkerQ hNι
  have hkerφ' : φ'.ker = AddSubgroup.zmultiples Q' := hkerQ' hNι'
  have hkerβ : β.ker = AddSubgroup.zmultiples Q := by
    rw [← hkerφ]
    refine AddSubgroup.ext fun P => ?_
    rw [AddMonoidHom.mem_ker, AddMonoidHom.mem_ker, hβ_comp]
    refine ⟨fun h => hτinj (h.trans (map_zero _).symm), fun h => ?_⟩
    rw [h, map_zero]

  have hβs : Function.Surjective β :=
    pointMapOfPushforward_surjective W.toAffine _ (ι.comp τ) hιτint hιτfin hNιτ
  have hφ's : Function.Surjective φ' :=
    pointMapOfPushforward_surjective W.toAffine _ ι' hι' hfin' hNι'

  have hNne : ((2 * n + 1 : ℤ) : AddMonoid.End W.toAffine.Point) ≠ 0 := by
    intro h
    have := Ws13S7.intCast_addMonoidEnd_point_injective W.toAffine (h.trans Int.cast_zero.symm)
    omega
  obtain ⟨M, hM⟩ := IsogenyEndDatum.exists_pointEnd_eq_of_mem_isogenyEndSubring hNs
    ((2 * n + 1 : ℤ) : AddMonoid.End W.toAffine.Point) (intCast_mem _ _) hNne
  have hMapp : ∀ P, M.pointEnd (hNs M) P = (2 * n + 1 : ℤ) • P := fun P => by
    rw [hM, AddMonoid.End.intCast_apply]

  let φ'D : IsogenyHomDatum W.toAffine (W.veluQuotient (W.oddOrderSummingSet Q' n)).toAffine :=
    ⟨ι', hι', hfin'⟩
  have hmem_of_ker : ∀ P, φ' P = 0 → (2 * n + 1 : ℤ) • P = 0 := by
    intro P hP
    have hPm : P ∈ AddSubgroup.zmultiples Q' := by rw [← hkerφ']; exact hP
    obtain ⟨k, rfl⟩ := AddSubgroup.mem_zmultiples_iff.mp hPm
    have h21 : (2 * n + 1 : ℤ) • Q' = 0 := by
      have h : ((2 * n + 1 : ℕ) : ℤ) • Q' = 0 := by
        rw [natCast_zsmul, ← hQ', addOrderOf_nsmul_eq_zero]
      exact_mod_cast h
    rw [smul_comm, h21, zsmul_zero]
  obtain ⟨χ, hNχ, hχ⟩ := IsogenyHomDatum.exists_pointHom_comp_eq_of_ker_le_of_isCentred φ'D hNι'
    (IsogenyHomDatum.ofEndDatum M) (hNs M) (fun P hP => by
      show M.pointEnd (hNs M) P = 0
      rw [hMapp]; exact hmem_of_ker P hP)
  set ψ' := χ.pointHom hNχ with hψ'_def
  have hdual₁ : ∀ P, ψ' (φ' P) = (2 * n + 1 : ℤ) • P := fun P => by
    have h := hχ P
    rw [← hMapp P]; exact h
  have hdual₂ : ∀ S, φ' (ψ' S) = (2 * n + 1 : ℤ) • S := fun S => by
    obtain ⟨P, rfl⟩ := hφ's S
    rw [hdual₁, map_zsmul]

  have hDint : ((ι.comp τ).comp χ.ι).toRingHom.IsIntegral :=
    RingHom.IsIntegral.trans _ _ χ.hι hιτint
  let D : IsogenyEndDatum W.toAffine :=
    ⟨(ι.comp τ).comp χ.ι, hDint, finiteAlong_comp χ.ι (ι.comp τ) χ.hfin hιτfin⟩
  have hD : ∀ P, D.pointEnd (hNs D) P = ψ' (β P) := fun P =>
    pointMapOfPushforward_comp (ι.comp τ) hιτint hιτfin hNιτ χ.ι χ.hι χ.hfin hNχ
      hDint D.hfin (hNs D) P
  obtain ⟨m, hm⟩ := hEnd D
  set θ := ψ'.comp β with hθ_def
  have hθm : ∀ P, θ P = m • P := fun P => by
    show ψ' (β P) = m • P
    rw [← hD P]; exact hm P

  have hcardQ' : Nat.card (AddSubgroup.zmultiples Q') = 2 * n + 1 := by
    rw [Nat.card_zmultiples, hQ']
  have hcardQ : Nat.card (AddSubgroup.zmultiples Q) = 2 * n + 1 := by
    rw [Nat.card_zmultiples, hQ]
  have hkerψ' : Nat.card ψ'.ker = 2 * n + 1 := by
    have hcomp : Nat.card (ψ'.comp φ').ker = (2 * n + 1) ^ 2 := by
      have h := kw_nat_card_ker_of_zsmul (W := W.toAffine) (f := ψ'.comp φ')
        (N := (2 * n + 1 : ℤ)) (by omega) (fun P => hdual₁ P)
      have habs : (2 * (n : ℤ) + 1).natAbs = 2 * n + 1 := by omega
      rw [habs] at h; exact h
    have hsplit := cmm5_dp_natCard_ker_comp φ' ψ' hφ's
    rw [hcomp, hkerφ', hcardQ', sq] at hsplit
    exact (Nat.eq_of_mul_eq_mul_right (by omega) hsplit).symm

  have hkerθ : Nat.card θ.ker = (2 * n + 1) ^ 2 := by
    have hsplit := cmm5_dp_natCard_ker_comp β ψ' hβs
    rw [hkerβ, hcardQ, hkerψ'] at hsplit
    rw [hsplit]; ring
  have hmne : m ≠ 0 := by
    intro h0
    have hall : ∀ P, θ P = 0 := fun P => by rw [hθm, h0, zero_zsmul]
    have htop : θ.ker = ⊤ :=
      AddSubgroup.ext fun P => ⟨fun _ => trivial, fun _ => AddMonoidHom.mem_ker.mpr (hall P)⟩
    rw [htop] at hkerθ
    have : Infinite W.toAffine.Point := kw_point_infinite
    simp only [AddSubgroup.card_top, Nat.card_eq_zero_of_infinite] at hkerθ
    exact absurd hkerθ.symm (by positivity)
  have hm_abs : m.natAbs = 2 * n + 1 := by
    have hcard := kw_nat_card_ker_of_zsmul (W := W.toAffine) hmne hθm
    rw [hkerθ, sq, sq] at hcard
    exact (Nat.mul_self_inj).mp hcard.symm

  have hkey : ∀ P, (2 * n + 1 : ℤ) • β P = m • φ' P := fun P => by
    have h1 : φ' (ψ' (β P)) = (2 * n + 1 : ℤ) • β P := hdual₂ (β P)
    have h2 : φ' (θ P) = m • φ' P := by rw [hθm, map_zsmul]
    rw [← h1]; exact h2

  have hmcases : m = (2 * n + 1 : ℤ) ∨ m = -(2 * n + 1 : ℤ) := by
    rcases Int.natAbs_eq m with h | h <;> [left; right] <;> omega
  have hNz : (2 * n + 1 : ℤ) ≠ 0 := by omega
  have hkerβ' : β.ker = AddSubgroup.zmultiples Q' := by
    rcases hmcases with hm' | hm'
    · have hδ : β - φ' = 0 :=
        kw_eq_zero_of_zsmul_eq_zero (W := W.toAffine) hNz (β - φ') fun P => by
          rw [AddMonoidHom.sub_apply, smul_sub, hkey P, hm', sub_self]
      have heq : β = φ' := sub_eq_zero.mp hδ
      rw [heq]; exact hkerφ'
    · have hδ : β + φ' = 0 :=
        kw_eq_zero_of_zsmul_eq_zero (W := W.toAffine) hNz (β + φ') fun P => by
          rw [AddMonoidHom.add_apply, smul_add, hkey P, hm', ← add_smul, neg_add_cancel,
            zero_smul]
      have heq : β = -φ' := eq_neg_iff_add_eq_zero.mpr hδ
      rw [heq, ← hkerφ']
      exact AddSubgroup.ext fun P => by
        simp only [AddMonoidHom.mem_ker, AddMonoidHom.neg_apply, neg_eq_zero]
  exact hkerβ.symm.trans hkerβ'

/-! ### The headline -/

/-- **Equal Vélu-quotient `j`-invariants force equal cyclic subgroups.**  Verbatim from
`Theorems/Thm_WeierstrassCurve_zmultiples_eq_of_veluQuotient_j_eq_of_forall_isogenyEndDatum_exists_int.lean`. -/
theorem zmultiples_eq_of_veluQuotient_j_eq_of_forall_isogenyEndDatum_exists_int
    [DecidableEq (HahnSeries ℚ (AlgebraicClosure ℚ))] [CharZero (HahnSeries ℚ (AlgebraicClosure ℚ))]
    [IsAlgClosed (HahnSeries ℚ (AlgebraicClosure ℚ))]
    (W : WeierstrassCurve (HahnSeries ℚ (AlgebraicClosure ℚ))) [W.IsElliptic]
    [GenusOnePlaceGate W.toAffine] [GenusOnePlaceGate.IsCentred W.toAffine] [AbelTheorem W.toAffine]
    (hNs : ∀ D : IsogenyEndDatum W.toAffine, NormFormulaAlong (HahnSeries ℚ (AlgebraicClosure ℚ)) D.ι D.hfin)
    (hEnd : ∀ D : IsogenyEndDatum W.toAffine, ∃ m : ℤ, ∀ P : W.toAffine.Point, D.pointEnd (hNs D) P = m • P)
    (n : ℕ) (Q Q' : W.toAffine.Point)
    (hQ : addOrderOf Q = 2 * n + 1) (hQ' : addOrderOf Q' = 2 * n + 1)
    (hΔ : (W.veluQuotient (W.oddOrderSummingSet Q n)).Δ ≠ 0)
    (hΔ' : (W.veluQuotient (W.oddOrderSummingSet Q' n)).Δ ≠ 0)
    (hj : haveI : (W.veluQuotient (W.oddOrderSummingSet Q n)).IsElliptic := ⟨isUnit_iff_ne_zero.mpr hΔ⟩
      haveI : (W.veluQuotient (W.oddOrderSummingSet Q' n)).IsElliptic := ⟨isUnit_iff_ne_zero.mpr hΔ'⟩
      (W.veluQuotient (W.oddOrderSummingSet Q n)).j = (W.veluQuotient (W.oddOrderSummingSet Q' n)).j) :
    AddSubgroup.zmultiples Q = AddSubgroup.zmultiples Q' :=
  kw_veluOddQuotientJInjOnCyclic_of_isogenyEndInt W hNs hEnd n Q Q' hQ hQ' hΔ hΔ' hj

end WeierstrassCurve

end
