/-
  Layer 0b — the level-`N` function field of `X(N)`: the Fricke generators and the
  `ℂ`-subalgebra of `ℍ → ℂ` they generate.

  `ModularCurve.LevelN.ring N` is generated by the Hauptmodul `jAnalytic` and the Fricke
  functions `fricke N v = -(E₄ E₆ / Δ) / 2592 · ℘_N(v)`, where `wp N v τ` is the
  Weierstrass `℘`-function of the period pair `ofTau τ` at the `N`-tortion point
  `(v 0 · τ + v 1) / N`. Its fraction field is the field of modular functions of level
  `N`, on which `SL(2, ℤ)` acts with kernel `Γ(N) ⊔ ±1` (the rows of
  `topics/modularCurve/WORKORDER-A-levelN-field.md`).

  This is the whole definition layer subject A needs: the eight ready `LevelN` rows
  import this module and nothing else new.

  FLT provenance, pinned `aa2d8b3`:
  `Definitions/Def_ModularCurve_LevelNFunctionField.lean` lines 1–53, ported whole,
  statements verbatim (binders as the pin writes them).
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_LevelNFunctionField.lean

  `PeriodPair`, `PeriodPair.ofTau` and `PeriodPair.weierstrassP` are the port's
  (`FLTForHuman/Elliptic/PeriodPair/Basic.lean`, mathlib
  `Mathlib/Analysis/SpecialFunctions/Elliptic/Weierstrass.lean`). The pin's `E₄`, `E₆`,
  `discriminant` are mathlib's `ModularForm.*`.
-/
import FLTForHuman.Elliptic.PeriodPair.Basic
import Mathlib.Analysis.SpecialFunctions.Elliptic.Weierstrass
import Mathlib.NumberTheory.ModularForms.Discriminant
import Mathlib.NumberTheory.ModularForms.LevelOne.Basic

set_option autoImplicit false

noncomputable section

open UpperHalfPlane

open scoped MatrixGroups

namespace ModularCurve.LevelN

def wp (N : ℕ) (v : Fin 2 → ZMod N) (τ : ℍ) : ℂ :=
  ((2 * (Real.pi : ℂ) * Complex.I) ^ 2)⁻¹ *
    PeriodPair.weierstrassP (PeriodPair.ofTau τ)
      ((((v 0).val : ℂ) * (τ : ℂ) + ((v 1).val : ℂ)) / (N : ℂ))

def fricke (N : ℕ) (v : Fin 2 → ZMod N) (τ : ℍ) : ℂ :=
  -(ModularForm.E₄ τ * ModularForm.E₆ τ / ModularForm.discriminant τ) / 2592 * wp N v τ

def jAnalytic (τ : ℍ) : ℂ :=
  ModularForm.E₄ τ ^ 3 / ModularForm.discriminant τ

def generators (N : ℕ) : Set (ℍ → ℂ) :=
  insert jAnalytic {g : ℍ → ℂ | ∃ v : Fin 2 → ZMod N, v ≠ 0 ∧ g = fricke N v}

def ring (N : ℕ) : Subalgebra ℂ (ℍ → ℂ) :=
  Algebra.adjoin ℂ (generators N)

theorem jAnalytic_mem_generators (N : ℕ) : jAnalytic ∈ generators N :=
  Set.mem_insert _ _

theorem fricke_mem_generators (N : ℕ) {v : Fin 2 → ZMod N} (hv : v ≠ 0) :
    fricke N v ∈ generators N :=
  Set.mem_insert_of_mem _ ⟨v, hv, rfl⟩

theorem jAnalytic_mem (N : ℕ) : jAnalytic ∈ ring N :=
  Algebra.subset_adjoin (jAnalytic_mem_generators N)

theorem fricke_mem (N : ℕ) {v : Fin 2 → ZMod N} (hv : v ≠ 0) : fricke N v ∈ ring N :=
  Algebra.subset_adjoin (fricke_mem_generators N hv)

def jGen (N : ℕ) : ring N :=
  ⟨jAnalytic, jAnalytic_mem N⟩

@[simp]
theorem coe_jGen (N : ℕ) : ((jGen N : ring N) : ℍ → ℂ) = jAnalytic :=
  rfl

end ModularCurve.LevelN

end
