/-
The automorphism lifting of `ModularCurve.exists_algEquiv_laurentBaseChange_cover`
(pin `P2M/Sol/S_ModularCurve_exists_algEquiv_laurentBaseChange_cover.lean`,
423 raw / 281 content).

**Route chosen: the tensor-product route (scout option (ii)).** The pin proves the
general-`L` statement (`[Field L] [Algebra ℚ L]`, no algebraicity) by the `S3d`/
`S4H` construction — an abstract `Algebra.adjoin K (Set.range φ)` automorphism
built from a `ℚ`-basis, extended by `IsFractionRing.algEquivOfAlgEquiv` and fed
the transfer `S4A.linearIndependent_coeffEmb` (whose `S4C` module-instance shim
is v4.34 API drift). The port instead uses the already-ported `baseChangeHom`:

* `baseChangeHom L F₀ : L ⊗[ℚ] F₀ →ₐ[L] LaurentSeries L` has range exactly
  `Algebra.adjoin L (Set.range φ₀)` (`φ₀ = coeffEmb L ∘ F₀.subtype`), so
  `codRestrict` + injectivity makes it an `L`-algebra equivalence onto that
  subalgebra;
* `Algebra.TensorProduct.congr (AlgEquiv.refl L) σ` transports `σ` across the
  tensor product, and conjugating by the equivalence gives an `L`-automorphism of
  `Algebra.adjoin L (Set.range φ₀)`;
* the scoped mathlib instance
  `IsFractionRing (Algebra.adjoin L S) (IntermediateField.adjoin L S)` plus
  `IsFractionRing.algEquivOfAlgEquiv` extends it to `laurentBaseChange L F₀`.

The bare `≃+*` `σ₀` is upgraded to `F₀ ≃ₐ[ℚ] F₀` first (`ℚ` is prime, so
`ℚ →+* F₀` is a subsingleton), which is what makes the tensor-product congr
applicable. No `[Algebra.IsAlgebraic ℚ L]` is used.

FLT provenance, pinned `aa2d8b3`:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_ModularCurve_exists_algEquiv_laurentBaseChange_cover.lean
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Theorems/Thm_ModularCurve_exists_algEquiv_laurentBaseChange_cover.lean
-/
import FLTForHuman.ModularCurve.Defs.GeometricBaseChange
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.TensorProduct.Maps

set_option autoImplicit false

noncomputable section

open scoped TensorProduct
open scoped IntermediateField.algebraAdjoinAdjoin

namespace ModularCurve

section Cover

variable (L : Type*) [Field L] [Algebra ℚ L]
variable (F₀ : IntermediateField ℚ (LaurentSeries ℚ))

/-- The coefficient embedding restricted to `F₀`. -/
private abbrev φ₀ : F₀ →+* LaurentSeries L := (coeffEmb L).comp (SubringClass.subtype F₀)

private theorem φ₀_apply (y : F₀) : φ₀ L F₀ y = coeffEmb L (y : LaurentSeries ℚ) := rfl

private theorem range_φ₀ :
    Set.range (φ₀ L F₀) = ⇑(coeffEmb L) '' (F₀ : Set (LaurentSeries ℚ)) := by
  ext x
  constructor
  · rintro ⟨y, rfl⟩
    exact ⟨y, y.2, rfl⟩
  · rintro ⟨a, ha, rfl⟩
    exact ⟨⟨a, ha⟩, rfl⟩

private theorem laurentBaseChange_eq_adjoin :
    laurentBaseChange L F₀ = IntermediateField.adjoin L (Set.range (φ₀ L F₀)) := by
  rw [range_φ₀]
  rfl

/-- The `L`-subalgebra generated by the coefficient image of `F₀`: the range of
`baseChangeHom`. -/
private abbrev Rg : Subalgebra L (LaurentSeries L) := Algebra.adjoin L (Set.range (φ₀ L F₀))

private theorem baseChangeHom_mem_Rg (x : L ⊗[ℚ] F₀) : baseChangeHom L F₀ x ∈ Rg L F₀ := by
  induction x using TensorProduct.inductionOn with
  | tmul c f =>
      rw [baseChangeHom_tmul]
      exact mul_mem (Subalgebra.algebraMap_mem _ c)
        (Algebra.subset_adjoin (Set.mem_range_self f))
  | add x y hx hy => rw [map_add]; exact add_mem hx hy

/-- `baseChangeHom` corestricted to its range, the subalgebra `Rg`. -/
private def beta : L ⊗[ℚ] F₀ →ₐ[L] Rg L F₀ :=
  (baseChangeHom L F₀).codRestrict (Rg L F₀) (baseChangeHom_mem_Rg L F₀)

private theorem beta_injective : Function.Injective (beta L F₀) := fun _ _ h =>
  baseChangeHom_injective L F₀ (Subtype.ext_iff.mp h)

private theorem range_baseChangeHom : (baseChangeHom L F₀).range = Rg L F₀ := by
  refine le_antisymm ?_ ?_
  · rintro y ⟨x, rfl⟩
    exact baseChangeHom_mem_Rg L F₀ x
  · rw [Rg, Algebra.adjoin_le_iff]
    rintro _ ⟨y, rfl⟩
    exact ⟨1 ⊗ₜ[ℚ] y, by simp [φ₀_apply]⟩

private theorem beta_surjective : Function.Surjective (beta L F₀) := by
  intro a
  have ha : (a : LaurentSeries L) ∈ (baseChangeHom L F₀).range := by
    rw [range_baseChangeHom]
    exact a.2
  obtain ⟨x, hx⟩ := ha
  exact ⟨x, Subtype.ext (by simpa [beta] using hx)⟩

/-- The tensor-product model of the range of `baseChangeHom`. -/
private def e : L ⊗[ℚ] F₀ ≃ₐ[L] Rg L F₀ :=
  AlgEquiv.ofBijective (beta L F₀) ⟨beta_injective L F₀, beta_surjective L F₀⟩

private theorem e_one_tmul (y : F₀) :
    e L F₀ (1 ⊗ₜ[ℚ] y) = ⟨φ₀ L F₀ y, Algebra.subset_adjoin (Set.mem_range_self y)⟩ := by
  apply Subtype.ext
  simp [e, beta, AlgHom.coe_codRestrict, φ₀_apply]

/-- Transport of `σ` to the range subalgebra `Rg`. -/
private def rho (σ : F₀ ≃ₐ[ℚ] F₀) : Rg L F₀ ≃ₐ[L] Rg L F₀ :=
  (e L F₀).symm.trans
    ((Algebra.TensorProduct.congr (AlgEquiv.refl : L ≃ₐ[L] L) σ).trans (e L F₀))

private theorem rho_apply_gen (σ : F₀ ≃ₐ[ℚ] F₀) (y : F₀) :
    rho L F₀ σ ⟨φ₀ L F₀ y, Algebra.subset_adjoin (Set.mem_range_self y)⟩ =
      ⟨φ₀ L F₀ (σ y), Algebra.subset_adjoin (Set.mem_range_self (σ y))⟩ := by
  have h2 : (Algebra.TensorProduct.congr (AlgEquiv.refl : L ≃ₐ[L] L) σ) (1 ⊗ₜ[ℚ] y)
      = 1 ⊗ₜ[ℚ] σ y := by
    rw [Algebra.TensorProduct.congr_apply, Algebra.TensorProduct.map_tmul]
    simp
  rw [rho, AlgEquiv.trans_apply, AlgEquiv.trans_apply, ← e_one_tmul L F₀ y,
    AlgEquiv.symm_apply_apply, h2]
  exact e_one_tmul L F₀ (σ y)

/-- The abstract cover: an `L`-automorphism of any intermediate field that is
`IntermediateField.adjoin L (Set.range φ₀)` acting as `σ` on the coefficient
image of `F₀`. -/
private theorem exists_cover_adjoin (σ : F₀ ≃ₐ[ℚ] F₀) (M : IntermediateField L (LaurentSeries L))
    (hM : M = IntermediateField.adjoin L (Set.range (φ₀ L F₀))) :
    ∃ τ : M ≃ₐ[L] M, ∀ y : F₀,
      ((τ ⟨φ₀ L F₀ y, hM ▸ IntermediateField.subset_adjoin L _ (Set.mem_range_self y)⟩ : M) :
          LaurentSeries L) = φ₀ L F₀ (σ y) := by
  subst hM
  refine ⟨IsFractionRing.algEquivOfAlgEquiv (R := L) (A := Rg L F₀) (B := Rg L F₀)
    (K := IntermediateField.adjoin L (Set.range (φ₀ L F₀)))
    (L := IntermediateField.adjoin L (Set.range (φ₀ L F₀))) (rho L F₀ σ), fun y => ?_⟩
  have key : ((IsFractionRing.algEquivOfAlgEquiv (R := L) (A := Rg L F₀) (B := Rg L F₀)
      (K := IntermediateField.adjoin L (Set.range (φ₀ L F₀)))
      (L := IntermediateField.adjoin L (Set.range (φ₀ L F₀))) (rho L F₀ σ))
        (algebraMap (Rg L F₀) (IntermediateField.adjoin L (Set.range (φ₀ L F₀)))
          ⟨φ₀ L F₀ y, Algebra.subset_adjoin (Set.mem_range_self y)⟩) : LaurentSeries L)
      = φ₀ L F₀ (σ y) := by
    rw [IsFractionRing.algEquivOfAlgEquiv_algebraMap, rho_apply_gen]
    rfl
  exact key

end Cover

/-- Any ring automorphism of `F₀` is a `ℚ`-algebra automorphism (`ℚ` is prime). -/
private def ratAlgEquiv {F₀ : IntermediateField ℚ (LaurentSeries ℚ)} (σ₀ : ↥F₀ ≃+* ↥F₀) :
    F₀ ≃ₐ[ℚ] F₀ :=
  AlgEquiv.ofRingEquiv (f := σ₀) fun c =>
    RingHom.congr_fun (Subsingleton.elim ((σ₀ : ↥F₀ →+* ↥F₀).comp (algebraMap ℚ ↥F₀))
      (algebraMap ℚ ↥F₀)) c

theorem exists_algEquiv_laurentBaseChange_cover
    (L : Type*) [Field L] [Algebra ℚ L] (F₀ : IntermediateField ℚ (LaurentSeries ℚ))
    (σ₀ : ↥F₀ ≃+* ↥F₀) :
    ∃ τ : ↥(laurentBaseChange L F₀) ≃ₐ[L] ↥(laurentBaseChange L F₀),
      ∀ y : ↥F₀,
        ((τ ⟨coeffEmb L (y : LaurentSeries ℚ),
              coeffEmb_mem_laurentBaseChange L y.2⟩ :
            ↥(laurentBaseChange L F₀)) : LaurentSeries L)
          = coeffEmb L ((σ₀ y : ↥F₀) : LaurentSeries ℚ) := by
  obtain ⟨τ, hτ⟩ :=
    exists_cover_adjoin L F₀ (ratAlgEquiv σ₀) (laurentBaseChange L F₀)
      (laurentBaseChange_eq_adjoin L F₀)
  refine ⟨τ, fun y => ?_⟩
  have h1 : (⟨φ₀ L F₀ y,
        laurentBaseChange_eq_adjoin L F₀ ▸ IntermediateField.subset_adjoin L _ (Set.mem_range_self y)⟩ :
        laurentBaseChange L F₀) =
      ⟨coeffEmb L (y : LaurentSeries ℚ), coeffEmb_mem_laurentBaseChange L y.2⟩ :=
    Subtype.ext rfl
  rw [← h1]
  have h2 := hτ y
  rw [show (ratAlgEquiv σ₀) y = σ₀ y from rfl] at h2
  simpa [φ₀_apply] using h2

end ModularCurve

end
