/-
X₁'s function-field and Jacobian vocabulary — the missing remainder of FLT's
`Definitions/Def_ModularCurve_X1.lean`
(<https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_X1.lean>).

The pin's `FunctionField` block (lines 66–126) is split: `intSeriesC`,
`intFormRatiosC`, `mem_intFormRatiosC`, `qExpFunctionFieldC`,
`intFormRatiosC_subset` and `div_mem_qExpFunctionFieldC` were already ported in
`ModularCurve/JqIntegralRatios.lean` (with the `Restrict` block's
`restrictForm`/`coe_restrictForm`/`restrictForm_apply`); this module adds the
three `Set`/`IntermediateField` monotonicity lemmas (pin 95, 116, 124), the
`LevelOne` block (pin 130–176) and the `Jacobian` abbreviations (pin 178–214).

Deferred with `SET-X1-A`'s boundary (recorded by the manager): the three
`JOne.torsionGaloisRep` declarations (pin 192–207) need the unported
`Pic0`/`SemilinearAut` torsion-action block
(`Def_AlgebraicCurve_BaseChangeGalois.lean:206–356` plus
`Def_ModularCurve_ArithmeticGalois.lean:85–105`).

FLT provenance, pinned `aa2d8b3`:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_X1.lean
-/
import FLTForHuman.ModularCurve.JqIntegralRatios
import FLTForHuman.ModularCurve.Defs.Laurent
import FLTForHuman.AlgebraicCurve.Defs.Divisor
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure

set_option autoImplicit false

noncomputable section

open UpperHalfPlane IntermediateField HahnSeries AlgebraicCurve CongruenceSubgroup

open scoped MatrixGroups

namespace ModularCurve

/-! ## The remainder of the pin's `FunctionField` block -/

section FunctionField

variable (K : Type*) [Field K] (Γ : Subgroup SL(2, ℤ))

/-- The constant `1` is a ratio of integral `q`-expansions (of the constant form
`1` in weight `0`). -/
theorem one_mem_intFormRatiosC : (1 : LaurentSeries K) ∈ intFormRatiosC K Γ := by
  refine ⟨0, 1, 1, 1, 1, ?_, ?_, by simp, by simp⟩ <;>
  · show IsIntegralQExp (⇑(1 : ModularForm (Γ : Subgroup (GL (Fin 2) ℝ)) 0)) 1
    rw [ModularForm.one_coe_eq_one, IsIntegralQExp, map_one, qExpansion_one]

variable {Γ} in

theorem intFormRatiosC_mono {Γ' : Subgroup SL(2, ℤ)} (h : Γ' ≤ Γ) :
    intFormRatiosC K Γ ⊆ intFormRatiosC K Γ' := by
  rintro x ⟨k, f, g, pf, pg, hf, hg, hg0, rfl⟩
  have h' : (Γ' : Subgroup (GL (Fin 2) ℝ)) ≤ (Γ : Subgroup (GL (Fin 2) ℝ)) := Subgroup.map_mono h
  exact ⟨k, restrictForm h' f, restrictForm h' g, pf, pg, hf, hg, hg0, rfl⟩

variable {Γ} in

theorem qExpFunctionFieldC_mono {Γ' : Subgroup SL(2, ℤ)} (h : Γ' ≤ Γ) :
    qExpFunctionFieldC K Γ ≤ qExpFunctionFieldC K Γ' :=
  IntermediateField.adjoin.mono K _ _ (intFormRatiosC_mono K h)

end FunctionField

/-! ## The `LevelOne` block -/

section LevelOne

variable (K : Type*) [Field K] (M : ℕ)

/-- X₁'s `q`-expansion function field: the ratios of integral `q`-expansions of
forms for `Γ₁(M)`. -/
def x1FunctionFieldC : IntermediateField K (LaurentSeries K) :=
  qExpFunctionFieldC K (Gamma1 M)

abbrev x1FunctionField : IntermediateField ℚ (LaurentSeries ℚ) :=
  x1FunctionFieldC ℚ M

theorem x1FunctionFieldC_rat : x1FunctionFieldC ℚ M = x1FunctionField M := rfl

/-- The field generated by ratios of integral `q`-expansions of forms for
`Γ₁(M) ⊓ Γ₀(t)`. -/
def x1x0FunctionFieldC (t : ℕ) : IntermediateField K (LaurentSeries K) :=
  qExpFunctionFieldC K (Gamma1 M ⊓ Gamma0 t)

theorem x1FunctionFieldC_le_x1x0 (t : ℕ) : x1FunctionFieldC K M ≤ x1x0FunctionFieldC K M t :=
  qExpFunctionFieldC_mono K inf_le_left

theorem x1x0FunctionFieldC_one : x1x0FunctionFieldC K M 1 = x1FunctionFieldC K M := by
  have : Gamma1 M ⊓ Gamma0 1 = Gamma1 M := by
    refine le_antisymm inf_le_left (le_inf le_rfl ?_)
    intro A _
    rw [Gamma0_mem]
    exact Subsingleton.elim _ _
  rw [x1x0FunctionFieldC, this, x1FunctionFieldC]

variable {M} in

theorem Gamma1_le_of_dvd {M' : ℕ} (h : M ∣ M') : Gamma1 M' ≤ Gamma1 M := by
  intro A hA
  rw [Gamma1_mem] at hA ⊢
  obtain ⟨h00, h11, h10⟩ := hA
  refine ⟨?_, ?_, ?_⟩
  · have := congrArg (ZMod.castHom h (ZMod M)) h00
    rwa [map_intCast, map_one] at this
  · have := congrArg (ZMod.castHom h (ZMod M)) h11
    rwa [map_intCast, map_one] at this
  · have := congrArg (ZMod.castHom h (ZMod M)) h10
    rwa [map_intCast, map_zero] at this

variable {M} in

theorem x1FunctionFieldC_le_of_dvd {M' : ℕ} (h : M ∣ M') :
    x1FunctionFieldC K M ≤ x1FunctionFieldC K M' :=
  qExpFunctionFieldC_mono K (Gamma1_le_of_dvd h)

end LevelOne

/-! ## The `Jacobian` abbreviations -/

section Jacobian

variable (M : ℕ)

/-- X₁'s function field base-changed to `ℚ̄`. -/
abbrev x1FunctionFieldBar :
    IntermediateField (AlgebraicClosure ℚ) (LaurentSeries (AlgebraicClosure ℚ)) :=
  laurentBaseChange (AlgebraicClosure ℚ) (x1FunctionField M)

/-- The Jacobian `J₁(M) = Pic⁰` of `X₁(M)` over `ℚ̄`. -/
abbrev JOne : Type _ :=
  Pic0 (AlgebraicClosure ℚ) (x1FunctionFieldBar M)

/-- The `K`-valued Jacobian `J₁(M) = Pic⁰` of the layer function field. -/
abbrev JOneC (K : Type*) [Field K] : Type _ :=
  Pic0 K (x1FunctionFieldC K M)

end Jacobian

end ModularCurve

end
