/-
  Layer 0b — the collapse of `FunctionFieldGeneration` to an equality of fields.

  This is the only theorem in Layer 0, and the first *result* of the whole
  effort: the generation statement of math/010 §2 is equivalent to the two
  function fields coinciding.

  FLT provenance, pinned `aa2d8b3`:
  * statement — `Theorems/Thm_ModularCurve_functionFieldGeneration_iff_full_eq.lean` line 6;
  * proof — `P2M/Sol/S_ModularCurve_functionFieldGeneration_iff_full_eq.lean` lines 11–21.
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Theorems/Thm_ModularCurve_functionFieldGeneration_iff_full_eq.lean#L6
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_ModularCurve_functionFieldGeneration_iff_full_eq.lean#L11-L21

  The proof is definitional (`le_antisymm`, `adjoin_le_iff`, `jqd_mem_full`), so
  it needs nothing beyond Layer 0's definitions.

  Assumes `FunctionFieldGeneration` (`Defs/Target`) and `modularFunctionField`,
  `modularFunctionFieldFull`, `modularFunctionField_le_full`, `jqd_mem_full`
  (`Defs/Fields`). Not under `Defs/` because it is a result, not a definition.
-/
import FLTForHuman.ModularCurve.Defs.Fields
import FLTForHuman.ModularCurve.Defs.Target

set_option autoImplicit false

noncomputable section

open PowerSeries HahnSeries IntermediateField

namespace ModularCurve

/-- `j(q ^ d)` for every `d ∣ N` is generated by `j(q)` and `j(q ^ N)` — i.e.
`FunctionFieldGeneration N` — exactly when the all-divisors field collapses onto
the two-generator field. -/
theorem functionFieldGeneration_iff_full_eq (N : ℕ) [NeZero N] :
    FunctionFieldGeneration N ↔ modularFunctionFieldFull N = modularFunctionField N := by
  constructor
  · intro hgen
    refine le_antisymm ?_ (modularFunctionField_le_full N)
    rw [modularFunctionFieldFull, adjoin_le_iff]
    rintro x ⟨d, hne, hdvd, rfl⟩
    exact hgen d hdvd hne
  · intro heq d hdvd _
    show qExpand ℚ d jq ∈ modularFunctionField N
    rw [← heq]
    exact jqd_mem_full N hdvd

end ModularCurve

end
