"""Galois representations on E[l] — illustrative demo.

CONCEPT
    For E over a field K and a prime l invertible in K, the action of the
    absolute Galois group on E[l] is a two-dimensional representation

        rho_{E,l} : G_K -> GL_2(F_l).

    The Weil pairing forces det rho_{E,l} = chi_l, the mod-l cyclotomic
    character; over a totally real field this makes rho_{E,l} odd, because
    complex conjugation acts on the l-th roots of unity by inversion.  At a
    good prime p, Frobenius has characteristic polynomial T^2 - a_p T + p, so
    its trace is a_p and its determinant is p = chi_l(Frob_p).

    Over a finite field F_p the Galois group is pro-cyclic, generated by
    Frobenius, so the representation is determined by the single operator
    rho(Frob); for l != p it is semisimple and irreducible exactly when
    T^2 - a_p T + p is irreducible over F_l.

FLT ANCHOR
    ResidualGaloisRep                (Def_GaloisRep_Residual.lean, line 22)
    ResidualGaloisRep.IsAttachedTo   (line 48)
    ResidualGaloisRep.IsOdd          (line 57)
    ResidualGaloisRep.IsIrreducible  (line 61)
    FreyPackage.Mazur_Frey           (Thm_FreyPackage_Mazur_Frey.lean)
    FreyPackage.frey_reducible_hasCofixedLine
        (Thm_FreyPackage_frey_reducible_hasCofixedLine.lean, line 15)

WHY IT MATTERS FOR FLT
    The proof attaches rho_{E,p} to the Frey curve.  It needs the
    representation irreducible -- Mazur's Eisenstein-ideal argument for p >= 17
    -- and odd with determinant chi_p, which is what Serre's conjecture and the
    modularity-lifting hypotheses require.  If it were reducible, Serre's
    observation would produce a Galois-stable cofixed line, and that is what
    the proof excludes.

RUN
    python3 galois_rep.py
    python3 galois_rep.py > galois_rep.expected.txt
"""

import sympy as sp

from ffcurve import EllipticCurve, FiniteField
from ffcurve.galois import (charpoly_mod, cyclotomic_character_of_conjugation,
                            determinant_mod, frobenius_matrix,
                            has_eigenvector_mod, inverse_is_conjugate,
                            inversion_nontrivial, is_irreducible_mod,
                            real_subfield_degree, trace_mod)
from report import Report

CURVES = [("y^2 = x^3 - x  over GF(7)", 0, 7),
          ("y^2 = x^3 + 2  over GF(7)", -1, 7),
          ("y^2 = x^3 + 1  over GF(5)", 0, 5),
          ("y^2 = x^3 + x + 1 over GF(5)", -3, 5),
          ("y^2 = x^3 + 15x over GF(41)", -8, 41)]
LS = (2, 3, 5, 7, 11, 13)


def trace_det_ok(a, q, lu):
    """Does T^2 - a T + q really have trace -(-a) and constant term q mod lu?"""
    cs = charpoly_mod(a, q, lu).all_coeffs()  # descending
    return (len(cs) == 3 and (int(cs[0]) - 1) % lu == 0
            and (int(cs[1]) + a) % lu == 0 and (int(cs[2]) - q) % lu == 0)


def main():
    R = Report("Galois representations on E[l]")

    R.note("""
        The Galois group acts on the l-torsion of an elliptic curve, giving a
        two-dimensional representation over F_l.  This demo computes that
        representation over finite fields, where the Galois group is generated
        by Frobenius and the single operator rho(Frob) is the whole
        representation, and it verifies the two structural constraints the FLT
        proof relies on: the determinant is the cyclotomic character, and the
        representation is odd.
    """)

    # ---- 1 -------------------------------------------------------------
    R.section("1. The representation, over a finite field")
    R.note("""
        Take E: y^2 = x^3 + 1 over GF(5).  Its 3-torsion is not rational over
        GF(5); it appears over GF(25), where a basis of E[3] can be chosen.
        The 5-power Frobenius then acts as an explicit 2x2 matrix with entries
        in Z/3, and that matrix *is* rho_{E,3}(Frob_5) in this basis.
    """)
    p, l = 5, 3
    K = FiniteField(p, 2)
    EK = EllipticCurve(K, 0, 1)
    M = frobenius_matrix(K, EK, p, l)
    a_p = 0  # #E(GF(5)) = 6, so a_5 = 5 + 1 - 6
    R.data(f"E: y^2 = x^3 + 1 over GF(5),  #E(GF(5)) = 6,  a_5 = {a_p}")
    R.data(f"rho(Frob) on E[3] in a basis: M = {M}   (entries in Z/{l})")
    R.data(f"trace(M) = {trace_mod(M, l)},   det(M) = {determinant_mod(M, l)}")

    # ---- 2 -------------------------------------------------------------
    R.section("2. The determinant is the cyclotomic character")
    R.note("""
        Frobenius acts on the l-th roots of unity by zeta -> zeta^p, so
        chi_l(Frob_p) = p in (Z/l)^x.  The Weil pairing (base/007) makes the
        determinant of the action on E[l] the same character, so det rho(Frob)
        must be p mod l -- and it is.
    """)
    R.check("det rho(Frob) = p mod l = chi_l(Frob)",
            determinant_mod(M, l) == p % l)
    R.check("trace rho(Frob) = a_p mod l", trace_mod(M, l) == a_p % l)
    (a, b), (c, d) = M
    sat = (((a * a + b * c) - a_p * a + p) % l == 0
           and ((a * b + b * d) - a_p * b) % l == 0
           and ((c * a + d * c) - a_p * c) % l == 0
           and ((c * b + d * d) - a_p * d + p) % l == 0)
    R.check("M satisfies its characteristic polynomial T^2 - a_p T + p", sat)
    R.data("constant term p is the determinant, i.e. the cyclotomic character;")
    R.data("the trace a_p is the coefficient matched with a Hecke eigenvalue.")

    # ---- 3 -------------------------------------------------------------
    R.section("3. Oddness: complex conjugation acts by inversion")
    R.note("""
        Complex conjugation c sends zeta_n to zeta_n^(-1).  That inversion is a
        Galois automorphism of Q(zeta_n) because the cyclotomic polynomial
        Phi_n is palindromic -- its roots come in inverse pairs -- and it is
        nontrivial for n > 2.  Its fixed field is the real subfield, of degree
        phi(n)/2.  So chi_n(c) = -1, and any representation whose determinant is
        chi_n is odd: det rho(c) = -1.
    """)
    R.data("n | Phi_n palindromic | inversion nontrivial | chi_n(c) | real degree (phi/2)")
    cyc_ok, real_ok = True, True
    for n in range(3, 11):
        pal = inverse_is_conjugate(n)
        nontriv = inversion_nontrivial(n)
        chi = cyclotomic_character_of_conjugation(n)
        rd = real_subfield_degree(n)
        half = int(sp.totient(n)) // 2
        cyc_ok = cyc_ok and pal and nontriv and chi == n - 1
        real_ok = real_ok and rd == half
        R.data(f"{n:2d} | {str(pal):17} | {str(nontriv):20} | {chi:7d} | {rd} ({half})")
    R.check("Phi_n is palindromic and inversion is a nontrivial automorphism",
            cyc_ok)
    R.check("chi_n(c) = -1 for n > 2, hence det rho(c) = -1 (rho is odd)",
            all(cyclotomic_character_of_conjugation(n) == n - 1 != 1
                for n in range(3, 11)))
    R.check("the fixed field of conjugation is the real subfield of degree phi(n)/2",
            real_ok)

    # ---- 4 -------------------------------------------------------------
    R.section("4. Frobenius and the characteristic polynomial")
    R.note("""
        At a good prime p the characteristic polynomial of rho(Frob_p) is
        T^2 - a_p T + p: trace a_p, determinant p.  The trace is the Hecke
        eigenvalue side (hecke_eichler_shimura, modular_qexp) and the
        determinant is the cyclotomic character side (section 2).
    """)
    R.data("curve                          | a_p | trace | determinant")
    for (name, a, q) in CURVES:
        R.data(f"{name:30s} | {a:3d} | {a:5d} | {q:11d}")
    R.check("the Frobenius polynomial has trace a_p and constant term p mod l",
            all(trace_det_ok(a, q, lu)
                for (_, a, q) in CURVES for lu in LS if lu != q))

    # ---- 5 -------------------------------------------------------------
    R.section("5. Irreducible or reducible")
    R.note("""
        Over a finite field the representation is generated by Frobenius, and
        for l different from p it is semisimple; hence it is irreducible
        exactly when T^2 - a_p T + p is irreducible over F_l.  Reducibility
        means there is a Galois-stable line, i.e. an eigenvector for the
        matrix.
    """)
    header = "curve".ljust(30) + "| a_p | " + " | ".join(f"l={lu}" for lu in LS)
    R.data(header)
    verdicts = {}
    for (name, a, q) in CURVES:
        row = []
        for lu in LS:
            if lu == q:
                row.append("--")
                continue
            irr = is_irreducible_mod(a, q, lu)
            verdicts[(name, lu)] = irr
            row.append("irr" if irr else "red")
        R.data(f"{name:30s}| {a:3d} | " + " | ".join(f"{cell:3s}" for cell in row))
    R.check("the concrete matrix M is reducible, and its polynomial splits mod 3",
            has_eigenvector_mod(M, l)[0] and not is_irreducible_mod(a_p, p, l))
    R.check("an eigenvector of M over F_l exists exactly when the polynomial splits",
            has_eigenvector_mod(M, l)[0] == (not is_irreducible_mod(a_p, p, l)))
    R.check("E: y^2 = x^3 - x over GF(7) is irreducible at l = 3, 5, 13 "
            "and reducible at l = 2, 11",
            [verdicts[("y^2 = x^3 - x  over GF(7)", lu)]
             for lu in (3, 5, 13)] == [True, True, True]
            and [verdicts[("y^2 = x^3 - x  over GF(7)", lu)]
                 for lu in (2, 11)] == [False, False])

    # ---- 6 -------------------------------------------------------------
    R.section("6. The formalization")
    R.note("""
        ResidualGaloisRep bundles a finite-dimensional k-vector space with a
        continuous action of the absolute Galois group of Q that factors
        through a finite level.  IsOdd is the determinant condition above:
        det rho(c) = -1 at complex conjugation.  IsIrreducible says there is no
        Galois-stable subspace, and IsAttachedTo records the Frobenius
        polynomial X^2 - a X + l linking the representation to a cusp form.
    """)
    R.note("""
        For the Frey curve the proof needs GaloisRepIsIrreducible, which is
        FreyPackage.Mazur_Frey for p >= 17 (Mazur's Eisenstein-ideal argument)
        with small primes handled separately by Kummer theory and explicit
        descents.  In the reducible case Serre's observation,
        FreyPackage.frey_reducible_hasCofixedLine, produces a Galois-stable
        line on which the quotient acts trivially -- the cofixed line that the
        rest of the argument rules out.
    """)

    R.finish()


if __name__ == "__main__":
    main()
