"""Primitive coset representatives for Gamma_0(N) -- illustrative demo.

CONCEPT
    Section 8 of base/020 counts the index [SL_2(Z) : Gamma_0(N)] a second
    time, without the group theory of sections 3-7, by enumerating a set of
    upper-triangular matrices of determinant N:

        primCosetReps(N) = { (a, b, d) : a d = N, 0 <= b < d,
                                          gcd(a, gcd(b, d)) = 1 },

    and showing its cardinality is again psi(N) = N prod_{p | N} (1 + 1/p).

    The section is dense with vocabulary, and every word is a statement about
    a 2x2 integer matrix M and the two lattices it carries.  The *row lattice*
    is the subgroup of Z^2 generated by the rows; the *column lattice* is the
    one generated by the columns.  The left action M -> U M (U in SL_2(Z))
    preserves the row lattice, the right action M -> M V preserves the column
    lattice.

    * Primitive: the Smith normal form of M is diag(1, N).  Smith form is
      U M V = diag(d1, d2) with U, V in SL_2(Z), d1 | d2, d1 the gcd of the
      entries and d1 d2 = |det M|; so primitive means d1 = 1.
    * Row cyclic: Z^2 modulo the row lattice is isomorphic to Z/d1 x Z/d2,
      which is cyclic exactly when d1 = 1 -- the same condition.
    * Hermite normal form: the unique upper-triangular U M = [[a, b], [0, d]]
      with a, d > 0 and 0 <= b < d, i.e. the canonical representative of the
      left orbit (row lattice).  Its diagonal is not the Smith diagonal; its
      first invariant factor is gcd(a, gcd(b, d)), so primitivity is exactly
      the displayed coprimality condition.
    * The displayed triples are therefore a transversal for the left action,
      and the set of determinant-N primitive matrices is the double coset
      SL_2(Z) diag(1, N) SL_2(Z).
    * Projective line: unimodular pairs (a, c) in (Z/N)^2 modulo units; the
      triples parameterise the same cyclic subgroups of order N, so both
      counts give psi(N).
    * Fibre count: reindexing the triples by (a, d) makes each inner b-count a
      totient count, #{b < d : gcd(gcd(a,d), b) = 1} = (d/g) phi(g) with
      g = gcd(a, d).

    The demo fixes N = 12 (override on the command line) and exhibits all of
    this on explicit matrices and vectors.

FLT ANCHOR
    ModularCurve.primCosetReps            (Definitions/Def_ModularCurve_PrimCosetReps.lean, line 8)
    ModularCurve.card_filter_coprime_range_mul, card_fibre, card_primCosetReps_eq_sum
                                          (P2M/Sol/S_ModularCurve_card_primCosetReps_eq_dedekindPsi.lean, lines 18, 33, 50)
    ModularCurve.h_mul, isMultiplicative_G, h_prime_pow, G_prime_pow, G_eq_Psi
                                          (same file, lines 132, 162, 170, 215, 277)
    ModularCurve.Psi_apply                (P2M/Sol/S_ModularCurve_card_primCosetReps_eq_dedekindPsi.lean, line 243)
    Matrix.SpecialLinearGroup.exists_eq_mul_diagonal_mul_of_gcd_eq_one
                                          (P2M/Sol/S_Matrix_SpecialLinearGroup_exists_eq_mul_diagonal_mul_of_gcd_eq_one.lean, line 48)
    ModularCurve.card_projectiveLine_zmod (P2M/Sol/S_ModularCurve_card_projectiveLine_zmod.lean, line 248)
    ModularCurve.card_quotient_borel     (P2M/Sol/S_ModularCurve_Gamma0_index.lean, line 236)
    ModularCurve.Gamma0_index             (P2M/Sol/S_ModularCurve_Gamma0_index.lean, line 227, "solution")
    pin: anthropics/fermats-last-theorem@aa2d8b3

WHY IT MATTERS FOR FLT
    The index [SL_2(Z) : Gamma_0(N)] = psi(N) is the degree of the cover
    X_0(N) -> X(1), and the q-expansion layer of the proof enumerates the
    index set concretely as primCosetReps(N).  Section 8 proves the count
    independently of the group-theoretic route, and the fibre count
    (d/g) phi(g) is the arithmetic core that the formalization reuses for
    Psi = mu^2 * id.  Seeing the triples as Hermite normal forms of primitive
    determinant-N matrices explains why that finite list is the right index
    set at all: it is a complete set of row-lattice representatives, one per
    cyclic subgroup of order N in (Z/N)^2.

RUN
    python3 prim_coset_reps.py
    python3 prim_coset_reps.py > prim_coset_reps.expected.txt
    python3 prim_coset_reps.py 6        # the same story at another N
"""

import sys
from math import gcd, lcm

from sympy import Matrix, Rational, totient

from ffcurve.lattices import (
    canonical_pair, det2, element_order, hnf2, is_primitive, is_sl2, mat_mul,
    projective_line, quotient_generator, quotient_key,
    reduced_row_lattice_generator, same_column_lattice, same_row_lattice,
    smith2, unimodular_pairs, units,
)
from report import Report


# --------------------------------------------------------------------------
# small arithmetic helpers (the counting side of section 8)
# --------------------------------------------------------------------------

def prime_factors(n):
    """The distinct primes dividing ``n``."""
    out, m, p = [], n, 2
    while p * p <= m:
        if m % p == 0:
            out.append(p)
            while m % p == 0:
                m //= p
        p += 1
    if m > 1:
        out.append(m)
    return out


def factorisation(n):
    """``n`` as ``(p, exponent)`` pairs."""
    out, m, p = [], n, 2
    while p * p <= m:
        if m % p == 0:
            e = 0
            while m % p == 0:
                m //= p
                e += 1
            out.append((p, e))
        p += 1
    if m > 1:
        out.append((m, 1))
    return out


def dedekind_psi(n):
    """psi(n) = n prod_{p | n} (1 + 1/p), the index of Gamma_0(n)."""
    r = n
    for p in prime_factors(n):
        r = r // p * (p + 1)
    return r


def squarefree_divisors(n):
    """The squarefree divisors of ``n`` (including 1)."""
    divs = [1]
    for p in prime_factors(n):
        divs += [d * p for d in divs]
    return sorted(divs)


def dedekind_psi_divisor_sum(n):
    """sum over squarefree d | n of n/d, the divisor-sum presentation."""
    return sum(n // d for d in squarefree_divisors(n))


def prim_coset_reps(n):
    """The triples (a, b, d) of base/020 section 1."""
    out = []
    for d in range(1, n + 1):
        if n % d:
            continue
        a = n // d
        for b in range(d):
            if gcd(a, gcd(b, d)) == 1:
                out.append((a, b, d))
    return out


def fibre_value(a, d):
    """h(a, d) = (d/g) phi(g), g = gcd(a, d): the number of b < d coprime to g."""
    g = gcd(a, d)
    return (d // g) * int(totient(g))


def G(n):
    """G(n) = sum over ad = n of the fibre value h(a, d)."""
    return sum(fibre_value(a, n // a) for a in range(1, n + 1) if n % a == 0)


# --------------------------------------------------------------------------
# formatting helpers
# --------------------------------------------------------------------------

def fmt(M):
    return f"[[{M[0][0]}, {M[0][1]}], [{M[1][0]}, {M[1][1]}]]"


def fmt_sym(M):
    """Format a sympy matrix, keeping rational entries such as 1/12."""
    return "[" + ", ".join(
        "[" + ", ".join(str(M[i, j]) for j in range(M.cols)) + "]"
        for i in range(M.rows)) + "]"


def diag_mat(a, d):
    return [[a, 0], [0, d]]


def inv_sl2(M):
    """Inverse of a matrix of determinant 1."""
    return [[M[1][1], -M[0][1]], [-M[1][0], M[0][0]]]


def quotient_profile(M):
    """(d1, d2, {order: count}) for the group Z^2 / (row lattice of M)."""
    _, D, _ = smith2(M)
    d1, d2 = D[0][0], D[1][1]
    orders = {}
    for x in range(d1):
        for y in range(d2):
            ox = 1 if x == 0 else d1 // gcd(x, d1)
            oy = 1 if y == 0 else d2 // gcd(y, d2)
            o = lcm(ox, oy)
            orders[o] = orders.get(o, 0) + 1
    return d1, d2, orders


def is_unimodular_by_bezout(n, pair):
    """Brute force: does there exist (x, y) with x*a + y*c = 1 mod n?"""
    a, c = pair
    return any((x * a + y * c - 1) % n == 0
               for x in range(n) for y in range(n))


def sl2_zmod(n):
    """All of SL_2(Z/n), enumerated by brute force over the n^4 tuples."""
    return [g for g in ((a, b, c, d)
                        for a in range(n) for b in range(n)
                        for c in range(n) for d in range(n))
            if (g[0] * g[3] - g[1] * g[2] - 1) % n == 0]


# --------------------------------------------------------------------------
# the demo
# --------------------------------------------------------------------------

def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    R = Report(f"Primitive coset representatives and the index of Gamma_0({n})")

    psi = dedekind_psi(n)
    phi = int(totient(n))
    triples = prim_coset_reps(n)
    fact = " * ".join(f"{p}^{e}" if e > 1 else str(p)
                      for p, e in factorisation(n)) or "1"

    # a prime whose square divides N, if any: the only obstruction to
    # primitivity, since d1 | d2 = N/d1 forces d1^2 | N.
    q_bad = next((p for p in prime_factors(n) if n % (p * p) == 0), None)
    M_nonprim = diag_mat(q_bad, n // q_bad) if q_bad else None
    M_upper = [[q_bad, 1], [0, n // q_bad]] if q_bad else None
    M_generic = [[n + 1, 1], [1, 1]]

    # ---- 1 -------------------------------------------------------------
    R.section("1. The running example: N, psi(N), phi(N)")
    R.note(f"""
        Fix N = {n} = {fact} and write psi(N) = N prod_{{p | N}} (1 + 1/p)
        for the index of Gamma_0(N), and phi(N) = #(Z/N)^* for Euler's
        totient.  At N = {n} the product is
        {n} * {' * '.join(f'(1 + 1/{p})' for p in prime_factors(n))} = {psi},
        while phi({n}) = {phi}.  The divisor-sum form of psi is the sum of N/d
        over the squarefree divisors d of N.
    """)
    R.data(f"N = {n} = {fact},  prime factors = {prime_factors(n)}")
    R.data(f"psi(N) = {psi},  phi(N) = {phi}")
    R.data(f"squarefree divisors = {squarefree_divisors(n)}"
           f"  ->  sum N/d = {dedekind_psi_divisor_sum(n)}")
    R.check("psi(N) = N prod (1 + 1/p) = sum over squarefree d | N of N/d",
            psi == dedekind_psi_divisor_sum(n))
    R.check("psi is multiplicative on coprime arguments",
            all(dedekind_psi(a * b) == dedekind_psi(a) * dedekind_psi(b)
                for a in range(1, 40) for b in range(1, 40) if gcd(a, b) == 1))

    R.note("""
        On a prime power psi and phi are complementary: psi(p^k) =
        p^k + p^(k-1) counts the k-digit residues together with the leading
        k-1-digit ones, phi(p^k) = p^k - p^(k-1) counts the units, and
        psi(p^k) + phi(p^k) = 2 p^k.  Section 8's fibre count produces
        psi(p^k) out of phi on the same prime power, which is why the two
        functions meet here.
    """)
    rows = []
    for p in (2, 3, 5):
        for k in (1, 2, 3):
            rows.append(f"p={p}, k={k}: psi={p**k + p**(k-1):4d}  "
                        f"phi={p**k - p**(k-1):4d}  sum={2 * p**k:4d}")
    for i in range(0, len(rows), 3):
        R.data("   ".join(rows[i:i + 3]))
    R.check("psi(p^k) = p^k + p^(k-1) and psi(p^k) + phi(p^k) = 2 p^k",
            all(dedekind_psi(p**k) == p**k + p**(k-1)
                and dedekind_psi(p**k) + int(totient(p**k)) == 2 * p**k
                for p in (2, 3, 5) for k in (1, 2, 3)))

    # ---- 2 -------------------------------------------------------------
    R.section("2. The projective line: unimodular pairs modulo units")
    R.note("""
        A pair (a, c) in (Z/N)^2 is unimodular when it generates the unit
        ideal, i.e. there exist x, y with x a + y c = 1.  Over Z/N that is the
        same as gcd(a, c, N) = 1.  The unit group (Z/N)^* acts on unimodular
        pairs by scaling, freely: if u a = a and u c = c for a unimodular pair
        then u = 1.  The projective line P^1(Z/N) is the set of orbits.
    """)
    pairs = unimodular_pairs(n)
    bezout_ok = all(
        is_unimodular_by_bezout(n, p) == (gcd(gcd(p[0], p[1]), n) == 1)
        for p in [(a, c) for a in range(n) for c in range(n)])
    sizes = {}
    for p in pairs:
        key = canonical_pair(n, p)
        sizes[key] = sizes.get(key, 0) + 1
    R.data(f"unimodular pairs: {len(pairs)} = N^2 prod (1 - p^-2);  "
           f"units: {units(n)} (phi = {phi})")
    R.data(f"orbit sizes: {sorted(set(sizes.values()))};  "
           f"lines: {len(projective_line(n))} = psi(N) = {psi}")
    reps = [f"{a}:{c}" for a, c in projective_line(n)]
    for i in range(0, len(reps), 8):
        R.data("  ".join(f"{s:>5s}" for s in reps[i:i + 8]))
    R.check("unimodular iff gcd(a, c, N) = 1 (Bezout by brute force)", bezout_ok)
    R.check("the unit action is free: every orbit has exactly phi(N) elements",
            set(sizes.values()) == {phi} and len(sizes) == len(pairs) // phi)
    R.check("#P^1(Z/N) = #unimodular pairs / phi(N) = psi(N)",
            len(projective_line(n)) == psi)

    R.note("""
        The same count is the index of the Borel subgroup B(Z/N) of upper
        triangular matrices in SL_2(Z/N): a matrix is sent to the line of its
        first column, and two matrices have first columns in the same unit
        orbit exactly when they differ by an element of B.  So the right
        cosets of B are the lines, #(SL_2(Z/N) / B(Z/N)) = #P^1(Z/N).
    """)
    if n <= 16:
        els = sl2_zmod(n)
        borel = [g for g in els if g[2] % n == 0]
        fibres = {}
        for g in els:
            key = canonical_pair(n, (g[0], g[2]))
            fibres[key] = fibres.get(key, 0) + 1
        R.data(f"#SL_2(Z/{n}) = {len(els)} = N^3 prod (1 - p^-2);  "
               f"#B(Z/{n}) = {len(borel)} = N phi(N) = {n * phi};  "
               f"fibres = {len(fibres)}, "
               f"each of size {sorted(set(fibres.values()))}")
        R.check("the right cosets gB are the lines: every first-column fibre "
                "has size #B = N phi(N)",
                set(fibres.values()) == {n * phi} and len(borel) == n * phi)
        R.check("#(SL_2(Z/N) / B(Z/N)) = #P^1(Z/N) = psi(N)",
                len(fibres) == psi)
    else:
        R.note(f"(SL_2(Z/{n}) is too large to enumerate here; run with a "
               f"smaller N to see the coset fibres counted.)")

    # ---- 3 -------------------------------------------------------------
    R.section("3. Smith normal form: primitive = diag(1, N) = row cyclic")
    R.note("""
        For an integer matrix M of determinant N, Smith normal form is
        U M V = diag(d1, d2) with U, V in SL_2(Z), d1 | d2.  The first
        invariant factor d1 is the gcd of the four entries of M, and
        d1 d2 = N; the matrix is primitive when d1 = 1, i.e. when its Smith
        form is diag(1, N).  The row lattice L = rows(M) gives
        Z^2 / L = Z/d1 x Z/d2, so primitive is also exactly "row cyclic":
        the quotient is a cyclic group of order N.  (A non-primitive
        determinant-N matrix can exist only when some p^2 divides N, since
        d1 | d2 forces d1^2 | N.)
    """)
    samples = [("diag(1, N)", diag_mat(1, n))]
    if M_upper is not None:
        samples.append((f"upper triangular ({q_bad}, 1, {n // q_bad})",
                        M_upper))
    if M_nonprim is not None:
        samples.append((f"diag({q_bad}, {n // q_bad})", M_nonprim))
    samples.append(("a generic primitive matrix", M_generic))
    for label, M in samples:
        d = det2(M)
        U, D, V = smith2(M)
        d1, d2, orders = quotient_profile(M)
        R.data(f"{label}:  M = {fmt(M)}, det = {d}, gcd(entries) = {d1}")
        R.data(f"    U = {fmt(U)},  V = {fmt(V)},  U M V = {fmt(D)}")
        R.data(f"    quotient Z^2 / L = Z/{d1} x Z/{d2}, element orders "
               f"{dict(sorted(orders.items()))}, generator "
               f"{quotient_generator(M)}")
        R.check(f"U M V = diag({D[0][0]}, {D[1][1]}) with U, V in SL_2(Z) "
                f"for {label}",
                is_sl2(U) and is_sl2(V) and mat_mul(mat_mul(U, M), V) == D)
    R.check("primitive iff Smith form is diag(1, N) iff gcd(entries) = 1",
            all((smith2(M)[1][0][0] == 1) == is_primitive(M)
                for _, M in samples))
    R.check("the quotient is cyclic (max element order N) iff d1 = 1",
            all((max(quotient_profile(M)[2]) == abs(det2(M)))
                == (quotient_profile(M)[0] == 1)
                for _, M in samples))

    R.note("""
        A generator of Z^2 / L is a vector v whose N multiples hit all N
        classes.  For diag(1, N) the class of (0, 1) runs through
        0, 1, ..., N-1, which is the cyclic quotient in coordinates.  When
        N has a square factor, diag(p, N/p) is non-primitive and no vector
        generates: the quotient has exponent N/p < N.
    """)
    M1 = diag_mat(1, n)
    seq = [quotient_key(M1, (0, k))[1] for k in range(n)]
    R.data(f"diag(1, N): classes of k*(0, 1), k = 0..{n - 1}: {seq}")
    if M_nonprim is not None:
        d1n, d2n, ordersn = quotient_profile(M_nonprim)
        R.data(f"{fmt(M_nonprim)}: quotient Z/{d1n} x Z/{d2n}, element orders "
               f"{dict(sorted(ordersn.items()))}")
    R.check("a primitive matrix has a quotient generator; a non-primitive one "
            "has none",
            quotient_generator(M1) is not None
            and (M_nonprim is None or quotient_generator(M_nonprim) is None))

    # ---- 4 -------------------------------------------------------------
    R.section("4. Hermite normal form: the left action's canonical form")
    R.note("""
        Row operations are the left action M -> U M with U in SL_2(Z).  They
        preserve the row lattice, and the Hermite normal form is the unique
        representative of that orbit which is upper triangular,
        [[a, b], [0, d]] with a, d > 0 and 0 <= b < d: the Euclidean steps
        make the (1,0) entry zero, then reduce b modulo d.  The point to keep
        apart from Smith form is which gcd shows up: the diagonal (a, d) of
        the Hermite form is *not* the Smith diagonal, but the first invariant
        factor of the Hermite form is gcd(a, b, d) = gcd(a, gcd(b, d)), so
        the triples of section 8 are exactly the Hermite forms that are
        primitive.
    """)
    examples = [("a generic primitive matrix", M_generic)]
    if M_upper is not None:
        examples.insert(0, (f"[[{q_bad}, 1], [0, {n // q_bad}]]", M_upper))
    if M_nonprim is not None:
        examples.append((f"diag({q_bad}, {n // q_bad})", M_nonprim))
    for label, M in examples:
        U, H = hnf2(M)
        _, D, _ = smith2(M)
        R.data(f"{label}:  U = {fmt(U)},  H = U M = {fmt(H)},  "
               f"det U = {det2(U)},  Smith diagonal = ({D[0][0]}, {D[1][1]})")
        R.check(f"H = U M is upper triangular with a, d > 0, 0 <= b < d, "
                f"and (gcd(a, b, d) = 1) iff M is primitive, for {label}",
                H[1][0] == 0 and H[0][0] > 0 and H[1][1] > 0
                and 0 <= H[0][1] < H[1][1]
                and (gcd(gcd(H[0][0], H[0][1]), H[1][1]) == 1) == is_primitive(M))
    if M_upper is not None:
        R.check(f"Hermite diagonal ({q_bad}, {n // q_bad}) differs from the "
                f"Smith diagonal (1, {n}) at {fmt(M_upper)}",
                hnf2(M_upper)[1] == M_upper
                and smith2(M_upper)[1] == diag_mat(1, n))

    R.note("""
        The left action preserves the row lattice and the Hermite form is a
        complete invariant of it: M and U M have the same Hermite form for
        every U.  So the Hermite forms of determinant-N matrices are a
        transversal of the left action, one representative per row lattice of
        index N; those whose quotient Z^2/L is cyclic (equivalently, that are
        primitive) are the triples below.
    """)
    U = [[1, 2], [0, 1]]
    M = M_generic
    _, H2 = hnf2(M)
    R.data(f"M = {fmt(M)},  U' = {fmt(U)},  U' M = {fmt(mat_mul(U, M))}")
    R.data(f"Hermite form of both is {fmt(H2)}")
    R.check("the left action preserves the row lattice",
            same_row_lattice(M, mat_mul(U, M)))
    R.check("the Hermite form is constant on a left orbit",
            hnf2(mat_mul(U, M))[1] == hnf2(M)[1])
    R.check("the Hermite form is unique: distinct triples have distinct "
            "row lattices",
            all(not same_row_lattice([[t1[0], t1[1]], [0, t1[2]]],
                                     [[t2[0], t2[1]], [0, t2[2]]])
                for i, t1 in enumerate(triples) for t2 in triples[i + 1:]))

    R.data(f"primCosetReps({n}): {len(triples)} triples (a, b, d) = "
           f"Hermite forms of primitive determinant-{n} matrices")
    cells = [f"({a},{b},{d})" for a, b, d in triples]
    for i in range(0, len(cells), 8):
        R.data("  ".join(f"{s:>8s}" for s in cells[i:i + 8]))
    R.check("every triple is a fixed point of Hermite reduction and is primitive",
            all(hnf2([[a, b], [0, d]])[1] == [[a, b], [0, d]]
                and is_primitive([[a, b], [0, d]])
                for a, b, d in triples))
    R.check(f"card primCosetReps({n}) = psi({n}) = {psi}",
            len(triples) == psi)

    # ---- 5 -------------------------------------------------------------
    R.section("5. Left vs right action, the double coset, and Gamma_0(N)")
    R.note("""
        The two actions do different things.  Left multiplication U M mixes
        the rows, so it fixes the row lattice; right multiplication M V mixes
        the columns, so it fixes the column lattice but moves the row lattice
        in general.  Smith form uses both at once, which is why it can put a
        primitive M into diag(1, N) for any M in the set: the determinant-N
        primitive matrices are exactly the double coset
        SL_2(Z) diag(1, N) SL_2(Z).
    """)
    M = M_generic
    sample_sl2 = [[[1, 1], [0, 1]], [[1, 0], [1, 1]], [[2, 1], [1, 1]],
                  [[1, 2], [0, 1]], [[0, -1], [1, 0]], [[1, 3], [1, 4]]]
    left_witness = next((U for U in sample_sl2
                         if same_row_lattice(M, mat_mul(U, M))
                         and not same_column_lattice(M, mat_mul(U, M))), None)
    right_witness = next((V for V in sample_sl2
                          if same_column_lattice(M, mat_mul(M, V))
                          and not same_row_lattice(M, mat_mul(M, V))), None)
    V = [[1, 1], [0, 1]]
    R.data(f"M = {fmt(M)},  V = {fmt(V)},  M V = {fmt(mat_mul(M, V))}")
    R.check("the left action preserves the row lattice for every U in the sample",
            all(same_row_lattice(M, mat_mul(U, M)) for U in sample_sl2))
    R.check("the right action preserves the column lattice for every V in the "
            "sample",
            all(same_column_lattice(M, mat_mul(M, V)) for V in sample_sl2))
    if left_witness is not None and right_witness is not None:
        R.data(f"a left witness U = {fmt(left_witness)} moves the column "
               f"lattice; a right witness V = {fmt(right_witness)} moves the "
               f"row lattice")
        R.check("left action can change the column lattice, right action can "
                "change the row lattice",
                same_row_lattice(M, mat_mul(left_witness, M))
                and not same_column_lattice(M, mat_mul(left_witness, M))
                and same_column_lattice(M, mat_mul(M, right_witness))
                and not same_row_lattice(M, mat_mul(M, right_witness)))
    else:
        R.note("At N = 1 every determinant-1 matrix has both lattices equal "
               "to Z^2, so no witness exists; run with N >= 2 to see one.")

    R.note("""
        For a primitive M the Smith decomposition U M V = diag(1, N) reads
        M = U^{-1} diag(1, N) V^{-1}, the double coset membership in
        coordinates; a non-primitive M has d1 > 1, and d1 is unchanged by
        either unimodular action, so it is outside the double coset.
    """)
    ok_dc = True
    for a, b, d in triples:
        Mh = [[a, b], [0, d]]
        U, D, V = smith2(Mh)
        if not (mat_mul(mat_mul(inv_sl2(U), diag_mat(1, n)), inv_sl2(V)) == Mh):
            ok_dc = False
    R.check("every triple is U diag(1, N) V with U, V in SL_2(Z) "
            "(the double coset)",
            ok_dc and all(is_sl2(inv_sl2(smith2([[a, b], [0, d]])[0]))
                          for a, b, d in triples))
    R.check("a non-primitive determinant-N matrix is not in the double coset "
            "(its d1 is invariant)",
            M_nonprim is None or smith2(M_nonprim)[1][0][0] != 1)

    R.note("""
        The group Gamma_0(N) reappears as the stabiliser of the matrix
        diag(N, 1).  Right multiplication moves the row lattice, L -> L
        gamma, so gamma stabilises diag(N, 1) when L gamma = L, for
        L = N Z x Z the row lattice of diag(N, 1).  That happens exactly when
        the second row (c, d) of gamma lies in L, i.e. N | c: the defining
        congruence of Gamma_0(N).  Equivalently, conjugating gamma =
        [[a, b], [c, d]] by diag(N, 1) gives [[a, N b], [c/N, d]].  The factor
        diag(N, 1)^-1 is not an integer matrix, and that is fine: the
        conjugation is a test over Q, and the test is whether the product is
        integral, which happens iff N | c.
    """)
    M0 = diag_mat(n, 1)
    small = [[[1, 0], [0, 1]], [[1, 1], [0, 1]], [[2, 3], [1, 2]],
             [[5, 2], [2, 1]], [[2, 1], [3, 2]]]
    R.data("diag(N,1) gamma diag(N,1)^-1 = [[a, N b], [c/N, d]] on samples:")
    for g in small:
        C = Matrix([[n, 0], [0, 1]]) * Matrix(g) \
            * Matrix([[Rational(1, n), 0], [0, 1]])
        c = g[1][0]
        R.data(f"    gamma = {fmt(g)}, c = {c:3d}:  "
               f"conjugate = {fmt_sym(C)},  "
               f"integral = {all(x.is_Integer for x in C)},  "
               f"L gamma = L = {same_row_lattice(M0, mat_mul(M0, g))}")
    box = [[[a, b], [c, d]]
           for a in range(-3, 4) for b in range(-3, 4)
           for c in range(-3, 4) for d in range(-3, 4)
           if a * d - b * c == 1]
    gamma0_count = sum(1 for g in box if g[1][0] % n == 0)
    R.data(f"over the {len(box)} matrices of SL_2(Z) with entries in "
           f"[-3, 3], {gamma0_count} lie in Gamma_0(N) and stabilise L")
    R.check("diag(N,1) gamma diag(N,1)^-1 is integral iff N | gamma[1][0] "
            "iff gamma stabilises the row lattice L = N Z x Z",
            all((all(x.is_Integer for x in
                     Matrix([[n, 0], [0, 1]]) * Matrix(g)
                     * Matrix([[Rational(1, n), 0], [0, 1]])))
                == (g[1][0] % n == 0)
                == same_row_lattice(M0, mat_mul(M0, g))
                for g in box))

    # ---- 6 -------------------------------------------------------------
    R.section("6. The fibre count: a totient count in the second coordinate")
    R.note("""
        Reindex the triples by the first and third entries.  For each (a, d)
        with ad = N the admissible b are exactly those below d that are
        coprime to g = gcd(a, d), because gcd(a, gcd(b, d)) = gcd(g, b).
        Residues coprime to g are g-periodic, so a block of m periods
        contains m phi(g) of them and #{b < d : gcd(g, b) = 1} = (d/g) phi(g).
        That value h(a, d) is the fibre count, and summing it over the
        divisors-antidiagonal gives G(N) = psi(N).
    """)
    rows, total = [], 0
    for a in range(1, n + 1):
        if n % a:
            continue
        d = n // a
        g = gcd(a, d)
        count = sum(1 for b in range(d) if gcd(g, b) == 1)
        h = fibre_value(a, d)
        total += count
        rows.append(f"(a,d)=({a:2d},{d:2d}) g={g:2d}  "
                    f"#{{b<d: gcd(g,b)=1}}={count:3d}  (d/g)phi(g)={h:3d}")
    for i in range(0, len(rows), 2):
        R.data("    ".join(rows[i:i + 2]))
    R.data(f"sum over ad = {n}: {total}")
    R.check("gcd(a, gcd(b, d)) = gcd(gcd(a, d), b) for every triple",
            all(gcd(a, gcd(b, d)) == gcd(gcd(a, d), b)
                for a, b, d in triples))
    R.check("the fibre count is the totient count: "
            "#{b < d : gcd(g,b) = 1} = (d/g) phi(g)",
            all(sum(1 for b in range(n // a) if gcd(gcd(a, n // a), b) == 1)
                == fibre_value(a, n // a)
                for a in range(1, n + 1) if n % a == 0))
    R.check("the block law #{b < g m : gcd(g, b) = 1} = m phi(g)",
            all(sum(1 for b in range(g * m) if gcd(g, b) == 1)
                == m * int(totient(g))
                for g in range(1, 13) for m in range(1, 5)))
    R.check(f"G({n}) = sum over ad = N of h(a, d) = psi({n})", G(n) == psi)

    R.note("""
        The fibre value is multiplicative in the pair, so G is multiplicative
        and it is enough to check it on prime powers, where
        h(p^(k-j), p^j) = phi(p^j) for 1 <= j <= k-1 and the two end terms
        contribute 1 and p^k, giving G(p^k) = p^k + p^(k-1).  Two
        multiplicative functions agreeing on prime powers are equal, so
        G = Psi = mu^2 * id and the second headline follows.
    """)
    R.check("G is multiplicative on coprime arguments",
            all(G(m * q) == G(m) * G(q)
                for m in range(1, 13) for q in range(1, 13) if gcd(m, q) == 1))
    R.check("G(p^k) = p^k + p^(k-1), agreeing with psi",
            all(G(p**k) == p**k + p**(k-1) == dedekind_psi(p**k)
                for p in (2, 3, 5) for k in (1, 2, 3)))
    R.check("Psi = mu^2 * id on the squarefree divisor sum: "
            "G(N) = sum over squarefree d | N of N/d",
            G(n) == dedekind_psi_divisor_sum(n))

    # ---- 7 -------------------------------------------------------------
    R.section("7. What the formalization does with this")
    R.note("""
        The formalization records the index set as the triples
        (ModularCurve.primCosetReps), reindexes them by the
        divisors-antidiagonal (card_primCosetReps_eq_sum), and counts each
        fibre by the totient block fact (card_filter_coprime_range_mul) to
        get dedekindPsiFibre and card_fibre.  Multiplicativity of the summand
        (h_mul, isMultiplicative_G) reduces the count to prime powers
        (h_prime_pow, G_prime_pow), and G_eq_Psi, Psi_apply identify the
        result with psi.  The double-coset statement behind section 8.1 is
        exists_eq_mul_diagonal_mul_of_gcd_eq_one, which exhibits the two outer
        SL_2(Z) factors for a primitive matrix; the section-5 route to the
        same number is card_quotient_borel and card_projectiveLine_zmod.
    """)
    R.note("""
        Concretely, the matrices in this demo are the ones the q-expansion
        layer enumerates: the triples (a, b, d) index the cosets of
        Gamma_0(N), and the row lattice of [[a, b], [0, d]] modulo N is a
        cyclic subgroup of order N in (Z/N)^2 -- a point of the projective
        line of section 2.  The reduced-row-lattice map makes that explicit.
    """)
    gen_classes = [canonical_pair(n, reduced_row_lattice_generator(n, t))
                   for t in triples]
    R.data("(a,b,d) |-> generator of its row lattice mod N, first three: "
           f"{[(t, reduced_row_lattice_generator(n, t)) for t in triples[:3]]}")
    R.check("each triple's row lattice is cyclic of order N and its generator "
            "is a unimodular pair",
            all(reduced_row_lattice_generator(n, t) is not None
                and element_order(n, reduced_row_lattice_generator(n, t)) == n
                and gcd(*reduced_row_lattice_generator(n, t), n) == 1
                for t in triples))
    R.check("the triples and the projective line match bijectively through "
            "that generator",
            len(set(gen_classes)) == len(projective_line(n)) == len(triples))

    R.finish()


if __name__ == "__main__":
    main()
