"""Riemann-Roch — illustrative demo.

CONCEPT
    For a divisor D on a smooth projective curve of genus g,

        ell(D) - ell(K - D) = deg D + 1 - g,

    where ell(D) = dim L(D) with L(D) = {f : div(f) >= -D}, and K is a
    canonical divisor: deg K = 2g - 2 and ell(K) = g.  Equivalently the
    Riemann inequality ell(D) >= deg D + 1 - g, with equality as soon as
    deg D > 2g - 2.

FLT ANCHOR
    AlgebraicCurve.RiemannInequality, RiemannIndexFormula, FunctionFieldRiemannRoch
        (Def_AlgebraicCurve_RiemannRochRows.lean)
    AlgebraicCurve.ell, indexOfSpecialty     (Def_AlgebraicCurve_AdelicIndex.lean)
    AlgebraicCurve.HasCanonicalDivisor, genus (Def_AlgebraicCurve_CanonicalDivisor.lean)

WHY IT MATTERS FOR FLT
    Riemann-Roch is how degree information about divisors becomes dimension
    information about spaces of functions: it is the engine behind the genus
    computations and the degree counts on J_0(N) used by the Hecke action and
    the Eisenstein-ideal argument (math/009).  The formalization carries it for
    an arbitrary function field satisfying IsCurveOver; this demo computes it
    in the cases where ell(D) is elementary, so the identity can be seen rather
    than assumed.

RUN
    python3 riemann_roch.py
    python3 riemann_roch.py > riemann_roch.expected.txt
"""

from ffcurve import EllipticCurve, FiniteField
from ffcurve.riemann_roch import (basis, canonical_degree, genus_from_canonical,
                                  l_dim, monomial_str, monomials, non_gap_orders,
                                  pole_order)
from report import Report

FAILURES = []


def names(g, monos):
    return ", ".join(monomial_str(g, m) for m in monos)


def main():
    R = Report("Riemann-Roch")

    R.note("""
        For a divisor D on a smooth projective curve of genus g, let L(D) be
        the space of rational functions whose poles are bounded by D, and
        ell(D) its dimension.  Riemann-Roch says that L(D) and L(K - D), for K
        a canonical divisor, together account for deg D + 1 - g dimensions.
    """)

    # ---- 1 -------------------------------------------------------------
    R.section("1. The statement")
    R.data("ell(D) - ell(K - D) = deg D + 1 - g")
    R.data("deg K = 2g - 2,   ell(K) = g,   genus = (deg K + 2) / 2")
    R.note("""
        The quantity ell(K - D) is the index of specialty: it vanishes as soon
        as deg D > 2g - 2, which gives the Riemann inequality
        ell(D) >= deg D + 1 - g with equality in that range.
    """)
    R.note("""
        To compute ell(D) concretely, take D = n*P for a rational Weierstrass
        point P of a hyperelliptic curve y^2 = f(x), deg f = 2g + 1.  The
        monomials x^i y^j have pole order 2i + (2g + 1)j at P, so those of
        order at most n span L(n*P).  They are not independent: the Weierstrass
        relation y^2 = f(x) makes y^2 x^i and x^(i + 2g + 1) have the same pole
        order, so their difference has smaller order.  A basis has one function
        per distinct order, hence

            ell(n*P) = #{ 2i + (2g+1)j <= n },   counted without multiplicity,

        i.e. the number of non-gaps at most n.  For g = 0 every order is a
        non-gap and the basis is 1, x, x^2, ... .
    """)

    # ---- 2 -------------------------------------------------------------
    R.section("2. Genus 0: the projective line")
    R.note("""
        On P^1 take D = n*infinity.  Then L(D) is the space of polynomials of
        degree at most n, of dimension n + 1, and the canonical divisor is
        -2*infinity (the differential dt has a double pole and no zeros).
    """)
    for n in range(5):
        R.data(f"n = {n}:  basis {names(0, basis(0, n))}   ell = {l_dim(0, n)}")
    R.check("genus 0: ell(n*inf) = n + 1 for n = 0..4",
            all(l_dim(0, n) == n + 1 for n in range(5)))
    R.check("genus 0: Riemann-Roch holds for n = 0..4",
            all(l_dim(0, n) - l_dim(0, canonical_degree(0) - n) == n + 1 - 0
                for n in range(5)))
    R.check("genus 0: deg K = -2 and ell(K) = 0 = g",
            canonical_degree(0) == -2 and l_dim(0, canonical_degree(0)) == 0)

    # ---- 3 -------------------------------------------------------------
    R.section("3. Genus 1: an elliptic curve")
    R.note("""
        For an elliptic curve a degree-zero divisor is principal exactly when
        its points sum to O, so a canonical divisor may be taken to be 0: the
        holomorphic differential dx/(2y) has neither zeros nor poles.  The
        non-gaps at O are generated by 2 and 3, so the single gap is order 1.
    """)
    F = FiniteField(7)
    E = EllipticCurve(F, -1, 0)
    R.data(f"concrete model: E: {E!r},  #E = {E.cardinality()}")
    for n in range(6):
        R.data(f"n = {n}:  spanning monomials {names(1, monomials(1, n))}"
               f"   count {len(monomials(1, n))}")
        R.data(f"        basis {names(1, basis(1, n))}   ell = {l_dim(1, n)}")
    R.note("""
        At n = 6 the two counts differ: x^3 and y^2 both have pole order 6 and
        are related by y^2 = x^3 - x for this curve, so the spanning set has 7
        elements but L(6*O) has dimension 6.
    """)
    R.check("genus 1: ell(n*O) = n for n >= 1 and ell(0) = 1",
            l_dim(1, 0) == 1 and all(l_dim(1, n) == n for n in range(1, 7)))
    R.check("genus 1: the basis realises exactly the non-gaps at O",
            all([pole_order(1, m) for m in basis(1, n)] == non_gap_orders(1, n)
                for n in range(8)))
    R.check("genus 1: the only gap at O is pole order 1",
            [m for m in range(8) if m not in non_gap_orders(1, 7)] == [1])
    R.check("genus 1: spanning monomials outnumber the basis once orders repeat",
            len(monomials(1, 6)) == 7 and l_dim(1, 6) == 6)
    R.check("genus 1: K = 0, so deg K = 0 and ell(K) = 1 = g",
            canonical_degree(1) == 0 and l_dim(1, canonical_degree(1)) == 1)
    R.check("genus 1: Riemann-Roch holds for n = 0..8",
            all(l_dim(1, n) - l_dim(1, canonical_degree(1) - n) == n + 1 - 1
                for n in range(9)))

    # ---- 4 -------------------------------------------------------------
    R.section("4. Higher genus: hyperelliptic curves")
    R.note("""
        For y^2 = f(x) with deg f = 2g + 1 the point at infinity is a
        Weierstrass point with semigroup <2, 2g + 1>, and the canonical divisor
        is (2g - 2)*infinity.  The table computes both sides of Riemann-Roch on
        D = n*infinity.  While deg D <= 2g - 2 the index of specialty
        ell(K - D) is nonzero and the Riemann inequality is strict; beyond that
        point ell(D) = deg D + 1 - g.
    """)
    R.data("g | n | ell(n*inf) | ell(K - n*inf) | deg D + 1 - g | Riemann-Roch")
    for g in (2, 3):
        for n in range(2 * g + 3):
            left = l_dim(g, n) - l_dim(g, canonical_degree(g) - n)
            rhs = n + 1 - g
            R.data(f"{g} | {n} | {l_dim(g, n)} | "
                   f"{l_dim(g, canonical_degree(g) - n)} | {rhs} | "
                   f"{'ok' if left == rhs else 'MISMATCH'}")
    R.check("genus 2, 3: Riemann-Roch holds on every row above",
            all(l_dim(g, n) - l_dim(g, canonical_degree(g) - n) == n + 1 - g
                for g in (2, 3) for n in range(2 * g + 3)))
    R.check("genus 1, 2, 3: repeated orders make the spanning set larger than ell",
            [len(monomials(g, 2 * (2 * g + 1))) - l_dim(g, 2 * (2 * g + 1))
             for g in (1, 2, 3)] == [1, 1, 1])
    R.check("deg K = 2g - 2 and ell(K) = g for g = 2, 3, 4",
            all(canonical_degree(g) == 2 * g - 2 and l_dim(g, canonical_degree(g)) == g
                for g in (2, 3, 4)))
    R.check("genus = (deg K + 2) / 2 for g = 0..4",
            all(genus_from_canonical(canonical_degree(g)) == g for g in range(5)))
    R.check("Riemann inequality ell(D) >= deg D + 1 - g for g = 1..4",
            all(l_dim(g, n) >= n + 1 - g for g in range(1, 5)
                for n in range(2 * g + 3)))
    R.check("equality exactly when deg D > 2g - 2",
            all((l_dim(g, n) == n + 1 - g) == (n > 2 * g - 2)
                for g in range(1, 5) for n in range(2 * g + 3)))

    # ---- 5 -------------------------------------------------------------
    R.section("5. The formalization")
    R.note("""
        In AlgebraicCurve the ingredients of the statement are: LSpace D, the
        function space L(D); ell D = finrank K (LSpace D); and
        indexOfSpecialty D = ell (K - D).  RiemannRochRows.lean defines, as
        Props, RiemannInequality (deg D + 1 - genus <= ell D),
        RiemannIndexFormula (indexOfSpecialty D = ell D - (deg D + 1 - genus))
        and FunctionFieldRiemannRoch (ell D - ell (K - D) = deg D + 1 - genus).
    """)
    R.note("""
        Genus is not assumed.  CanonicalDivisor.lean defines it from a
        canonical divisor by genus = (deg K + 2) / 2, which is the formula
        checked above; ell(K) = g then follows from Riemann-Roch rather than
        being built in.  In the FLT proof this is what converts degree counts
        on J_0(N) into dimension counts feeding the Hecke action (math/009);
        the genus-1 case computed here is the elliptic curve of base/007.
    """)

    R.finish()


if __name__ == "__main__":
    main()
