/-
Ω is generated by `dπ` at a place, after FLT's
`P2M/Sol/S_AlgebraicCurve_exists_mem_D_eq_smul_D_of_isCurveOver.lean` (1,422 ln),
pinned at `aa2d8b3`:

<https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_AlgebraicCurve_exists_mem_D_eq_smul_D_of_isCurveOver.lean>.

The pin file inlines its whole `s12` prelude (61 private helpers, ≈670 lines);
every one already has a public home in the port's
`AlgebraicCurve/Canonical/HasCanonicalDivisor.lean` (`ValSubringKaehlerSpanTop`,
`valSubringKaehlerSpanTop_of_isCurveOver_of_perfectField_s12`,
`Place.dCoordGenerates_of_valSubringKaehlerSpanTop`,
`Place.exists_mem_D_eq_smul_dCoord_s12`,
`Place.exists_unit_D_eq_smul_dCoord_s12`,
`isLocalization_centerIdeal_of_isDedekindDomain`, …). This module imports that
home rather than re-proving it and lands the headline at its `Theorems/` wrapper
statement.
-/
import FLTForHuman.AlgebraicCurve.Canonical.HasCanonicalDivisor
import Mathlib.RingTheory.Kaehler.Basic

set_option autoImplicit false

noncomputable section

open KaehlerDifferential

namespace AlgebraicCurve

/-- At a place `v` with `v.ord π = 1`, the Kähler differential of an integral `x`
is an integral multiple of `D π` (the pin
`exists_mem_D_eq_smul_D_of_isCurveOver`; statement from its `Theorems/` wrapper). -/
theorem exists_mem_D_eq_smul_D_of_isCurveOver
    {K F : Type*} [Field K] [Field F] [Algebra K F]
    [PerfectField K] [Algebra.EssFiniteType K F] [AlgebraicCurve.IsCurveOver K F]
    (v : AlgebraicCurve.Place K F) {π : F} (hπ : v.ord π = 1) {x : F} (hx : x ∈ v.toValuationSubring) :
    ∃ c : F, c ∈ v.toValuationSubring ∧ KaehlerDifferential.D K F x = c • KaehlerDifferential.D K F π :=
  exists_mem_D_eq_smul_D_of_isCurveOver_s12 v hπ hx

end AlgebraicCurve
