/-
  The Weierstrass function field is a finite extension of `RatFunc F`.

  Over a field `F`, the function field of a Weierstrass curve `W` is generated by
  `yCoord` over `RatFunc F` (`adjoin_yCoord_eq_top`), and since `yCoord` is
  integral over `RatFunc F` (`isIntegral_yCoord`, in
  `FunctionFieldQuadratic.lean`) the extension is finite-dimensional
  (`finiteDimensional_ratFunc_functionField`). Together these are the remaining
  hypotheses of `AlgebraicCurve.hasPrincipalDivisors_of_finiteDimensional_ratFunc`,
  which gives the capstone `WeierstrassCurve.Affine.hasPrincipalDivisors_functionField`
  (`PrincipalDivisors.lean`).

  Transcribed from `P2M/Sol/S_WeierstrassCurve_Affine_adjoin_yCoord_eq_top.lean`
  and `P2M/Sol/S_WeierstrassCurve_Affine_finiteDimensional_ratFunc_functionField.lean`
  (pinned `aa2d8b3`, 29 + 18 lines); the statements are the `Theorems/` wrappers',
  and both are their own graph nodes, so taking them here closes them too.
-/
import FLTForHuman.WeierstrassCurve.FunctionFieldQuadratic

set_option autoImplicit false

noncomputable section

open Polynomial

namespace WeierstrassCurve.Affine

theorem adjoin_yCoord_eq_top {F : Type*} [Field F] {W : WeierstrassCurve.Affine F} :
    IntermediateField.adjoin (RatFunc F) {WeierstrassCurve.Affine.yCoord W} = ⊤ := by
  rw [eq_top_iff]
  rintro z -
  have hpoly : ∀ p : F[X],
      polyToFunctionField W p ∈ IntermediateField.adjoin (RatFunc F) {yCoord W} := by
    intro p
    rw [← algebraMap_polynomial_eq_polyToFunctionField,
      IsScalarTower.algebraMap_apply F[X] (RatFunc F) W.FunctionField]
    exact IntermediateField.algebraMap_mem _ _
  have hcoord : ∀ r : W.CoordinateRing,
      algebraMap W.CoordinateRing W.FunctionField r
        ∈ IntermediateField.adjoin (RatFunc F) {yCoord W} := by
    intro r
    obtain ⟨p, q, rfl⟩ := CoordinateRing.exists_smul_basis_eq r
    rw [algebraMap_smul_basis]
    exact add_mem (hpoly p)
      (mul_mem (hpoly q) (IntermediateField.mem_adjoin_simple_self _ _))
  obtain ⟨a, b, hb, hab⟩ := IsFractionRing.div_surjective (A := W.CoordinateRing) z
  rw [← hab]
  exact div_mem (hcoord a) (hcoord b)

theorem finiteDimensional_ratFunc_functionField {F : Type*} [Field F]
    (W : WeierstrassCurve.Affine F) :
    FiniteDimensional (RatFunc F) W.FunctionField := by
  have h1 : FiniteDimensional (RatFunc F)
      (IntermediateField.adjoin (RatFunc F) {yCoord W}) :=
    IntermediateField.adjoin.finiteDimensional isIntegral_yCoord
  rw [adjoin_yCoord_eq_top (W := W)] at h1
  exact (IntermediateField.topEquiv
    (F := RatFunc F) (E := W.FunctionField)).toLinearEquiv.finiteDimensional

end WeierstrassCurve.Affine

end
