/-
The `X_H(M)` function-field vocabulary — the Γ_H block of FLT's
`Definitions/Def_ModularCurve_XH.lean` (lines 20–127)
(<https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_XH.lean>).

The pin's `Groups` block (lines 20–68) is **not** transcribed: its four lemmas
`translation_mem_GammaH`, `Gamma1_le_GammaH`, `GammaH_bot`, `GammaH_mono` are the
`CohCarrier` copies already public in `ModularForms/Defs/GammaH.lean`, where they
have their one home. This module lands the pin's `FunctionField` block (72–117)
plus the `xHFunctionFieldBar` abbreviation (123–126); the pin's `Jacobian` block
(`JH`/`torsionGaloisRep`/`tateGaloisRep`/`JHC`, lines 127–175) is off this cone and
deferred to the successor Jacobian topics.

The mathematics is thin over the ported vocabulary: `xHFunctionFieldC K M H` is
`qExpFunctionFieldC K (CohCarrier.GammaH M H)`, and `qExpFunctionFieldC`
(`ModularCurve/JqIntegralRatios.lean`), its monotonicity `qExpFunctionFieldC_mono`
and `x1FunctionFieldC` (`ModularCurve/X1/Defs.lean`), `CohCarrier.GammaH` and its
top/bottom specialization (`ModularForms/Defs/GammaH.lean`) and `laurentBaseChange`
(`ModularCurve/Defs/Laurent.lean`) are all ported. `xHFunctionFieldBar` stays an
`abbrev` as in the pin, so the `rfl` bridges unfold.

FLT provenance, pinned `aa2d8b3`:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_XH.lean
-/
import FLTForHuman.ModularCurve.JqIntegralRatios
import FLTForHuman.ModularCurve.X1.Defs
import FLTForHuman.ModularCurve.Defs.Laurent
import FLTForHuman.ModularForms.Defs.GammaH
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure

set_option autoImplicit false

noncomputable section

open UpperHalfPlane IntermediateField HahnSeries AlgebraicCurve CongruenceSubgroup

open scoped MatrixGroups

namespace ModularCurve

section FunctionField

variable (K : Type*) [Field K] (M : ℕ) (H : Subgroup (ZMod M)ˣ)

/-- The `q`-expansion function field of `X_H(M)` over `K`: the ratios of integral
`q`-expansions of forms for `Γ_H(M)`. -/
def xHFunctionFieldC : IntermediateField K (LaurentSeries K) :=
  qExpFunctionFieldC K (CohCarrier.GammaH M H)

/-- The `q`-expansion function field of `X_H(M)` over `ℚ`. -/
abbrev xHFunctionField : IntermediateField ℚ (LaurentSeries ℚ) :=
  xHFunctionFieldC ℚ M H

theorem xHFunctionFieldC_rat : xHFunctionFieldC ℚ M H = xHFunctionField M H := rfl

/-- The field generated by ratios of integral `q`-expansions of forms for
`Γ_H(M) ⊓ Γ₀(t)`. -/
def xHTopFunctionFieldC (t : ℕ) : IntermediateField K (LaurentSeries K) :=
  qExpFunctionFieldC K (CohCarrier.GammaH M H ⊓ Gamma0 t)

theorem xHFunctionFieldC_le_top (t : ℕ) : xHFunctionFieldC K M H ≤ xHTopFunctionFieldC K M H t :=
  qExpFunctionFieldC_mono K inf_le_left

theorem xHTopFunctionFieldC_one : xHTopFunctionFieldC K M H 1 = xHFunctionFieldC K M H := by
  have : CohCarrier.GammaH M H ⊓ Gamma0 1 = CohCarrier.GammaH M H := by
    refine le_antisymm inf_le_left (le_inf le_rfl ?_)
    intro A _
    rw [Gamma0_mem]
    exact Subsingleton.elim _ _
  rw [xHTopFunctionFieldC, this, xHFunctionFieldC]

theorem xHFunctionFieldC_le_x1 : xHFunctionFieldC K M H ≤ x1FunctionFieldC K M :=
  qExpFunctionFieldC_mono K (CohCarrier.Gamma1_le_GammaH M H)

theorem x0_le_xHFunctionFieldC : qExpFunctionFieldC K (Gamma0 M) ≤ xHFunctionFieldC K M H :=
  qExpFunctionFieldC_mono K (CohCarrier.GammaH_le_Gamma0 H)

variable {H} in

theorem xHFunctionFieldC_antitone {H' : Subgroup (ZMod M)ˣ} (h : H ≤ H') :
    xHFunctionFieldC K M H' ≤ xHFunctionFieldC K M H :=
  qExpFunctionFieldC_mono K (CohCarrier.GammaH_mono h)

theorem xHFunctionFieldC_top : xHFunctionFieldC K M ⊤ = qExpFunctionFieldC K (Gamma0 M) := by
  rw [xHFunctionFieldC, CohCarrier.GammaH_top]

theorem xHFunctionFieldC_bot : xHFunctionFieldC K M ⊥ = x1FunctionFieldC K M := by
  rw [xHFunctionFieldC, CohCarrier.GammaH_bot]
  rfl

end FunctionField

section Bar

variable (M : ℕ) (H : Subgroup (ZMod M)ˣ)

/-- `X_H(M)`'s function field base-changed to `ℚ̄`. -/
abbrev xHFunctionFieldBar :
    IntermediateField (AlgebraicClosure ℚ) (LaurentSeries (AlgebraicClosure ℚ)) :=
  laurentBaseChange (AlgebraicClosure ℚ) (xHFunctionField M H)

end Bar

end ModularCurve

end
