/-
  The generic `ℤ²`-lattice invariants: the generator of a subgroup of `ℤ`, the
  Hermite-normal-form lattice `latticeOf a d b`, and the canonical HNF triple
  `(aOf H, bOf H, dOf H)` recovered from an arbitrary `H ≤ ℤ × ℤ`.

  This is the second piece of row S: pure `ℤ`-lattice arithmetic, independent of
  the `PeriodPair` uniformization.  The pin wraps it in `namespace QuaternionAlgebra`
  (a `p2m_*` scaffolding artefact — there is no quaternion content), so the
  statements are re-homed verbatim in `IntPairSubgroup`, at the pin's last names.

  Pin source, `anthropics/fermats-last-theorem@aa2d8b3`:

    `P2M/Sol/S_PeriodPair_exists_mem_primCosetReps_and_jLattice_eq_of_isAddCyclic.lean`
    lines 246–428 (`namespace QuaternionAlgebra`, sections `NatGen`, `LatticeOf`,
    `ProductIndex`, `StructureTheorem`).

  <https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_PeriodPair_exists_mem_primCosetReps_and_jLattice_eq_of_isAddCyclic.lean>

  **Foundations are mathlib's, the invariants are the pin's.** Every primitive is
  in `v4.34.0`: `Int.subgroup_cyclic` (every subgroup of `ℤ` is cyclic, so
  `natGen K` is "the generator of `K`"), `Int.index_zmultiples`,
  `AddSubgroup.mem_closure_pair`, `AddSubgroup.mem_prod`, `AddSubgroup.index`,
  `AddSubgroup.{index_map,relIndex_mul_index,relIndex_sup_left,relIndex_comap,
  relIndex_top_right}`.  What is *not* in mathlib is the pin's named invariants —
  `natGen`, `latticeOf`, `aOf`, `dOf`, `bOf`, `latticeOf_canonical_eq` — which the
  `PeriodPair` transport (`Elliptic/PeriodPair/PrimCosetReps.lean`) consumes by
  name, so they are written as they stand.

  **The determinant-index formula did not replace the projection route.**  The pin
  proves `H.index = dOf H * aOf H` through the exact sequence
  `0 → ℤ → ℤ² → ℤ → 0` (`index_eq_comap_inr_mul_map_fst`) and the two
  `natGen`-indexes.  `AddSubgroup.index_eq_natAbs_det` would instead need a
  `Basis (Fin 2) ℤ ↥H` — i.e. an explicit HNF basis of `H`, which is *what this
  module constructs* (`latticeOf_canonical_eq`); computing the index from it
  would circularise the argument and add a basis-independence step.  The pin's
  route stands; recorded as the set's one audit negative.

  This module is mathlib-only.  It imports no `FLTForHuman` module.
-/
import Mathlib.GroupTheory.Archimedean
import Mathlib.LinearAlgebra.FreeModule.Int
import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Tactic

set_option autoImplicit false

noncomputable section

open AddSubgroup AddMonoidHom

namespace IntPairSubgroup

/-! ## `natGen` — the generator of a subgroup of `ℤ` -/

section NatGen

/-- The positive generator of a subgroup `K ≤ ℤ`: `K = zmultiples (natGen K)`.  Pin
`QuaternionAlgebra.natGen`. -/
noncomputable def natGen (K : AddSubgroup ℤ) : ℕ :=
  (Int.subgroup_cyclic K).choose.natAbs

/-- `zmultiples` only sees `|a|`. -/
theorem zmultiples_natAbs (a : ℤ) :
    AddSubgroup.zmultiples ((a.natAbs : ℕ) : ℤ) = AddSubgroup.zmultiples a := by
  ext x
  rw [Int.mem_zmultiples_iff, Int.mem_zmultiples_iff, Int.natAbs_dvd]

/-- `natGen` generates its subgroup. -/
theorem zmultiples_natGen (K : AddSubgroup ℤ) :
    AddSubgroup.zmultiples ((natGen K : ℕ) : ℤ) = K := by
  have h := (Int.subgroup_cyclic K).choose_spec
  rw [natGen, zmultiples_natAbs, AddSubgroup.zmultiples_eq_closure, ← h]

/-- The generator is a member. -/
theorem natGen_cast_mem (K : AddSubgroup ℤ) : ((natGen K : ℕ) : ℤ) ∈ K := by
  have h : ((natGen K : ℕ) : ℤ) ∈ AddSubgroup.zmultiples ((natGen K : ℕ) : ℤ) :=
    AddSubgroup.mem_zmultiples _
  rwa [zmultiples_natGen K] at h

/-- The index of a subgroup of `ℤ` is its generator. -/
theorem index_eq_natGen (K : AddSubgroup ℤ) : K.index = natGen K := by
  conv_lhs => rw [← zmultiples_natGen K]
  rw [Int.index_zmultiples, Int.natAbs_natCast]

/-- Every element of `K` is a multiple of the generator. -/
theorem dvd_of_mem_natGen {K : AddSubgroup ℤ} {y : ℤ} (hy : y ∈ K) :
    ((natGen K : ℕ) : ℤ) ∣ y := by
  rw [← zmultiples_natGen K, Int.mem_zmultiples_iff] at hy
  exact hy

end NatGen

/-! ## `latticeOf` — the HNF lattice generated by `(a, b)` and `(0, d)` -/

section LatticeOf

/-- The subgroup of `ℤ × ℤ` generated by `(a, b)` and `(0, d)`.  Pin
`QuaternionAlgebra.latticeOf`. -/
def latticeOf (a d : ℕ) (b : ℤ) : AddSubgroup (ℤ × ℤ) :=
  AddSubgroup.closure {(((a : ℕ) : ℤ), b), ((0 : ℤ), ((d : ℕ) : ℤ))}

/-- Membership in `latticeOf`, in coordinates. -/
theorem mem_latticeOf_iff {a d : ℕ} {b : ℤ} {z : ℤ × ℤ} :
    z ∈ latticeOf a d b ↔
      ∃ m n : ℤ, z = (m * (a : ℤ), m * b + n * (d : ℤ)) := by
  rw [latticeOf, AddSubgroup.mem_closure_pair]
  constructor
  · rintro ⟨m, n, hmn⟩
    exact ⟨m, n, by
      rw [← hmn]
      simp only [Prod.smul_mk, smul_eq_mul, Prod.mk_add_mk, mul_zero, add_zero]⟩
  · rintro ⟨m, n, hz⟩
    exact ⟨m, n, by
      rw [hz]
      simp only [Prod.smul_mk, smul_eq_mul, Prod.mk_add_mk, mul_zero, add_zero]⟩

end LatticeOf

/-! ## The projection exact sequence `0 → B → A × B → A → 0` -/

section ProductIndex

variable {A B : Type*} [AddCommGroup A] [AddCommGroup B]

/-- The kernel of the first projection is the range of the second inclusion. -/
theorem ker_fst_eq_range_inr : (fst A B).ker = (inr A B).range := by
  ext ⟨x, y⟩
  simp [AddSubgroup.mem_prod, eq_comm]

/-- The index of `H ≤ A × B` is the product of the indexes of its projections. -/
theorem index_eq_comap_inr_mul_map_fst (H : AddSubgroup (A × B)) :
    H.index = (H.comap (inr A B)).index * (H.map (fst A B)).index := by
  have hsurj : Function.Surjective (fst A B) := fun x => ⟨(x, 0), rfl⟩
  have h1 : (H.map (fst A B)).index = (H ⊔ (fst A B).ker).index := by
    rw [AddSubgroup.index_map, AddMonoidHom.range_eq_top.mpr hsurj, AddSubgroup.index_top,
      mul_one]
  have h2 : H.relIndex (H ⊔ (fst A B).ker) * (H ⊔ (fst A B).ker).index = H.index :=
    AddSubgroup.relIndex_mul_index le_sup_left
  have h3 : H.relIndex (H ⊔ (fst A B).ker) = H.relIndex (fst A B).ker :=
    AddSubgroup.relIndex_sup_left (fst A B).ker H
  have h4 : (H.comap (inr A B)).index = H.relIndex (inr A B).range := by
    rw [← AddSubgroup.relIndex_top_right, AddSubgroup.relIndex_comap,
      ← AddMonoidHom.range_eq_map]
  rw [h4, ← ker_fst_eq_range_inr, ← h3, h1]
  exact h2.symm

end ProductIndex

/-! ## The structure theorem: the canonical HNF triple of `H ≤ ℤ × ℤ` -/

section StructureTheorem

variable (H : AddSubgroup (ℤ × ℤ))

/-- The first HNF coordinate: the generator of the first projection. -/
noncomputable def aOf : ℕ := natGen (H.map (fst ℤ ℤ))

/-- The third HNF coordinate: the generator of the kernel of the first projection. -/
noncomputable def dOf : ℕ := natGen (H.comap (inr ℤ ℤ))

/-- The index of `H` is `dOf H * aOf H`. -/
theorem index_eq_dOf_mul_aOf : H.index = dOf H * aOf H := by
  rw [index_eq_comap_inr_mul_map_fst, index_eq_natGen, index_eq_natGen, aOf, dOf]

/-- `(0, dOf H)` lies in `H`. -/
theorem zero_dOf_mem : ((0 : ℤ), ((dOf H : ℕ) : ℤ)) ∈ H :=
  natGen_cast_mem (H.comap (inr ℤ ℤ))

/-- The second coordinate of `(0, y) ∈ H` is a multiple of `dOf H`. -/
theorem dOf_dvd_of_zero_mem {y : ℤ} (hy : ((0 : ℤ), y) ∈ H) : ((dOf H : ℕ) : ℤ) ∣ y :=
  dvd_of_mem_natGen (K := H.comap (inr ℤ ℤ)) hy

/-- `H` contains a point over `aOf H`. -/
theorem exists_over_aOf : ∃ y : ℤ, (((aOf H : ℕ) : ℤ), y) ∈ H := by
  obtain ⟨z, hz, hz1⟩ := AddSubgroup.mem_map.mp (natGen_cast_mem (H.map (fst ℤ ℤ)))
  refine ⟨z.2, ?_⟩
  have hzeq : (((aOf H : ℕ) : ℤ), z.2) = z := by
    obtain ⟨z1, z2⟩ := z
    simp only [Prod.mk.injEq, and_true]
    exact hz1.symm
  rwa [hzeq]

/-- The second HNF coordinate, normalised to `[0, dOf H)`. -/
noncomputable def bOf : ℤ := (exists_over_aOf H).choose % ((dOf H : ℕ) : ℤ)

/-- `(aOf H, bOf H) ∈ H`. -/
theorem aOf_bOf_mem : (((aOf H : ℕ) : ℤ), bOf H) ∈ H := by
  have h0 := (exists_over_aOf H).choose_spec
  set y0 := (exists_over_aOf H).choose with hy0

  have hd : ((0 : ℤ), ((dOf H : ℕ) : ℤ) * (y0 / ((dOf H : ℕ) : ℤ))) ∈ H := by
    have := H.zsmul_mem (zero_dOf_mem H) (y0 / ((dOf H : ℕ) : ℤ))
    simpa [Prod.smul_mk, smul_eq_mul, mul_comm] using this
  have hmem := H.sub_mem h0 hd
  have heq : (((aOf H : ℕ) : ℤ), y0) - ((0 : ℤ), ((dOf H : ℕ) : ℤ) * (y0 / ((dOf H : ℕ) : ℤ)))
      = (((aOf H : ℕ) : ℤ), bOf H) := by
    rw [Prod.mk_sub_mk, sub_zero, bOf, ← hy0, Int.emod_def]
  rwa [heq] at hmem

/-- `bOf` is nonnegative. -/
theorem bOf_nonneg (hd : dOf H ≠ 0) : 0 ≤ bOf H :=
  Int.emod_nonneg _ (by exact_mod_cast hd)

/-- `bOf` is below `dOf`. -/
theorem bOf_lt (hd : dOf H ≠ 0) : bOf H < ((dOf H : ℕ) : ℤ) :=
  Int.emod_lt_of_pos _ (by omega)

/-- **The structure theorem**: every `H ≤ ℤ × ℤ` is `latticeOf (aOf H) (dOf H) (bOf H)`. -/
theorem latticeOf_canonical_eq : latticeOf (aOf H) (dOf H) (bOf H) = H := by
  apply le_antisymm
  ·
    rw [latticeOf]
    apply (AddSubgroup.closure_le H).mpr
    rintro z (rfl | rfl)
    · exact aOf_bOf_mem H
    · exact zero_dOf_mem H
  ·
    rintro ⟨x, y⟩ hxy
    rw [mem_latticeOf_iff]

    have hx : ((aOf H : ℕ) : ℤ) ∣ x := by
      have hmem : x ∈ H.map (fst ℤ ℤ) := ⟨(x, y), hxy, rfl⟩
      exact dvd_of_mem_natGen (K := H.map (fst ℤ ℤ)) hmem
    obtain ⟨m, rfl⟩ := hx

    have hsub : (((aOf H : ℕ) : ℤ) * m, m * bOf H) ∈ H := by
      have := H.zsmul_mem (aOf_bOf_mem H) m
      simpa [Prod.smul_mk, smul_eq_mul, mul_comm] using this
    have hfiber : ((0 : ℤ), y - m * bOf H) ∈ H := by
      have := H.sub_mem hxy hsub
      simpa using this
    obtain ⟨n, hn⟩ := dOf_dvd_of_zero_mem H hfiber
    refine ⟨m, n, ?_⟩
    rw [Prod.mk.injEq]
    constructor
    · ring
    · linear_combination hn

end StructureTheorem

end IntPairSubgroup

end
