/-
  The regular sequence `C ϖ, X₁, …, Xₙ`, the maximal ideal of a multivariate
  power series ring, and its adic completeness — the power-series facts the
  patching cluster needs.

  Generic facts about `MvPowerSeries σ R` that the patching cluster consumes:

  * `MvPowerSeries.isRegular_C_cons_X` — if `ϖ` is a non-zero-divisor and a
    non-unit, then `C ϖ, X₁, …, Xₙ` is a regular sequence in `R[[X₁,…,Xₙ]]`;
  * `MvPowerSeries.ofList_C_cons_X_eq_maximalIdeal` — over a local `R` with
    `maximalIdeal R = span {ϖ}`, that sequence generates the maximal ideal of
    `R[[X₁,…,Xₙ]]`;
  * `MvPowerSeries.mem_pow_span_X_of_coeff_eq_zero` — a series all of whose
    coefficients of total degree `< k` vanish lies in the `k`-th power of the ideal
    spanned by the variables;
  * `MvPowerSeries.residue_comp_C_surjective` — the residue map of `R[[X₁,…,Xₙ]]`
    composed with the constant embedding is surjective onto the residue field of
    `R`;
  * `MvPowerSeries.isAdicComplete_maximalIdeal` — if `R` is `𝔪`-adically complete
    then so is `R[[X₁,…,Xₙ]]` at its maximal ideal.

  The five statements are the pin's `Theorems/` wrappers verbatim; the proofs are
  transcribed from the pin's `P2M/Sol/S_MvPowerSeries_*.lean` (pinned `aa2d8b3`),
  whose `vanishIdeal` engine and `dropVar`/`smodEq`/`LocalCoeff` helpers are
  written **once** here (the pin repeats them across its `S_` files, playbook §2).
  Everything but the five statements is `private`.

  The fourth fact the descent needs, `IsNoetherianRing (MvPowerSeries σ R)` for
  finite `σ` over a Noetherian `R`, is now a mathlib **instance**
  (`MvPowerSeries.instIsNoetherianRing`, `Mathlib.RingTheory.MvPowerSeries.Equiv`),
  so the pin's `MvPowerSeries.isNoetherianRing_of_finite` is not ported; the
  descent calls `inferInstance`.

  **Why this module exists.** Work order §0 claims `free_and_ker_eq_span` is
  "self-contained (mathlib plus T11's `PatchingDatum`)" and independent of SET 5.
  That is not the case: the pin's node imports and uses these four
  `MvPowerSeries.*` lemmas. The three absent ones were ported by SET 4 so the
  descent builds; SET 5 extends the same module with the two adic-completeness
  facts (`residue_comp_C_surjective`, `isAdicComplete_maximalIdeal`) rather than
  re-deriving the shared engine in a new file.
-/
import Mathlib.RingTheory.MvPowerSeries.Inverse
import Mathlib.RingTheory.MvPowerSeries.Equiv
import Mathlib.RingTheory.MvPowerSeries.Trunc
import Mathlib.RingTheory.AdicCompletion.Noetherian
import Mathlib.RingTheory.Regular.RegularSequence
import Mathlib.RingTheory.Regular.IsSMulRegular
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.Algebra.GroupWithZero.NonZeroDivisors
import Mathlib.Data.Finsupp.Order

set_option autoImplicit false

open MvPowerSeries

universe u v

namespace MvPowerSeriesReg

open MvPowerSeries

variable {σ : Type u} {R : Type v} [CommRing R]

/-- The ideal of series whose coefficients vanish on the monomials supported
inside `S`. Used to identify the ideals generated by the variables; this is the
pin's `vanishIdeal` (private here). -/
private def vanishIdeal (S : Set σ) (𝔞 : Ideal R) : Ideal (MvPowerSeries σ R) where
  carrier := {φ | ∀ m : σ →₀ ℕ, (∀ j ∈ S, m j = 0) → coeff m φ ∈ 𝔞}
  zero_mem' := fun m _ => by simp
  add_mem' := fun {φ ψ} hφ hψ m hm => by
    rw [map_add]; exact 𝔞.add_mem (hφ m hm) (hψ m hm)
  smul_mem' := fun ψ φ hφ m hm => by
    classical
    rw [smul_eq_mul, coeff_mul]
    refine 𝔞.sum_mem fun p hp => 𝔞.mul_mem_left _ (hφ p.2 fun j hj => ?_)
    have h := Finset.HasAntidiagonal.mem_antidiagonal.mp hp
    have : p.2 j ≤ m j := by rw [← h]; exact Nat.le_add_left _ _
    have hmj := hm j hj
    omega

private theorem mem_vanishIdeal_iff {S : Set σ} {𝔞 : Ideal R} {φ : MvPowerSeries σ R} :
    φ ∈ vanishIdeal S 𝔞 ↔ ∀ m : σ →₀ ℕ, (∀ j ∈ S, m j = 0) → coeff m φ ∈ 𝔞 := Iff.rfl

private theorem X_mem_vanishIdeal {S : Set σ} (𝔞 : Ideal R) {j : σ} (hj : j ∈ S) :
    (X j : MvPowerSeries σ R) ∈ vanishIdeal S 𝔞 := by
  classical
  intro m hm
  rw [coeff_X, ite_eq_right]
  · exact 𝔞.zero_mem
  · rintro rfl
    have := hm j hj
    simp at this

private theorem C_mem_vanishIdeal (S : Set σ) {𝔞 : Ideal R} {a : R} (ha : a ∈ 𝔞) :
    (C a : MvPowerSeries σ R) ∈ vanishIdeal S 𝔞 := by
  classical
  intro m _
  rw [coeff_C]
  split_ifs
  · exact ha
  · exact 𝔞.zero_mem

private theorem map_C_sup_span_le_vanishIdeal (S : Set σ) (𝔞 : Ideal R) :
    𝔞.map (C : R →+* MvPowerSeries σ R) ⊔ Ideal.span ((X : σ → MvPowerSeries σ R) '' S) ≤
      vanishIdeal S 𝔞 := by
  refine sup_le ?_ ?_
  · rw [Ideal.map_le_iff_le_comap]
    intro a ha
    exact C_mem_vanishIdeal S ha
  · rw [Ideal.span_le]
    rintro _ ⟨j, hj, rfl⟩
    exact X_mem_vanishIdeal 𝔞 hj

private theorem vanishIdeal_le_of_principal (S : Finset σ) (a : R) :
    vanishIdeal (↑S : Set σ) (Ideal.span {a}) ≤
      Ideal.span {(C a : MvPowerSeries σ R)} ⊔ Ideal.span ((X : σ → MvPowerSeries σ R) '' ↑S) := by
  classical
  induction S using Finset.induction_on with
  | empty =>
    intro φ hφ

    have hdiv : ∀ m : σ →₀ ℕ, ∃ b : R, coeff m φ = a * b := fun m => by
      obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp (hφ m (by simp))
      exact ⟨b, by rw [← hb, mul_comm]⟩
    choose g hg using hdiv
    have hφeq : φ = C a * (show MvPowerSeries σ R from g) := by
      ext m
      rw [coeff_C_mul, hg m, coeff_apply]
    rw [hφeq]
    exact Ideal.mem_sup_left (Ideal.mul_mem_right _ _ (Ideal.subset_span rfl))
  | insert j S hjS ih =>
    intro φ hφ

    let h : MvPowerSeries σ R := fun m => if m j = 0 then φ m else 0
    have hcoeff : ∀ m : σ →₀ ℕ, coeff m h = if m j = 0 then coeff m φ else 0 := fun m => rfl
    have hX : (X j : MvPowerSeries σ R) ∣ φ - h := by
      rw [X_dvd_iff]
      intro m hm
      rw [map_sub, hcoeff, ite_eq_left hm, sub_self]
    have hh : h ∈ vanishIdeal (↑S : Set σ) (Ideal.span {a}) := by
      intro m hm
      rw [hcoeff]
      split_ifs with hmj
      · exact hφ m (fun i hi => by
          rcases Finset.mem_insert.mp (Finset.mem_coe.mp hi) with rfl | hi
          · exact hmj
          · exact hm i (Finset.mem_coe.mpr hi))
      · exact Ideal.zero_mem _
    have hsub : Ideal.span ((X : σ → MvPowerSeries σ R) '' ↑S) ≤
        Ideal.span ((X : σ → MvPowerSeries σ R) '' ↑(insert j S)) :=
      Ideal.span_mono (Set.image_mono (by simp))
    have h1 : φ - h ∈ Ideal.span ((X : σ → MvPowerSeries σ R) '' ↑(insert j S)) := by
      obtain ⟨q, hq⟩ := hX
      rw [hq]
      exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨j, by simp, rfl⟩)
    have h2 := (sup_le_sup_left hsub _) (ih hh)
    have : φ = (φ - h) + h := by ring
    rw [this]
    exact Ideal.add_mem _ (Ideal.mem_sup_right h1) h2

private theorem vanishIdeal_eq_of_principal (S : Finset σ) (a : R) :
    vanishIdeal (↑S : Set σ) (Ideal.span {a}) =
      Ideal.span {(C a : MvPowerSeries σ R)} ⊔ Ideal.span ((X : σ → MvPowerSeries σ R) '' ↑S) := by
  refine le_antisymm (vanishIdeal_le_of_principal S a) ?_
  have := map_C_sup_span_le_vanishIdeal (↑S : Set σ) (Ideal.span {a} : Ideal R)
  rwa [Ideal.map_span, Set.image_singleton] at this

private theorem vanishIdeal_bot_eq (S : Finset σ) :
    vanishIdeal (↑S : Set σ) (⊥ : Ideal R) = Ideal.span ((X : σ → MvPowerSeries σ R) '' ↑S) := by
  have h := vanishIdeal_eq_of_principal S (0 : R)
  rw [Ideal.span_singleton_eq_bot.mpr rfl] at h
  rw [h, map_zero, Ideal.span_singleton_eq_bot.mpr rfl, bot_sup_eq]

private theorem mem_vanishIdeal_of_X_mul_mem {S : Set σ} {𝔞 : Ideal R} {i : σ} (hi : i ∉ S)
    {φ : MvPowerSeries σ R} (h : X i * φ ∈ vanishIdeal S 𝔞) : φ ∈ vanishIdeal S 𝔞 := by
  intro m hm
  have := h (Finsupp.single i 1 + m) fun j hj => by
    have hji : j ≠ i := fun e => hi (e ▸ hj)
    rw [Finsupp.add_apply, Finsupp.single_eq_of_ne hji, hm j hj]
  rwa [X_def, coeff_add_monomial_mul, one_mul] at this

private theorem mem_vanishIdeal_of_C_mul_mem {S : Set σ} {a : R} (ha : a ∈ nonZeroDivisors R)
    {φ : MvPowerSeries σ R} (h : C a * φ ∈ vanishIdeal S (⊥ : Ideal R)) :
    φ ∈ vanishIdeal S (⊥ : Ideal R) := by
  intro m hm
  have := h m hm
  rw [coeff_C_mul, Ideal.mem_bot] at this
  exact Ideal.mem_bot.mpr ((mem_nonZeroDivisors_iff.mp ha).1 _ this)

private theorem setOf_mem_take_ofFn {α : Type*} {n : ℕ} (f : Fin n → α) (i : ℕ) :
    {x | x ∈ (List.ofFn f).take i} = f '' {j : Fin n | (j : ℕ) < i} := by
  ext x
  simp only [Set.mem_ofPred_eq, Set.mem_image]
  constructor
  · intro hx
    obtain ⟨k, hk, rfl⟩ := List.mem_iff_getElem.mp hx
    simp only [List.length_take, List.length_ofFn, lt_min_iff] at hk
    exact ⟨⟨k, hk.2⟩, hk.1, by simp⟩
  · rintro ⟨j, hj, rfl⟩
    rw [List.mem_iff_getElem]
    refine ⟨j, by simp; omega, by simp⟩

private theorem ofList_take_ofFn_X {n : ℕ} (i : ℕ) :
    Ideal.ofList ((List.ofFn (X : Fin n → MvPowerSeries (Fin n) R)).take i) =
      vanishIdeal (↑(Finset.univ.filter fun j : Fin n => (j : ℕ) < i) : Set (Fin n)) (⊥ : Ideal R) := by
  rw [vanishIdeal_bot_eq, Ideal.ofList, setOf_mem_take_ofFn, Finset.coe_filter]
  simp

private theorem ofList_ofFn_X {n : ℕ} :
    Ideal.ofList (List.ofFn (X : Fin n → MvPowerSeries (Fin n) R)) =
      vanishIdeal (Set.univ : Set (Fin n)) (⊥ : Ideal R) := by
  have h := ofList_take_ofFn_X (R := R) (n := n) n
  rw [List.take_of_length_le (by simp)] at h
  rw [h]
  congr 1
  ext j
  simp

private theorem ideal_smul_top_eq {A : Type*} [CommRing A] (I : Ideal A) :
    (I • ⊤ : Submodule A A) = I := by
  rw [smul_eq_mul, Ideal.mul_top]

private theorem isWeaklyRegular_X (n : ℕ) :
    RingTheory.Sequence.IsWeaklyRegular (MvPowerSeries (Fin n) R)
      (List.ofFn (X : Fin n → MvPowerSeries (Fin n) R)) := by
  refine ⟨fun i hi => ?_⟩
  rw [ofList_take_ofFn_X, ideal_smul_top_eq, isSMulRegular_quotient_iff_mem_of_smul_mem]
  intro φ hφ
  rw [List.getElem_ofFn, smul_eq_mul] at hφ
  refine mem_vanishIdeal_of_X_mul_mem ?_ hφ
  simp

private theorem isWeaklyRegular_X_append_C (n : ℕ) {ϖ : R} (hϖ : ϖ ∈ nonZeroDivisors R) :
    RingTheory.Sequence.IsWeaklyRegular (MvPowerSeries (Fin n) R)
      (List.ofFn (X : Fin n → MvPowerSeries (Fin n) R) ++ [C ϖ]) := by
  rw [RingTheory.Sequence.isWeaklyRegular_append_iff]
  refine ⟨isWeaklyRegular_X n, ?_⟩
  rw [RingTheory.Sequence.isWeaklyRegular_singleton_iff, ofList_ofFn_X, ideal_smul_top_eq,
    isSMulRegular_quotient_iff_mem_of_smul_mem]
  intro φ hφ
  rw [smul_eq_mul] at hφ
  exact mem_vanishIdeal_of_C_mul_mem hϖ hφ

private theorem ofList_X_append_C (n : ℕ) (ϖ : R) :
    Ideal.ofList (List.ofFn (X : Fin n → MvPowerSeries (Fin n) R) ++ [C ϖ]) =
      vanishIdeal (Set.univ : Set (Fin n)) (Ideal.span {ϖ}) := by
  rw [Ideal.ofList_append, Ideal.ofList_singleton, ofList_ofFn_X, ← Finset.coe_univ,
    vanishIdeal_bot_eq, vanishIdeal_eq_of_principal, sup_comm]

private theorem isRegular_X_append_C (n : ℕ) {ϖ : R} (hϖ : ϖ ∈ nonZeroDivisors R)
    (hu : ¬IsUnit ϖ) :
    RingTheory.Sequence.IsRegular (MvPowerSeries (Fin n) R)
      (List.ofFn (X : Fin n → MvPowerSeries (Fin n) R) ++ [C ϖ]) := by
  refine ⟨isWeaklyRegular_X_append_C n hϖ, ?_⟩
  rw [ofList_X_append_C, ideal_smul_top_eq]
  intro h
  have h1 : (1 : MvPowerSeries (Fin n) R) ∈ vanishIdeal (Set.univ : Set (Fin n)) (Ideal.span {ϖ}) := by
    rw [← h]; trivial
  have := h1 0 (by simp)
  rw [coeff_zero_one, Ideal.mem_span_singleton] at this
  exact hu (isUnit_of_dvd_one this)

private theorem ofList_X_append_C_eq_maximalIdeal [IsLocalRing R] (n : ℕ) {ϖ : R}
    (hϖ : IsLocalRing.maximalIdeal R = Ideal.span {ϖ}) :
    Ideal.ofList (List.ofFn (X : Fin n → MvPowerSeries (Fin n) R) ++ [C ϖ]) =
      IsLocalRing.maximalIdeal (MvPowerSeries (Fin n) R) := by
  apply le_antisymm
  · rw [Ideal.ofList, Ideal.span_le]
    intro x hx
    simp only [List.mem_append, List.mem_ofFn, List.mem_singleton, Set.mem_ofPred_eq] at hx
    rcases hx with ⟨j, rfl⟩ | rfl
    · rw [SetLike.mem_coe, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_iff_constantCoeff,
        constantCoeff_X]
      exact not_isUnit_zero
    · rw [SetLike.mem_coe, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_iff_constantCoeff,
        constantCoeff_C]
      have : ϖ ∈ IsLocalRing.maximalIdeal R := hϖ ▸ Ideal.mem_span_singleton_self ϖ
      exact this
  · intro φ hφ
    rw [ofList_X_append_C]
    intro m hm
    have hm0 : m = 0 := by ext j; exact hm j trivial
    subst hm0
    rw [← hϖ, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, coeff_zero_eq_constantCoeff]
    exact fun hc => hφ (isUnit_iff_constantCoeff.mpr hc)

/-- **Drop the coefficients of `φ` with a nonzero `i`-th exponent.** The pin's
`dropVar`, factored out of `mem_pow_span_X_of_coeff_eq_zero` so that the three
uses share one declaration (playbook §2). -/
private def dropVar (i : σ) (φ : MvPowerSeries σ R) : MvPowerSeries σ R :=
  fun m => if m i = 0 then φ m else 0

/-- The coefficient of `dropVar i φ` is `coeff m φ` exactly on the monomials with
`m i = 0`. The pin's `coeff_dropVar`. -/
private theorem coeff_dropVar (i : σ) (φ : MvPowerSeries σ R) (m : σ →₀ ℕ) :
    coeff m (dropVar i φ) = if m i = 0 then coeff m φ else 0 := rfl

end MvPowerSeriesReg

/-- **The sequence `C ϖ, X₁, …, Xₙ` is regular.** Stated verbatim from
`Theorems/Thm_MvPowerSeries_isRegular_C_cons_X.lean`. -/
theorem MvPowerSeries.isRegular_C_cons_X {R : Type u} [CommRing R] (n : ℕ) {ϖ : R}
    (hϖ : ϖ ∈ nonZeroDivisors R) (hu : ¬IsUnit ϖ) :
    RingTheory.Sequence.IsRegular (MvPowerSeries (Fin n) R)
      (MvPowerSeries.C ϖ :: List.ofFn (MvPowerSeries.X : Fin n → MvPowerSeries (Fin n) R)) := by
  have hperm : Ideal.ofList (C ϖ :: List.ofFn (X : Fin n → MvPowerSeries (Fin n) R)) =
      Ideal.ofList (List.ofFn (X : Fin n → MvPowerSeries (Fin n) R) ++ [C ϖ]) := by
    rw [Ideal.ofList_cons, Ideal.ofList_append, Ideal.ofList_singleton, sup_comm]
  refine ⟨⟨fun i hi => ?_⟩, ?_⟩
  · rw [isSMulRegular_quotient_iff_mem_of_smul_mem]
    intro φ hφ
    cases i with
    | zero =>
      simp only [List.take_zero, Ideal.ofList_nil, Submodule.bot_smul, Submodule.mem_bot,
        List.getElem_cons_zero] at hφ ⊢
      rw [smul_eq_mul] at hφ

      ext m
      have := congrArg (coeff m) hφ
      rw [coeff_C_mul, map_zero] at this
      rw [map_zero]
      exact (mem_nonZeroDivisors_iff.mp hϖ).1 _ this
    | succ k =>
      simp only [List.take_succ_cons, List.getElem_cons_succ, List.getElem_ofFn] at hφ ⊢
      rw [Ideal.ofList_cons, MvPowerSeriesReg.ofList_take_ofFn_X, MvPowerSeriesReg.vanishIdeal_bot_eq,
        ← MvPowerSeriesReg.vanishIdeal_eq_of_principal, MvPowerSeriesReg.ideal_smul_top_eq] at hφ ⊢
      rw [smul_eq_mul] at hφ
      refine MvPowerSeriesReg.mem_vanishIdeal_of_X_mul_mem ?_ hφ
      simp
  · rw [hperm]
    exact (MvPowerSeriesReg.isRegular_X_append_C n hϖ hu).top_ne_smul

/-- **`C ϖ, X₁, …, Xₙ` generates the maximal ideal.** Stated verbatim from
`Theorems/Thm_MvPowerSeries_ofList_C_cons_X_eq_maximalIdeal.lean`. -/
theorem MvPowerSeries.ofList_C_cons_X_eq_maximalIdeal {R : Type u} [CommRing R] [IsLocalRing R]
    (n : ℕ) {ϖ : R} (hϖ : IsLocalRing.maximalIdeal R = Ideal.span {ϖ}) :
    Ideal.ofList (MvPowerSeries.C ϖ :: List.ofFn (MvPowerSeries.X : Fin n → MvPowerSeries (Fin n) R)) =
      IsLocalRing.maximalIdeal (MvPowerSeries (Fin n) R) := by
  rw [Ideal.ofList_cons, ← MvPowerSeriesReg.ofList_X_append_C_eq_maximalIdeal n hϖ, Ideal.ofList_append,
    Ideal.ofList_singleton, sup_comm]

/-- **The augmentation ideal is spanned by the variables.** Stated verbatim from
`Theorems/Thm_MvPowerSeries_mem_pow_span_X_of_coeff_eq_zero.lean`. -/
theorem MvPowerSeries.mem_pow_span_X_of_coeff_eq_zero {σ : Type u} {R : Type v} [Finite σ]
    [CommRing R] (k : ℕ) (φ : MvPowerSeries σ R)
    (hφ : ∀ m : σ →₀ ℕ, m.degree < k → MvPowerSeries.coeff m φ = 0) :
    φ ∈ Ideal.span (Set.range (MvPowerSeries.X : σ → MvPowerSeries σ R)) ^ k := by
  classical
  have := Fintype.ofFinite σ
  set J : Ideal (MvPowerSeries σ R) := Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) with hJ
  induction k generalizing φ with
  | zero => simp
  | succ k ihk =>

    suffices h : ∀ (s : Finset σ) (ψ : MvPowerSeries σ R), (∀ m : σ →₀ ℕ, m.degree < k + 1 → coeff m ψ = 0) →
        (∀ m : σ →₀ ℕ, ¬ (m.support ⊆ s) → coeff m ψ = 0) → ψ ∈ J ^ (k + 1) by
      exact h Finset.univ φ hφ fun m hm => (hm (Finset.subset_univ _)).elim
    intro s
    induction s using Finset.induction_on with
    | empty =>
      intro ψ h0 hs
      have : ψ = 0 := by
        ext m
        by_cases hm : m = 0
        · subst hm; rw [map_zero]; exact h0 0 (by simp)
        · rw [map_zero]
          refine hs m fun hsub => hm ?_
          ext j
          have : j ∉ m.support := fun hj => by simpa using hsub hj
          simpa [Finsupp.mem_support_iff] using this
      rw [this]; exact Ideal.zero_mem _
    | insert i s hi ih =>
      intro ψ h0 hs
      have hdrop : ∀ m : σ →₀ ℕ,
          coeff m (MvPowerSeriesReg.dropVar i ψ) = if m i = 0 then coeff m ψ else 0 :=
        MvPowerSeriesReg.coeff_dropVar i ψ
      have hdiv : (X i : MvPowerSeries σ R) ∣ ψ - MvPowerSeriesReg.dropVar i ψ := by
        rw [X_dvd_iff]
        intro m hm
        rw [map_sub, hdrop, ite_eq_left hm, sub_self]
      obtain ⟨q, hq⟩ := hdiv

      have hqk : ∀ m : σ →₀ ℕ, m.degree < k → coeff m q = 0 := by
        intro m hm
        have h1 : coeff (Finsupp.single i 1 + m) (X i * q) = coeff m q := by
          rw [X, coeff_add_monomial_mul, one_mul]
        have h2 : coeff (Finsupp.single i 1 + m) (ψ - MvPowerSeriesReg.dropVar i ψ) = 0 := by
          rw [map_sub, hdrop, ite_eq_right (by simp), sub_zero]
          exact h0 _ (by rw [map_add, Finsupp.degree_single]; omega)
        rw [← h1, ← hq, h2]
      have hrest : MvPowerSeriesReg.dropVar i ψ ∈ J ^ (k + 1) := by
        refine ih _ ?_ ?_
        · intro m hm
          rw [hdrop]
          split_ifs
          · exact h0 m hm
          · rfl
        · intro m hm
          rw [hdrop]
          split_ifs with hmi
          · refine hs m fun hsub => hm fun j hj => ?_
            rcases Finset.mem_insert.mp (hsub hj) with rfl | h
            · exact absurd hmi (by simpa [Finsupp.mem_support_iff] using hj)
            · exact h
          · rfl
      have : ψ = MvPowerSeriesReg.dropVar i ψ + X i * q := by rw [← hq]; ring
      rw [this, pow_succ']
      exact Ideal.add_mem _ (pow_succ' J k ▸ hrest)
        (Ideal.mul_mem_mul (Ideal.subset_span ⟨i, rfl⟩) (ihk q hqk))

namespace MvPowerSeriesReg

open IsLocalRing

variable {σ : Type u} {R : Type v} [CommRing R]

/-- **The maximal ideal of `R[[X]]` is the preimage of `𝔪_R` under the constant
coefficient.** The pin's `maximalIdeal_eq_comap` (private here; the pin declares
it in both the `residue_comp_C_surjective` and `isAdicComplete_maximalIdeal`
files). -/
private theorem maximalIdeal_eq_comap [IsLocalRing R] :
    maximalIdeal (MvPowerSeries σ R) = (maximalIdeal R).comap (constantCoeff (σ := σ) (R := R)) := by
  ext φ
  rw [Ideal.mem_comap, mem_maximalIdeal, mem_maximalIdeal, mem_nonunits_iff, mem_nonunits_iff,
    isUnit_iff_constantCoeff]

/-- **The augmentation ideal is the kernel of the constant coefficient.** The
pin's `mem_span_X_of_constantCoeff_eq_zero` (private here). -/
private theorem mem_span_X_of_constantCoeff_eq_zero [Finite σ] (φ : MvPowerSeries σ R)
    (hφ : constantCoeff φ = 0) : φ ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) := by
  classical
  have := Fintype.ofFinite σ
  suffices h : ∀ (s : Finset σ) (ψ : MvPowerSeries σ R), constantCoeff ψ = 0 →
      (∀ m : σ →₀ ℕ, ¬ (m.support ⊆ s) → coeff m ψ = 0) →
      ψ ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) by
    exact h Finset.univ φ hφ fun m hm => (hm (Finset.subset_univ _)).elim
  intro s
  induction s using Finset.induction_on with
  | empty =>
    intro ψ h0 hs
    have : ψ = 0 := by
      ext m
      by_cases hm : m = 0
      · subst hm; simpa using h0
      · rw [map_zero]
        refine hs m fun hsub => hm ?_
        ext j
        have : j ∉ m.support := fun hj => by simpa using hsub hj
        simpa [Finsupp.mem_support_iff] using this
    rw [this]; exact Ideal.zero_mem _
  | insert i s hi ih =>
    intro ψ h0 hs
    have hdiv : (X i : MvPowerSeries σ R) ∣ ψ - dropVar i ψ := by
      rw [X_dvd_iff]
      intro m hm
      rw [map_sub, coeff_dropVar, ite_eq_left hm, sub_self]
    obtain ⟨q, hq⟩ := hdiv
    have hrest : dropVar i ψ ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) := by
      refine ih _ ?_ ?_
      · rw [← coeff_zero_eq_constantCoeff_apply, coeff_dropVar, ite_eq_left (by simp),
          coeff_zero_eq_constantCoeff_apply, h0]
      · intro m hm
        rw [coeff_dropVar]
        split_ifs with hmi
        · refine hs m fun hsub => hm fun j hj => ?_
          have hj' := hsub hj
          rcases Finset.mem_insert.mp hj' with rfl | h
          · exact absurd hmi (by simpa [Finsupp.mem_support_iff] using hj)
          · exact h
        · rfl
    have : ψ = dropVar i ψ + X i * q := by rw [← hq]; ring
    rw [this]
    exact Ideal.add_mem _ hrest (Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩))

/-- **`𝔐 = 𝔪·R[[X]] + (X)`.** The pin's `maximalIdeal_eq_map_C_sup_span_X`
(private here). -/
private theorem maximalIdeal_eq_map_C_sup_span_X [Finite σ] [IsLocalRing R] :
    maximalIdeal (MvPowerSeries σ R) =
      (maximalIdeal R).map (C (σ := σ) (R := R)) ⊔
        Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) := by
  apply le_antisymm
  · intro φ hφ
    rw [maximalIdeal_eq_comap, Ideal.mem_comap] at hφ
    have hsplit : φ = C (constantCoeff φ) + (φ - C (constantCoeff φ)) := by ring
    rw [hsplit]
    refine Ideal.add_mem _ (Ideal.mem_sup_left (Ideal.mem_map_of_mem _ hφ))
      (Ideal.mem_sup_right (mem_span_X_of_constantCoeff_eq_zero _ ?_))
    rw [map_sub, constantCoeff_C, sub_self]
  · refine sup_le ?_ ?_
    · rw [Ideal.map_le_iff_le_comap]
      intro a ha
      rw [Ideal.mem_comap, maximalIdeal_eq_comap, Ideal.mem_comap, constantCoeff_C]
      exact ha
    · rw [Ideal.span_le]
      rintro _ ⟨i, rfl⟩
      rw [SetLike.mem_coe, maximalIdeal_eq_comap, Ideal.mem_comap, constantCoeff_X]
      exact Ideal.zero_mem _

/-- `x ≡ y` modulo `I ^ n • ⊤` is `x - y ∈ I ^ n`. The pin's helper, shared by
the two adic arguments below (the pin repeats it in
`S_IsAdicComplete_map_of_surjective.lean`; see the note in
`FLTForHuman/Algebra/AdicCompleteMap.lean`). -/
private theorem smodEq_pow_smul_top_iff (I : Ideal R) (n : ℕ) (x y : R) :
    x ≡ y [SMOD (I ^ n • ⊤ : Submodule R R)] ↔ x - y ∈ I ^ n := by
  rw [SModEq.sub_mem, smul_eq_mul, Ideal.mul_top]

/-- **The truncation at total degree `k` is congruent to the series mod `(X)^k`.**
The pin's `sub_truncTotal_mem_pow_span_X` (private here). -/
private theorem sub_truncTotal_mem_pow_span_X [Finite σ] (k : ℕ) (φ : MvPowerSeries σ R) :
    φ - (truncTotal k φ : MvPolynomial σ R) ∈
      Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) ^ k := by
  refine mem_pow_span_X_of_coeff_eq_zero k _ fun m hm => ?_
  rw [map_sub, MvPolynomial.coeff_coe, coeff_truncTotal _ hm, sub_self]

section LocalCoeff

variable [IsLocalRing R]

local notation "𝔐" => maximalIdeal (MvPowerSeries σ R)
local notation "𝔪" => maximalIdeal R

/-- A coefficient of an element of `𝔐 ^ n` lies in `𝔪 ^ (n - deg)`. The pin's
`coeff_mem_pow_of_mem_pow` (private here). -/
private theorem coeff_mem_pow_of_mem_pow (n : ℕ) (x : MvPowerSeries σ R) (hx : x ∈ 𝔐 ^ n)
    (m : σ →₀ ℕ) : coeff m x ∈ 𝔪 ^ (n - m.degree) := by
  classical
  induction n generalizing x m with
  | zero => simp
  | succ n ih =>
    rw [pow_succ] at hx
    refine Submodule.mul_induction_on hx ?_ ?_
    · intro y hy z hz
      rw [coeff_mul]
      refine Ideal.sum_mem _ fun p hp => ?_
      rw [Finset.HasAntidiagonal.mem_antidiagonal] at hp
      have hdeg : p.1.degree + p.2.degree = m.degree := by rw [← map_add, hp]
      by_cases hp2 : p.2 = 0
      · have hp1 : p.1 = m := by simpa [hp2] using hp
        have hz0 : coeff p.2 z ∈ 𝔪 := by
          rw [hp2, coeff_zero_eq_constantCoeff_apply]
          rw [maximalIdeal_eq_comap, Ideal.mem_comap] at hz
          exact hz
        have hmem := Ideal.mul_mem_mul (ih y hy p.1) hz0
        rw [← pow_succ] at hmem
        rw [hp1] at hmem ⊢
        have hle : n + 1 - m.degree ≤ n - m.degree + 1 := by omega
        exact Ideal.pow_le_pow_right hle hmem
      · have hp2' : 0 < p.2.degree := by
          rw [Nat.pos_iff_ne_zero, Ne, Finsupp.degree_eq_zero_iff]
          exact hp2
        have hmem := Ideal.mul_mem_right (coeff p.2 z) _ (ih y hy p.1)
        have hle : n + 1 - m.degree ≤ n - p.1.degree := by omega
        exact Ideal.pow_le_pow_right hle hmem
    · intro y z hy hz
      rw [map_add]
      exact Ideal.add_mem _ hy hz

/-- Constants in `𝔪 ^ k` lie in `𝔐 ^ k`. The pin's `C_mem_pow` (private here). -/
private theorem C_mem_pow (k : ℕ) (c : R) (hc : c ∈ 𝔪 ^ k) :
    (C c : MvPowerSeries σ R) ∈ 𝔐 ^ k := by
  have h : (𝔪).map (C (σ := σ) (R := R)) ≤ 𝔐 := by
    rw [Ideal.map_le_iff_le_comap]
    intro a ha
    rw [Ideal.mem_comap, maximalIdeal_eq_comap, Ideal.mem_comap, constantCoeff_C]
    exact ha
  have := Ideal.pow_right_mono h k
  rw [← Ideal.map_pow] at this
  exact this (Ideal.mem_map_of_mem _ hc)

/-- The ideal spanned by the variables lies in `𝔐`. The pin's `span_X_le`. -/
private theorem span_X_le : Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) ≤ 𝔐 := by
  rw [Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  rw [SetLike.mem_coe, maximalIdeal_eq_comap, Ideal.mem_comap, constantCoeff_X]
  exact Ideal.zero_mem _

variable [Finite σ]

/-- A monomial of total degree `d` lies in `𝔐 ^ d`. The pin's
`monomial_one_mem_pow`. -/
private theorem monomial_one_mem_pow (m : σ →₀ ℕ) :
    (monomial m (1 : R) : MvPowerSeries σ R) ∈ 𝔐 ^ m.degree := by
  classical
  refine Ideal.pow_right_mono span_X_le m.degree (mem_pow_span_X_of_coeff_eq_zero _ _ fun m' hm' => ?_)
  rw [coeff_monomial, ite_eq_right]
  rintro rfl
  exact lt_irrefl _ hm'

/-- A monomial `m·c` with `c ∈ 𝔪 ^ (n - deg m)` lies in `𝔐 ^ n`. The pin's
`monomial_mem_pow`. -/
private theorem monomial_mem_pow (n : ℕ) (m : σ →₀ ℕ) (c : R) (hc : c ∈ 𝔪 ^ (n - m.degree)) :
    (monomial m c : MvPowerSeries σ R) ∈ 𝔐 ^ n := by
  have : (monomial m c : MvPowerSeries σ R) = C c * monomial m 1 := by
    rw [← monomial_zero_eq_C_apply, monomial_mul_monomial, zero_add, mul_one]
  rw [this]
  have hmem := Ideal.mul_mem_mul (C_mem_pow _ c hc) (monomial_one_mem_pow (R := R) m)
  rw [← pow_add] at hmem
  have hle : n ≤ n - m.degree + m.degree := by omega
  exact Ideal.pow_le_pow_right hle hmem

/-- Conversely, coefficient-wise membership in the right powers gives membership
in `𝔐 ^ n`. The pin's `mem_pow_of_coeff_mem_pow`. -/
private theorem mem_pow_of_coeff_mem_pow (n : ℕ) (x : MvPowerSeries σ R)
    (hx : ∀ m : σ →₀ ℕ, m.degree < n → coeff m x ∈ 𝔪 ^ (n - m.degree)) : x ∈ 𝔐 ^ n := by
  classical
  have hsplit : x = (truncTotal n x : MvPolynomial σ R) + (x - (truncTotal n x : MvPolynomial σ R)) := by ring
  rw [hsplit]
  refine Ideal.add_mem _ ?_ (Ideal.pow_right_mono span_X_le n (sub_truncTotal_mem_pow_span_X n x))
  have hcoe : ((truncTotal n x : MvPolynomial σ R) : MvPowerSeries σ R) =
      ∑ m ∈ (Finsupp.finite_of_degree_lt (σ := σ) n).toFinset, monomial m (coeff m x) := by
    rw [truncTotal, truncFinset_apply, ← MvPolynomial.coeToMvPowerSeries.ringHom_apply, map_sum]
    simp only [MvPolynomial.coeToMvPowerSeries.ringHom_apply, MvPolynomial.coe_monomial]
  rw [hcoe]
  refine Ideal.sum_mem _ fun m hm => monomial_mem_pow n m _ (hx m ?_)
  simpa using hm

/-- **`R[[X]]` is `𝔐`-adically complete when `R` is `𝔪`-adically complete.** The
pin's `isAdicComplete_maximalIdeal` (private here; the public statement is the
`Theorems/` wrapper). -/
private theorem isAdicComplete_maximalIdeal [IsAdicComplete (maximalIdeal R) R] :
    IsAdicComplete 𝔐 (MvPowerSeries σ R) := by
  have hH : IsHausdorff 𝔐 (MvPowerSeries σ R) := ⟨fun x hx => by
    ext m
    rw [map_zero]
    refine IsHausdorff.haus (inferInstance : IsHausdorff 𝔪 R) (coeff m x) fun k => ?_
    rw [SModEq.zero, smul_eq_mul, Ideal.mul_top]
    have hk := hx (k + m.degree)
    rw [SModEq.zero, smul_eq_mul, Ideal.mul_top] at hk
    have := coeff_mem_pow_of_mem_pow (k + m.degree) x hk m
    rwa [show k + m.degree - m.degree = k by omega] at this⟩
  have hP : IsPrecomplete 𝔐 (MvPowerSeries σ R) := ⟨fun g hg => by
    have hgd : ∀ {k l : ℕ}, k ≤ l → g l - g k ∈ 𝔐 ^ k := fun h => by
      have := (smodEq_pow_smul_top_iff _ _ _ _).mp (hg h)
      rwa [← neg_sub, Ideal.neg_mem_iff] at this
    have hc : ∀ m : σ →₀ ℕ, ∃ c : R, ∀ k, coeff m (g (k + m.degree)) - c ∈ 𝔪 ^ k := by
      intro m
      obtain ⟨c, hc⟩ := IsPrecomplete.prec (inferInstance : IsPrecomplete 𝔪 R)
        (f := fun k => coeff m (g (k + m.degree))) (fun {k l} hkl => by
          rw [smodEq_pow_smul_top_iff, ← map_sub]
          have := coeff_mem_pow_of_mem_pow (k + m.degree) _
            (hgd (show k + m.degree ≤ l + m.degree by omega)) m
          rw [show k + m.degree - m.degree = k by omega] at this
          rwa [← neg_sub, map_neg, Ideal.neg_mem_iff])
      exact ⟨c, fun k => (smodEq_pow_smul_top_iff _ _ _ _).mp (hc k)⟩
    choose c hc using hc
    let L : MvPowerSeries σ R := fun m => c m
    refine ⟨L, fun n => ?_⟩
    refine (smodEq_pow_smul_top_iff 𝔐 n (g n) L).mpr ?_
    refine mem_pow_of_coeff_mem_pow n _ fun m hm => ?_
    rw [map_sub]
    have h := hc m (n - m.degree)
    rw [show n - m.degree + m.degree = n by omega] at h
    exact h⟩
  exact ⟨⟩

end LocalCoeff

/-- **The residue map composed with `C` is surjective.** The pin's
`residue_comp_C_surjective` (private here; the public statement is the
`Theorems/` wrapper). -/
private theorem residue_comp_C_surjective [IsLocalRing R] :
    Function.Surjective (⇑(residue (MvPowerSeries σ R)) ∘ ⇑(C (σ := σ) (R := R))) := by
  intro x
  obtain ⟨φ, rfl⟩ := residue_surjective x
  refine ⟨constantCoeff φ, ?_⟩
  simp only [Function.comp_apply]
  rw [residue_def, residue_def]
  refine (Ideal.Quotient.eq (I := maximalIdeal (MvPowerSeries σ R))).mpr ?_
  rw [maximalIdeal_eq_comap, Ideal.mem_comap, map_sub, constantCoeff_C, sub_self]
  exact Ideal.zero_mem _

end MvPowerSeriesReg

/-- **The residue map of `R[[X]]` composed with `C` is surjective.** Stated
verbatim from `Theorems/Thm_MvPowerSeries_residue_comp_C_surjective.lean`. -/
theorem MvPowerSeries.residue_comp_C_surjective {σ : Type u} {R : Type v} [CommRing R]
    [IsLocalRing R] :
    Function.Surjective (⇑(IsLocalRing.residue (MvPowerSeries σ R)) ∘
      ⇑(MvPowerSeries.C (σ := σ) (R := R))) :=
  MvPowerSeriesReg.residue_comp_C_surjective

/-- **`R[[X]]` is adically complete at its maximal ideal.** Stated verbatim from
`Theorems/Thm_MvPowerSeries_isAdicComplete_maximalIdeal.lean`. -/
theorem MvPowerSeries.isAdicComplete_maximalIdeal {σ : Type u} {R : Type v} [Finite σ]
    [CommRing R] [IsLocalRing R] [IsAdicComplete (IsLocalRing.maximalIdeal R) R] :
    IsAdicComplete (IsLocalRing.maximalIdeal (MvPowerSeries σ R)) (MvPowerSeries σ R) :=
  MvPowerSeriesReg.isAdicComplete_maximalIdeal
