/-
The countable function-field descent: the headline

  `WeierstrassCurve.exists_intermediateField_countable_map_eq_and_finrankAlong_eq`

of the D column, together with the descent block it rests on. This is set **D-2** of
`topics/velu/WORKORDER-P2-basechange.md`; the work order is
`topics/velu/WORKORDER-P2b-intermediate-field.md`.

The mathematics is generic field theory over a countable subfield, not Weierstrass
geometry: given an integral finite endomorphism `ι` of `E.toAffine.FunctionField` over
an algebraically closed `K` of characteristic zero, one descends the pair `(E, ι)` to a
**countable** `K₀ ≤ K` and compares `finrankAlong` at `K` and at `AlgebraicClosure K₀`.
The pin's route is kept unchanged:

* `iA_*` descends the coefficients of a function-field element along a chosen
  subfield `K₀` (the coordinate-ring basis `Xⁿ`, `XⁿY` and the numerator/denominator of
  `IsLocalization.sec`);
* `iCa_*` builds the *canonical* such `K₀ = ModularCurve.iCa_K₀` as the `IntermediateField`
  generated by the curve coefficients together with the coefficients of `D.ι X` and
  `D.ι yGen`;
* `iP_*` pins the descended point `(xP, yP)`, its equation and its endomorphism `ι₀`;
* `iPFA_*` proves the pinned `ι₀` finite along `K₀` (the exchange/`adjoin` argument),
  `iPFE_*` proves `finrankAlong K₀ ι₀ = D.degree` by the tensor-product base change of
  set D-1;
* `iE2E_*` chains `SubfieldDescent → IotaDescendToFG → IotaDescendToFG'' → FGFieldDescent`
  and feeds the headline.

Statement authority. The headline is written from the `Theorems/` wrapper
`Theorems/Thm_WeierstrassCurve_exists_intermediateField_countable_map_eq_and_finrankAlong_eq.lean`
(binders `{K : Type u}`), **not** from the `S_` file's `solution` (`{K : Type uK}`); the
wrapper wins. Everything else is transcribed from the pin
`P2M/Sol/S_WeierstrassCurve_exists_intermediateField_countable_map_eq_and_finrankAlong_eq.lean`
at `aa2d8b3`.

Pin↔port name map. The module's public surface is the pin's public *interface* of this
node:

* `Countable.of_module_finite`;
* the self-contained descent predicates `KwIsogenyEndDatum{FGFieldDescent,
  SubfieldDescent'',IotaDescendToFG,SubfieldDescent,BaseChangeToAlgebraicClosure{,,''},
  FGFieldDescentIotaAtom',IotaDescendToFG''}`;
* the headline.

Everything else is a helper **local to this module** (no other set imports this module),
so per `studies/pin-name-prefixes-and-the-checker.md` §4 it stays `private`, written at
its pin name with the pin's collision token `kw_` stripped (`kw_iA_phi ↦ iA_phi`,
`kw_iotaSubd_countable_of_fg ↦ iotaSubd_countable_of_fg`, …). The checker does not read
the port's private layer, so each renamed helper is deliberately outside the statement
diff; its statement is transcribed verbatim from the pin nonetheless. The `KwIota*`
`Prop`s (`IotaPinnedFinrank`, `IotaPinnedFinrankEq`, `IotaPinnedFiniteSeam`,
`IotaCanonicalFinrank`) mention those helpers in their bodies, so they stay `private`
too; the public predicates above mention no helper.

Already public in the port and **imported, not re-proved** (set D-1 and its own
dependencies): `TreeIsogenyEndDatum` and its `degree`, `kw_functionField_algHom_ext`,
`kw_coordinateRingBasis`, the whole `pointPullback*` column, the D-1 function-field
tensor base change in both the `General` and the `NoAC` spelling
(`kw_functionFieldTensorIsDomain_dischargeGeneralNoAC`,
`kw_tensorFracIotaFinrankSeam_dischargeGeneralNoAC`,
`kw_functionFieldTensorFracEquivGeneralNoAC`,
`kw_tensorFracIotaRingHomGeneralNoAC_algebraMap`,
`kw_isogenyEndDatumBaseChangeIotaGeneralNoAC`, …), `yGen`,
`polyToFunctionField_eq_aeval`, `equation_map_polyToFunctionField_yGen`,
`transcendental_polyToFunctionField_X`, `algebraMap_eq_mk_C_C`.

Not ported here (deliberately, the boundary of the set): the `mrtw60a*` variable-change
block (D-3), the `kw_surgehgf4_pck*` block (D-4), the `kw_surge_hgf4_*` /
`KwD5BetweenCurves*` seam (D-4/D-5), and anything from the S row.

Reference (public mirror, pinned):
<https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_WeierstrassCurve_exists_intermediateField_countable_map_eq_and_finrankAlong_eq.lean>
-/
import FLTForHuman.WeierstrassCurve.Isogeny.BaseChange
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
import Mathlib.FieldTheory.RatFunc.IntermediateField
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.AlgebraicIndependent.Transcendental
import Mathlib.SetTheory.Cardinal.Basic
import Mathlib.Data.Set.Countable

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

noncomputable section

open Polynomial
open scoped Polynomial.Bivariate WeierstrassCurve TensorProduct
open AlgebraicCurve

universe u uK

namespace Countable

/-! ### Countability of a finite module over a countable ring

The pin's `Countable.of_module_finite`, the generic fact behind the pin's `Countable`
instance for number fields. It is the only reason the pin's `Countable` block exists. -/


lemma Countable.of_module_finite (R M : Type*) [Semiring R] [Countable R]
    [AddCommMonoid M] [Module R M] [Module.Finite R M] : Countable M := by
  obtain ⟨n, s, h⟩ := Module.Finite.exists_fin (R := R) (M := M)
  rw [← Set.countable_univ_iff]
  have : Countable (Submodule.span R (Set.range s)) := inferInstance
  rwa [h] at this

end Countable

section DescentPredicates

/-! ### The countable-descent predicates -/


def KwIsogenyEndDatumFGFieldDescent (K : Type uK) [Field K] [Algebra ℚ K] [DecidableEq K]
    [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K) [E.IsElliptic] (N : ℕ) : Prop :=
  (∃ D : TreeIsogenyEndDatum E.toAffine, D.degree = N) →
    ∃ (K₀ : IntermediateField ℚ K) (_ : Countable K₀)
      (E₀ : WeierstrassCurve K₀) (_ : E₀.IsElliptic) (_ : E₀.map (algebraMap K₀ K) = E)
      (D₀ : TreeIsogenyEndDatum (E₀⁄(AlgebraicClosure K₀))), D₀.degree = N

def KwIsogenyEndDatumSubfieldDescent'' (K : Type uK) [Field K] [Algebra ℚ K]
    [DecidableEq K] [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K) [E.IsElliptic]
    (N : ℕ) : Prop :=
  (∃ D : TreeIsogenyEndDatum E.toAffine, D.degree = N) →
    ∃ (K₀ : IntermediateField ℚ K) (_ : K₀.FG)
      (E₀ : WeierstrassCurve K₀) (_ : E₀.IsElliptic) (_ : E₀.map (algebraMap K₀ K) = E)
      (D' : TreeIsogenyEndDatum E₀.toAffine), D'.degree = N

def KwIsogenyEndDatumIotaDescendToFG (K : Type uK) [Field K] [Algebra ℚ K]
    [DecidableEq K] [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K) [E.IsElliptic]
    (D : TreeIsogenyEndDatum E.toAffine) : Prop :=
  ∃ (K₀ : IntermediateField ℚ K) (_ : K₀.FG)
    (E₀ : WeierstrassCurve K₀) (_ : E₀.IsElliptic) (_ : E₀.map (algebraMap K₀ K) = E)
    (ι₀ : E₀.toAffine.FunctionField →ₐ[K₀] E₀.toAffine.FunctionField)
    (_ : ι₀.toRingHom.IsIntegral) (_ : FiniteAlong K₀ ι₀),
    finrankAlong K₀ ι₀ = D.degree

section SubfieldDescent


theorem subfieldDescent_of_iotaDescend (K : Type uK) [Field K] [Algebra ℚ K]
    [DecidableEq K] [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K) [E.IsElliptic]
    (N : ℕ)
    (hIota : ∀ D : TreeIsogenyEndDatum E.toAffine, KwIsogenyEndDatumIotaDescendToFG K E D) :
    KwIsogenyEndDatumSubfieldDescent'' K E N := by
  intro ⟨D, hDN⟩
  obtain ⟨K₀, hfg, E₀, hE₀ell, hE₀map, ι₀, hι₀, hfin₀, hdeg₀⟩ := hIota D
  haveI : E₀.IsElliptic := hE₀ell
  exact ⟨K₀, hfg, E₀, hE₀ell, hE₀map, ⟨ι₀, hι₀, hfin₀⟩, hdeg₀.trans hDN⟩

def KwIsogenyEndDatumBaseChangeToAlgebraicClosure'' (K₀ : Type uK) [Field K₀] [CharZero K₀]
    (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic] (N : ℕ) : Prop :=
  (∃ D' : TreeIsogenyEndDatum E₀.toAffine, D'.degree = N) →
    ∃ D₀ : TreeIsogenyEndDatum (E₀⁄(AlgebraicClosure K₀)), D₀.degree = N

theorem baseChangeToAC_uncond (K₀ : Type uK) [Field K₀] [DecidableEq K₀] [CharZero K₀]
    (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic] (N : ℕ) :
    KwIsogenyEndDatumBaseChangeToAlgebraicClosure'' K₀ E₀ N := by
  haveI : DecidableEq (AlgebraicClosure K₀) := Classical.decEq _
  haveI : CharZero (AlgebraicClosure K₀) :=
    charZero_of_injective_algebraMap (algebraMap K₀ (AlgebraicClosure K₀)).injective
  intro ⟨D', hD'⟩
  have hmap_id : E₀⁄K₀ = E₀ := by
    show E₀.map (algebraMap K₀ K₀) = E₀
    rw [Algebra.algebraMap_self, WeierstrassCurve.map_id]
  have hD'' : ∃ D : TreeIsogenyEndDatum (E₀⁄K₀), D.degree = N := by
    rw [hmap_id]; exact ⟨D', hD'⟩
  exact kw_isogenyEndDatumBaseChangeAlong_dischargeGeneralNoAC E₀ K₀ (AlgebraicClosure K₀)
    (Algebra.ofId K₀ (AlgebraicClosure K₀)) N hD''

end SubfieldDescent


section Atom


def KwIsogenyEndDatumSubfieldDescent (K : Type uK) [Field K] [Algebra ℚ K]
    [DecidableEq K] [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K) [E.IsElliptic]
    (N : ℕ) : Prop :=
  (∃ D : TreeIsogenyEndDatum E.toAffine, D.degree = N) →
    ∃ (K₀ : IntermediateField ℚ K) (_ : K₀.FG)
      (E₀ : WeierstrassCurve K₀) (_ : E₀.IsElliptic) (_ : E₀.map (algebraMap K₀ K) = E)
      (D' : TreeIsogenyEndDatum E₀.toAffine), D'.degree = N

def KwIsogenyEndDatumBaseChangeToAlgebraicClosure (K₀ : Type uK) [Field K₀] [CharZero K₀]
    (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic] (N : ℕ) : Prop :=
  (∃ D' : TreeIsogenyEndDatum E₀.toAffine, D'.degree = N) →
    ∃ D₀ : TreeIsogenyEndDatum (E₀⁄(AlgebraicClosure K₀)), D₀.degree = N

def KwIsogenyEndDatumFGFieldDescentIotaAtom' (K : Type uK) [Field K] [Algebra ℚ K]
    [DecidableEq K] [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K) [E.IsElliptic]
    (N : ℕ) : Prop :=
  (∃ D : TreeIsogenyEndDatum E.toAffine, D.degree = N) →
    ∃ (K₀ : IntermediateField ℚ K) (_ : K₀.FG)
      (E₀ : WeierstrassCurve K₀) (_ : E₀.IsElliptic) (_ : E₀.map (algebraMap K₀ K) = E)
      (D₀ : TreeIsogenyEndDatum (E₀⁄(AlgebraicClosure K₀))), D₀.degree = N

theorem iotaAtom_of_subfieldDescent_of_baseChangeToAC (K : Type uK) [Field K] [Algebra ℚ K]
    [DecidableEq K] [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K) [E.IsElliptic]
    (N : ℕ) (hSD : KwIsogenyEndDatumSubfieldDescent K E N)
    (hBC : ∀ (K₀ : Type uK) [Field K₀] [CharZero K₀] (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic],
      KwIsogenyEndDatumBaseChangeToAlgebraicClosure K₀ E₀ N) :
    KwIsogenyEndDatumFGFieldDescentIotaAtom' K E N := by
  intro hD
  obtain ⟨K₀, hfg, E₀, hE₀ell, hE₀map, D', hD'deg⟩ := hSD hD
  haveI : E₀.IsElliptic := hE₀ell
  haveI : CharZero (↥K₀) :=
    charZero_of_injective_algebraMap (algebraMap ℚ (↥K₀)).injective
  obtain ⟨D₀, hD₀deg⟩ := hBC (↥K₀) E₀ ⟨D', hD'deg⟩
  exact ⟨K₀, hfg, E₀, hE₀ell, hE₀map, D₀, hD₀deg⟩

theorem iotaSubd_countable_of_fg {K : Type uK} [Field K] [Algebra ℚ K]
    {K₀ : IntermediateField ℚ K} (hfg : K₀.FG) : Countable (↥K₀) := by
  obtain ⟨s, hs⟩ := hfg
  rw [← hs]

  have h2 : Cardinal.lift.{0} (Cardinal.mk ↥(IntermediateField.adjoin ℚ (↑s : Set K))) ≤ Cardinal.aleph0 :=
    (IntermediateField.lift_cardinalMk_adjoin_le ℚ (↑s : Set K)).trans
      (max_le (max_le (Cardinal.lift_le_aleph0.mpr Cardinal.mk_le_aleph0)
        (Cardinal.lift_le_aleph0.mpr (Set.Countable.le_aleph0 s.countable_toSet))) le_rfl)
  exact Cardinal.mk_le_aleph0_iff.mp (Cardinal.lift_le_aleph0.mp h2)

theorem fgFieldDescent_of_subfieldDescent_of_baseChangeToAC (K : Type uK) [Field K]
    [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K] (E : WeierstrassCurve K)
    [E.IsElliptic] (N : ℕ) (hSD : KwIsogenyEndDatumSubfieldDescent K E N)
    (hBC : ∀ (K₀ : Type uK) [Field K₀] [CharZero K₀] (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic],
      KwIsogenyEndDatumBaseChangeToAlgebraicClosure K₀ E₀ N) :
    KwIsogenyEndDatumFGFieldDescent K E N := by
  intro hD
  obtain ⟨K₀, hfg, E₀, hE₀ell, hE₀map, D₀, hD₀deg⟩ :=
    iotaAtom_of_subfieldDescent_of_baseChangeToAC K E N hSD hBC hD
  exact ⟨K₀, iotaSubd_countable_of_fg hfg, E₀, hE₀ell, hE₀map, D₀, hD₀deg⟩

end Atom

end DescentPredicates


section Carriers

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K]
variable {K₀ : IntermediateField ℚ K}
variable (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]

local notation3 "E" => E₀.map (algebraMap K₀ K)


def iA_polyDescend (p : Polynomial K) (hmem : ∀ j, p.coeff j ∈ K₀) : Polynomial K₀ :=
  ∑ j ∈ p.support, Polynomial.C (⟨p.coeff j, hmem j⟩ : K₀) * Polynomial.X ^ j

theorem iA_polyDescend_map (p : Polynomial K) (hmem : ∀ j, p.coeff j ∈ K₀) :
    (iA_polyDescend p hmem).map (algebraMap K₀ K) = p := by
  unfold iA_polyDescend; rw [Polynomial.map_sum]
  conv_rhs => rw [p.as_sum_support_C_mul_X_pow]
  exact Finset.sum_congr rfl fun j _ => by
    rw [Polynomial.map_mul, Polynomial.map_C, Polynomial.map_pow, Polynomial.map_X]; rfl

def iA_crCoeffsIn (c : (E).toAffine.CoordinateRing) : Prop :=
  ∀ (i : Fin 2) (j : ℕ),
    ((CoordinateRing.basis (E).toAffine).repr c i).coeff j ∈ K₀

def iA_crDescend (c : (E).toAffine.CoordinateRing) (hmem : iA_crCoeffsIn E₀ c) :
    E₀.toAffine.CoordinateRing :=
  ∑ i : Fin 2, (iA_polyDescend
      ((CoordinateRing.basis (E).toAffine).repr c i) (hmem i))
    • (CoordinateRing.basis E₀.toAffine) i

theorem iA_crDescend_map (c : (E).toAffine.CoordinateRing)
    (hmem : iA_crCoeffsIn E₀ c) :
    CoordinateRing.map E₀.toAffine (algebraMap K₀ K) (iA_crDescend E₀ c hmem) = c := by
  unfold iA_crDescend; rw [map_sum]
  conv_rhs => rw [← (CoordinateRing.basis (E).toAffine).sum_repr c]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [CoordinateRing.map_smul]; congr 1
  · exact iA_polyDescend_map _ (hmem i)
  · rcases Fin.exists_fin_two.mp ⟨i, rfl⟩ with h | h
    · exact h ▸ by rw [CoordinateRing.basis_zero, CoordinateRing.basis_zero, map_one]
    · exact h ▸ by rw [CoordinateRing.basis_one, CoordinateRing.basis_one,
        CoordinateRing.map_mk, Polynomial.map_X]

theorem iA_phiEquation :
    (E₀.map (algebraMap K₀ (E).toAffine.FunctionField)).toAffine.Equation
      (polyToFunctionField (E).toAffine X) (yGen (E).toAffine) := by
  have h : E₀.map (algebraMap K₀ (E).toAffine.FunctionField)
      = (E).map (algebraMap K (E).toAffine.FunctionField) := by
    rw [show (algebraMap K₀ (E).toAffine.FunctionField)
        = (algebraMap K (E).toAffine.FunctionField).comp (algebraMap K₀ K) from
      IsScalarTower.algebraMap_eq K₀ K (E).toAffine.FunctionField,
      ← WeierstrassCurve.map_map]
  exact h ▸ equation_map_polyToFunctionField_yGen (W := (E).toAffine)

theorem iA_phiTranscendental :
    Function.Injective
      (Polynomial.aeval (R := K₀) (polyToFunctionField (E).toAffine X)) :=
  (injective_iff_map_eq_zero _).mpr fun p hp => transcendental_iff.mp
    ((transcendental_polyToFunctionField_X (W := (E).toAffine)).restrictScalars
      (R := K₀) (algebraMap K₀ K).injective) p hp

def iA_phi : E₀.toAffine.FunctionField →ₐ[K₀] (E).toAffine.FunctionField :=
  pointPullbackHomTo (iA_phiEquation E₀) (iA_phiTranscendental E₀)

theorem iA_polyToFF_eq_aeval (W : WeierstrassCurve.Affine K) :
    polyToFunctionField W = (Polynomial.aeval (R := K) (polyToFunctionField W X)).toRingHom := by
  refine Polynomial.ringHom_ext (fun c => ?_) ?_
  · rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, Polynomial.aeval_C,
      polyToFunctionField_apply,
      show (algebraMap (Polynomial K) W.CoordinateRing) (C c)
        = (algebraMap K W.CoordinateRing) c from
        (IsScalarTower.algebraMap_apply K (Polynomial K) W.CoordinateRing c).symm,
      ← IsScalarTower.algebraMap_apply K W.CoordinateRing W.FunctionField]
  · rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, Polynomial.aeval_X]

theorem iA_phiCRCompat (c₀ : E₀.toAffine.CoordinateRing) :
    iA_phi E₀ (algebraMap E₀.toAffine.CoordinateRing E₀.toAffine.FunctionField c₀)
      = algebraMap (E).toAffine.CoordinateRing (E).toAffine.FunctionField
          (CoordinateRing.map E₀.toAffine (algebraMap K₀ K) c₀) := by
  obtain ⟨g, rfl⟩ := AdjoinRoot.mk_surjective c₀
  unfold iA_phi
  rw [pointPullbackHomTo_algebraMap, CoordinateRing.map_mk]
  revert g
  suffices h : ((pointPullbackCoordHomTo (iA_phiEquation E₀)).toRingHom.comp
        (CoordinateRing.mk E₀.toAffine))
      = ((algebraMap (E).toAffine.CoordinateRing (E).toAffine.FunctionField).comp
          (CoordinateRing.mk (E).toAffine)).comp
        (Polynomial.mapRingHom (Polynomial.mapRingHom (algebraMap K₀ K))) by
    intro g; exact congrFun (congrArg DFunLike.coe h) g
  refine Polynomial.ringHom_ext (fun p => ?_) ?_
  · simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
      Polynomial.coe_mapRingHom, Polynomial.map_C]
    rw [← algebraMap_polynomial_eq_mk_C, ← algebraMap_polynomial_eq_mk_C,
      ← polyToFunctionField_apply]
    have hlhs := congrFun (congrArg DFunLike.coe
      (pointPullbackCoordHomTo_comp_algebraMap (iA_phiEquation E₀))) p
    simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe] at hlhs
    rw [hlhs, show polyToFunctionField (E).toAffine (p.map (algebraMap K₀ K))
        = (Polynomial.aeval (R := K) (polyToFunctionField (E).toAffine X))
            (p.map (algebraMap K₀ K)) from
      congrFun (congrArg DFunLike.coe (iA_polyToFF_eq_aeval (E).toAffine)) _]
    exact (Polynomial.aeval_map_algebraMap K (polyToFunctionField (E).toAffine X) p).symm
  · simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
      Polynomial.coe_mapRingHom, Polynomial.map_X]
    rw [pointPullbackCoordHomTo_mk, Polynomial.eval₂_X]; rfl

theorem iA_ffDescend_exists (x : (E).toAffine.FunctionField)
    (hnum : iA_crCoeffsIn E₀
      (IsLocalization.sec (nonZeroDivisors (E).toAffine.CoordinateRing) x).1)
    (hden : iA_crCoeffsIn E₀
      ((IsLocalization.sec (nonZeroDivisors (E).toAffine.CoordinateRing) x).2 :
        (E).toAffine.CoordinateRing)) :
    ∃ x₀ : E₀.toAffine.FunctionField, iA_phi E₀ x₀ = x := by
  let s := IsLocalization.sec (nonZeroDivisors (E).toAffine.CoordinateRing) x
  have hdenNZ : (s.2 : (E).toAffine.CoordinateRing) ≠ 0 := nonZeroDivisors.coe_ne_zero _
  refine ⟨algebraMap _ _ (iA_crDescend E₀ s.1 hnum)
    / algebraMap _ _ (iA_crDescend E₀ (↑s.2) hden), ?_⟩
  have hFFdenNZ : algebraMap (E).toAffine.CoordinateRing (E).toAffine.FunctionField
      (s.2 : (E).toAffine.CoordinateRing) ≠ 0 :=
    (map_ne_zero_iff _ (IsFractionRing.injective _ _)).mpr hdenNZ
  rw [map_div₀, iA_phiCRCompat, iA_phiCRCompat,
    iA_crDescend_map E₀ s.1 hnum, iA_crDescend_map E₀ _ hden,
    div_eq_iff hFFdenNZ]
  exact (IsLocalization.sec_spec (nonZeroDivisors (E).toAffine.CoordinateRing) x).symm

end Carriers


section Assembly

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable {K₀ : IntermediateField ℚ K}
variable (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]

local notation3 "E" => E₀.map (algebraMap K₀ K)


def iA_CoeffsHyp (D : TreeIsogenyEndDatum (E).toAffine) : Prop :=
  (iA_crCoeffsIn E₀ (IsLocalization.sec (nonZeroDivisors (E).toAffine.CoordinateRing)
      (D.ι (polyToFunctionField (E).toAffine X))).1
    ∧ iA_crCoeffsIn E₀ ((IsLocalization.sec (nonZeroDivisors
        (E).toAffine.CoordinateRing) (D.ι (polyToFunctionField (E).toAffine X))).2 :
      (E).toAffine.CoordinateRing))
  ∧ (iA_crCoeffsIn E₀ (IsLocalization.sec (nonZeroDivisors (E).toAffine.CoordinateRing)
      (D.ι (yGen (E).toAffine))).1
    ∧ iA_crCoeffsIn E₀ ((IsLocalization.sec (nonZeroDivisors
        (E).toAffine.CoordinateRing) (D.ι (yGen (E).toAffine))).2 :
      (E).toAffine.CoordinateRing))

def KwIsogenyEndDatumIotaDescendToFG'' (K : Type uK) [Field K] [Algebra ℚ K]
    [DecidableEq K] [IsAlgClosed K] [CharZero K] (E' : WeierstrassCurve K) [E'.IsElliptic]
    (D : TreeIsogenyEndDatum E'.toAffine) : Prop :=
  ∃ (K₀ : IntermediateField ℚ K) (_ : K₀.FG)
    (E₀ : WeierstrassCurve K₀) (_ : E₀.IsElliptic) (_ : E₀.map (algebraMap K₀ K) = E')
    (ι₀ : E₀.toAffine.FunctionField →ₐ[K₀] E₀.toAffine.FunctionField)
    (_ : ι₀.toRingHom.IsIntegral) (_ : FiniteAlong K₀ ι₀),
    finrankAlong K₀ ι₀ = D.degree

end Assembly


section Pinned

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable {K₀ : IntermediateField ℚ K}
variable (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]
variable (D : TreeIsogenyEndDatum (E₀.map (algebraMap K₀ K)).toAffine)
variable (hcoeffs : iA_CoeffsHyp E₀ D)

local notation3 "E" => E₀.map (algebraMap K₀ K)


def iP_xP : E₀.toAffine.FunctionField :=
  Classical.choose (iA_ffDescend_exists E₀ (D.ι (polyToFunctionField (E).toAffine X))
    hcoeffs.1.1 hcoeffs.1.2)

def iP_yP : E₀.toAffine.FunctionField :=
  Classical.choose (iA_ffDescend_exists E₀ (D.ι (yGen (E).toAffine))
    hcoeffs.2.1 hcoeffs.2.2)

theorem iP_xP_spec :
    iA_phi E₀ (iP_xP E₀ D hcoeffs) = D.ι (polyToFunctionField (E).toAffine X) :=
  Classical.choose_spec (iA_ffDescend_exists E₀ _ hcoeffs.1.1 hcoeffs.1.2)

theorem iP_yP_spec :
    iA_phi E₀ (iP_yP E₀ D hcoeffs) = D.ι (yGen (E).toAffine) :=
  Classical.choose_spec (iA_ffDescend_exists E₀ _ hcoeffs.2.1 hcoeffs.2.2)

theorem iP_equation :
    (E₀.map (algebraMap K₀ E₀.toAffine.FunctionField)).toAffine.Equation
      (iP_xP E₀ D hcoeffs) (iP_yP E₀ D hcoeffs) := by
  set xP := iP_xP E₀ D hcoeffs with hxP
  set yP := iP_yP E₀ D hcoeffs with hyP

  have hDι : ((E).map (algebraMap K (E).toAffine.FunctionField)).toAffine.Equation
      (D.ι (polyToFunctionField (E).toAffine X)) (D.ι (yGen (E).toAffine)) := by
    have h₀ := equation_map_polyToFunctionField_yGen (W := (E).toAffine)
    rw [Affine.equation_iff] at h₀ ⊢
    have h₁ := congrArg D.ι h₀
    simp only [map_add, map_mul, map_pow, WeierstrassCurve.map_a₁, WeierstrassCurve.map_a₂, WeierstrassCurve.map_a₃,
      WeierstrassCurve.map_a₄, WeierstrassCurve.map_a₆, AlgHom.commutes] at h₁ ⊢
    linear_combination h₁
  rw [Affine.equation_iff] at hDι ⊢
  have hΦx : iA_phi E₀ xP = D.ι (polyToFunctionField (E).toAffine X) :=
    hxP ▸ iP_xP_spec E₀ D hcoeffs
  have hΦy : iA_phi E₀ yP = D.ι (yGen (E).toAffine) :=
    hyP ▸ iP_yP_spec E₀ D hcoeffs
  have hΦc : ∀ (c : K₀), iA_phi E₀ (algebraMap K₀ E₀.toAffine.FunctionField c)
      = algebraMap K (E).toAffine.FunctionField (algebraMap K₀ K c) :=
    fun c => ((iA_phi E₀).commutes c).trans
      (IsScalarTower.algebraMap_apply K₀ K (E).toAffine.FunctionField c)

  have hΦinj : Function.Injective (iA_phi E₀) :=
    (iA_phi E₀).toRingHom.injective
  refine hΦinj ?_
  simp only [map_add, map_mul, map_pow, WeierstrassCurve.map_a₁, WeierstrassCurve.map_a₂, WeierstrassCurve.map_a₃,
    WeierstrassCurve.map_a₄, WeierstrassCurve.map_a₆] at hDι ⊢
  rw [hΦc, hΦc, hΦc, hΦc, hΦc, hΦx, hΦy]
  exact hDι

theorem iP_transcendental :
    Function.Injective (Polynomial.aeval (R := K₀) (iP_xP E₀ D hcoeffs)) := by
  refine (injective_iff_map_eq_zero _).mpr fun p hp => ?_

  have hK : Transcendental K (D.ι (polyToFunctionField (E).toAffine X)) := by
    intro halg
    obtain ⟨r, hr0, hreval⟩ := halg
    refine (transcendental_polyToFunctionField_X (W := (E).toAffine)) ⟨r, hr0, ?_⟩
    apply D.ι.toRingHom.injective
    rw [_root_.map_zero, ← hreval]
    exact (Polynomial.aeval_algHom_apply D.ι _ r).symm
  have hDιX : Transcendental K₀ (D.ι (polyToFunctionField (E).toAffine X)) :=
    hK.restrictScalars (R := K₀) (algebraMap K₀ K).injective

  refine transcendental_iff.mp hDιX p ?_
  calc Polynomial.aeval (R := K₀) (D.ι (polyToFunctionField (E).toAffine X)) p
      = Polynomial.aeval (R := K₀) (iA_phi E₀ (iP_xP E₀ D hcoeffs)) p := by
        rw [iP_xP_spec E₀ D hcoeffs]
    _ = iA_phi E₀ (Polynomial.aeval (R := K₀) (iP_xP E₀ D hcoeffs) p) :=
        Polynomial.aeval_algHom_apply (iA_phi E₀) (iP_xP E₀ D hcoeffs) p
    _ = iA_phi E₀ 0 := by rw [hp]
    _ = 0 := _root_.map_zero _

def iP_ι₀ : E₀.toAffine.FunctionField →ₐ[K₀] E₀.toAffine.FunctionField :=
  pointPullbackHomTo (iP_equation E₀ D hcoeffs) (iP_transcendental E₀ D hcoeffs)

theorem iP_ι₀_X :
    iP_ι₀ E₀ D hcoeffs (polyToFunctionField E₀.toAffine X) = iP_xP E₀ D hcoeffs :=
  pointPullbackHomTo_polyToFunctionField_X _ _

theorem iP_ι₀_yGen :
    iP_ι₀ E₀ D hcoeffs (yGen E₀.toAffine) = iP_yP E₀ D hcoeffs :=
  pointPullbackHomTo_yGen _ _

def KwIotaPinnedFinrank : Prop :=
  (iP_ι₀ E₀ D hcoeffs).toRingHom.IsIntegral
    ∧ FiniteAlong K₀ (iP_ι₀ E₀ D hcoeffs)
    ∧ finrankAlong K₀ (iP_ι₀ E₀ D hcoeffs) = D.degree

end Pinned


section CoeffSet

variable {K : Type uK} [Field K] [DecidableEq K]


def iCa_crRepr (E : WeierstrassCurve K) (c : E.toAffine.CoordinateRing)
    (i : Fin 2) : Polynomial K :=
  (CoordinateRing.basis E.toAffine).repr c i

def iCa_crCoeffSet (E : WeierstrassCurve K) (c : E.toAffine.CoordinateRing) :
    Finset K :=
  ((iCa_crRepr E c 0).support.image (iCa_crRepr E c 0).coeff) ∪
  ((iCa_crRepr E c 1).support.image (iCa_crRepr E c 1).coeff)

def iCa_ffNum (E : WeierstrassCurve K) (x : E.toAffine.FunctionField) :
    E.toAffine.CoordinateRing :=
  (IsLocalization.sec (nonZeroDivisors E.toAffine.CoordinateRing) x).1

def iCa_ffDen (E : WeierstrassCurve K) (x : E.toAffine.FunctionField) :
    E.toAffine.CoordinateRing :=
  ((IsLocalization.sec (nonZeroDivisors E.toAffine.CoordinateRing) x).2 :
    E.toAffine.CoordinateRing)

def iCa_ffCoeffSet (E : WeierstrassCurve K) (x : E.toAffine.FunctionField) :
    Finset K :=
  iCa_crCoeffSet E (iCa_ffNum E x) ∪ iCa_crCoeffSet E (iCa_ffDen E x)

theorem iCa_crRepr_coeff_mem (E : WeierstrassCurve K)
    (c : E.toAffine.CoordinateRing) (i : Fin 2) (j : ℕ) :
    (iCa_crRepr E c i).coeff j ∈ (↑(iCa_crCoeffSet E c) : Set K) ∪ {0} := by
  by_cases hj : j ∈ (iCa_crRepr E c i).support
  · refine Or.inl ?_
    simp only [iCa_crCoeffSet, Finset.coe_union, Finset.coe_image, Set.mem_union,
      Set.mem_image, Finset.mem_coe]
    rcases Fin.exists_fin_two.mp ⟨i, rfl⟩ with h | h
    · exact h ▸ Or.inl ⟨j, hj, rfl⟩
    · exact h ▸ Or.inr ⟨j, hj, rfl⟩
  · exact Or.inr (by simpa using Polynomial.notMem_support_iff.mp hj)

end CoeffSet


section Canonical

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable (E : WeierstrassCurve K) [E.IsElliptic] (D : TreeIsogenyEndDatum E.toAffine)


def iCa_genSet : Set K :=
  {E.a₁, E.a₂, E.a₃, E.a₄, E.a₆} ∪
    ↑(iCa_ffCoeffSet E (D.ι (polyToFunctionField E.toAffine X))) ∪
    ↑(iCa_ffCoeffSet E (D.ι (yGen E.toAffine)))

theorem iCa_genSet_finite : (iCa_genSet E D).Finite := by
  unfold iCa_genSet
  exact ((((Set.finite_singleton _).insert _ |>.insert _ |>.insert _ |>.insert _).union
    (Finset.finite_toSet _)).union (Finset.finite_toSet _))

def iCa_K₀ : IntermediateField ℚ K := IntermediateField.adjoin ℚ (iCa_genSet E D)

theorem iCa_K₀_fg : (iCa_K₀ E D).FG :=
  ⟨(iCa_genSet_finite E D).toFinset, by rw [Set.Finite.coe_toFinset]; rfl⟩

theorem iCa_K₀_mem_aᵢ :
    E.a₁ ∈ iCa_K₀ E D ∧ E.a₂ ∈ iCa_K₀ E D ∧ E.a₃ ∈ iCa_K₀ E D ∧
    E.a₄ ∈ iCa_K₀ E D ∧ E.a₆ ∈ iCa_K₀ E D := by
  have h : ({E.a₁, E.a₂, E.a₃, E.a₄, E.a₆} : Set K) ⊆ iCa_K₀ E D := fun x hx =>
    IntermediateField.subset_adjoin ℚ _ (Or.inl (Or.inl hx))
  exact ⟨h (Or.inl rfl), h (Or.inr (Or.inl rfl)), h (Or.inr (Or.inr (Or.inl rfl))),
    h (Or.inr (Or.inr (Or.inr (Or.inl rfl)))), h (Or.inr (Or.inr (Or.inr (Or.inr rfl))))⟩

def iCa_E₀ : WeierstrassCurve (iCa_K₀ E D) where
  a₁ := ⟨E.a₁, (iCa_K₀_mem_aᵢ E D).1⟩
  a₂ := ⟨E.a₂, (iCa_K₀_mem_aᵢ E D).2.1⟩
  a₃ := ⟨E.a₃, (iCa_K₀_mem_aᵢ E D).2.2.1⟩
  a₄ := ⟨E.a₄, (iCa_K₀_mem_aᵢ E D).2.2.2.1⟩
  a₆ := ⟨E.a₆, (iCa_K₀_mem_aᵢ E D).2.2.2.2⟩

theorem iCa_E₀_map :
    (iCa_E₀ E D).map (algebraMap (iCa_K₀ E D) K) = E := by ext <;> rfl

private scoped instance iCa_E₀_isElliptic : (iCa_E₀ E D).IsElliptic := by
  constructor; rw [isUnit_iff_ne_zero]; intro h0
  have : (algebraMap (iCa_K₀ E D) K) (iCa_E₀ E D).Δ = E.Δ := by
    rw [← WeierstrassCurve.map_Δ, iCa_E₀_map]
  rw [h0, _root_.map_zero] at this; exact E.isUnit_Δ.ne_zero this.symm

theorem iCa_crCoeffsIn_of_ffCoeffSet_subset (E' : WeierstrassCurve K)
    (x : E'.toAffine.FunctionField) {K₀' : IntermediateField ℚ K}
    (hsub : (↑(iCa_ffCoeffSet E' x) : Set K) ⊆ K₀') (i : Fin 2) (j : ℕ) :
    ((CoordinateRing.basis E'.toAffine).repr (iCa_ffNum E' x) i).coeff j ∈ K₀' ∧
    ((CoordinateRing.basis E'.toAffine).repr (iCa_ffDen E' x) i).coeff j ∈ K₀' := by
  have hN := iCa_crRepr_coeff_mem E' (iCa_ffNum E' x) i j
  have hD := iCa_crRepr_coeff_mem E' (iCa_ffDen E' x) i j
  unfold iCa_crRepr at hN hD
  refine ⟨?_, ?_⟩
  · rcases hN with hN | hN
    · exact hsub (by simp only [iCa_ffCoeffSet, Finset.coe_union]; exact Or.inl hN)
    · simp only [Set.mem_singleton_iff] at hN; exact hN ▸ zero_mem K₀'
  · rcases hD with hD | hD
    · exact hsub (by simp only [iCa_ffCoeffSet, Finset.coe_union]; exact Or.inr hD)
    · simp only [Set.mem_singleton_iff] at hD; exact hD ▸ zero_mem K₀'

def iCa_D' :
    TreeIsogenyEndDatum ((iCa_E₀ E D).map (algebraMap (iCa_K₀ E D) K)).toAffine :=
  Eq.mpr (congrArg (fun W => TreeIsogenyEndDatum W.toAffine) (iCa_E₀_map E D)) D

def KwIotaCanonicalFinrank : Prop :=
  ∀ hcoeffs : iA_CoeffsHyp (iCa_E₀ E D) (iCa_D' E D),
    KwIotaPinnedFinrank (iCa_E₀ E D) (iCa_D' E D) hcoeffs

theorem iCa_ffCoeffSet_subset_X :
    (↑(iCa_ffCoeffSet E (D.ι (polyToFunctionField E.toAffine X))) : Set K)
      ⊆ iCa_K₀ E D :=
  fun _ hc => IntermediateField.subset_adjoin ℚ _ (Or.inl (Or.inr hc))

theorem iCa_ffCoeffSet_subset_Y :
    (↑(iCa_ffCoeffSet E (D.ι (yGen E.toAffine))) : Set K) ⊆ iCa_K₀ E D :=
  fun _ hc => IntermediateField.subset_adjoin ℚ _ (Or.inr hc)

end Canonical

section Commute

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable {K₀ : IntermediateField ℚ K}
variable (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]
variable (D : TreeIsogenyEndDatum (E₀.map (algebraMap K₀ K)).toAffine)
variable (hcoeffs : iA_CoeffsHyp E₀ D)

local notation3 "E" => E₀.map (algebraMap K₀ K)


theorem iPF_phi_X :
    iA_phi E₀ (polyToFunctionField E₀.toAffine X)
      = polyToFunctionField (E).toAffine X :=
  pointPullbackHomTo_polyToFunctionField_X _ _

theorem iPF_phi_yGen :
    iA_phi E₀ (yGen E₀.toAffine) = yGen (E).toAffine :=
  pointPullbackHomTo_yGen _ _

def KwIotaPinnedFiniteSeam : Prop :=
  FiniteAlong K₀ (iP_ι₀ E₀ D hcoeffs)
    ∧ finrankAlong K₀ (iP_ι₀ E₀ D hcoeffs) = D.degree

theorem iotaPinnedFinrank_of_finiteSeam
    (hSeam : KwIotaPinnedFiniteSeam E₀ D hcoeffs) :
    KwIotaPinnedFinrank E₀ D hcoeffs := by
  obtain ⟨hfin, hdeg⟩ := hSeam
  exact ⟨RingHom.Finite.to_isIntegral (f := (iP_ι₀ E₀ D hcoeffs).toRingHom) hfin,
    hfin, hdeg⟩

end Commute


section Cast

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]


theorem iCaW_degree_mpr {W W' : WeierstrassCurve K}
    (heq : W = W') (D : TreeIsogenyEndDatum W'.toAffine) :
    (Eq.mpr (congrArg (fun V => TreeIsogenyEndDatum V.toAffine) heq) D).degree = D.degree := by
  subst heq; rfl

theorem iCaW_coeffsHyp_of_subset_cast {K₀ : IntermediateField ℚ K}
    (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]
    {W' : WeierstrassCurve K} (heq : E₀.map (algebraMap K₀ K) = W')
    (D : TreeIsogenyEndDatum W'.toAffine)
    (hX : (↑(iCa_ffCoeffSet W' (D.ι (polyToFunctionField W'.toAffine X))) : Set K)
      ⊆ (K₀ : Set K))
    (hY : (↑(iCa_ffCoeffSet W' (D.ι (yGen W'.toAffine))) : Set K)
      ⊆ (K₀ : Set K)) :
    iA_CoeffsHyp E₀
      (Eq.mpr (congrArg (fun V => TreeIsogenyEndDatum V.toAffine) heq) D) := by
  subst heq
  refine ⟨⟨fun i j => ?_, fun i j => ?_⟩, fun i j => ?_, fun i j => ?_⟩
  · exact (iCa_crCoeffsIn_of_ffCoeffSet_subset _ _ hX i j).1
  · exact (iCa_crCoeffsIn_of_ffCoeffSet_subset _ _ hX i j).2
  · exact (iCa_crCoeffsIn_of_ffCoeffSet_subset _ _ hY i j).1
  · exact (iCa_crCoeffsIn_of_ffCoeffSet_subset _ _ hY i j).2

theorem iCaW_descend_of_pinned_cast {K₀ : IntermediateField ℚ K}
    (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]
    {W' : WeierstrassCurve K} [W'.IsElliptic]
    (heq : E₀.map (algebraMap K₀ K) = W')
    (D : TreeIsogenyEndDatum W'.toAffine) (hfg : K₀.FG)
    (hcoeffs : iA_CoeffsHyp E₀
        (Eq.mpr (congrArg (fun V => TreeIsogenyEndDatum V.toAffine) heq) D))
    (hFinrank : KwIotaPinnedFinrank E₀
        (Eq.mpr (congrArg (fun V => TreeIsogenyEndDatum V.toAffine) heq) D) hcoeffs) :
    KwIsogenyEndDatumIotaDescendToFG'' K W' D := by
  obtain ⟨hint, hfin, hdeg⟩ := hFinrank
  exact ⟨K₀, hfg, E₀, inferInstance, heq, iP_ι₀ E₀ _ hcoeffs, hint, hfin,
    hdeg.trans (iCaW_degree_mpr heq D)⟩

end Cast


section Wire

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable (E : WeierstrassCurve K) [E.IsElliptic] (D : TreeIsogenyEndDatum E.toAffine)


theorem iCaW_hcoeffs_canonical :
    iA_CoeffsHyp (iCa_E₀ E D) (iCa_D' E D) :=
  iCaW_coeffsHyp_of_subset_cast (iCa_E₀ E D) (iCa_E₀_map E D) D
    (iCa_ffCoeffSet_subset_X E D) (iCa_ffCoeffSet_subset_Y E D)

theorem iotaDescendToFG_of_canonicalFinrank
    (hCan : KwIotaCanonicalFinrank E D) :
    KwIsogenyEndDatumIotaDescendToFG'' K E D :=
  iCaW_descend_of_pinned_cast (iCa_E₀ E D) (iCa_E₀_map E D) D
    (iCa_K₀_fg E D) (iCaW_hcoeffs_canonical E D)
    (hCan (iCaW_hcoeffs_canonical E D))

end Wire


section Exchange

variable {K : Type*} [Field K] (W : WeierstrassCurve.Affine K)


theorem iPFA_isTranscendenceBasis_coord :
    IsTranscendenceBasis K
      (fun _ : Fin 1 => algebraMap (RatFunc K) W.FunctionField RatFunc.X) := by
  haveI : Algebra.IsAlgebraic (RatFunc K) (RatFunc K) :=
    Algebra.IsAlgebraic.of_finite (RatFunc K) (RatFunc K)
  haveI : Algebra.IsAlgebraic (Polynomial K) (RatFunc K) :=
    (IsFractionRing.comap_isAlgebraic_iff
      (A := Polynomial K) (K := RatFunc K) (C := RatFunc K)).mpr inferInstance
  haveI : FaithfulSMul (Polynomial K) (RatFunc K) :=
    (faithfulSMul_iff_algebraMap_injective (Polynomial K) (RatFunc K)).mpr
      (IsFractionRing.injective (Polynomial K) (RatFunc K))
  haveI : Algebra.IsAlgebraic (RatFunc K) W.FunctionField :=
    Algebra.IsAlgebraic.of_finite (RatFunc K) W.FunctionField
  haveI : FaithfulSMul (RatFunc K) W.FunctionField :=
    (faithfulSMul_iff_algebraMap_injective (RatFunc K) W.FunctionField).mpr
      (algebraMap (RatFunc K) W.FunctionField).injective
  have h0 : IsTranscendenceBasis K (fun _ : Fin 1 => (Polynomial.X : Polynomial K)) :=
    IsTranscendenceBasis.polynomial (ι := Fin 1) (R := K)
  have h1 := h0.algebraMap_comp (A := RatFunc K)
  have h2 := h1.algebraMap_comp (A := W.FunctionField)
  have hfun : (algebraMap (RatFunc K) W.FunctionField ∘
      (algebraMap (Polynomial K) (RatFunc K) ∘ fun _ : Fin 1 => (Polynomial.X : Polynomial K)))
      = fun _ : Fin 1 => algebraMap (RatFunc K) W.FunctionField RatFunc.X := by
    funext i; simp only [Function.comp_apply]; rw [RatFunc.algebraMap_X]
  rwa [hfun] at h2

theorem iPFA_isAlgebraic_adjoin_transcendental {g : W.FunctionField}
    (hg : Transcendental K g) :
    Algebra.IsAlgebraic (↥K⟮g⟯) W.FunctionField := by
  classical
  have hgind : AlgebraicIndepOn K id ({g} : Set W.FunctionField) := by
    refine algebraicIndependent_unique_type_iff.mpr ?_
    simpa using hg
  obtain ⟨s, hgs, hbasis⟩ := exists_isTranscendenceBasis_superset hgind
  have hcard := hbasis.lift_cardinalMk_eq (iPFA_isTranscendenceBasis_coord W)
  simp only [Cardinal.mk_fin, Nat.cast_one, Cardinal.lift_one, Cardinal.lift_eq_one] at hcard
  have hsub : s.Subsingleton := Cardinal.mk_le_one_iff_set_subsingleton.mp hcard.le
  have hseq : s = {g} := hsub.eq_singleton_of_mem (hgs rfl)
  subst hseq
  rw [hbasis.isAlgebraic_iff]
  intro i
  have hi : (i : W.FunctionField) = g := i.2
  rw [hi]
  have h1 := isAlgebraic_algebraMap (R := ↥K⟮g⟯) (A := W.FunctionField)
    (IntermediateField.AdjoinSimple.gen K g)
  rwa [IntermediateField.AdjoinSimple.algebraMap_gen] at h1

theorem iPFA_finiteDimensional_adjoin_transcendental {g : W.FunctionField}
    (hg : Transcendental K g) :
    FiniteDimensional (↥K⟮g⟯) W.FunctionField := by
  classical
  have halg : Algebra.IsAlgebraic (↥K⟮g⟯) W.FunctionField :=
    iPFA_isAlgebraic_adjoin_transcendental W hg
  obtain ⟨s, hs⟩ :=
    Module.finite_def.mp (inferInstance : Module.Finite (RatFunc K) W.FunctionField)
  set t : W.FunctionField := algebraMap (RatFunc K) W.FunctionField RatFunc.X with ht
  set E : IntermediateField (↥K⟮g⟯) W.FunctionField :=
    IntermediateField.adjoin (↥K⟮g⟯) (insert t (↑s : Set W.FunctionField)) with hE
  have htE : t ∈ E := IntermediateField.subset_adjoin _ _ (Set.mem_insert _ _)
  have hrange : ∀ r : RatFunc K, algebraMap (RatFunc K) W.FunctionField r ∈ E := by
    intro r
    have hr : r ∈ IntermediateField.adjoin K {(RatFunc.X : RatFunc K)} := by
      rw [RatFunc.adjoin_X]; exact IntermediateField.mem_top
    have hmap : algebraMap (RatFunc K) W.FunctionField r ∈
        (IntermediateField.adjoin K {(RatFunc.X : RatFunc K)}).map
          (IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField) := ⟨r, hr, rfl⟩
    rw [IntermediateField.adjoin_map, Set.image_singleton] at hmap
    have himg : (IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField)
        (RatFunc.X : RatFunc K) = t := rfl
    rw [himg] at hmap
    have hle : IntermediateField.adjoin K {t} ≤ E.restrictScalars K :=
      IntermediateField.adjoin_simple_le_iff.mpr
        ((IntermediateField.mem_restrictScalars K).mpr htE)
    exact (IntermediateField.mem_restrictScalars K).mp (hle hmap)
  have hmem : ∀ x : W.FunctionField, x ∈ E := by
    intro x
    have hx : x ∈ Submodule.span (RatFunc K) (↑s : Set W.FunctionField) := by
      rw [hs]; exact Submodule.mem_top
    refine Submodule.span_induction (fun y hy => ?_) ?_ (fun y z _ _ hy hz => ?_)
      (fun r y _ hy => ?_) hx
    · exact IntermediateField.subset_adjoin _ _ (Set.mem_insert_of_mem _ hy)
    · exact zero_mem E
    · exact add_mem hy hz
    · rw [Algebra.smul_def]
      exact mul_mem (hrange _) hy
  have heqTop : E = ⊤ := eq_top_iff.mpr (fun x _ => hmem x)
  have hfinE : FiniteDimensional (↥K⟮g⟯) (↥E) :=
    IntermediateField.finiteDimensional_adjoin
      (S := insert t (↑s : Set W.FunctionField))
      (fun z _ => isAlgebraic_iff_isIntegral.mp (halg.isAlgebraic z))
  rw [heqTop] at hfinE
  exact (IntermediateField.topEquiv (F := ↥K⟮g⟯) (E := W.FunctionField))
    |>.toLinearEquiv.finiteDimensional

end Exchange

section Discharge

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable {K₀ : IntermediateField ℚ K}
variable (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]
variable (D : TreeIsogenyEndDatum (E₀.map (algebraMap K₀ K)).toAffine)
variable (hcoeffs : iA_CoeffsHyp E₀ D)

local notation3 "E" => E₀.map (algebraMap K₀ K)


theorem iPFA_finiteAlong :
    FiniteAlong K₀ (iP_ι₀ E₀ D hcoeffs) := by
  set ι₀ := iP_ι₀ E₀ D hcoeffs
  set xP := iP_xP E₀ D hcoeffs

  have hxPtr : Transcendental K₀ xP :=
    transcendental_iff_injective.mpr (iP_transcendental E₀ D hcoeffs)

  have hfd : FiniteDimensional (↥(K₀ : Type uK)⟮xP⟯) E₀.toAffine.FunctionField :=
    iPFA_finiteDimensional_adjoin_transcendental E₀.toAffine hxPtr

  have hxPrange : xP ∈ ι₀.fieldRange :=
    ⟨polyToFunctionField E₀.toAffine X, iP_ι₀_X E₀ D hcoeffs⟩
  have hle : (K₀ : Type uK)⟮xP⟯ ≤ ι₀.fieldRange :=
    IntermediateField.adjoin_simple_le_iff.mpr hxPrange

  letI algIncl : Algebra (↥(K₀ : Type uK)⟮xP⟯) (↥ι₀.fieldRange) :=
    (IntermediateField.inclusion hle).toRingHom.toAlgebra
  haveI towIncl : IsScalarTower (↥(K₀ : Type uK)⟮xP⟯) (↥ι₀.fieldRange)
      E₀.toAffine.FunctionField :=
    IsScalarTower.of_algebraMap_eq (fun r => rfl)

  haveI hfdR : FiniteDimensional (↥ι₀.fieldRange) E₀.toAffine.FunctionField :=
    FiniteDimensional.right (↥(K₀ : Type uK)⟮xP⟯) (↥ι₀.fieldRange) E₀.toAffine.FunctionField

  show ι₀.toRingHom.Finite
  let ρ : E₀.toAffine.FunctionField →+* ↥ι₀.fieldRange :=
    { toFun := fun x => ⟨ι₀ x, x, rfl⟩
      map_one' := Subtype.ext (map_one ι₀)
      map_mul' := fun a b => Subtype.ext (map_mul ι₀ a b)
      map_zero' := Subtype.ext (_root_.map_zero ι₀)
      map_add' := fun a b => Subtype.ext (map_add ι₀ a b) }
  have hsurj : Function.Surjective ρ := by rintro ⟨y, x, rfl⟩; exact ⟨x, rfl⟩
  have hfactor : ι₀.toRingHom
      = (algebraMap (↥ι₀.fieldRange) E₀.toAffine.FunctionField).comp ρ := by
    ext x; rfl
  rw [hfactor]
  exact RingHom.Finite.comp hfdR (RingHom.Finite.of_surjective _ hsurj)

def KwIotaPinnedFinrankEq : Prop :=
  finrankAlong K₀ (iP_ι₀ E₀ D hcoeffs) = D.degree

theorem iotaPinnedFiniteSeam_of_finrankEq
    (hdeg : KwIotaPinnedFinrankEq E₀ D hcoeffs) :
    KwIotaPinnedFiniteSeam E₀ D hcoeffs :=
  ⟨iPFA_finiteAlong E₀ D hcoeffs, hdeg⟩

end Discharge

section FinrankEq

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable {K₀ : IntermediateField ℚ K}
variable (E₀ : WeierstrassCurve K₀) [E₀.IsElliptic]
variable (D : TreeIsogenyEndDatum (E₀.map (algebraMap K₀ K)).toAffine)
variable (hcoeffs : iA_CoeffsHyp E₀ D)

local notation3 "E" => E₀.map (algebraMap K₀ K)


theorem iPFE_functionField_ringHom_ext {F : Type*} [Field F] {W : Affine F}
    {L : Type*} [Field L] {f g : W.FunctionField →+* L}
    (hF : ∀ r : F, f (algebraMap F W.FunctionField r) = g (algebraMap F W.FunctionField r))
    (hX : f (polyToFunctionField W X) = g (polyToFunctionField W X))
    (hy : f (yGen W) = g (yGen W)) : f = g := by
  letI : Algebra F L := (f.comp (algebraMap F W.FunctionField)).toAlgebra
  let f' : W.FunctionField →ₐ[F] L := { f with commutes' := fun _ => rfl }
  let g' : W.FunctionField →ₐ[F] L := { g with commutes' := fun r => (hF r).symm }
  have heq : f' = g' := kw_functionField_algHom_ext hX hy
  exact congrArg AlgHom.toRingHom heq

theorem iPFE_finrankEq : KwIotaPinnedFinrankEq E₀ D hcoeffs := by
  set ι₀ := iP_ι₀ E₀ D hcoeffs
  have hfin := iPFA_finiteAlong E₀ D hcoeffs
  have hint : ι₀.toRingHom.IsIntegral :=
    RingHom.Finite.to_isIntegral (f := ι₀.toRingHom) hfin

  let D₀ : TreeIsogenyEndDatum (E₀⁄(K₀ : Type uK)) := ⟨ι₀, hint, hfin⟩
  have hD₀_deg : D₀.degree = finrankAlong K₀ ι₀ := rfl

  haveI hdom : IsDomain ((E₀⁄(K₀ : Type uK)).FunctionField ⊗[K₀] K) :=
    kw_functionFieldTensorIsDomain_dischargeGeneralNoAC E₀ (K₀ : Type uK) K
  let T := (E₀⁄(K₀ : Type uK)).FunctionField ⊗[K₀] K
  let FrT := FractionRing T
  let ψ := kw_functionFieldTensorFracEquivGeneralNoAC E₀ (K₀ : Type uK) K
  let ιFr := kw_tensorFracIotaRingHomGeneralNoAC E₀ (K₀ : Type uK) K D₀
  let Φ := iA_phi E₀

  have hκ : ∀ a : E₀.toAffine.FunctionField,
      ψ (Φ a) = algebraMap T FrT (a ⊗ₜ[K₀] (1 : K)) := by
    have heq : (ψ : (E₀⁄K).FunctionField →+* FrT).comp Φ.toRingHom
        = (algebraMap T FrT).comp
          (Algebra.TensorProduct.includeLeftRingHom (R := K₀)) := by
      refine iPFE_functionField_ringHom_ext (fun r => ?_) ?_ ?_
      ·

        show ψ (Φ (algebraMap K₀ E₀.toAffine.FunctionField r))
            = algebraMap T FrT (algebraMap K₀ E₀.toAffine.FunctionField r ⊗ₜ[K₀] (1 : K))
        have hL : ψ (Φ (algebraMap K₀ E₀.toAffine.FunctionField r))
            = algebraMap K FrT (algebraMap K₀ K r) := by
          rw [Φ.commutes r, IsScalarTower.algebraMap_apply K₀ K (E).toAffine.FunctionField r]
          exact ψ.commutes (algebraMap K₀ K r)

        have hT : (algebraMap K₀ E₀.toAffine.FunctionField r ⊗ₜ[K₀] (1 : K) : T)
            = algebraMap K T (algebraMap K₀ K r) :=
          (Algebra.TensorProduct.tmul_one_eq_one_tmul (A := E₀.toAffine.FunctionField)
              (B := K) r).trans
            (Algebra.TensorProduct.includeRight_apply (algebraMap K₀ K r)).symm
        exact hL.trans ((IsScalarTower.algebraMap_apply K T FrT (algebraMap K₀ K r)).trans
          (congrArg (algebraMap T FrT) hT.symm))
      · show ψ (Φ (polyToFunctionField E₀.toAffine X)) = _
        rw [iPF_phi_X E₀]
        exact kw_functionFieldTensorFracHomGeneralNoAC_X E₀ (K₀ : Type uK) K
      · show ψ (Φ (yGen E₀.toAffine)) = _
        rw [iPF_phi_yGen E₀]
        exact kw_functionFieldTensorFracHomGeneralNoAC_yGen E₀ (K₀ : Type uK) K
    exact fun a => DFunLike.congr_fun heq a

  let D₀' := kw_isogenyEndDatumBaseChangeIotaGeneralNoAC E₀ (K₀ : Type uK) K D₀
  have hψ_Φ_ι₀ : ∀ a, ψ (Φ (ι₀ a)) = ιFr (ψ (Φ a)) := by
    intro a
    rw [hκ (ι₀ a), hκ a,
      kw_tensorFracIotaRingHomGeneralNoAC_algebraMap E₀ (K₀ : Type uK) K D₀,
      kw_tensorIotaRingHomGeneralNoAC_tmul E₀ (K₀ : Type uK) K D₀]
    rfl
  have hD₀'_gen : ∀ a, D₀' (Φ a) = Φ (ι₀ a) := by
    intro a
    show ψ.symm (ιFr (ψ (Φ a))) = Φ (ι₀ a)
    rw [← hψ_Φ_ι₀]
    exact ψ.symm_apply_apply _
  have hD₀'_eq : D₀' = D.ι := by
    refine kw_functionField_algHom_ext ?_ ?_
    ·

      calc D₀' (polyToFunctionField (E₀⁄K) X)
          = D₀' (Φ (polyToFunctionField E₀.toAffine X)) :=
            congrArg D₀' (iPF_phi_X E₀).symm
        _ = Φ (ι₀ (polyToFunctionField E₀.toAffine X)) := hD₀'_gen _
        _ = Φ (iP_xP E₀ D hcoeffs) := congrArg Φ (iP_ι₀_X E₀ D hcoeffs)
        _ = D.ι (polyToFunctionField (E).toAffine X) := iP_xP_spec E₀ D hcoeffs
    ·
      calc D₀' (yGen (E₀⁄K))
          = D₀' (Φ (yGen E₀.toAffine)) := congrArg D₀' (iPF_phi_yGen E₀).symm
        _ = Φ (ι₀ (yGen E₀.toAffine)) := hD₀'_gen _
        _ = Φ (iP_yP E₀ D hcoeffs) := congrArg Φ (iP_ι₀_yGen E₀ D hcoeffs)
        _ = D.ι (yGen (E).toAffine) := iP_yP_spec E₀ D hcoeffs

  have hcomm : ∀ x, ιFr (ψ x) = ψ (D.ι x) := fun x => by
    have h1 : D.ι x = D₀' x := (DFunLike.congr_fun hD₀'_eq x).symm
    calc ιFr (ψ x) = ψ (ψ.symm (ιFr (ψ x))) := (ψ.apply_symm_apply _).symm
      _ = ψ (D₀' x) := rfl
      _ = ψ (D.ι x) := by rw [h1]

  have hfin_eq : finrankAlong K D.ι = D₀.degree := by
    obtain ⟨_, hdeg_Fr⟩ :=
      kw_tensorFracIotaFinrankSeam_dischargeGeneralNoAC E₀ (K₀ : Type uK) K D₀
    refine (?_ : finrankAlong K D.ι = _).trans hdeg_Fr
    exact @Algebra.finrank_eq_of_equiv_equiv
      (E₀⁄K).FunctionField (E₀⁄K).FunctionField _ _ (algebraAlong D.ι)
      FrT FrT _ _ ιFr.toAlgebra ψ.toRingEquiv ψ.toRingEquiv
      (RingHom.ext hcomm)
  show finrankAlong K₀ ι₀ = D.degree
  rw [show D.degree = finrankAlong K D.ι from rfl, hfin_eq, hD₀_deg]

end FinrankEq


section Uncond

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]
variable (E : WeierstrassCurve K) [E.IsElliptic] (D : TreeIsogenyEndDatum E.toAffine)


theorem iPFE_pinnedFinrank_uncond : KwIotaPinnedFinrank E₀ D hcoeffs :=
  iotaPinnedFinrank_of_finiteSeam E₀ D hcoeffs
    (iotaPinnedFiniteSeam_of_finrankEq E₀ D hcoeffs
      (iPFE_finrankEq E₀ D hcoeffs))

theorem iPFE_canonicalFinrank_uncond : KwIotaCanonicalFinrank E D :=
  fun hcoeffs => iPFE_pinnedFinrank_uncond (iCa_E₀ E D) (iCa_D' E D) hcoeffs

theorem iPFE_iotaDescendToFG_uncond :
    KwIsogenyEndDatumIotaDescendToFG'' K E D :=
  iotaDescendToFG_of_canonicalFinrank E D (iPFE_canonicalFinrank_uncond E D)

end Uncond


section E2EChain

variable {K : Type uK} [Field K] [Algebra ℚ K] [DecidableEq K] [IsAlgClosed K] [CharZero K]


theorem iE2E_iotaDescendToFG_of_iotaDescendToFG''
    (E : WeierstrassCurve K) [E.IsElliptic] (D : TreeIsogenyEndDatum E.toAffine)
    (h : KwIsogenyEndDatumIotaDescendToFG'' K E D) :
    KwIsogenyEndDatumIotaDescendToFG K E D := h

theorem iE2E_iotaDescendToFG_uncond (E : WeierstrassCurve K) [E.IsElliptic]
    (D : TreeIsogenyEndDatum E.toAffine) :
    KwIsogenyEndDatumIotaDescendToFG K E D :=
  iE2E_iotaDescendToFG_of_iotaDescendToFG'' E D
    (iPFE_iotaDescendToFG_uncond E D)

theorem iE2E_subfieldDescent_of_subfieldDescent''
    (E : WeierstrassCurve K) [E.IsElliptic] (N : ℕ)
    (h : KwIsogenyEndDatumSubfieldDescent'' K E N) :
    KwIsogenyEndDatumSubfieldDescent K E N := h

theorem iE2E_subfieldDescent_uncond (E : WeierstrassCurve K) [E.IsElliptic] (N : ℕ) :
    KwIsogenyEndDatumSubfieldDescent K E N :=
  iE2E_subfieldDescent_of_subfieldDescent'' E N
    (subfieldDescent_of_iotaDescend K E N
      (fun D => iE2E_iotaDescendToFG_uncond E D))

theorem iE2E_fgFieldDescent_uncond (E : WeierstrassCurve K) [E.IsElliptic] (N : ℕ) :
    KwIsogenyEndDatumFGFieldDescent K E N :=
  fgFieldDescent_of_subfieldDescent_of_baseChangeToAC K E N
    (iE2E_subfieldDescent_uncond E N)
    (fun K₀ _ _ E₀ _ =>
      haveI : DecidableEq K₀ := Classical.decEq K₀
      baseChangeToAC_uncond K₀ E₀ N)

end E2EChain

end ModularCurve


namespace WeierstrassCurve

/-- The countable-descent headline. -/
theorem exists_intermediateField_countable_map_eq_and_finrankAlong_eq
    {K : Type u} [Field K] [CharZero K] [IsAlgClosed K]
    (E : WeierstrassCurve K) [E.IsElliptic]
    (ι : E.toAffine.FunctionField →ₐ[K] E.toAffine.FunctionField)
    (hι : ι.toRingHom.IsIntegral) (hfin : AlgebraicCurve.FiniteAlong K ι) :
    ∃ (K₀ : IntermediateField ℚ K), Countable K₀ ∧
      ∃ (E₀ : WeierstrassCurve K₀), E₀.IsElliptic ∧ E₀.map (algebraMap K₀ K) = E ∧
        ∃ (ι₀ : (E₀.baseChange (AlgebraicClosure K₀)).toAffine.FunctionField →ₐ[AlgebraicClosure K₀]
            (E₀.baseChange (AlgebraicClosure K₀)).toAffine.FunctionField),
          ι₀.toRingHom.IsIntegral ∧
          ∃ (hfin₀ : AlgebraicCurve.FiniteAlong (AlgebraicClosure K₀) ι₀),
            AlgebraicCurve.finrankAlong (AlgebraicClosure K₀) ι₀
              = AlgebraicCurve.finrankAlong K ι := by
  classical
  obtain ⟨K₀, hK₀, E₀, hE₀, hmap, D₀, hdeg⟩ :=
    ModularCurve.fgFieldDescent_uncond (K := K) E (AlgebraicCurve.finrankAlong K ι)
      ⟨⟨ι, hι, hfin⟩, rfl⟩
  exact ⟨K₀, hK₀, E₀, hE₀, hmap, D₀.ι, D₀.hι, D₀.hfin, hdeg⟩

end WeierstrassCurve
