/-
  The Frobenius-density degree-one count: the stabilizer of a prime above
  `ratPrimeIdeal ℓ` is generated by its arithmetic Frobenius, and the number of
  degree-one primes of `𝓞 E` above `ratPrimeIdeal ℓ` equals the number of cosets
  `(L ≃ₐ[ℚ] L) ⧸ H` fixed by that Frobenius.

  This module carries the three headlines
  * `stabilizer_eq_zpowers_arithFrobAt`,
  * `ncard_degreeOne_primesOver_under`,
  * `ncard_degreeOne_primesOver_eq_ncard_frobFixed`,

  transcribed from the pinned FLT solution files (`aa2d8b3`, `P2M/Sol/`):
  `S_FrobeniusDensity_stabilizer_eq_zpowers_arithFrobAt.lean` (122 lines),
  `S_FrobeniusDensity_ncard_degreeOne_primesOver_under.lean` (246 lines) and
  `S_FrobeniusDensity_ncard_degreeOne_primesOver_eq_ncard_frobFixed.lean`
  (44 lines). The mathematics is math/018 §6.

  The pin's `card_le_of_forall_pow_eq` copies are *not* restated: the port
  reuses the shared `FrobeniusDensity.card_le_of_forall_pow_eq` from
  `FrobeniusDensity/Basic.lean`, which is why that module is imported here.
  All other helpers are transcribed `private`, exactly as in the pin.
-/
import FLTForHuman.NumberTheory.FrobeniusDensity.BadPrimes
import FLTForHuman.NumberTheory.FrobeniusDensity.Basic
import Mathlib.NumberTheory.RamificationInertia.Galois
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.FieldTheory.Fixed
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.Tactic.Group

set_option autoImplicit false
open NumberField Ideal
open scoped Pointwise
attribute [local instance 1001] NumberField.RingOfIntegers.instMulSemiringAction
attribute [local instance] Ideal.Quotient.field

namespace FrobeniusDensity

/-! ## Order bounds for an arithmetic Frobenius -/

section OrderBound

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
  {G : Type*} [Group G] [MulSemiringAction G S] [SMulCommClass G R S]

private theorem IsArithFrobAt.mk_pow_smul' {σ : G} {Q : Ideal S} (h : IsArithFrobAt R σ Q)
    (m : ℕ) (x : S) :
    Ideal.Quotient.mk Q (σ ^ m • x) =
      Ideal.Quotient.mk Q x ^ Nat.card (R ⧸ Q.under R) ^ m := by
  induction m with
  | zero => simp
  | succ m ih =>
    have h1 : Ideal.Quotient.mk Q (σ • (σ ^ m • x)) =
        Ideal.Quotient.mk Q (σ ^ m • x) ^ Nat.card (R ⧸ Q.under R) := by
      rw [← map_pow, Ideal.Quotient.eq]
      exact h (σ ^ m • x)
    rw [pow_succ' σ m, mul_smul, h1, ih, ← pow_mul, pow_succ]

private theorem IsArithFrobAt.card_quotient_le_pow' {σ : G} {Q : Ideal S} [Q.IsPrime]
    [Finite (S ⧸ Q)] (h : IsArithFrobAt R σ Q) {m : ℕ} (hm : m ≠ 0) (hσ : σ ^ m = 1) :
    Nat.card (S ⧸ Q) ≤ Nat.card (R ⧸ Q.under R) ^ m := by
  have hq : 1 < Nat.card (R ⧸ Q.under R) := by
    have h1 : Finite (R ⧸ Q.under R) := h.finite_quotient
    have h2 : (Q.under R).IsPrime := Ideal.IsPrime.comap _
    have h3 : Nontrivial (R ⧸ Q.under R) := Ideal.Quotient.nontrivial_iff.mpr h2.ne_top
    exact Finite.one_lt_card
  refine card_le_of_forall_pow_eq (Nat.one_lt_pow hm hq) fun y ↦ ?_
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective y
  rw [← IsArithFrobAt.mk_pow_smul' h m x, hσ, one_smul]

end OrderBound

/-! ## The stabilizer is generated by an arithmetic Frobenius -/

section Stabilizer

private theorem isSeparable_residue' {L : Type*} [Field L] [NumberField L] {ℓ : ℕ}
    (hℓ : ℓ.Prime) (Q : Ideal (𝓞 L)) [Q.IsPrime] [Q.LiesOver (ratPrimeIdeal ℓ)] :
    Algebra.IsSeparable (ℤ ⧸ ratPrimeIdeal ℓ) ((𝓞 L) ⧸ Q) := by
  haveI : Fact ℓ.Prime := ⟨hℓ⟩
  have hQbot : Q ≠ ⊥ := ne_bot_of_liesOver_ratPrimeIdeal hℓ
  haveI : Finite ((𝓞 L) ⧸ Q) := finite_quotient_of_ne_bot hQbot
  haveI : Finite (ℤ ⧸ ratPrimeIdeal ℓ) :=
    Ring.HasFiniteQuotients.finiteQuotient (ratPrimeIdeal_ne_bot hℓ)
  haveI : Q.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hQbot
  haveI : (ratPrimeIdeal ℓ).IsMaximal :=
    ((Ideal.span_singleton_prime (by exact_mod_cast hℓ.ne_zero)).mpr
      (Int.prime_iff_natAbs_prime.mpr (by simpa using hℓ))).isMaximal (ratPrimeIdeal_ne_bot hℓ)
  exact Algebra.IsAlgebraic.isSeparable_of_perfectField

theorem stabilizer_eq_zpowers_arithFrobAt
    {L : Type*} [Field L] [NumberField L] [IsGalois ℚ L]
    {ℓ : ℕ} (hℓ : ℓ.Prime) (Q : Ideal (𝓞 L)) [Q.IsPrime]
    [Q.LiesOver (FrobeniusDensity.ratPrimeIdeal ℓ)] (hinertia : Q.inertia (L ≃ₐ[ℚ] L) = ⊥) :
    haveI : Finite ((𝓞 L) ⧸ Q) :=
      FrobeniusDensity.finite_quotient_of_ne_bot
        (FrobeniusDensity.ne_bot_of_liesOver_ratPrimeIdeal hℓ)
    MulAction.stabilizer (L ≃ₐ[ℚ] L) Q
      = Subgroup.zpowers (arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q) := by
  haveI : Fact ℓ.Prime := ⟨hℓ⟩
  have hQbot : Q ≠ ⊥ := ne_bot_of_liesOver_ratPrimeIdeal hℓ
  haveI : Finite ((𝓞 L) ⧸ Q) := finite_quotient_of_ne_bot hQbot
  haveI : Q.IsMaximal := Ideal.IsPrime.isMaximal ‹_› hQbot
  haveI : (ratPrimeIdeal ℓ).IsMaximal :=
    ((Ideal.span_singleton_prime (by exact_mod_cast hℓ.ne_zero)).mpr
      (Int.prime_iff_natAbs_prime.mpr (by simpa using hℓ))).isMaximal (ratPrimeIdeal_ne_bot hℓ)
  haveI : Finite (ℤ ⧸ ratPrimeIdeal ℓ) :=
    Ring.HasFiniteQuotients.finiteQuotient (ratPrimeIdeal_ne_bot hℓ)
  haveI := isSeparable_residue' (L := L) hℓ Q
  have hfrob : IsArithFrobAt ℤ (arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q) Q :=
    IsArithFrobAt.arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q
  have hle : Subgroup.zpowers (arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q)
      ≤ MulAction.stabilizer (L ≃ₐ[ℚ] L) Q :=
    Subgroup.zpowers_le.mpr hfrob.mem_stabilizer
  have hcard : Nat.card (MulAction.stabilizer (L ≃ₐ[ℚ] L) Q)
      = Module.finrank (ℤ ⧸ ratPrimeIdeal ℓ) ((𝓞 L) ⧸ Q) := by
    rw [Ideal.card_stabilizer_eq_card_inertia_mul_finrank (ratPrimeIdeal ℓ) Q, hinertia]
    simp [Ideal.inertiaDeg_eq_of_isMaximal (ratPrimeIdeal ℓ) Q]
  have hord : Module.finrank (ℤ ⧸ ratPrimeIdeal ℓ) ((𝓞 L) ⧸ Q)
      ≤ orderOf (arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q) := by
    have hbound := IsArithFrobAt.card_quotient_le_pow' hfrob
      (orderOf_pos (arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q)).ne' (pow_orderOf_eq_one _)
    rw [card_quotient_under_int (ℓ := ℓ) Q, Module.natCard_eq_pow_finrank
      (K := ℤ ⧸ ratPrimeIdeal ℓ) (V := (𝓞 L) ⧸ Q), card_quotient_ratPrimeIdeal] at hbound
    exact (Nat.pow_le_pow_iff_right hℓ.one_lt).mp hbound
  refine (Subgroup.eq_of_le_of_card_ge hle ?_).symm
  rw [hcard, Nat.card_eq_fintype_card, Fintype.card_zpowers]
  exact hord

end Stabilizer

/-! ## Degree-one primes under a Galois subgroup -/

section DegreeOne

variable {L : Type*} [Field L] [NumberField L]

private theorem inertia_smul_eq_bot {Q : Ideal (𝓞 L)}
    (hQ : Q.inertia (L ≃ₐ[ℚ] L) = ⊥) (g : L ≃ₐ[ℚ] L) :
    (g • Q).inertia (L ≃ₐ[ℚ] L) = ⊥ := by
  rw [Subgroup.eq_bot_iff_forall] at hQ ⊢
  intro σ hσ
  have h : g⁻¹ * σ * g ∈ Q.inertia (L ≃ₐ[ℚ] L) := by
    intro x
    have hx := hσ (g • x)
    rw [Submodule.mem_toAddSubgroup, Ideal.mem_pointwise_smul_iff_inv_smul_mem, smul_sub] at hx
    simpa [Submodule.mem_toAddSubgroup, mul_smul] using hx
  have h1 := hQ _ h
  rw [show σ = g * (g⁻¹ * σ * g) * g⁻¹ by group, h1]
  group

variable {H : Subgroup (L ≃ₐ[ℚ] L)} {E : IntermediateField ℚ L} [IsGaloisGroup H E L]

private theorem under_smul_of_mem {σ : L ≃ₐ[ℚ] L} (hσ : σ ∈ H) (Q : Ideal (𝓞 L)) :
    (σ • Q).under (𝓞 E) = Q.under (𝓞 E) := by
  rw [show σ • Q = (⟨σ, hσ⟩ : H) • Q from rfl]
  exact Ideal.under_smul (𝓞 E) Q (⟨σ, hσ⟩ : H)

scoped instance : SMulCommClass H (𝓞 E) (𝓞 L) := IsGaloisGroup.commutes

private theorem isArithFrobAt_coe_of_card_eq {Q : Ideal (𝓞 L)} {τ : H}
    (h : IsArithFrobAt (𝓞 E) τ Q)
    (hcard : Nat.card ((𝓞 E) ⧸ Q.under (𝓞 E)) = Nat.card (ℤ ⧸ Q.under ℤ)) :
    IsArithFrobAt ℤ (τ : L ≃ₐ[ℚ] L) Q := by
  intro x
  have hx := h x
  rw [hcard] at hx
  exact hx

private theorem exists_isArithFrobAt_mem {Q : Ideal (𝓞 L)} [Q.IsPrime] (hQ : Q ≠ ⊥)
    (hcard : Nat.card ((𝓞 E) ⧸ Q.under (𝓞 E)) = Nat.card (ℤ ⧸ Q.under ℤ)) :
    ∃ σ : L ≃ₐ[ℚ] L, σ ∈ H ∧ IsArithFrobAt ℤ σ Q := by
  have : Finite ((𝓞 L) ⧸ Q) := finite_quotient_of_ne_bot hQ
  obtain ⟨τ, hτ⟩ := IsArithFrobAt.exists_of_isInvariant (𝓞 E) H Q
  exact ⟨(τ : L ≃ₐ[ℚ] L), τ.2, isArithFrobAt_coe_of_card_eq hτ hcard⟩

private theorem mem_of_isArithFrobAt_of_card_eq {Q : Ideal (𝓞 L)} [Q.IsPrime] (hQ : Q ≠ ⊥)
    {σ : L ≃ₐ[ℚ] L} (hσ : IsArithFrobAt ℤ σ Q)
    (hcard : Nat.card ((𝓞 E) ⧸ Q.under (𝓞 E)) = Nat.card (ℤ ⧸ Q.under ℤ))
    (hinertia : Q.inertia (L ≃ₐ[ℚ] L) ≤ H) :
    σ ∈ H := by
  obtain ⟨τ, hτH, hτ⟩ := exists_isArithFrobAt_mem (H := H) (E := E) hQ hcard
  have hmem : σ * τ⁻¹ ∈ Q.inertia (L ≃ₐ[ℚ] L) := hσ.mul_inv_mem_inertia hτ
  simpa using mul_mem (hinertia hmem) hτH

variable {ℓ : ℕ} [IsGalois ℚ L]

private theorem le_card_quotient_under (hℓ : ℓ.Prime) (Q : Ideal (𝓞 L)) [Q.IsPrime]
    [Q.LiesOver (ratPrimeIdeal ℓ)] :
    ℓ ≤ Nat.card ((𝓞 E) ⧸ Q.under (𝓞 E)) := by
  haveI h𝔮 : (Q.under (𝓞 E)).LiesOver (ratPrimeIdeal ℓ) := Ideal.LiesOver.tower_bot Q _ _
  have h𝔮bot : Q.under (𝓞 E) ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot (ratPrimeIdeal_ne_bot hℓ) _
  have : Finite ((𝓞 E) ⧸ Q.under (𝓞 E)) := finite_quotient_of_ne_bot h𝔮bot
  calc ℓ = Nat.card (ℤ ⧸ (Q.under (𝓞 E)).under ℤ) :=
        (card_quotient_under_int (ℓ := ℓ) (Q.under (𝓞 E))).symm
    _ ≤ Nat.card ((𝓞 E) ⧸ Q.under (𝓞 E)) :=
        Nat.card_le_card_of_injective _ (FaithfulSMul.algebraMap_injective _ _)

private theorem exists_isArithFrobAt' {Q : Ideal (𝓞 L)} [Q.IsPrime] (hQ : Q ≠ ⊥) :
    ∃ σ : L ≃ₐ[ℚ] L, IsArithFrobAt ℤ σ Q :=
  have : Finite (𝓞 L ⧸ Q) := finite_quotient_of_ne_bot hQ
  IsArithFrobAt.exists_of_isInvariant ℤ (L ≃ₐ[ℚ] L) Q

private theorem card_under_eq_of_stabilizer_le (hℓ : ℓ.Prime) (Q : Ideal (𝓞 L)) [Q.IsPrime]
    [Q.LiesOver (ratPrimeIdeal ℓ)]
    (hstab : MulAction.stabilizer (L ≃ₐ[ℚ] L) Q ≤ H) :
    Nat.card ((𝓞 E) ⧸ Q.under (𝓞 E)) = ℓ := by
  refine le_antisymm ?_ (le_card_quotient_under hℓ Q)
  have hQbot : Q ≠ ⊥ := ne_bot_of_liesOver_ratPrimeIdeal hℓ
  obtain ⟨σ, hσ⟩ := exists_isArithFrobAt' (L := L) hQbot
  have hσH : σ ∈ H := hstab hσ.mem_stabilizer
  haveI h𝔮 : (Q.under (𝓞 E)).LiesOver (ratPrimeIdeal ℓ) := Ideal.LiesOver.tower_bot Q _ _
  have h𝔮bot : Q.under (𝓞 E) ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot (ratPrimeIdeal_ne_bot hℓ) _
  have : Finite ((𝓞 E) ⧸ Q.under (𝓞 E)) := finite_quotient_of_ne_bot h𝔮bot
  have hpow : ∀ y : (𝓞 E) ⧸ Q.under (𝓞 E), y ^ ℓ = y := by
    intro y
    obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective y
    rw [← map_pow, eq_comm, Ideal.Quotient.eq, Ideal.mem_comap]
    have hfix : (MulSemiringAction.toAlgHom ℤ (𝓞 L) σ) (algebraMap (𝓞 E) (𝓞 L) x)
        = algebraMap (𝓞 E) (𝓞 L) x := smul_algebraMap (⟨σ, hσH⟩ : H) x
    have hcong := hσ (algebraMap (𝓞 E) (𝓞 L) x)
    rw [card_quotient_under_int (ℓ := ℓ) Q, hfix] at hcong
    simpa using hcong
  exact card_le_of_forall_pow_eq hℓ.one_lt hpow

private theorem stabilizer_le_of_card_under_eq (hℓ : ℓ.Prime) (Q : Ideal (𝓞 L)) [Q.IsPrime]
    [Q.LiesOver (ratPrimeIdeal ℓ)] (hinertia : Q.inertia (L ≃ₐ[ℚ] L) = ⊥)
    (hdeg : Nat.card ((𝓞 E) ⧸ Q.under (𝓞 E)) = ℓ) :
    MulAction.stabilizer (L ≃ₐ[ℚ] L) Q ≤ H := by
  have hQbot : Q ≠ ⊥ := ne_bot_of_liesOver_ratPrimeIdeal hℓ
  haveI : Finite ((𝓞 L) ⧸ Q) := finite_quotient_of_ne_bot hQbot
  rw [stabilizer_eq_zpowers_arithFrobAt hℓ Q hinertia, Subgroup.zpowers_le]
  refine mem_of_isArithFrobAt_of_card_eq (E := E) hQbot
    (IsArithFrobAt.arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q) ?_ (hinertia ▸ bot_le)
  rw [hdeg, card_quotient_under_int (ℓ := ℓ) Q]

variable (E) in
private def restrictPrime (Q₀ : Ideal (𝓞 L)) (x : (L ≃ₐ[ℚ] L) ⧸ H) : Ideal (𝓞 E) :=
  Quotient.liftOn' x (fun g ↦ (g⁻¹ • Q₀).under (𝓞 E)) fun g₁ g₂ hg ↦ by
    have h : g₁⁻¹ * g₂ ∈ H := QuotientGroup.leftRel_apply.mp hg
    show (g₁⁻¹ • Q₀).under (𝓞 E) = (g₂⁻¹ • Q₀).under (𝓞 E)
    rw [show g₂⁻¹ = (g₁⁻¹ * g₂)⁻¹ * g₁⁻¹ by group, mul_smul]
    exact (under_smul_of_mem (inv_mem h) _).symm

private theorem restrictPrime_mk (Q₀ : Ideal (𝓞 L)) (g : L ≃ₐ[ℚ] L) :
    restrictPrime E Q₀ (g : (L ≃ₐ[ℚ] L) ⧸ H) = (g⁻¹ • Q₀).under (𝓞 E) := rfl

private theorem mem_stabilizer_inv_smul_iff (Q₀ : Ideal (𝓞 L)) (g σ : L ≃ₐ[ℚ] L) :
    σ ∈ MulAction.stabilizer (L ≃ₐ[ℚ] L) (g⁻¹ • Q₀)
      ↔ g * σ * g⁻¹ ∈ MulAction.stabilizer (L ≃ₐ[ℚ] L) Q₀ := by
  rw [MulAction.stabilizer_smul_eq_stabilizer_map_conj, Subgroup.mem_map_equiv,
    MulAut.conj_symm_apply]
  group

private theorem forall_smul_eq_iff_stabilizer_le (Q₀ : Ideal (𝓞 L)) (g : L ≃ₐ[ℚ] L) :
    (∀ d ∈ MulAction.stabilizer (L ≃ₐ[ℚ] L) Q₀, d • (g : (L ≃ₐ[ℚ] L) ⧸ H) = g)
      ↔ MulAction.stabilizer (L ≃ₐ[ℚ] L) (g⁻¹ • Q₀) ≤ H := by
  constructor
  · intro hfix σ hσ
    have hd : g * σ * g⁻¹ ∈ MulAction.stabilizer (L ≃ₐ[ℚ] L) Q₀ :=
      (mem_stabilizer_inv_smul_iff Q₀ g σ).mp hσ
    have h1 := hfix _ hd
    rw [MulAction.Quotient.smul_coe, smul_eq_mul, QuotientGroup.eq,
      show (g * σ * g⁻¹ * g)⁻¹ * g = σ⁻¹ by group] at h1
    simpa using h1
  · intro hle d hd
    rw [MulAction.Quotient.smul_coe, smul_eq_mul, QuotientGroup.eq,
      show (d * g)⁻¹ * g = g⁻¹ * d⁻¹ * g by group]
    refine hle ((mem_stabilizer_inv_smul_iff Q₀ g _).mpr ?_)
    rw [show g * (g⁻¹ * d⁻¹ * g) * g⁻¹ = d⁻¹ by group]
    exact inv_mem hd

private theorem exists_mem_smul_eq_of_under_eq (Q Q' : Ideal (𝓞 L)) [Q.IsPrime] [Q'.IsPrime]
    (h : Q.under (𝓞 E) = Q'.under (𝓞 E)) :
    ∃ σ ∈ H, σ • Q = Q' := by
  haveI : Q'.LiesOver (Q.under (𝓞 E)) := ⟨h⟩
  obtain ⟨τ, hτ⟩ := Ideal.exists_smul_eq_of_isGaloisGroup (Q.under (𝓞 E)) Q Q' H
  exact ⟨(τ : L ≃ₐ[ℚ] L), τ.2, hτ⟩

theorem ncard_degreeOne_primesOver_under
    {L : Type*} [Field L] [NumberField L] [IsGalois ℚ L]
    {H : Subgroup (L ≃ₐ[ℚ] L)} {E : IntermediateField ℚ L} [IsGaloisGroup H E L]
    {ℓ : ℕ} (hℓ : ℓ.Prime) (Q₀ : Ideal (𝓞 L)) [Q₀.IsPrime]
    [Q₀.LiesOver (FrobeniusDensity.ratPrimeIdeal ℓ)] (hinertia : Q₀.inertia (L ≃ₐ[ℚ] L) = ⊥) :
    {𝔮 ∈ (FrobeniusDensity.ratPrimeIdeal ℓ).primesOver (𝓞 E) |
      Nat.card ((𝓞 E) ⧸ 𝔮) = ℓ}.ncard
      = {x : (L ≃ₐ[ℚ] L) ⧸ H |
          ∀ d ∈ MulAction.stabilizer (L ≃ₐ[ℚ] L) Q₀, d • x = x}.ncard := by
  set S : Set ((L ≃ₐ[ℚ] L) ⧸ H) :=
    {x | ∀ d ∈ MulAction.stabilizer (L ≃ₐ[ℚ] L) Q₀, d • x = x} with hS
  set T : Set (Ideal (𝓞 E)) :=
    {𝔮 ∈ (ratPrimeIdeal ℓ).primesOver (𝓞 E) | Nat.card ((𝓞 E) ⧸ 𝔮) = ℓ} with hT
  have hinj : Set.InjOn (restrictPrime E Q₀) S := by
    intro x hx y hy hxy
    obtain ⟨g₁, rfl⟩ := QuotientGroup.mk_surjective x
    obtain ⟨g₂, rfl⟩ := QuotientGroup.mk_surjective y
    rw [restrictPrime_mk, restrictPrime_mk] at hxy
    obtain ⟨τ, hτH, hτ⟩ := exists_mem_smul_eq_of_under_eq (H := H) (g₁⁻¹ • Q₀) (g₂⁻¹ • Q₀) hxy
    have hd : g₂ * τ * g₁⁻¹ ∈ MulAction.stabilizer (L ≃ₐ[ℚ] L) Q₀ := by
      rw [MulAction.mem_stabilizer_iff, mul_smul, mul_smul, hτ, smul_inv_smul]
    have hfix := hx _ hd
    rw [MulAction.Quotient.smul_coe, smul_eq_mul, QuotientGroup.eq] at hfix
    have h2 : τ⁻¹ * g₂⁻¹ * g₁ ∈ H := by
      rw [show τ⁻¹ * g₂⁻¹ * g₁ = (g₂ * τ * g₁⁻¹ * g₁)⁻¹ * g₁ by group]
      exact hfix
    have h3 : g₂⁻¹ * g₁ ∈ H := by
      rw [show g₂⁻¹ * g₁ = τ * (τ⁻¹ * g₂⁻¹ * g₁) by group]
      exact mul_mem hτH h2
    rw [QuotientGroup.eq, show g₁⁻¹ * g₂ = (g₂⁻¹ * g₁)⁻¹ by group]
    exact inv_mem h3
  have himage : restrictPrime E Q₀ '' S = T := by
    ext 𝔮
    constructor
    · rintro ⟨x, hx, rfl⟩
      obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective x
      replace hx : MulAction.stabilizer (L ≃ₐ[ℚ] L) (g⁻¹ • Q₀) ≤ H :=
        (forall_smul_eq_iff_stabilizer_le Q₀ g).mp hx
      rw [restrictPrime_mk]
      refine ⟨⟨inferInstance, Ideal.LiesOver.tower_bot (g⁻¹ • Q₀) _ _⟩, ?_⟩
      exact card_under_eq_of_stabilizer_le hℓ (g⁻¹ • Q₀) hx
    · rintro ⟨⟨h𝔮p, h𝔮l⟩, h𝔮deg⟩
      haveI := h𝔮p
      haveI := h𝔮l
      obtain ⟨⟨Q, hQp, hQl⟩⟩ := Ideal.nonempty_primesOver (S := 𝓞 L) 𝔮
      haveI := hQp
      haveI := hQl
      haveI : Q.LiesOver (ratPrimeIdeal ℓ) := Ideal.LiesOver.trans Q 𝔮 _
      obtain ⟨g, hg⟩ := Ideal.exists_smul_eq_of_isGaloisGroup
        (ratPrimeIdeal ℓ) Q₀ Q (L ≃ₐ[ℚ] L)
      refine ⟨((g⁻¹ : L ≃ₐ[ℚ] L) : (L ≃ₐ[ℚ] L) ⧸ H), ?_, ?_⟩
      · refine (forall_smul_eq_iff_stabilizer_le Q₀ g⁻¹).mpr ?_
        rw [inv_inv, hg]
        refine stabilizer_le_of_card_under_eq (E := E) hℓ Q
          (hg ▸ inertia_smul_eq_bot hinertia g) ?_
        rw [← Q.over_def 𝔮]
        exact h𝔮deg
      · rw [restrictPrime_mk, inv_inv, hg]
        exact (Q.over_def 𝔮).symm
  rw [← himage]
  exact hinj.ncard_image

end DegreeOne

/-! ## Specialising the stabilizer to the Frobenius-generated subgroup -/

section FrobFixed

private theorem forall_mem_zpowers_smul_eq_iff {G α : Type*} [Group G] [MulAction G α]
    (σ : G) (x : α) :
    (∀ d ∈ Subgroup.zpowers σ, d • x = x) ↔ σ • x = x := by
  constructor
  · exact fun h ↦ h σ (Subgroup.mem_zpowers σ)
  · intro h d hd
    have : Subgroup.zpowers σ ≤ MulAction.stabilizer G x := Subgroup.zpowers_le.mpr h
    exact this hd

theorem ncard_degreeOne_primesOver_eq_ncard_frobFixed
    {L : Type*} [Field L] [NumberField L] [IsGalois ℚ L]
    {H : Subgroup (L ≃ₐ[ℚ] L)} {E : IntermediateField ℚ L} [IsGaloisGroup H E L]
    {ℓ : ℕ} (hℓ : ℓ.Prime) (Q₀ : Ideal (𝓞 L)) [Q₀.IsPrime]
    [Q₀.LiesOver (FrobeniusDensity.ratPrimeIdeal ℓ)] (hinertia : Q₀.inertia (L ≃ₐ[ℚ] L) = ⊥) :
    haveI : Finite ((𝓞 L) ⧸ Q₀) :=
      FrobeniusDensity.finite_quotient_of_ne_bot
        (FrobeniusDensity.ne_bot_of_liesOver_ratPrimeIdeal hℓ)
    {𝔮 ∈ (FrobeniusDensity.ratPrimeIdeal ℓ).primesOver (𝓞 E) |
      Nat.card ((𝓞 E) ⧸ 𝔮) = ℓ}.ncard
      = {x : (L ≃ₐ[ℚ] L) ⧸ H | arithFrobAt ℤ (L ≃ₐ[ℚ] L) Q₀ • x = x}.ncard := by
  haveI : Finite ((𝓞 L) ⧸ Q₀) :=
    FrobeniusDensity.finite_quotient_of_ne_bot
      (FrobeniusDensity.ne_bot_of_liesOver_ratPrimeIdeal hℓ)
  rw [ncard_degreeOne_primesOver_under (H := H) (E := E) hℓ Q₀ hinertia]
  congr 1
  ext x
  rw [Set.mem_ofPred_eq, Set.mem_ofPred_eq,
    stabilizer_eq_zpowers_arithFrobAt hℓ Q₀ hinertia,
    forall_mem_zpowers_smul_eq_iff]

end FrobFixed

end FrobeniusDensity
