/-
  The Möbius / `zpowers` group-theoretic counting chain of the Frobenius-density
  input (S7-II).

  This module carries:

  * the arithmetic Möbius inversion identity
    `ArithmeticFunction.sum_moebius_filter_dvd`;
  * the group-theoretic `sum_moebius_mem_zpowers` (deferred by H1 because its pin
    proof consumes `ArithmeticFunction.sum_moebius_filter_dvd`) and its two
    headline consequences `FrobeniusDensity.sum_moebius_mul_pos` and
    `FrobeniusDensity.weight_eq`.

  The shared group-theoretic prelude (`mem_zpowers_pow_div_iff`,
  `exists_pow_coprime_eq_of_orderOf_eq`, `orderOf_pow_orderOf_div`,
  `ncard_conj_mem_eq_card_mul_ncard`, `ncard_eq_sum_indicator`) is imported from
  the H1 `Basic.lean` and not re-proved.

  Transcribed from the pinned FLT solution files (`aa2d8b3`,
  `P2M/Sol/S_ArithmeticFunction_sum_moebius_filter_dvd.lean`,
  `P2M/Sol/S_FrobeniusDensity_sum_moebius_mul_pos.lean`,
  `P2M/Sol/S_FrobeniusDensity_weight_eq.lean`).
-/
import FLTForHuman.NumberTheory.FrobeniusDensity.Basic
import Mathlib.NumberTheory.ArithmeticFunction.Moebius

set_option autoImplicit false

open scoped ArithmeticFunction.Moebius ArithmeticFunction.zeta
open ArithmeticFunction Finset

namespace ArithmeticFunction

theorem sum_moebius_filter_dvd {n m : ℕ} (hn : n ≠ 0) (hm : m ∣ n) :
    ∑ f ∈ n.divisors, ArithmeticFunction.moebius (n / f) * (if m ∣ f then 1 else 0)
      = if m = n then 1 else 0 := by
  have hre : ∑ f ∈ n.divisors, μ (n / f) * (if m ∣ f then 1 else 0)
      = ∑ f ∈ n.divisors, μ f * (if m ∣ n / f then 1 else 0) := by
    rw [← Nat.sum_div_divisors n (fun f => μ f * (if m ∣ n / f then 1 else 0))]
    refine Finset.sum_congr rfl fun f hf => ?_
    rw [Nat.div_div_self (Nat.mem_divisors.mp hf).1 hn]
  rw [hre]
  have hsum : ∑ f ∈ n.divisors, μ f * (if m ∣ n / f then 1 else 0)
      = ∑ f ∈ (n / m).divisors, μ f := by
    rw [← Nat.divisors_filter_dvd_of_dvd hn (Nat.div_dvd_of_dvd hm), Finset.sum_filter]
    refine Finset.sum_congr rfl fun f hf => ?_
    have hfn : f ∣ n := (Nat.mem_divisors.mp hf).1
    have hiff : m ∣ n / f ↔ f ∣ n / m := by
      rw [Nat.dvd_div_iff_mul_dvd hfn, Nat.dvd_div_iff_mul_dvd hm, mul_comm]
    rw [if_congr hiff rfl rfl]
    split <;> simp
  rw [hsum]
  have hsum2 : ∑ d ∈ (n/m).divisors, μ d = if n/m = 1 then 1 else 0 := by
    have h2 : (μ * ζ : ArithmeticFunction ℤ) (n/m) = (1 : ArithmeticFunction ℤ) (n/m) := by
      rw [moebius_mul_coe_zeta]
    rwa [coe_mul_zeta_apply, one_apply] at h2
  rw [hsum2]
  congr 1
  simp only [eq_iff_iff]
  constructor
  · intro h; have := Nat.eq_mul_of_div_eq_right hm h; omega
  · rintro rfl; exact Nat.div_self (Nat.pos_of_ne_zero hn)

end ArithmeticFunction

namespace FrobeniusDensity

section Weight

variable {G : Type*} [Group G] [Finite G]

/-- Möbius inversion over the divisor lattice of `orderOf σ`: the sum over the
divisors `f` of the Möbius weight of the subgroup generated by `σ ^ (orderOf σ / f)`
picks out the elements of the cyclic subgroup whose order is exactly `orderOf σ`. -/
theorem sum_moebius_mem_zpowers (σ y : G) :
    ∑ f ∈ (orderOf σ).divisors,
        (ArithmeticFunction.moebius (orderOf σ / f)) *
          (if y ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0)
      = if y ∈ Subgroup.zpowers σ ∧ orderOf y = orderOf σ then 1 else 0 := by
  classical
  have hn0 : orderOf σ ≠ 0 := (orderOf_pos σ).ne'
  by_cases hy : y ∈ Subgroup.zpowers σ
  · have hdvd : orderOf y ∣ orderOf σ := orderOf_dvd_of_mem_zpowers hy
    have hcong : ∀ f ∈ (orderOf σ).divisors,
        (ArithmeticFunction.moebius (orderOf σ / f)) *
            (if y ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0)
          = (ArithmeticFunction.moebius (orderOf σ / f)) *
              (if orderOf y ∣ f then 1 else 0) := by
      intro f hf
      obtain ⟨hfn, -⟩ := Nat.mem_divisors.mp hf
      have hf0 : f ≠ 0 := by
        rintro rfl
        exact hn0 (Nat.eq_zero_of_zero_dvd hfn)
      congr 1
      rw [if_congr (mem_zpowers_pow_div_iff σ y hfn hf0) rfl rfl]
      simp [hy]
    rw [Finset.sum_congr rfl hcong,
      ArithmeticFunction.sum_moebius_filter_dvd hn0 hdvd]
    simp [hy]
  · have hcong : ∀ f ∈ (orderOf σ).divisors,
        (ArithmeticFunction.moebius (orderOf σ / f)) *
            (if y ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0) = 0 := by
      intro f hf
      obtain ⟨hfn, -⟩ := Nat.mem_divisors.mp hf
      have hf0 : f ≠ 0 := by
        rintro rfl
        exact hn0 (Nat.eq_zero_of_zero_dvd hfn)
      have h : y ∉ Subgroup.zpowers (σ ^ (orderOf σ / f)) := fun hmem =>
        hy ((mem_zpowers_pow_div_iff σ y hfn hf0).mp hmem).1
      simp [h]
    rw [Finset.sum_congr rfl hcong]
    simp [hy]

end Weight

open scoped Classical in
theorem sum_moebius_mul_pos {G : Type*} [Group G] [Finite G] (σ : G) :
    0 < ∑ f ∈ (orderOf σ).divisors,
      (ArithmeticFunction.moebius (orderOf σ / f)) * (f : ℤ) := by
  have hfin : Fintype G := Fintype.ofFinite G
  have hn0 : orderOf σ ≠ 0 := (orderOf_pos σ).ne'
  have hcard : ∀ f ∈ (orderOf σ).divisors,
      (f : ℤ) = ∑ y : G, (if y ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0) := by
    intro f hf
    obtain ⟨hfn, -⟩ := Nat.mem_divisors.mp hf
    have hf0 : f ≠ 0 := by
      rintro rfl
      exact hn0 (Nat.eq_zero_of_zero_dvd hfn)
    rw [← ncard_eq_sum_indicator]
    norm_cast
    have h1 : {y : G | y ∈ Subgroup.zpowers (σ ^ (orderOf σ / f))}.ncard
        = Nat.card (Subgroup.zpowers (σ ^ (orderOf σ / f))) := by
      rw [← Nat.card_coe_set_eq]
      exact Nat.card_congr (Equiv.subtypeEquivRight fun y => Iff.rfl)
    rw [h1, Nat.card_eq_fintype_card, Fintype.card_zpowers]
    exact (orderOf_pow_orderOf_div σ hfn hf0).symm
  calc (0 : ℤ) < if (σ : G) ∈ Subgroup.zpowers σ ∧ orderOf σ = orderOf σ then 1 else 0 := by
        simp [Subgroup.mem_zpowers]
    _ ≤ ∑ y : G, (if y ∈ Subgroup.zpowers σ ∧ orderOf y = orderOf σ then 1 else 0) := by
        refine Finset.single_le_sum (f := fun y : G =>
          (if y ∈ Subgroup.zpowers σ ∧ orderOf y = orderOf σ then (1:ℤ) else 0))
          (fun y _ => by positivity) (Finset.mem_univ σ)
    _ = ∑ y : G, ∑ f ∈ (orderOf σ).divisors, (ArithmeticFunction.moebius (orderOf σ / f)) *
          (if y ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0) :=
        Finset.sum_congr rfl fun y _ => (sum_moebius_mem_zpowers σ y).symm
    _ = ∑ f ∈ (orderOf σ).divisors, ∑ y : G, (ArithmeticFunction.moebius (orderOf σ / f)) *
          (if y ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0) := Finset.sum_comm
    _ = ∑ f ∈ (orderOf σ).divisors, (ArithmeticFunction.moebius (orderOf σ / f)) * (f : ℤ) := by
        refine Finset.sum_congr rfl fun f hf => ?_
        rw [hcard f hf, Finset.mul_sum]

open scoped Classical in
theorem weight_eq {G : Type*} [Group G] [Finite G] (σ τ : G) :
    ∑ f ∈ (orderOf σ).divisors,
        (ArithmeticFunction.moebius (orderOf σ / f)) *
          ((f : ℤ) * ({x : G ⧸ Subgroup.zpowers (σ ^ (orderOf σ / f)) | τ • x = x}.ncard : ℤ))
      = ({g : G | ∃ k : ℕ, k.Coprime (orderOf σ) ∧ g * σ ^ k * g⁻¹ = τ}.ncard : ℤ) := by
  have hfin : Fintype G := Fintype.ofFinite G
  have hn0 : orderOf σ ≠ 0 := (orderOf_pos σ).ne'
  have hstep1 : ∀ f ∈ (orderOf σ).divisors,
      (f : ℤ) * ({x : G ⧸ Subgroup.zpowers (σ ^ (orderOf σ / f)) | τ • x = x}.ncard : ℤ)
        = ({g : G | g⁻¹ * τ * g ∈ Subgroup.zpowers (σ ^ (orderOf σ / f))}.ncard : ℤ) := by
    intro f hf
    obtain ⟨hfn, -⟩ := Nat.mem_divisors.mp hf
    have hf0 : f ≠ 0 := by
      rintro rfl
      exact hn0 (Nat.eq_zero_of_zero_dvd hfn)
    have hcard : Nat.card (Subgroup.zpowers (σ ^ (orderOf σ / f))) = f := by
      rw [Nat.card_eq_fintype_card, Fintype.card_zpowers]
      exact orderOf_pow_orderOf_div σ hfn hf0
    rw [ncard_conj_mem_eq_card_mul_ncard, hcard]
    push_cast
    ring
  rw [Finset.sum_congr rfl fun f hf => by rw [hstep1 f hf]]
  have hstep2 : ∀ f ∈ (orderOf σ).divisors,
      (ArithmeticFunction.moebius (orderOf σ / f)) *
          ({g : G | g⁻¹ * τ * g ∈ Subgroup.zpowers (σ ^ (orderOf σ / f))}.ncard : ℤ)
        = ∑ g : G, (ArithmeticFunction.moebius (orderOf σ / f)) *
            (if g⁻¹ * τ * g ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0) := by
    intro f _
    rw [ncard_eq_sum_indicator, Finset.mul_sum]
  rw [Finset.sum_congr rfl hstep2, Finset.sum_comm]
  have hstep3 : ∀ g : G,
      ∑ f ∈ (orderOf σ).divisors, (ArithmeticFunction.moebius (orderOf σ / f)) *
          (if g⁻¹ * τ * g ∈ Subgroup.zpowers (σ ^ (orderOf σ / f)) then 1 else 0)
        = if ∃ k : ℕ, k.Coprime (orderOf σ) ∧ g * σ ^ k * g⁻¹ = τ then 1 else 0 := by
    intro g
    rw [sum_moebius_mem_zpowers σ (g⁻¹ * τ * g)]
    congr 1
    simp only [eq_iff_iff]
    constructor
    · rintro ⟨hmem, hord⟩
      obtain ⟨k, hk, hkeq⟩ := exists_pow_coprime_eq_of_orderOf_eq hmem hord
      exact ⟨k, hk, by rw [hkeq]; group⟩
    · rintro ⟨k, hk, hkeq⟩
      have hyk : g⁻¹ * τ * g = σ ^ k := by rw [← hkeq]; group
      refine ⟨hyk ▸ Subgroup.pow_mem _ (Subgroup.mem_zpowers σ) _, ?_⟩
      rw [hyk]
      rcases Nat.eq_zero_or_pos k with rfl | hk0
      · simp only [Nat.coprime_zero_left] at hk
        simp [hk]
      · rw [orderOf_pow' σ hk0.ne', Nat.Coprime.gcd_eq_one (Nat.coprime_comm.mp hk),
          Nat.div_one]
  rw [Finset.sum_congr rfl fun g _ => hstep3 g, ← ncard_eq_sum_indicator]

end FrobeniusDensity
