/-
  The finite/free Hecke algebra (T10, unblocked by route C′).

  `CuspForm.heckeAlgebra N k S` is the `ℤ`-subalgebra of `End_ℂ(S_k(Γ₀(N)))`
  generated by the `T_ℓ` and `U_q` (`Defs/HeckeAlgebra`); T9 showed it preserves
  the integral lattice `intLattice N k` (`mem_intLattice_of_mem_heckeAlgebra`).
  This module closes the finiteness half that SET 4 had to leave blocked: the
  lattice is finitely generated (`intLattice_fg`, in `HeckeLattice.lean`), the
  Hecke algebra embeds `ℤ`-linearly into `End_ℤ(intLattice)` (the action
  *restricts* to the lattice), `End_ℤ` of a finite free `ℤ`-module is finite, and
  the embedding is injective because a `ℂ`-linear endomorphism vanishing on a
  full-rank lattice is zero (`HasIntegralStructure.eq_zero_of_forall_mem_intLattice`).

  The hypothesis `HasIntegralStructure N k` is now available unconditionally for
  `2 ≤ k` — route C′ proved it in `ModularForms/WeightOne/IntegralStructure.lean`
  via the trace over `Γ₁ ⊴ Γ₀` — so `moduleFinite_heckeAlgebra` specialises it and
  the pin's two `_two` one-liners follow. The weight-`k ≤ 1` branch is handled
  separately: `S_k(Γ₀(N))` is then a subsingleton (negative weight, weight `0`
  cusp forms, or `-1 ∈ Γ₀` and odd weight), so the algebra is a subsingleton.

  Headlines (statements verbatim from the pinned `Theorems/` wrappers):

  * `CuspForm.HasIntegralStructure.eq_zero_of_forall_mem_intLattice`;
  * `CuspForm.intLattice_fg`, `CuspForm.intLattice_free_and_finite`
    (`HeckeLattice.lean`, where the lattice coefficient block lives);
  * `CuspForm.HasIntegralStructure.moduleFinite_heckeAlgebra`,
    `…moduleFree_heckeAlgebra`;
  * `CuspForm.moduleFinite_heckeAlgebra`,
    `CuspForm.moduleFinite_heckeAlgebra_two`,
    `CuspForm.fg_toSubmodule_heckeAlgebra`;
  * `CuspForm.finrank_span_heckeAlgebra_eq_finrank` — the `ℂ`-span of the weight-2
    Hecke algebra has the dimension of `S₂(Γ₀(N))`, via the `a₁` pairing
    (`a1Pairing`, injective in both slots) rather than the Petersson product.

  **The pin's largest dedup holds.** `S_CuspForm_moduleFinite_heckeAlgebra_two.lean`
  is 4,308 lines and re-derives the Hecke analytic/`repMat`/`heckeSlashSum`
  machinery the port already has; it is now the one-liner
  `CuspForm.moduleFinite_heckeAlgebra N 2 S`. `S_CuspForm_hasIntegralStructure_two.lean`
  (212 lines) is already the one-liner `hasIntegralStructure_two` in
  `WeightOne/IntegralStructure.lean`.

  **Still blocked (not this module).** Three of T10's eigenbasis-span targets need
  infrastructure the port does not carry: `span_heckeTLin_eigen_eq_top` needs the
  Petersson inner product and `petersson_heckeTLin`; `exists_cyclic_span_heckeAlgebra`
  (and its corollary `exists_top_eq_heckeAlgebra_adjoin_smul`) needs the
  newform/Atkin–Lehner separation `CuspForm.exists_finite_separated_newform_family`;
  `heckeEvalForms_range_eq_top` needs `Def_CuspForm_HeckeEvalForms` (via
  `Def_HeckeGalois_EichlerShimura`). See `logs/hecke-port.md` §T10.

  FLT `anthropics/fermats-last-theorem@aa2d8b3`:
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_CuspForm_HasIntegralStructure_eq_zero_of_forall_mem_intLattice.lean
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_CuspForm_HasIntegralStructure_moduleFinite_heckeAlgebra.lean
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_CuspForm_HasIntegralStructure_moduleFree_heckeAlgebra.lean
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_CuspForm_moduleFinite_heckeAlgebra.lean
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_CuspForm_moduleFinite_heckeAlgebra_two.lean
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_CuspForm_fg_toSubmodule_heckeAlgebra.lean
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_CuspForm_finrank_span_heckeAlgebra_eq_finrank.lean
-/
import FLTForHuman.ModularForms.HeckeLattice
import FLTForHuman.ModularForms.HeckeEigenform
import FLTForHuman.ModularForms.WeightOne.IntegralStructure
import Mathlib.NumberTheory.ModularForms.CuspFormSubmodule
import Mathlib.NumberTheory.ModularForms.NormTrace
import Mathlib.NumberTheory.ModularForms.Cusps

set_option autoImplicit false

noncomputable section

open Complex Function Filter
open UpperHalfPlane hiding I
open scoped MatrixGroups ModularForm Manifold

namespace CuspForm

variable {N : ℕ} {k : ℤ} {S : Set ℕ}

/-- The full-rank predicate makes a `ℂ`-linear endomorphism that vanishes on the
lattice zero. Stated verbatim from
`Theorems/Thm_CuspForm_HasIntegralStructure_eq_zero_of_forall_mem_intLattice.lean`. -/
theorem HasIntegralStructure.eq_zero_of_forall_mem_intLattice {N : ℕ} {k : ℤ}
    (hN : CuspForm.HasIntegralStructure N k)
    (t : Module.End ℂ (CuspForm (CongruenceSubgroup.Gamma0 N) k))
    (h : ∀ f ∈ CuspForm.intLattice N k, t f = 0) : t = 0 :=
  LinearMap.ext_on hN fun f hf ↦ by rw [LinearMap.zero_apply]; exact h f hf

/-- The Hecke algebra is finite over `ℤ` as soon as the lattice is full-rank.
Stated verbatim from
`Theorems/Thm_CuspForm_HasIntegralStructure_moduleFinite_heckeAlgebra.lean`. -/
theorem HasIntegralStructure.moduleFinite_heckeAlgebra {N : ℕ} [NeZero N] {k : ℤ}
    (hN : CuspForm.HasIntegralStructure N k) (hk : 1 ≤ k) (S : Set ℕ) :
    Module.Finite ℤ (CuspForm.heckeAlgebra N k S) := by
  classical
  let V := CuspForm (CongruenceSubgroup.Gamma0 N) k
  let L : Submodule ℤ V := intLattice N k
  have : Module.Finite ℤ L := Module.Finite.iff_fg.mpr (CuspForm.intLattice_fg N k)
  have : IsAddTorsionFree V := by
    refine ⟨fun n hn a b hab ↦ ?_⟩
    have h : (n : ℂ) • a = (n : ℂ) • b := by
      simpa only [Nat.cast_smul_eq_nsmul] using hab
    exact smul_right_injective V (Nat.cast_ne_zero.mpr hn) h
  have : IsAddTorsionFree L := by
    refine ⟨fun n hn a b hab ↦ ?_⟩
    apply Subtype.ext
    exact IsAddTorsionFree.nsmul_right_injective (M := V) hn
      (by simpa using congrArg Subtype.val hab)
  have : Module.Free ℤ L := inferInstance
  let ψ : heckeAlgebra N k S →ₗ[ℤ] Module.End ℤ L :=
    { toFun := fun t ↦ ((t : Module.End ℂ V).restrictScalars ℤ).restrict
        (fun f hf ↦ CuspForm.mem_intLattice_of_mem_heckeAlgebra hk t.2 hf)
      map_add' := fun t t' ↦ by ext f; rfl
      map_smul' := fun n t ↦ by ext f; rfl }
  have hψ : Function.Injective ψ := by
    rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
    intro t ht
    apply Subtype.ext
    refine CuspForm.HasIntegralStructure.eq_zero_of_forall_mem_intLattice hN
      (t : Module.End ℂ V) fun f hf ↦ ?_
    calc (t : Module.End ℂ V) f = ((ψ t ⟨f, hf⟩ : L) : V) := rfl
      _ = 0 := by rw [ht]; rfl
  exact Module.Finite.of_injective ψ hψ

/-- The Hecke algebra is free over `ℤ` under the same hypothesis. Stated verbatim
from `Theorems/Thm_CuspForm_HasIntegralStructure_moduleFree_heckeAlgebra.lean`. -/
theorem HasIntegralStructure.moduleFree_heckeAlgebra {N : ℕ} [NeZero N] {k : ℤ}
    (hN : CuspForm.HasIntegralStructure N k) (hk : 1 ≤ k) (S : Set ℕ) :
    Module.Free ℤ (CuspForm.heckeAlgebra N k S) := by
  have := CuspForm.HasIntegralStructure.moduleFinite_heckeAlgebra hN hk S
  infer_instance

/-! ## The weight-`k ≤ 1` branch: the cusp-form space is a subsingleton -/

/-- `-1` lies in `Γ₀(N)` (it lies in every `Gamma0`). -/
private theorem neg_one_mem_gamma0 (N : ℕ) :
    (-1 : GL (Fin 2) ℝ) ∈ ((CongruenceSubgroup.Gamma0 N : Subgroup SL(2, ℤ)) :
      Subgroup (GL (Fin 2) ℝ)) := by
  refine Subgroup.mem_map.mpr ⟨-1, ?_, ?_⟩
  · simp [CongruenceSubgroup.Gamma0_mem]
  · ext i j
    simp [Matrix.SpecialLinearGroup.coe_neg, Matrix.one_apply]

/-- For `k ≤ 1` there are no nonzero `Γ₀(N)` cusp forms: negative weight, weight
`0` cusp forms (constant, hence zero at the cusp `∞`), or weight `1` with
`-1 ∈ Γ₀(N)`. -/
private theorem eq_zero_of_weight_le_one (N : ℕ) [NeZero N] (k : ℤ) (hk : k ≤ 1)
    (f : CuspForm (CongruenceSubgroup.Gamma0 N) k) : f = 0 := by
  apply CuspForm.toModularFormₗ_injective
  rw [map_zero]
  set F : ModularForm (CongruenceSubgroup.Gamma0 N) k := CuspForm.toModularFormₗ f with hF
  rcases lt_trichotomy k 0 with hk0 | rfl | hk0
  · exact ModularForm.isZero_of_neg_weight hk0 F
  · obtain ⟨c, hc⟩ := ModularForm.eq_const_of_weight_zero F
    have hz : UpperHalfPlane.IsZeroAtImInfty (F : UpperHalfPlane → ℂ) := by
      have hcusp : IsCusp OnePoint.infty
          (CongruenceSubgroup.Gamma0 N : Subgroup (GL (Fin 2) ℝ)) :=
        Subgroup.isCusp_of_mem_strictPeriods one_pos
          (by rw [CongruenceSubgroup.strictPeriods_Gamma0]; exact AddSubgroup.mem_zmultiples 1)
      simpa [hF, CuspForm.toModularFormₗ_eq_coe] using
        (OnePoint.isZeroAt_infty_iff.mp (f.zero_at_cusps' hcusp))
    have hc0 : c = 0 := by
      rw [hc] at hz
      exact tendsto_nhds_unique tendsto_const_nhds hz
    ext τ
    have hτ := congrFun hc τ
    simp only [hc0, Function.const_zero, Pi.zero_apply] at hτ
    simp [hτ]
  · obtain rfl : k = 1 := le_antisymm hk hk0
    exact ModularForm.eq_zero_of_neg_one_mem (neg_one_mem_gamma0 N) odd_one F

private theorem subsingleton_of_weight_le_one (N : ℕ) [NeZero N] (k : ℤ) (hk : k ≤ 1) :
    Subsingleton (CuspForm (CongruenceSubgroup.Gamma0 N) k) :=
  ⟨fun f g ↦ by rw [eq_zero_of_weight_le_one N k hk f, eq_zero_of_weight_le_one N k hk g]⟩

private theorem subsingleton_heckeAlgebra_of_weight_le_one (N : ℕ) [NeZero N] (k : ℤ)
    (hk : k ≤ 1) (S : Set ℕ) : Subsingleton (CuspForm.heckeAlgebra N k S) := by
  have := subsingleton_of_weight_le_one N k hk
  have : Subsingleton (Module.End ℂ (CuspForm (CongruenceSubgroup.Gamma0 N) k)) := inferInstance
  infer_instance

/-! ## The general finiteness, and the two `_two` one-liners -/

/-- The Hecke algebra is finite over `ℤ` for every weight. For `2 ≤ k` this is
route C′'s integral structure plus the lattice embedding; for `k ≤ 1` the algebra
is a subsingleton. Stated verbatim from
`Theorems/Thm_CuspForm_moduleFinite_heckeAlgebra.lean`. -/
theorem moduleFinite_heckeAlgebra (N : ℕ) [NeZero N] (k : ℤ) (S : Set ℕ) :
    Module.Finite ℤ (CuspForm.heckeAlgebra N k S) := by
  by_cases hk : 2 ≤ k
  · exact (CuspForm.hasIntegralStructure_of_two_le N k hk).moduleFinite_heckeAlgebra
      (le_trans one_le_two hk) S
  · have := subsingleton_heckeAlgebra_of_weight_le_one N k (by omega) S
    exact Module.Finite.of_finite

/-- The `k = 2` special case. FLT's own 4,308-line standalone proof is replaced by
the general theorem. Stated verbatim from
`Theorems/Thm_CuspForm_moduleFinite_heckeAlgebra_two.lean`. -/
theorem moduleFinite_heckeAlgebra_two (N : ℕ) [NeZero N] (S : Set ℕ) :
    Module.Finite ℤ (CuspForm.heckeAlgebra N 2 S) :=
  CuspForm.moduleFinite_heckeAlgebra N 2 S

/-- The finitely-generated form of `moduleFinite_heckeAlgebra_two`. Stated
verbatim from `Theorems/Thm_CuspForm_fg_toSubmodule_heckeAlgebra.lean`. -/
theorem fg_toSubmodule_heckeAlgebra (N : ℕ) [NeZero N] (S : Set ℕ) :
    (Subalgebra.toSubmodule (CuspForm.heckeAlgebra N 2 S)).FG :=
  Module.Finite.iff_fg.mp (CuspForm.moduleFinite_heckeAlgebra_two N S)

/-! ## The span of the weight-2 Hecke algebra

The first `q`-coefficient `a₁Pairing T f = a₁(T f)` is a pairing between the
`ℂ`-span `fullC` of the Hecke algebra at level `∅` and `S₂(Γ₀(N))`, injective in
both slots (in the first because a Hecke operator annihilating `a₁` of every form
annihilates the whole space, by the `T_p`/`U_p` recurrence along the `q`-expansion;
in the second by definition of `formKer`). Hence the two finite-dimensional
`ℂ`-vector spaces have the same dimension. -/

section FinrankSpan

open ModularForm ModularFormClass

private abbrev S2 (N : ℕ) : Type := CuspForm (CongruenceSubgroup.Gamma0 N) 2

private def fullC (N : ℕ) [NeZero N] : Subalgebra ℂ (Module.End ℂ (S2 N)) :=
  Algebra.adjoin ℂ (CuspForm.heckeGenerators N 2 (∅ : Set ℕ))

private instance instFullCIsMulCommutative (N : ℕ) [NeZero N] : IsMulCommutative (fullC N) :=
  Algebra.isMulCommutative_adjoin ℂ fun _ hT _ hT' _ =>
    CuspForm.commute_of_mem_heckeGenerators hT hT'

open scoped IsMulCommutative in
private instance instFullCCommRing (N : ℕ) [NeZero N] : CommRing (fullC N) := inferInstance

private theorem span_heckeAlgebra_eq_fullC (N : ℕ) [NeZero N] :
    Submodule.span ℂ (CuspForm.heckeAlgebra N 2 (∅ : Set ℕ) : Set (Module.End ℂ (S2 N)))
      = Subalgebra.toSubmodule (fullC N) := by
  apply le_antisymm
  · rw [Submodule.span_le]
    intro T hT
    have hle : CuspForm.heckeAlgebra N 2 (∅ : Set ℕ) ≤ (fullC N).restrictScalars ℤ := by
      refine Algebra.adjoin_le ?_
      intro x hx
      exact Algebra.subset_adjoin hx
    exact (hle hT : T ∈ fullC N)
  · rw [fullC, Algebra.adjoin_eq_span]
    apply Submodule.span_mono
    intro T hT
    change T ∈ CuspForm.heckeAlgebra N 2 (∅ : Set ℕ)
    exact (Submonoid.closure_le.mpr (fun x hx => Algebra.subset_adjoin hx)) hT

private theorem qCoeff_heckeTLin (N : ℕ) [NeZero N] {p : ℕ} (hp : p.Prime) (hpN : ¬ p ∣ N)
    (f : S2 N) (n : ℕ) :
    qCoeff (⇑(CuspForm.heckeTLin 2 hp hpN f)) n
      = qCoeff (⇑f) (p * n) + (p : ℂ) * (if p ∣ n then qCoeff (⇑f) (n / p) else 0) := by
  unfold qCoeff
  rw [CuspForm.qExpansion_heckeTLin hp hpN f, PowerSeries.coeff_heckeT]
  simp

private theorem qCoeff_heckeULin (N : ℕ) [NeZero N] {p : ℕ} (hp : p.Prime) (hpN : p ∣ N)
    (f : S2 N) (n : ℕ) :
    qCoeff (⇑(CuspForm.heckeULin 2 hpN f)) n = qCoeff (⇑f) (n * p) := by
  rw [CuspForm.coe_heckeULin_apply]
  rw [ModularFormClass.qCoeff_heckeU f
      (by rw [CongruenceSubgroup.strictPeriods_Gamma0]; exact AddSubgroup.mem_zmultiples 1)
      hp.ne_zero n,
    ModularForm.coeffHeckeU_apply]

private def formKer (N : ℕ) [NeZero N] : Set (S2 N) :=
  {f | ∀ T ∈ fullC N, qCoeff (⇑(T f)) 1 = 0}

private theorem formKer_stable (N : ℕ) [NeZero N] {f : S2 N} (hf : f ∈ formKer N)
    {U : Module.End ℂ (S2 N)} (hU : U ∈ fullC N) : U f ∈ formKer N := by
  intro T hT
  have h : (T * U) f = T (U f) := rfl
  rw [← h]
  exact hf _ ((fullC N).mul_mem hT hU)

private theorem qCoeff_eq_zero_of_mem_formKer (N : ℕ) [NeZero N] :
    ∀ (n : ℕ) (f : S2 N), f ∈ formKer N → qCoeff (⇑f) n = 0 := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro f hf
    rcases Nat.lt_or_ge n 2 with hn | hn
    · interval_cases n
      · exact CuspForm.qCoeff_zero f
      · simpa using hf 1 (fullC N).one_mem
    ·
      obtain ⟨p, hp, hpn⟩ := Nat.exists_prime_and_dvd (show n ≠ 1 by omega)
      obtain ⟨m, rfl⟩ := hpn
      have hm : m < p * m := by
        have := hp.one_lt
        have hm0 : 0 < m := Nat.pos_of_ne_zero (by rintro rfl; omega)
        nlinarith
      by_cases hpN : p ∣ N
      ·
        have hU : CuspForm.heckeULin 2 hpN f ∈ formKer N :=
          formKer_stable N hf (Algebra.subset_adjoin
            (CuspForm.heckeULin_mem_heckeGenerators hp hpN (by simp)))
        have := ih m hm _ hU
        rw [qCoeff_heckeULin N hp hpN] at this
        rwa [mul_comm] at this
      ·
        have hT : CuspForm.heckeTLin 2 hp hpN f ∈ formKer N :=
          formKer_stable N hf (Algebra.subset_adjoin
            (CuspForm.heckeTLin_mem_heckeGenerators hp hpN (by simp)))
        have h1 := ih m hm _ hT
        rw [qCoeff_heckeTLin N hp hpN] at h1
        have h2 : (if p ∣ m then qCoeff (⇑f) (m / p) else 0) = 0 := by
          split_ifs with hpm
          · exact ih (m / p) (lt_of_le_of_lt (Nat.div_le_self m p) hm) f hf
          · rfl
        rw [h2, mul_zero, add_zero] at h1
        exact h1

private theorem eq_zero_of_mem_formKer (N : ℕ) [NeZero N] {f : S2 N} (hf : f ∈ formKer N) :
    f = 0 := by
  refine ModularFormClass.eq_of_forall_qCoeff_eq
    (by rw [CongruenceSubgroup.strictPeriods_Gamma0]; exact AddSubgroup.mem_zmultiples 1) fun n => ?_
  rw [qCoeff_eq_zero_of_mem_formKer N n f hf]
  simp [ModularFormClass.qCoeff, FunLike.coe_zero, UpperHalfPlane.qExpansion_zero]

private theorem qCoeff_add' (N : ℕ) [NeZero N] (f g : S2 N) (n : ℕ) :
    qCoeff (⇑(f + g)) n = qCoeff (⇑f) n + qCoeff (⇑g) n := by
  simp only [qCoeff, FunLike.coe_add]
  rw [ModularForm.qExpansion_add one_pos
    (by rw [CongruenceSubgroup.strictPeriods_Gamma0]; exact AddSubgroup.mem_zmultiples 1) f g, map_add]

private theorem qCoeff_smul' (N : ℕ) [NeZero N] (c : ℂ) (f : S2 N) (n : ℕ) :
    qCoeff (⇑(c • f)) n = c * qCoeff (⇑f) n := by
  simp only [qCoeff]
  have hcoe : ⇑(c • f) = c • ⇑f := rfl
  rw [hcoe, ModularForm.qExpansion_smul one_pos
    (by rw [CongruenceSubgroup.strictPeriods_Gamma0]; exact AddSubgroup.mem_zmultiples 1) c f,
    map_smul, smul_eq_mul]

private def a1Pairing (N : ℕ) [NeZero N] : fullC N →ₗ[ℂ] S2 N →ₗ[ℂ] ℂ :=
  LinearMap.mk₂ ℂ (fun T f => qCoeff (⇑((T : Module.End ℂ (S2 N)) f)) 1)
    (fun T U f => by
      show qCoeff (⇑(((T : Module.End ℂ (S2 N)) + (U : Module.End ℂ (S2 N))) f)) 1 = _
      rw [LinearMap.add_apply, qCoeff_add'])
    (fun c T f => by
      show qCoeff (⇑((c • (T : Module.End ℂ (S2 N))) f)) 1 = _
      rw [LinearMap.smul_apply, qCoeff_smul', smul_eq_mul])
    (fun T f g => by
      show qCoeff (⇑((T : Module.End ℂ (S2 N)) (f + g))) 1 = _
      rw [map_add, qCoeff_add'])
    (fun c T f => by
      show qCoeff (⇑((T : Module.End ℂ (S2 N)) (c • f))) 1 = _
      rw [map_smul, qCoeff_smul', smul_eq_mul])

@[simp] private theorem a1Pairing_apply (N : ℕ) [NeZero N] (T : fullC N) (f : S2 N) :
    a1Pairing N T f = qCoeff (⇑((T : Module.End ℂ (S2 N)) f)) 1 := rfl

private def a1PairingDual (N : ℕ) [NeZero N] : S2 N →ₗ[ℂ] Module.Dual ℂ (fullC N) :=
  (a1Pairing N).flip

private theorem a1PairingDual_injective (N : ℕ) [NeZero N] :
    Function.Injective (a1PairingDual N) := by
  rw [injective_iff_map_eq_zero]
  intro f hf
  apply eq_zero_of_mem_formKer N
  intro T hT
  have := congrArg (fun ψ : Module.Dual ℂ (fullC N) => ψ ⟨T, hT⟩) hf
  simpa [a1PairingDual] using this

private theorem eq_zero_of_mem_fullC_of_forall_qCoeff_one_eq_zero (N : ℕ) [NeZero N]
    {T : Module.End ℂ (S2 N)} (hT : T ∈ fullC N)
    (h : ∀ f : S2 N, qCoeff (⇑(T f)) 1 = 0) : T = 0 := by
  refine LinearMap.ext fun f => ?_
  rw [LinearMap.zero_apply]
  apply eq_zero_of_mem_formKer N
  intro U hU
  have hcomm : U * T = T * U :=
    congrArg Subtype.val (mul_comm (⟨U, hU⟩ : fullC N) ⟨T, hT⟩)
  have : U (T f) = T (U f) := by
    change (U * T) f = (T * U) f
    rw [hcomm]
  rw [this]
  exact h (U f)

private theorem a1Pairing_injective (N : ℕ) [NeZero N] : Function.Injective (a1Pairing N) := by
  rw [injective_iff_map_eq_zero]
  intro T hT
  apply Subtype.ext
  refine eq_zero_of_mem_fullC_of_forall_qCoeff_one_eq_zero N T.2 fun f => ?_
  have := congrArg (fun ψ : S2 N →ₗ[ℂ] ℂ => ψ f) hT
  simpa using this

private theorem finrank_fullC_eq_finrank_cuspForm (N : ℕ) [NeZero N] :
    Module.finrank ℂ (fullC N) = Module.finrank ℂ (S2 N) := by
  have : FiniteDimensional ℂ (S2 N) := CuspForm.finiteDimensional_Gamma0 (N := N) (k := 2)
  refine le_antisymm ?_ ?_
  · have h1 : Module.finrank ℂ (fullC N) ≤ Module.finrank ℂ (Module.Dual ℂ (S2 N)) :=
      LinearMap.finrank_le_finrank_of_injective (a1Pairing_injective N)
    rwa [Subspace.dual_finrank_eq] at h1
  · have h2 : Module.finrank ℂ (S2 N) ≤ Module.finrank ℂ (Module.Dual ℂ (fullC N)) :=
      LinearMap.finrank_le_finrank_of_injective (a1PairingDual_injective N)
    rwa [Subspace.dual_finrank_eq] at h2

end FinrankSpan

/-- The `ℂ`-span of the weight-`2` Hecke algebra has the dimension of
`S₂(Γ₀(N))`. Stated verbatim from
`Theorems/Thm_CuspForm_finrank_span_heckeAlgebra_eq_finrank.lean`. -/
theorem finrank_span_heckeAlgebra_eq_finrank (N : ℕ) [NeZero N] :
    Module.finrank ℂ (Submodule.span ℂ (CuspForm.heckeAlgebra N 2 (∅ : Set ℕ) :
      Set (Module.End ℂ (CuspForm (CongruenceSubgroup.Gamma0 N) 2)))) =
      Module.finrank ℂ (CuspForm (CongruenceSubgroup.Gamma0 N) 2) := by
  rw [span_heckeAlgebra_eq_fullC (N := N)]
  exact finrank_fullC_eq_finrank_cuspForm N

end CuspForm

end
