/-
  The coefficient ring of a weight-one newform and the Galois action on it.

  If `f` is a weight-one cusp form of level `Γ₁(N)` with Nebentypus `ε`, normalized
  (`qCoeff f 1 = 1`) and an eigenform for `T_p` at every `p ∤ N`, then the
  `ℤ`-subalgebra `R` of `ℂ` generated by the Hecke eigenvalues `qCoeff f p` and the
  values of `ε` is finite as a `ℤ`-module, and every ring hom `τ : R →+* ℂ` is
  realised by a form `g` whose `p`-th coefficient is `τ (qCoeff f p)` and whose
  Nebentypus is `τ ∘ ε` (Deligne–Serre, weight one, the coefficient ring and its
  Galois conjugation).

  This is the pin's `S4a`, `491` lines, `45` declarations; the statement is the
  `Theorems/` wrapper verbatim, the proof transcribed from
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/P2M/Sol/S_DeligneSerre_exists_subalgebra_qCoeff_mem_forall_ringHom_exists_qCoeff_eq_of_weightOne_hecke_eigen.lean
  pinned `aa2d8b3`. The pin's `p2m_*` scaffolding, its large `attribute [-simp]`
  guards and the blanket `import Mathlib` are not ported; the `T_pow_mem_Gamma1`
  periodicity witness is already `CuspForm.cusp_periodic` in the H1 prelude, so the
  pin's `T_pow_mem_Gamma1`/`cusp_slash_T` need not be restated. Every helper is
  `private`; the module's public surface is the single target statement. The three
  generic nodes it glues together are imported from
  `FLTForHuman.Algebra.LatticeEigenvalues`.
-/
import FLTForHuman.Algebra.LatticeEigenvalues
import FLTForHuman.ModularForms.HeckePrelude
import FLTForHuman.ModularForms.HeckeTLinOneQCoeff
import FLTForHuman.ModularForms.HeckeEigenNebentypus
import FLTForHuman.ModularForms.WeightOne.Basic
import FLTForHuman.ModularForms.WeightOne.Gamma1IntegralBasis
import FLTForHuman.ModularForms.Defs.PrimitiveFormGamma1

set_option autoImplicit false

-- The pin's `haveI` walls are load-bearing; keep them literal (port convention).
set_option linter.style.haveILetI false

noncomputable section

open CongruenceSubgroup ModularForm ModularFormClass UpperHalfPlane Filter Function
open scoped MatrixGroups ModularForm UpperHalfPlane BigOperators

local notation "Γ₁ℝ" M => ((Gamma1 M : Subgroup SL(2, ℤ)) : Subgroup (GL (Fin 2) ℝ))

namespace DeligneSerre

variable {N : ℕ}

/-! ## The bundled `q`-coefficient functional -/

private theorem cusp_analytic (F : CuspForm (Γ₁ℝ N) 1) :
    AnalyticAt ℂ (cuspFunction 1 (⇑F)) 0 :=
  analyticAt_cuspFunction_zero one_pos (CuspForm.cusp_periodic F) (CuspForm.cusp_holo F)
    (CuspForm.cusp_bdd F)

private theorem qCoeff_add (F G : CuspForm (Γ₁ℝ N) 1) (n : ℕ) :
    qCoeff (⇑(F + G)) n = qCoeff (⇑F) n + qCoeff (⇑G) n := by
  rw [qCoeff, qCoeff, qCoeff, FunLike.coe_add,
    qExpansion_add (cusp_analytic F) (cusp_analytic G), map_add]

private theorem qCoeff_smul (c : ℂ) (F : CuspForm (Γ₁ℝ N) 1) (n : ℕ) :
    qCoeff (⇑(c • F)) n = c * qCoeff (⇑F) n := by
  rw [qCoeff, qCoeff, FunLike.coe_smul,
    qExpansion_smul (cusp_analytic F), map_smul, smul_eq_mul]

private def qcLin (N : ℕ) (n : ℕ) : CuspForm (Γ₁ℝ N) 1 →ₗ[ℂ] ℂ where
  toFun F := qCoeff (⇑F) n
  map_add' F G := qCoeff_add F G n
  map_smul' c F := qCoeff_smul c F n

private theorem qcLin_apply (n : ℕ) (F : CuspForm (Γ₁ℝ N) 1) :
    qcLin N n F = qCoeff (⇑F) n := rfl

private theorem qCoeff_zero_fun (n : ℕ) : qCoeff (0 : ℍ → ℂ) n = 0 := by
  simp [qCoeff, UpperHalfPlane.qExpansion_zero]

private theorem eq_zero_of_forall_qCoeff (F : CuspForm (Γ₁ℝ N) 1)
    (h : ∀ n, qCoeff (⇑F) n = 0) : F = 0 := by
  have h0 : (⇑F : ℍ → ℂ) = ⇑(0 : CuspForm (Γ₁ℝ N) 1) :=
    eq_of_forall_qCoeff_eq (CuspForm.cusp_periodic F) (CuspForm.cusp_holo F)
      (CuspForm.cusp_bdd F) (CuspForm.cusp_periodic 0) (CuspForm.cusp_holo 0)
      (CuspForm.cusp_bdd 0) (fun n => by
        rw [h n, FunLike.coe_zero, qCoeff_zero_fun])
  exact DFunLike.coe_injective h0

private theorem eq_of_forall_qCoeff (F G : CuspForm (Γ₁ℝ N) 1)
    (h : ∀ n, qCoeff (⇑F) n = qCoeff (⇑G) n) : F = G := by
  have : F - G = 0 := eq_zero_of_forall_qCoeff _ fun n => by
    rw [sub_eq_add_neg, qCoeff_add, ← neg_one_smul ℂ G, qCoeff_smul, h n]; ring
  exact sub_eq_zero.mp this

private instance finiteDimensional_cusp (N : ℕ) [NeZero N] :
    FiniteDimensional ℂ (CuspForm (Γ₁ℝ N) 1) :=
  CuspForm.finiteDimensional_of_isArithmetic (Γ₁ℝ N) 1

/-! ## The lattice of integral `q`-expansions -/

private def IntegralQExp (F : ℍ → ℂ) : Prop :=
  ∀ n : ℕ, qCoeff F n ∈ Set.range ((↑) : ℤ → ℂ)

private theorem integralQExp_zero : IntegralQExp (0 : ℍ → ℂ) := fun n =>
  ⟨0, by simp [qCoeff_zero_fun]⟩

private theorem integralQExp_add {F G : CuspForm (Γ₁ℝ N) 1} (hF : IntegralQExp ⇑F)
    (hG : IntegralQExp ⇑G) : IntegralQExp ⇑(F + G) := fun n => by
  obtain ⟨a, ha⟩ := hF n; obtain ⟨c, hc⟩ := hG n
  exact ⟨a + c, by rw [qCoeff_add, ← ha, ← hc]; push_cast; ring⟩

private theorem integralQExp_zsmul {F : CuspForm (Γ₁ℝ N) 1} (hF : IntegralQExp ⇑F)
    (m : ℤ) : IntegralQExp ⇑(m • F) := fun n => by
  obtain ⟨a, ha⟩ := hF n
  refine ⟨m * a, ?_⟩
  rw [← Int.cast_smul_eq_zsmul ℂ, qCoeff_smul, ← ha]; push_cast; ring

private theorem coe_slashOf {γ : SL(2, ℤ)} (hγ : γ ∈ Gamma0 N) (F : CuspForm (Γ₁ℝ N) 1) :
    ⇑(CuspForm.slashOfMemGamma0 N 1 hγ F) = (⇑F : ℍ → ℂ) ∣[(1 : ℤ)] γ := rfl

private def latt (N : ℕ) : Submodule ℤ (CuspForm (Γ₁ℝ N) 1) where
  carrier := {F | ∀ (γ : SL(2, ℤ)), γ ∈ Gamma0 N → IntegralQExp ((⇑F : ℍ → ℂ) ∣[(1 : ℤ)] γ)}
  zero_mem' := fun γ _ => by
    rw [FunLike.coe_zero, SlashAction.zero_slash]; exact integralQExp_zero
  add_mem' := fun {F G} hF hG γ hγ => by
    have h := integralQExp_add (hF γ hγ) (hG γ hγ) (F := CuspForm.slashOfMemGamma0 N 1 hγ F)
      (G := CuspForm.slashOfMemGamma0 N 1 hγ G)
    have e : CuspForm.slashOfMemGamma0 N 1 hγ F + CuspForm.slashOfMemGamma0 N 1 hγ G =
        CuspForm.slashOfMemGamma0 N 1 hγ (F + G) :=
      (map_add (ModularForm.Level.slashLinOfMemGamma0 N 1 hγ) F G).symm
    rw [e] at h
    exact h
  smul_mem' := fun m F hF γ hγ => by
    have h := integralQExp_zsmul (hF γ hγ) m (F := CuspForm.slashOfMemGamma0 N 1 hγ F)
    have e : m • CuspForm.slashOfMemGamma0 N 1 hγ F =
        ModularForm.Level.slashLinOfMemGamma0 N 1 hγ (m • F) := by
      rw [← Int.cast_smul_eq_zsmul ℂ, ← Int.cast_smul_eq_zsmul ℂ, map_smul]; rfl
    rw [e] at h
    exact h

private theorem mem_latt {F : CuspForm (Γ₁ℝ N) 1} :
    F ∈ latt N ↔ ∀ (γ : SL(2, ℤ)), γ ∈ Gamma0 N → IntegralQExp ((⇑F : ℍ → ℂ) ∣[(1 : ℤ)] γ) :=
  Iff.rfl

private theorem integralQExp_of_mem_latt {F : CuspForm (Γ₁ℝ N) 1} (hF : F ∈ latt N) :
    IntegralQExp ⇑F := by
  have := hF 1 (Subgroup.one_mem _)
  rwa [SlashAction.slash_one] at this

private theorem intCast_mem_range_ratCast {z : ℂ} (hz : z ∈ Set.range ((↑) : ℤ → ℂ)) :
    z ∈ Set.range ((↑) : ℚ → ℂ) := by
  obtain ⟨m, rfl⟩ := hz; exact ⟨m, by push_cast; rfl⟩

private theorem exists_finset_separating [NeZero N] :
    ∃ s : Finset ℕ, ∀ F : CuspForm (Γ₁ℝ N) 1, (∀ n ∈ s, qCoeff (⇑F) n = 0) → F = 0 := by
  classical
  obtain ⟨t, ht_sub, ht_span, ht_li⟩ :=
    exists_linearIndependent ℂ (Set.range (qcLin N : ℕ → CuspForm (Γ₁ℝ N) 1 →ₗ[ℂ] ℂ))
  have ht_fin : t.Finite := ht_li.setFinite
  haveI : Fintype t := ht_fin.fintype
  choose nOf hnOf using ht_sub
  refine ⟨Finset.univ.image (fun ψ : t => nOf ψ.2), fun F hF => ?_⟩
  apply eq_zero_of_forall_qCoeff
  intro n
  have hn : qcLin N n ∈ Submodule.span ℂ t := by
    rw [ht_span]; exact Submodule.subset_span (Set.mem_range_self n)
  change qcLin N n F = 0
  refine Submodule.span_induction (p := fun ψ _ => ψ F = 0) ?_ ?_ ?_ ?_ hn
  · intro ψ hψ
    have h1 := hF (nOf hψ) (Finset.mem_image.mpr ⟨⟨ψ, hψ⟩, Finset.mem_univ _, rfl⟩)
    rwa [← qcLin_apply, hnOf hψ] at h1
  · simp
  · intro ψ χ _ _ hψ hχ; simp [hψ, hχ]
  · intro r ψ _ hψ; simp [hψ]

private def intSub : Submodule ℤ ℂ := Submodule.span ℤ {1}

private theorem mem_intSub {z : ℂ} : z ∈ intSub ↔ z ∈ Set.range ((↑) : ℤ → ℂ) := by
  rw [intSub, Submodule.mem_span_singleton]
  constructor
  · rintro ⟨a, rfl⟩; exact ⟨a, by simp⟩
  · rintro ⟨a, rfl⟩; exact ⟨a, by simp⟩

private theorem latt_fg [NeZero N] : (latt N).FG := by
  classical
  obtain ⟨s, hs⟩ := exists_finset_separating (N := N)
  let M₀ : Submodule ℤ (s → ℂ) := Submodule.pi Set.univ (fun _ => intSub)
  have hM₀ : M₀.FG := Submodule.fg_pi (fun _ => Submodule.fg_span_singleton (1 : ℂ))
  haveI : Module.Finite ℤ M₀ := Module.Finite.iff_fg.mpr hM₀
  haveI : IsNoetherian ℤ M₀ := isNoetherian_of_isNoetherianRing_of_finite ℤ _
  let Ψ : latt N →ₗ[ℤ] M₀ :=
    { toFun := fun F => ⟨fun n => qCoeff (⇑(F : CuspForm (Γ₁ℝ N) 1)) n, fun n _ =>
        mem_intSub.mpr (integralQExp_of_mem_latt F.2 n)⟩
      map_add' := fun F G => by
        apply Subtype.ext; funext n
        simp only [Submodule.coe_add, Pi.add_apply]
        exact qCoeff_add _ _ _
      map_smul' := fun m F => by
        apply Subtype.ext; funext n
        simp only [Submodule.coe_smul, Pi.smul_apply, RingHom.id_apply]
        rw [← Int.cast_smul_eq_zsmul ℂ, qCoeff_smul]
        exact (zsmul_eq_mul _ m).symm }
  have hΨ : Function.Injective Ψ := by
    intro F G hFG
    apply Subtype.ext
    have h : (F : CuspForm (Γ₁ℝ N) 1) - G = 0 := hs _ fun n hn => by
      have := congrFun (congrArg Subtype.val hFG) ⟨n, hn⟩
      simp only [Ψ, LinearMap.coe_mk, AddHom.coe_mk] at this
      rw [sub_eq_add_neg, qCoeff_add, ← neg_one_smul ℂ (G : CuspForm (Γ₁ℝ N) 1), qCoeff_smul,
        this]
      ring
    exact sub_eq_zero.mp h
  haveI : Module.Finite ℤ (latt N) := Module.Finite.of_injective Ψ hΨ
  exact Module.Finite.iff_fg.mp inferInstance

private theorem slashOf_mem_latt {γ : SL(2, ℤ)} (hγ : γ ∈ Gamma0 N)
    {F : CuspForm (Γ₁ℝ N) 1} (hF : F ∈ latt N) :
    CuspForm.slashOfMemGamma0 N 1 hγ F ∈ latt N := by
  intro γ' hγ'
  rw [coe_slashOf, ← SlashAction.slash_mul]
  exact hF (γ * γ') (mul_mem hγ hγ')

private theorem diamond_mem_latt (d : ℕ) {F : CuspForm (Γ₁ℝ N) 1} (hF : F ∈ latt N) :
    CuspForm.diamondLinOne N 1 d F ∈ latt N := by
  by_cases hd : d.Coprime N
  · obtain ⟨γ, hγ⟩ := ModularForm.Level.exists_isDiamondLift_of_coprime hd
    have e : CuspForm.diamondLinOne N 1 d F = CuspForm.slashOfMemGamma0 N 1 hγ.1 F :=
      DFunLike.coe_injective (ModularForm.Level.coe_diamondLinOne_apply hγ F)
    rw [e]; exact slashOf_mem_latt hγ.1 hF
  · rw [ModularForm.Level.diamondLinOne_of_not_coprime hd]; exact hF

private theorem qCoeff_hecke (p : ℕ) (hp : p.Prime) (hpN : ¬ p ∣ N)
    (F : CuspForm (Γ₁ℝ N) 1) (n : ℕ) :
    qCoeff (⇑(CuspForm.heckeTLinOne 1 hp hpN F)) n =
      qCoeff (⇑F) (p * n) +
        (if p ∣ n then qCoeff (⇑(CuspForm.diamondLinOne N 1 p F)) (n / p) else 0) := by
  rw [CuspForm.qCoeff_heckeTLinOne 1 hp hpN F n, sub_self, zpow_zero, one_mul]

private theorem hecke_mem_latt (p : ℕ) (hp : p.Prime) (hpN : ¬ p ∣ N)
    {F : CuspForm (Γ₁ℝ N) 1} (hF : F ∈ latt N) :
    CuspForm.heckeTLinOne 1 hp hpN F ∈ latt N := by
  intro γ hγ n
  have e : (⇑(CuspForm.heckeTLinOne 1 hp hpN F) : ℍ → ℂ) ∣[(1 : ℤ)] γ =
      ⇑(CuspForm.heckeTLinOne 1 hp hpN (CuspForm.slashOfMemGamma0 N 1 hγ F)) := by
    rw [CuspForm.heckeTLinOne_slashOfMemGamma0]; rfl
  rw [e, qCoeff_hecke]
  have hG := slashOf_mem_latt hγ hF
  obtain ⟨a, ha⟩ := integralQExp_of_mem_latt hG (p * n)
  obtain ⟨c, hc⟩ := integralQExp_of_mem_latt (diamond_mem_latt p hG) (n / p)
  by_cases hpn : p ∣ n
  · exact ⟨a + c, by rw [ite_eq_left hpn, ← ha, ← hc]; push_cast; ring⟩
  · exact ⟨a, by rw [ite_eq_right hpn, ← ha, add_zero]⟩

private theorem latt_span {n : ℕ} (b : Module.Basis (Fin n) ℂ (CuspForm (Γ₁ℝ N) 1))
    (hb : ∀ i, b i ∈ latt N) : Submodule.span ℂ (latt N : Set (CuspForm (Γ₁ℝ N) 1)) = ⊤ := by
  apply eq_top_iff.mpr
  rw [← b.span_eq]
  apply Submodule.span_mono
  rintro _ ⟨i, rfl⟩
  exact hb i

private theorem coprime_of_prime {p : ℕ} (hp : p.Prime) (hpN : ¬ p ∣ N) : p.Coprime N :=
  (Nat.Prime.coprime_iff_not_dvd hp).mpr hpN

/-! ## The Hecke eigenform identifications -/

section Eigen

variable [NeZero N] (ε : DirichletCharacter ℂ N) (f : CuspForm (Γ₁ℝ N) 1)
  (hT : ∀ p : ℕ, p.Prime → ¬ p ∣ N → ∀ n : ℕ,
    qCoeff (⇑f) (p * n) + ε (p : ZMod N) * (if p ∣ n then qCoeff (⇑f) (n / p) else 0) =
      qCoeff (⇑f) p * qCoeff (⇑f) n)
include hT

private theorem slash_eq_smul {γ : SL(2, ℤ)} (hγ : γ ∈ Gamma0 N) :
    (⇑f : ℍ → ℂ) ∣[(1 : ℤ)] γ = ε ((γ 1 1 : ℤ) : ZMod N) • (⇑f : ℍ → ℂ) := by
  refine CuspForm.slash_eq_dirichlet_smul_of_qCoeff_hecke_eigen 1 f ε (fun p hp hpN => ?_) γ hγ
  refine ⟨qCoeff (⇑f) p, fun n => ?_⟩
  rw [sub_self, zpow_zero, mul_one, mul_comm n p]
  exact hT p hp hpN n

private theorem diamond_apply_eq {d : ℕ} (hd : d.Coprime N) :
    CuspForm.diamondLinOne N 1 d f = ε (d : ZMod N) • f := by
  obtain ⟨γ, hγ⟩ := ModularForm.Level.exists_isDiamondLift_of_coprime hd
  apply DFunLike.coe_injective
  show ⇑(CuspForm.diamondLinOne N 1 d f) = ⇑(ε (d : ZMod N) • f)
  rw [ModularForm.Level.coe_diamondLinOne_apply hγ, FunLike.coe_smul]
  have h := slash_eq_smul ε f hT hγ.1
  rw [hγ.2] at h
  exact h

private theorem hecke_apply_eq {p : ℕ} (hp : p.Prime) (hpN : ¬ p ∣ N) :
    CuspForm.heckeTLinOne 1 hp hpN f = qCoeff (⇑f) p • f := by
  apply eq_of_forall_qCoeff
  intro n
  rw [qCoeff_hecke, diamond_apply_eq ε f hT (coprime_of_prime hp hpN), qCoeff_smul, qCoeff_smul,
    ← hT p hp hpN n]
  by_cases hpn : p ∣ n
  · rw [ite_eq_left hpn, ite_eq_left hpn]
  · rw [ite_eq_right hpn, ite_eq_right hpn, mul_zero]

end Eigen

/-! ## The operator family and its eigenvalues -/

private def Idx (N : ℕ) : Type := {p : ℕ // p.Prime ∧ ¬ p ∣ N} ⊕ ℕ

private def opFam (N : ℕ) : Idx N → CuspForm (Γ₁ℝ N) 1 →ₗ[ℂ] CuspForm (Γ₁ℝ N) 1
  | Sum.inl p => CuspForm.heckeTLinOne 1 p.2.1 p.2.2
  | Sum.inr d => CuspForm.diamondLinOne N 1 d

private def evFam (ε : DirichletCharacter ℂ N) (f : CuspForm (Γ₁ℝ N) 1) : Idx N → ℂ
  | Sum.inl p => qCoeff (⇑f) p
  | Sum.inr d => if d.Coprime N then ε (d : ZMod N) else 1

private theorem opFam_mem_latt (j : Idx N) {F : CuspForm (Γ₁ℝ N) 1} (hF : F ∈ latt N) :
    opFam N j F ∈ latt N := by
  cases j with
  | inl p => exact hecke_mem_latt p.1 p.2.1 p.2.2 hF
  | inr d => exact diamond_mem_latt d hF

private theorem opFam_apply_eq [NeZero N] (ε : DirichletCharacter ℂ N)
    (f : CuspForm (Γ₁ℝ N) 1)
    (hT : ∀ p : ℕ, p.Prime → ¬ p ∣ N → ∀ n : ℕ,
      qCoeff (⇑f) (p * n) + ε (p : ZMod N) * (if p ∣ n then qCoeff (⇑f) (n / p) else 0) =
        qCoeff (⇑f) p * qCoeff (⇑f) n) (j : Idx N) :
    opFam N j f = evFam ε f j • f := by
  classical
  cases j with
  | inl p => exact hecke_apply_eq ε f hT p.2.1 p.2.2
  | inr d =>
    show CuspForm.diamondLinOne N 1 d f = (if d.Coprime N then ε (d : ZMod N) else 1) • f
    by_cases hd : d.Coprime N
    · rw [ite_eq_left hd]; exact diamond_apply_eq ε f hT hd
    · rw [ite_eq_right hd, one_smul, ModularForm.Level.diamondLinOne_of_not_coprime hd]; rfl

private theorem evFam_inr_of_coprime (ε : DirichletCharacter ℂ N) (f : CuspForm (Γ₁ℝ N) 1)
    {d : ℕ} (hd : d.Coprime N) : evFam ε f (Sum.inr d) = ε (d : ZMod N) := by
  classical
  show (if d.Coprime N then ε (d : ZMod N) else 1) = _
  rw [ite_eq_left hd]

private theorem dirichlet_mem_adjoin [NeZero N] (ε : DirichletCharacter ℂ N)
    (f : CuspForm (Γ₁ℝ N) 1) (x : ZMod N) :
    ε x ∈ Algebra.adjoin ℤ (Set.range (evFam ε f)) := by
  by_cases hx : IsUnit x
  · have hcop : (x.val).Coprime N := ZMod.val_coe_unit_coprime hx.unit
    have h := Algebra.subset_adjoin (R := ℤ) (Set.mem_range_self (f := evFam ε f) (Sum.inr x.val))
    rw [evFam_inr_of_coprime ε f hcop, ZMod.natCast_zmod_val] at h
    exact h
  · rw [MulChar.map_nonunit ε hx]; exact Subalgebra.zero_mem _

private theorem repr_opFam_mem_range [NeZero N] {n : ℕ}
    (b : Module.Basis (Fin n) ℂ (CuspForm (Γ₁ℝ N) 1)) (hb : ∀ i, b i ∈ latt N)
    (j : Idx N) (i i' : Fin n) :
    b.repr (opFam N j (b i)) i' ∈ Set.range ((↑) : ℚ → ℂ) := by
  refine Module.Basis.repr_mem_range_ratCast_of_forall_dual b (qcLin N)
    (fun F hF => eq_zero_of_forall_qCoeff F hF) (fun m i => ?_) _ (fun m => ?_) i'
  · exact intCast_mem_range_ratCast (integralQExp_of_mem_latt (hb i) m)
  · exact intCast_mem_range_ratCast (integralQExp_of_mem_latt (opFam_mem_latt j (hb i)) m)

/-! ## The coefficient ring and its conjugation -/

private theorem main [NeZero N] (ε : DirichletCharacter ℂ N) (f : CuspForm (Γ₁ℝ N) 1)
    (hf₁ : qCoeff (⇑f) 1 = 1)
    (hT : ∀ p : ℕ, p.Prime → ¬ p ∣ N → ∀ n : ℕ,
      qCoeff (⇑f) (p * n) + ε (p : ZMod N) * (if p ∣ n then qCoeff (⇑f) (n / p) else 0) =
        qCoeff (⇑f) p * qCoeff (⇑f) n) :
    ∃ R : Subalgebra ℤ ℂ, Module.Finite ℤ R ∧
      ∃ (hR : ∀ p : ℕ, p.Prime → ¬ p ∣ N → qCoeff (⇑f) p ∈ R)
        (hε : ∀ x : ZMod N, ε x ∈ R),
      ∀ τ : R →+* ℂ, ∃ (ε' : DirichletCharacter ℂ N) (g : CuspForm (Γ₁ℝ N) 1),
        (∀ x : ZMod N, ε' x = τ ⟨ε x, hε x⟩) ∧
        qCoeff (⇑g) 1 = 1 ∧
        (∀ (p : ℕ) (hp : p.Prime) (hpN : ¬ p ∣ N),
          qCoeff (⇑g) p = τ ⟨qCoeff (⇑f) p, hR p hp hpN⟩) ∧
        ∀ p : ℕ, p.Prime → ¬ p ∣ N → ∀ n : ℕ,
          qCoeff (⇑g) (p * n) + ε' (p : ZMod N) * (if p ∣ n then qCoeff (⇑g) (n / p) else 0) =
            qCoeff (⇑g) p * qCoeff (⇑g) n := by
  classical

  obtain ⟨n, b, hb0⟩ := CuspForm.exists_basis_gamma1_qCoeff_slash_mem_range_intCast N 1
  have hb : ∀ i, b i ∈ latt N := fun i γ hγ m => hb0 i γ hγ m

  have hf0 : f ≠ 0 := by
    intro h; rw [h, FunLike.coe_zero, qCoeff_zero_fun] at hf₁; exact zero_ne_one hf₁

  have hv : ∀ j, opFam N j f = evFam ε f j • f := opFam_apply_eq ε f hT

  let R : Subalgebra ℤ ℂ := Algebra.adjoin ℤ (Set.range (evFam ε f))
  haveI hRfin : Module.Finite ℤ R :=
    Submodule.moduleFinite_adjoin_eigenvalues_of_map_le_of_span_eq_top (latt N) latt_fg
      (latt_span b hb) (opFam N) (fun j F hF => opFam_mem_latt j hF) (evFam ε f) f hf0 hv
  have hR' : ∀ j, evFam ε f j ∈ R := fun j => Algebra.subset_adjoin (Set.mem_range_self j)
  have hR : ∀ p : ℕ, p.Prime → ¬ p ∣ N → qCoeff (⇑f) p ∈ R := fun p hp hpN =>
    hR' (Sum.inl ⟨p, hp, hpN⟩)
  have hε : ∀ x : ZMod N, ε x ∈ R := dirichlet_mem_adjoin ε f
  refine ⟨R, hRfin, hR, hε, fun τ => ?_⟩

  obtain ⟨w, hw1, hwS⟩ :=
    Module.Basis.exists_forall_apply_eq_ringHom_smul_of_repr_mem_range_ratCast b (opFam N)
      (repr_opFam_mem_range b hb) (qcLin N 1)
      (fun i => intCast_mem_range_ratCast (integralQExp_of_mem_latt (hb i) 1))
      (evFam ε f) f hv (by rw [qcLin_apply, hf₁]; exact one_ne_zero) R hR' τ
  rw [qcLin_apply] at hw1

  set c : ℂ := (qCoeff (⇑w) 1)⁻¹ with hc
  obtain ⟨g, hg_def⟩ : ∃ g : CuspForm (Γ₁ℝ N) 1, g = c • w := ⟨_, rfl⟩
  have hg1 : qCoeff (⇑g) 1 = 1 := by
    rw [hg_def, qCoeff_smul, hc, inv_mul_cancel₀ hw1]
  have hgS : ∀ j, opFam N j g = τ ⟨evFam ε f j, hR' j⟩ • g := fun j => by
    rw [hg_def, map_smul, hwS j, smul_comm]

  let ε' : DirichletCharacter ℂ N :=
    { toFun := fun x => τ ⟨ε x, hε x⟩
      map_one' := by
        have : (⟨ε 1, hε 1⟩ : R) = 1 := Subtype.ext (by simp)
        rw [this, map_one]
      map_mul' := fun x y => by
        have : (⟨ε (x * y), hε (x * y)⟩ : R) = ⟨ε x, hε x⟩ * ⟨ε y, hε y⟩ :=
          Subtype.ext (by simp [map_mul])
        rw [this, map_mul]
      map_nonunit' := fun x hx => by
        have : (⟨ε x, hε x⟩ : R) = 0 := Subtype.ext (by simp [MulChar.map_nonunit ε hx])
        show τ ⟨ε x, hε x⟩ = 0
        rw [this, map_zero] }
  have hε' : ∀ x : ZMod N, ε' x = τ ⟨ε x, hε x⟩ := fun x => rfl

  have hgT : ∀ (p : ℕ) (hp : p.Prime) (hpN : ¬ p ∣ N),
      CuspForm.heckeTLinOne 1 hp hpN g = τ ⟨qCoeff (⇑f) p, hR p hp hpN⟩ • g :=
    fun p hp hpN => hgS (Sum.inl ⟨p, hp, hpN⟩)
  have hgD : ∀ (p : ℕ) (hp : p.Prime) (hpN : ¬ p ∣ N),
      CuspForm.diamondLinOne N 1 p g = ε' (p : ZMod N) • g := by
    intro p hp hpN
    have h := hgS (Sum.inr p)
    have e : (⟨evFam ε f (Sum.inr p), hR' (Sum.inr p)⟩ : R) = ⟨ε (p : ZMod N), hε _⟩ :=
      Subtype.ext (evFam_inr_of_coprime ε f (coprime_of_prime hp hpN))
    rw [e] at h
    exact h
  have hgp : ∀ (p : ℕ) (hp : p.Prime) (hpN : ¬ p ∣ N),
      qCoeff (⇑g) p = τ ⟨qCoeff (⇑f) p, hR p hp hpN⟩ := by
    intro p hp hpN
    have E1 := qCoeff_hecke p hp hpN g 1
    rw [mul_one, ite_eq_right hp.not_dvd_one, add_zero, hgT p hp hpN, qCoeff_smul, hg1, mul_one] at E1
    exact E1.symm
  refine ⟨ε', g, hε', hg1, hgp, fun p hp hpN m => ?_⟩
  have E1 := qCoeff_hecke p hp hpN g m
  rw [hgD p hp hpN, qCoeff_smul] at E1
  rw [hgT p hp hpN, qCoeff_smul, ← hgp p hp hpN] at E1
  rw [E1]
  by_cases hpm : p ∣ m
  · rw [ite_eq_left hpm, ite_eq_left hpm]
  · rw [ite_eq_right hpm, ite_eq_right hpm, mul_zero]

end DeligneSerre

open CongruenceSubgroup
open scoped MatrixGroups

/-- **The coefficient ring of a weight-one Hecke eigenform and its Galois
conjugation.** Stated verbatim from
`Theorems/Thm_DeligneSerre_exists_subalgebra_qCoeff_mem_forall_ringHom_exists_qCoeff_eq_of_weightOne_hecke_eigen.lean`. -/
theorem DeligneSerre.exists_subalgebra_qCoeff_mem_forall_ringHom_exists_qCoeff_eq_of_weightOne_hecke_eigen
    (N : ℕ) [NeZero N] (ε : DirichletCharacter ℂ N) (f : CuspForm (Gamma1 N) 1)
    (hf₁ : ModularFormClass.qCoeff f 1 = 1)
    (hT : ∀ p : ℕ, p.Prime → ¬ p ∣ N → ∀ n : ℕ,
        ModularFormClass.qCoeff f (p * n) +
            ε (p : ZMod N) * (if p ∣ n then ModularFormClass.qCoeff f (n / p) else 0) =
          ModularFormClass.qCoeff f p * ModularFormClass.qCoeff f n) :
    ∃ R : Subalgebra ℤ ℂ, Module.Finite ℤ R ∧
      ∃ (hR : ∀ p : ℕ, p.Prime → ¬ p ∣ N → ModularFormClass.qCoeff f p ∈ R)
        (hε : ∀ x : ZMod N, ε x ∈ R),
      ∀ τ : R →+* ℂ, ∃ (ε' : DirichletCharacter ℂ N) (g : CuspForm (Gamma1 N) 1),
        (∀ x : ZMod N, ε' x = τ ⟨ε x, hε x⟩) ∧
        ModularFormClass.qCoeff g 1 = 1 ∧
        (∀ (p : ℕ) (hp : p.Prime) (hpN : ¬ p ∣ N),
          ModularFormClass.qCoeff g p = τ ⟨ModularFormClass.qCoeff f p, hR p hp hpN⟩) ∧
        ∀ p : ℕ, p.Prime → ¬ p ∣ N → ∀ n : ℕ,
          ModularFormClass.qCoeff g (p * n) +
              ε' (p : ZMod N) * (if p ∣ n then ModularFormClass.qCoeff g (n / p) else 0) =
            ModularFormClass.qCoeff g p * ModularFormClass.qCoeff g n :=
  DeligneSerre.main ε f hf₁ hT
