"""Galois representations on E[l], and the cyclotomic character.

For an elliptic curve E over a field K and a prime l invertible in K, the
action of the absolute Galois group G_K on E[l] is a two-dimensional
representation

    rho_{E,l} : G_K -> GL_2(F_l) = Aut(E[l]).

The Weil pairing forces its determinant to be the mod-l cyclotomic character
(base/007): det rho_{E,l}(sigma) = chi_l(sigma), where chi_l is defined by
sigma(zeta) = zeta^chi_l(sigma) on the l-th roots of unity.  When K is totally
real this makes rho_{E,l} *odd*: complex conjugation acts on mu_l by inversion,
so it has determinant -1.

Over a finite field F_p the Galois group is pro-cyclic, generated by Frobenius,
so the representation is determined by the single operator rho(Frob).  For
l != p it is semisimple, hence irreducible exactly when the characteristic
polynomial T^2 - a_p T + p is irreducible over F_l.

The cyclotomic facts are checked with sympy: x -> x^(-1) is a Galois
automorphism of Q(zeta_n) because the cyclotomic polynomial is palindromic, it
is nontrivial for n > 2, and its fixed field is the real subfield of degree
phi(n)/2.
"""

import sympy as sp


# ----------------------------------------------------------------------
# The cyclotomic character and complex conjugation
# ----------------------------------------------------------------------


def cyclotomic_poly(n):
    return sp.cyclotomic_poly(n, sp.symbols("x"))


def inverse_is_conjugate(n):
    """zeta_n -> zeta_n^(-1) preserves the minimal polynomial Phi_n."""
    x = sp.symbols("x")
    Phi = cyclotomic_poly(n)
    deg = int(sp.totient(n))
    return sp.rem(sp.expand(x ** deg * Phi.subs(x, 1 / x)), Phi, x) == 0


def inversion_nontrivial(n):
    """The inversion automorphism is nontrivial exactly when n > 2."""
    return n > 2


def cyclotomic_character_of_conjugation(n):
    """chi_n(c) for complex conjugation c: the class of -1 in (Z/n)^x."""
    return (-1) % n


def real_subfield_degree(n):
    """Degree of the fixed field of conjugation, from a resultant.

    The resultant is the square of the minimal polynomial of zeta + zeta^(-1)
    (each conjugate pair contributes twice), so the squarefree part is taken.
    """
    x, u = sp.symbols("x u")
    r = sp.resultant(cyclotomic_poly(n), x ** 2 - u * x + 1, x)
    return sp.degree(sp.Poly(r, u).sqf_part())


# ----------------------------------------------------------------------
# The representation over a finite field
# ----------------------------------------------------------------------


def charpoly_mod(a_p, p, l):
    """T^2 - a_p T + p as a polynomial over F_l."""
    T = sp.symbols("T")
    return sp.Poly(T ** 2 - a_p * T + p, T, modulus=l)


def is_irreducible_mod(a_p, p, l):
    """Is the Frobenius polynomial irreducible over F_l?"""
    return bool(charpoly_mod(a_p, p, l).is_irreducible)


def has_eigenvector_mod(matrix, l):
    """(does the 2x2 integer matrix have an eigenvector over F_l, an eigenvalue)."""
    (a, b), (c, d) = matrix
    for t in range(l):
        if ((a - t) * (d - t) - b * c) % l == 0:
            return True, t
    return False, None


def determinant_mod(matrix, l):
    (a, b), (c, d) = matrix
    return (a * d - b * c) % l


def trace_mod(matrix, l):
    (a, b), (c, d) = matrix
    return (a + d) % l


# ----------------------------------------------------------------------
# Concrete torsion bases and Frobenius matrices
# ----------------------------------------------------------------------


def _point_key(F, P):
    if P is None:
        return (1, 0, 0)
    return (0, F.key(P[0]), F.key(P[1]))


def torsion_basis(F, E, n):
    """A deterministic basis (P, Q) of the rational n-torsion."""
    pts = sorted([P for P in E.points() if E.mul(n, P) is None],
                 key=lambda P: _point_key(F, P))
    P = next(T for T in pts if T is not None and E.order(T) == n)
    sub = {E.mul(k, P) for k in range(n)}
    Q = next(T for T in pts if T not in sub)
    return P, Q


def _coords(F, E, n, P, Q, R):
    for a in range(n):
        for b in range(n):
            if E.add(E.mul(a, P), E.mul(b, Q)) == R:
                return a, b
    raise ValueError("point is not in the span")


def frobenius_matrix(F, E, q, n):
    """The q-power Frobenius as a 2x2 matrix on the rational n-torsion."""
    P, Q = torsion_basis(F, E, n)
    mP = (F.pow(P[0], q), F.pow(P[1], q))
    mQ = (F.pow(Q[0], q), F.pow(Q[1], q))
    a, b = _coords(F, E, n, P, Q, mP)
    c, d = _coords(F, E, n, P, Q, mQ)
    return ((a, b), (c, d))
