"""Integer 2x2 matrices: Smith and Hermite normal forms, and lines modulo N.

This is the matrix machinery behind ``base/020`` sections 5 and 8.  Everything
here is about a 2x2 integer matrix ``M`` and the two sublattices it carries:

* its **row lattice** -- the subgroup of Z^2 generated by the two rows, which
  the *left* action ``M -> U M`` (``U`` in SL_2(Z)) preserves;
* its **column lattice** -- the subgroup generated by the two columns, which
  the *right* action ``M -> M V`` (``V`` in SL_2(Z)) preserves.

The two normal forms:

* **Smith**: ``U M V = diag(d1, d2)`` with ``U, V`` in SL_2(Z) and
  ``d1 | d2``.  Here ``d1`` is the gcd of the four entries of ``M`` and
  ``d1 d2 = |det M|``; equivalently ``Z^2 / (row lattice)`` is isomorphic to
  ``Z/d1 x Z/d2``.  The matrix is **primitive** when ``d1 = 1``, i.e. when
  its Smith form is ``diag(1, N)`` for ``det M = N``, i.e. when that quotient
  is *cyclic*.  Sympy computes the decomposition (``smith_normal_decomp``);
  :func:`smith2` only fixes the signs so both outer factors lie in SL_2(Z).

* **Hermite**: ``U M = [[a, b], [0, d]]`` with ``U`` in SL_2(Z), ``a, d > 0``
  and ``0 <= b < d``.  This is the unique representative of the left orbit of
  ``M`` (its row lattice) in upper-triangular shape, and it is the shape the
  triples ``(a, b, d)`` of ``primCosetReps`` take.  Its diagonal is *not* the
  Smith diagonal: the first invariant factor of the Hermite form is
  ``gcd(a, b, d) = gcd(a, gcd(b, d))``, which is ``1`` exactly when the matrix
  is primitive.

The projective line ``P^1(Z/N)`` is also here, because it is the same lattice
story modulo ``N``: it is the set of unimodular pairs ``(a, c)`` -- pairs
generating the unit ideal, ``gcd(a, c, N) = 1`` -- modulo scaling by a unit.
A unimodular pair is exactly a vector of order ``N`` in ``(Z/N)^2``; it
generates a cyclic subgroup of order ``N``, and two pairs generate the same
subgroup exactly when they differ by a unit.

Matrices are lists of two rows of two ints; "SL_2(Z)" means determinant 1.
"""

from math import gcd

from sympy import Matrix, Rational
from sympy.matrices.normalforms import smith_normal_decomp


# --------------------------------------------------------------------------
# elementary 2x2 integer matrix arithmetic
# --------------------------------------------------------------------------

def det2(M):
    """Determinant of the 2x2 matrix ``M = [[a, b], [c, d]]``."""
    return M[0][0] * M[1][1] - M[0][1] * M[1][0]


def mat_mul(A, B):
    """Product of two 2x2 integer matrices."""
    return [
        [A[0][0] * B[0][0] + A[0][1] * B[1][0],
         A[0][0] * B[0][1] + A[0][1] * B[1][1]],
        [A[1][0] * B[0][0] + A[1][1] * B[1][0],
         A[1][0] * B[0][1] + A[1][1] * B[1][1]],
    ]


def is_sl2(M):
    """True when ``M`` has integer entries and determinant 1."""
    return det2(M) == 1


def gcd_entries(M):
    """The gcd of the four entries of ``M`` -- the first invariant factor."""
    g = 0
    for row in M:
        for x in row:
            g = gcd(g, abs(x))
    return g


def extended_gcd(a, b):
    """Return ``(g, s, t)`` with ``s*a + t*b = g = gcd(a, b) >= 0``."""
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r:
        q = old_r // r
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t


# --------------------------------------------------------------------------
# Smith normal form
# --------------------------------------------------------------------------

def smith2(M):
    """Return ``(U, D, V)`` with ``U M V = D = diag(d1, d2)``, ``d1 | d2``.

    ``d1`` is the gcd of the entries of ``M`` and ``d1*d2 = |det M|``; the
    outer factors are unimodular, and for the case used here -- ``det M > 0``
    -- both lie in SL_2(Z).  (When ``det M < 0`` no choice of signs can put
    both in SL_2 and keep both diagonal entries positive, since
    ``det U * det V = d1*d2 / det M < 0``.)  Requires ``det M != 0``.
    """
    if det2(M) == 0:
        raise ValueError("smith2 needs a nonsingular matrix")
    D, U, V = smith_normal_decomp(Matrix(M))
    U = [[int(U[0, 0]), int(U[0, 1])], [int(U[1, 0]), int(U[1, 1])]]
    V = [[int(V[0, 0]), int(V[0, 1])], [int(V[1, 0]), int(V[1, 1])]]
    D = [[int(D[0, 0]), int(D[0, 1])], [int(D[1, 0]), int(D[1, 1])]]
    # Sympy may return both outer factors with determinant -1 (their product
    # is +1).  Replacing U, V by S*U, V*S with S = diag(1, -1) keeps the
    # diagonal D and makes both determinants 1.
    if det2(M) > 0 and det2(U) == det2(V) == -1:
        S = [[1, 0], [0, -1]]
        U = mat_mul(S, U)
        V = mat_mul(V, S)
    if not (abs(det2(U)) == 1 and abs(det2(V)) == 1
            and mat_mul(mat_mul(U, M), V) == D):
        raise AssertionError("smith2 invariant violated")
    return U, D, V


def is_primitive(M):
    """True when the Smith form of ``M`` is ``diag(1, |det M|)``."""
    return gcd_entries(M) == 1


# --------------------------------------------------------------------------
# Hermite normal form (row style: H = U M)
# --------------------------------------------------------------------------

def hnf2(M):
    """Return ``(U, H)`` with ``H = U M`` upper triangular, ``H = [[a, b], [0, d]]``
    having ``a, d > 0`` and ``0 <= b < d``.

    This is the unique such matrix with the same row lattice as ``M``: the
    canonical representative of the left action on ``M``.  For the case used
    here, ``det M > 0``, the left factor lies in SL_2(Z); for ``det M < 0``
    it is only unimodular (its determinant must be ``-1`` to make both
    diagonal entries positive).  Requires ``det M != 0``.
    """
    if det2(M) == 0:
        raise ValueError("hnf2 needs a nonsingular matrix")
    (a, b), (c, d) = M
    # s*a + t*c = g > 0.  The matrix L below has determinant 1 and sends the
    # first column (a, c) to (g, 0).
    g, s, t = extended_gcd(a, c)
    L = [[s, t], [-c // g, a // g]]
    U = L
    H = mat_mul(L, M)
    if H[1][1] < 0:                       # make the lower diagonal positive
        H[1] = [-x for x in H[1]]
        U[1] = [-x for x in U[1]]
    # row0 -= q*row1 reduces b modulo d; row1 = (0, d) has zero first entry,
    # so a is untouched.
    q = H[0][1] // H[1][1]
    H[0] = [H[0][0] - q * H[1][0], H[0][1] - q * H[1][1]]
    U[0] = [U[0][0] - q * U[1][0], U[0][1] - q * U[1][1]]
    expected_det = 1 if det2(M) > 0 else -1
    if not (det2(U) == expected_det and mat_mul(U, M) == H):
        raise AssertionError("hnf2 invariant violated")
    return U, H


# --------------------------------------------------------------------------
# lattices, membership, and the quotient Z^2 / (row lattice)
# --------------------------------------------------------------------------

def lattice_coordinates(M, v):
    """Return ``(x, y)`` with ``x*row0 + y*row1 = v``, or ``None``.

    Since ``det M != 0`` the rational solution is unique, so the vector lies
    in the row lattice exactly when it is integral.
    """
    z = Matrix(M).T.solve(Matrix(v))
    sol = [Rational(x) for x in z]
    if all(x.q == 1 for x in sol):
        return [int(x) for x in sol]
    return None


def in_row_lattice(M, v):
    """True when ``v`` is an integer combination of the rows of ``M``."""
    return lattice_coordinates(M, v) is not None


def in_column_lattice(M, v):
    """True when ``v`` is an integer combination of the columns of ``M``."""
    return lattice_coordinates(transpose2(M), v) is not None


def transpose2(M):
    """Transpose of a 2x2 matrix."""
    return [[M[0][0], M[1][0]], [M[0][1], M[1][1]]]


def same_row_lattice(M1, M2):
    """True when the rows of ``M1`` and of ``M2`` generate the same lattice."""
    return (all(in_row_lattice(M1, r) for r in M2)
            and all(in_row_lattice(M2, r) for r in M1))


def same_column_lattice(M1, M2):
    """True when the columns of ``M1`` and of ``M2`` generate the same lattice."""
    return same_row_lattice(transpose2(M1), transpose2(M2))


def quotient_key(M, v):
    """The class of ``v`` in ``Z^2 / (row lattice of M)``.

    With ``U M V = diag(d1, d2)`` the row lattice is ``d1 Z x d2 Z`` in the
    ``V``-coordinates, so the class is the pair ``(v V) mod (d1, d2)``.
    """
    _, D, V = smith2(M)
    d1, d2 = D[0][0], D[1][1]
    w0 = v[0] * V[0][0] + v[1] * V[1][0]
    w1 = v[0] * V[0][1] + v[1] * V[1][1]
    return (w0 % d1, w1 % d2)


def quotient_generator(M):
    """A vector generating ``Z^2 / (row lattice of M)``, or ``None``.

    Searches a symmetric box of side ``2N``; a generator exists exactly when
    the matrix is primitive (the quotient is cyclic of order N).
    """
    n = abs(det2(M))
    _, D, V = smith2(M)
    d1, d2 = D[0][0], D[1][1]

    def key(v):
        w0 = v[0] * V[0][0] + v[1] * V[1][0]
        w1 = v[0] * V[0][1] + v[1] * V[1][1]
        return (w0 % d1, w1 % d2)

    for x, y in sorted(((x, y) for x in range(-n, n + 1)
                        for y in range(-n, n + 1)),
                       key=lambda v: (abs(v[0]) + abs(v[1]), v[0], v[1])):
        if len({key((k * x, k * y)) for k in range(n)}) == n:
            return (x, y)
    return None


# --------------------------------------------------------------------------
# the projective line P^1(Z/N)
# --------------------------------------------------------------------------

def units(n):
    """The unit group ``(Z/n)^*``, written as residues ``1 <= u < n``.

    For ``n = 1`` the zero ring has the single element ``0``; it is its own
    unit, so the list is ``[0]``.
    """
    if n == 1:
        return [0]
    return [u for u in range(1, n) if gcd(u, n) == 1]


def unimodular_pairs(n):
    """Pairs ``(a, c)`` in ``(Z/n)^2`` with ``gcd(a, c, n) = 1``."""
    return [(a, c) for a in range(n) for c in range(n)
            if gcd(gcd(a, c), n) == 1]


def canonical_pair(n, pair):
    """Lexicographically least unit multiple of ``pair`` in ``(Z/n)^2``."""
    a, c = pair
    best = (a % n, c % n)
    for u in units(n):
        cand = ((a * u) % n, (c * u) % n)
        if cand < best:
            best = cand
    return best


def projective_line(n):
    """One canonical representative per unit-orbit of unimodular pairs."""
    return sorted({canonical_pair(n, p) for p in unimodular_pairs(n)})


def element_order(n, v):
    """Order of ``v`` in the group ``(Z/n)^2``."""
    for k in range(1, n + 1):
        if v[0] * k % n == 0 and v[1] * k % n == 0:
            return k
    return n


def reduced_row_lattice_generator(n, triple):
    """A generator of the image of the row lattice of ``(a, b, d)`` in
    ``(Z/n)^2``.

    The row lattice ``L = <(a, b), (0, d)>`` has index ``N = ad``; when the
    triple is primitive the image ``L / N Z^2`` is cyclic of order ``N``, and
    any element of order ``N`` generates it.  Such an element is a unimodular
    pair.  Returns ``None`` if no element of order ``N`` exists.
    """
    a, b, d = triple
    rows = [(a % n, b % n), (0, d % n)]
    sub = set()
    for i in range(n):
        for j in range(n):
            sub.add(((i * rows[0][0] + j * rows[1][0]) % n,
                     (i * rows[0][1] + j * rows[1][1]) % n))
    for v in sorted(sub):
        if element_order(n, v) == n:
            return v
    return None
