"""Riemann-Roch data for curves with a rational Weierstrass point.

For a hyperelliptic curve ``y^2 = f(x)`` of genus ``g`` (``deg f = 2g + 1``) the
single point ``P`` at infinity is a Weierstrass point whose semigroup of pole
orders is generated by ``2`` and ``2g + 1``: the *non-gaps* are the numbers
``2i + (2g + 1) j``, and the gaps are ``1, 3, ..., 2g - 1``.

Two distinct counts matter, and confusing them is the usual mistake:

* the monomials ``x^i y^j`` with pole order ``2i + (2g+1) j <= n`` **span**
  ``L(nP)``, but they are not independent -- the Weierstrass relation
  ``y^2 = f(x)`` makes ``y^2 x^i`` and ``x^(i + 2g + 1)`` have the same pole
  order, so their difference has smaller order;
* a **basis** has one function per distinct non-gap order at most ``n``, so
  ``ell(nP)`` is the number of non-gaps ``<= n``, not the number of monomials.

``l_dim`` counts non-gaps (that is ``ell``), ``basis`` returns the standard
basis, and ``monomials`` returns the spanning set.  Riemann-Roch then reads

    ell(D) - ell(K - D) = deg D + 1 - g,

with ``deg K = 2g - 2`` and ``ell(K) = g``.

Special cases: ``g = 0`` (the rational curve) has every order a non-gap and
``ell(n * infinity) = n + 1``, with ``K = -2 * infinity``; ``g = 1`` (an
elliptic curve, generators ``2, 3``) has ``ell(n * O) = n`` for ``n >= 1``,
``ell(0) = 1``, and ``K = 0``.
"""


def non_gap_orders(g, n):
    """The pole orders ``<= n`` of functions with a pole only at P."""
    if n < 0:
        return []
    if g == 0:
        return list(range(n + 1))
    a, b = 2, 2 * g + 1
    orders = set()
    j = 0
    while b * j <= n:
        i = 0
        while a * i + b * j <= n:
            orders.add(a * i + b * j)
            i += 1
        j += 1
    return sorted(orders)


def l_dim(g, n):
    """ell(n * P): the number of non-gaps at most n, i.e. dim L(n * P)."""
    return len(non_gap_orders(g, n))


def monomials(g, n):
    """The spanning monomials ``x^i y^j`` with ``2i + (2g+1)j <= n``.

    They span ``L(n * P)`` but are linearly dependent; see the module docstring.
    """
    if n < 0:
        return []
    if g == 0:
        return [(i,) for i in range(n + 1)]
    a, b = 2, 2 * g + 1
    out = []
    j = 0
    while b * j <= n:
        i = 0
        while a * i + b * j <= n:
            out.append((i, j))
            i += 1
        j += 1
    return out


def basis(g, n):
    """The standard basis of ``L(n * P)``: one monomial per non-gap order."""
    if n < 0:
        return []
    if g == 0:
        return [(i,) for i in range(n + 1)]
    b = 2 * g + 1
    out = []
    for m in non_gap_orders(g, n):
        if m == 0:
            out.append((0, 0))
        elif m % 2 == 0:
            out.append((m // 2, 0))
        else:
            out.append(((m - b) // 2, 1))
    return out


def pole_order(g, mono):
    """Order of the pole of the monomial at P."""
    if g == 0:
        return mono[0]
    i, j = mono
    return 2 * i + (2 * g + 1) * j


def canonical_degree(g):
    """deg K = 2g - 2."""
    return 2 * g - 2


def genus_from_canonical(degK):
    """g = (deg K + 2) / 2, the formalization's definition of genus."""
    return (degK + 2) // 2


def monomial_str(g, mono):
    if g == 0:
        i = mono[0]
        return "1" if i == 0 else ("x" if i == 1 else f"x^{i}")
    i, j = mono
    parts = []
    if i:
        parts.append("x" if i == 1 else f"x^{i}")
    if j:
        parts.append("y" if j == 1 else f"y^{j}")
    return "*".join(parts) if parts else "1"
