/-
  T20 — the unconditional capstone.

  `Spine.lean` proves `functionFieldGeneration_of (h : Inputs)`: the theorem from
  FLT's seven significant statements, bundled. T15–T19 proved those seven, so this
  module constructs `inputs : Inputs` and discharges the conditional capstone:

  * `functionFieldGeneration` — the unconditional theorem, verbatim from
    `Theorems/Thm_ModularCurve_functionFieldGeneration.lean`;
  * the corollary layer the rest of FLT consumes — `modularFunctionField_eq_full`,
    `finrank_adjoin_jqN_eq_dedekindPsi`, `relfinrank_full_eq_dedekindPsi`, each a
    one-liner off `hall_all`.

  ## Source

  FLT `anthropics/fermats-last-theorem@aa2d8b3`:
  `P2M/Sol/S_ModularCurve_functionFieldGeneration.lean` node 728–732
  (`functionFieldGeneration`) and corollaries 713–721, 722–727, 739–749. The
  public statements are the `Theorems/` wrappers' verbatim.

  ## What is ours

  `inputs` is the port's assembly and has no pin counterpart: FLT's `hall_all` is
  applied to the seven statements directly. Everything else here is transcribed.
-/
import FLTForHuman.ModularCurve.FunctionFieldGeneration.Spine
import FLTForHuman.ModularCurve.FunctionFieldGeneration.Descent
import FLTForHuman.ModularCurve.FunctionFieldGeneration.DegreeStep
import FLTForHuman.ModularCurve.FunctionFieldGeneration.Nonmembership
import FLTForHuman.ModularCurve.FunctionFieldGeneration.Generation
import FLTForHuman.ModularCurve.FunctionFieldGeneration.SlotProduct
import FLTForHuman.ModularCurve.Defs.PhiAtSlot
import FLTForHuman.ModularCurve.ModularPolynomialProperties
import Mathlib.Data.Nat.Factorization.Induction

set_option autoImplicit false
-- The proof below installs typeclass instances with `haveI`/`letI`, as the pin does.
set_option linter.style.haveILetI false

noncomputable section

open Polynomial HahnSeries IntermediateField

namespace ModularCurve

/-! ## The seven `Inputs` fields, discharged -/

/-- **The unconditional `Inputs`.** Every field is one of the theorems T15–T19
proved: `Descent` supplies the two `Gen` fields, `DegreeStep` the degree step,
`Nonmembership` the prime-power tower, `Generation` the prime-power generator, and
`SlotProduct` the slot product and the prime non-membership. This is the port's
own assembly; FLT has no counterpart (`hall_all` consumes the fields' statements
directly). -/
theorem inputs : Inputs where
  full_eq_adjoin_full_div_prime := full_eq_adjoin_full_div_prime
  jqN_prime_not_mem_full := jqN_prime_not_mem_full
  jqN_pow_not_mem_adjoin_full := jqN_pow_not_mem_adjoin_full
  minpoly_jqN_map_eq_prod_slots := minpoly_jqN_map_eq_prod_slots
  modularFunctionField_eq_full_of := modularFunctionField_eq_full_of
  jqN_div_mem_modularFunctionField := jqN_div_mem_modularFunctionField
  relfinrank_full_eq_mul := relfinrank_full_eq_mul

/-- **The theorem.** For every `N ≠ 0`, every `j(q ^ d)` with `d ∣ N` lies in
`ℚ(j(q), j(q ^ N))`: the function field of `X₀(N)` is generated by `j` and
`j_N`. Unconditional. Verbatim from
`Theorems/Thm_ModularCurve_functionFieldGeneration.lean`. -/
theorem functionFieldGeneration (N : ℕ) [NeZero N] : FunctionFieldGeneration N :=
  functionFieldGeneration_of inputs N

/-! ## The corollary layer -/

/-- The two-generator field is the full divisor field. Verbatim from
`Theorems/Thm_ModularCurve_modularFunctionField_eq_full.lean`. -/
theorem modularFunctionField_eq_full (N : ℕ) [NeZero N] :
    modularFunctionField N = modularFunctionFieldFull N :=
  (hall_all inputs N (NeZero.ne N) N dvd_rfl).2

/-- The modular equation at level `N` has full degree `ψ(N)`. Verbatim from
`Theorems/Thm_ModularCurve_finrank_adjoin_jqN_eq_dedekindPsi.lean`. -/
theorem finrank_adjoin_jqN_eq_dedekindPsi (N : ℕ) [NeZero N] :
    Module.finrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
      (IntermediateField.adjoin (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
        ({jqN N} : Set (LaurentSeries ℚ))) = dedekindPsi N :=
  (hall_all inputs N (NeZero.ne N) N dvd_rfl).1

/-- The full field has degree `ψ(N)` over `ℚ(j)`. Verbatim from
`Theorems/Thm_ModularCurve_relfinrank_full_eq_dedekindPsi.lean`. -/
theorem relfinrank_full_eq_dedekindPsi (N : ℕ) [NeZero N] :
    IntermediateField.relfinrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
      (modularFunctionFieldFull N) = dedekindPsi N := by
  rw [← modularFunctionField_eq_full N, relfinrank_modularFunctionField N]
  exact finrank_adjoin_jqN_eq_dedekindPsi N

/-! ## The interface tail: the monic integrality input

The last of §2.1's five out-of-cone nodes is `exists_phiIrreducible_of_finrank_eq`,
which consumes the monic annihilator proved here. Both are transcribed from their
`Theorems/` wrappers; the pin's re-copies of T14's `phiAtSeed*` are imported. -/

/-- **`j(q ^ N)` is integral over `ℤ[X]`** (via `evalAtJ`): it has a monic
annihilator in `Polynomial (Polynomial ℤ)`. Verbatim from
`Theorems/Thm_ModularCurve_exists_monic_evalAtJ_jqN_eq_zero.lean`. -/
theorem exists_monic_evalAtJ_jqN_eq_zero (N : ℕ) [NeZero N] :
    ∃ P : Polynomial (Polynomial ℤ), P.Monic ∧ P.eval₂ evalAtJ (jqN N) = 0 := by
  letI : Algebra (Polynomial ℤ) (LaurentSeries ℚ) := evalAtJ.toAlgebra
  suffices h : ∀ (n : ℕ) [NeZero n], IsIntegral (Polynomial ℤ) (jqN n) by
    obtain ⟨P, hP, hval⟩ := h N
    exact ⟨P, hP, hval⟩
  intro n
  induction n using induction_on_primes with
  | zero => intro h; exact absurd rfl h.out
  | one =>
    intro _
    have hjq : jqN 1 = algebraMap (Polynomial ℤ) (LaurentSeries ℚ) Polynomial.X := by
      rw [jqN_one]
      exact evalAtJ_X.symm
    rw [hjq]
    exact isIntegral_algebraMap
  | prime_mul p a hp ih =>
    intro hpa
    haveI hNp : NeZero p := ⟨hp.ne_zero⟩
    haveI hNa : NeZero a := ⟨fun h => NeZero.ne (p * a) (by rw [h, Nat.mul_zero])⟩
    haveI hNap : NeZero (a * p) := ⟨by rw [Nat.mul_comm]; exact NeZero.ne (p * a)⟩
    haveI hFp : Fact p.Prime := ⟨hp⟩
    have hia : IsIntegral (Polynomial ℤ) (jqN a) := ih
    obtain ⟨data, -, -⟩ := exists_phiIrreducible_evalSymm p
    set A := Algebra.adjoin (Polynomial ℤ) ({jqN a} : Set (LaurentSeries ℚ)) with hA
    have hmem : jqN a ∈ A := Algebra.self_mem_adjoin_singleton _ _
    haveI : Algebra.IsIntegral (Polynomial ℤ) ↥A :=
      ⟨fun x => (isIntegral_algHom_iff
        (IsScalarTower.toAlgHom (Polynomial ℤ) ↥A (LaurentSeries ℚ))
        (fun _ _ h => Subtype.ext h)).mp
        (IsIntegral.of_mem_of_fg A hia.fg_adjoin_singleton _ x.2)⟩
    have hroot : Polynomial.eval₂ (algebraMap ↥A (LaurentSeries ℚ)) (jqN (a * p))
        (phiAtSeed data (⟨jqN a, hmem⟩ : ↥A)) = 0 := by
      rw [Polynomial.eval₂_eq_eval_map, phiAtSeed_map]
      exact phiAtSeed_jqN_eval p data a
    have hint : IsIntegral (Polynomial ℤ) (jqN (a * p)) :=
      isIntegral_trans (jqN (a * p)) ⟨phiAtSeed data (⟨jqN a, hmem⟩ : ↥A),
        phiAtSeed_monic data _, hroot⟩
    rwa [jqN_congr (Nat.mul_comm a p)] at hint

/-! ## The interface tail: an irreducible datum at every level

`exists_phiIrreducible_of_finrank_eq` is the last of §2.1's five out-of-cone nodes.
It turns the degree count `finrank = ψ(N)` into an irreducible modular-polynomial
datum, by comparing `minpoly (Polynomial ℤ) (jqN N)` with its image in `ℚ⟮jq⟯`
across the fraction-ring structure `Polynomial ℤ → ℚ⟮jq⟯` (`jq` is transcendental).
The three evaluation helpers are the pin's; `evalAtJGen_injective` is the port's
`ModularPolynomialIrreducible.lean:103`. -/

private theorem coe_evalAtJGen (g : Polynomial ℤ) :
    ((evalAtJGen g : ℚ⟮jq⟯) : LaurentSeries ℚ) = evalAtJ g :=
  RingHom.congr_fun algebraMap_comp_evalAtJGen g

private theorem aeval_map_intCast (g : Polynomial ℤ) :
    Polynomial.aeval jq (g.map (algebraMap ℤ ℚ)) = evalAtJ g := by
  rw [Polynomial.aeval_def, Polynomial.eval₂_map]
  congr 1
  exact RingHom.ext_int _ _

private theorem evalAtJ_C (b : ℤ) : evalAtJ (Polynomial.C b) = (b : LaurentSeries ℚ) := by
  simp [evalAtJ]

/-- **An irreducible datum at every level, from the degree count.** Given
`[ℚ⟮jq⟯(jqN N) : ℚ⟮jq⟯] = ψ(N)`, there is `data : ModularPolynomialData N` whose
transported polynomial is irreducible. Verbatim from
`Theorems/Thm_ModularCurve_exists_phiIrreducible_of_finrank_eq.lean`. -/
theorem exists_phiIrreducible_of_finrank_eq (N : ℕ) [NeZero N]
    (h : Module.finrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
      (IntermediateField.adjoin (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
        ({jqN N} : Set (LaurentSeries ℚ))) = dedekindPsi N) :
    ∃ data : ModularPolynomialData N, PhiIrreducible data := by
  letI : Algebra (Polynomial ℤ) ℚ⟮jq⟯ := evalAtJGen.toAlgebra
  letI : Algebra (Polynomial ℤ) (LaurentSeries ℚ) := evalAtJ.toAlgebra
  haveI tower : IsScalarTower (Polynomial ℤ) ℚ⟮jq⟯ (LaurentSeries ℚ) :=
    IsScalarTower.of_algebraMap_eq fun x =>
      (RingHom.congr_fun algebraMap_comp_evalAtJGen x).symm

  haveI : IsFractionRing (Polynomial ℤ) ℚ⟮jq⟯ := by
    refine { map_units := ?_, surj := ?_, exists_of_eq := ?_ }
    · rintro ⟨y, hy⟩
      rw [mem_nonZeroDivisors_iff_ne_zero] at hy
      refine isUnit_iff_ne_zero.mpr fun h0 => hy (evalAtJGen_injective ?_)
      rw [map_zero]
      exact h0
    · intro z
      by_cases hz : (z : LaurentSeries ℚ) = 0
      · refine ⟨(0, 1), ?_⟩
        have hz0 : z = 0 := Subtype.ext hz
        rw [hz0]
        simp
      · obtain ⟨r, s, hrs⟩ :=
          (IntermediateField.mem_adjoin_simple_iff ℚ (z : LaurentSeries ℚ)).mp z.2
        have hs0 : Polynomial.aeval jq s ≠ 0 := by
          intro h0
          apply hz
          rw [hrs, h0, div_zero]
        have hzs : (z : LaurentSeries ℚ) * Polynomial.aeval jq s = Polynomial.aeval jq r := by
          rw [hrs, div_mul_cancel₀ _ hs0]
        obtain ⟨br, hbr, hrn⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors ℤ) r
        obtain ⟨bs, hbs, hsn⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors ℤ) s
        rw [mem_nonZeroDivisors_iff_ne_zero] at hbr hbs
        have hrval : evalAtJ (IsLocalization.integerNormalization (nonZeroDivisors ℤ) r) =
            br • Polynomial.aeval jq r := by
          rw [← aeval_map_intCast, hrn]
          exact map_zsmul _ br r
        have hsval : evalAtJ (IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) =
            bs • Polynomial.aeval jq s := by
          rw [← aeval_map_intCast, hsn]
          exact map_zsmul _ bs s
        have hs'0 : IsLocalization.integerNormalization (nonZeroDivisors ℤ) s ≠ 0 := by
          intro h0
          have h1 : evalAtJ (IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) = 0 := by
            rw [h0, map_zero]
          rw [hsval] at h1
          have h2 : (bs : LaurentSeries ℚ) * Polynomial.aeval jq s = 0 :=
            (zsmul_eq_mul (Polynomial.aeval jq s) bs).symm.trans h1
          rcases mul_eq_zero.mp h2 with hb | hss
          · apply hbs
            have h3 : algebraMap ℚ (LaurentSeries ℚ) ((bs : ℚ)) =
                algebraMap ℚ (LaurentSeries ℚ) 0 := by
              rw [map_intCast, map_zero]
              exact hb
            have h4 : (bs : ℚ) = 0 := (algebraMap ℚ (LaurentSeries ℚ)).injective h3
            exact_mod_cast h4
          · exact hs0 hss
        have hcoe : ∀ g : Polynomial ℤ,
            ((algebraMap (Polynomial ℤ) ℚ⟮jq⟯ g : ℚ⟮jq⟯) : LaurentSeries ℚ) = evalAtJ g :=
          fun g => coe_evalAtJGen g
        have key : (z : LaurentSeries ℚ) *
            evalAtJ (Polynomial.C br * IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) =
            evalAtJ (Polynomial.C bs * IsLocalization.integerNormalization (nonZeroDivisors ℤ) r) := by
          rw [map_mul, map_mul, evalAtJ_C, evalAtJ_C, hrval, hsval, zsmul_eq_mul,
            zsmul_eq_mul, ← hzs]
          ring
        refine ⟨(Polynomial.C bs * IsLocalization.integerNormalization (nonZeroDivisors ℤ) r,
          ⟨Polynomial.C br * IsLocalization.integerNormalization (nonZeroDivisors ℤ) s,
            mem_nonZeroDivisors_of_ne_zero
              (mul_ne_zero (Polynomial.C_ne_zero.mpr hbr) hs'0)⟩), Subtype.ext ?_⟩
        show ((z * algebraMap (Polynomial ℤ) ℚ⟮jq⟯
            (Polynomial.C br * IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) :
              ℚ⟮jq⟯) : LaurentSeries ℚ) =
          ((algebraMap (Polynomial ℤ) ℚ⟮jq⟯
            (Polynomial.C bs * IsLocalization.integerNormalization (nonZeroDivisors ℤ) r) :
              ℚ⟮jq⟯) : LaurentSeries ℚ)
        rw [MulMemClass.coe_mul, hcoe, hcoe]
        exact key
    · intro x y hxy
      exact ⟨1, by rw [evalAtJGen_injective hxy]⟩

  have hx : IsIntegral (Polynomial ℤ) (jqN N) := by
    obtain ⟨P, hP, hval⟩ := exists_monic_evalAtJ_jqN_eq_zero N
    exact ⟨P, hP, hval⟩
  have hxQ : IsIntegral ℚ⟮jq⟯ (jqN N) := hx.tower_top

  have hmin := minpoly.isIntegrallyClosed_eq_field_fractions' ℚ⟮jq⟯ hx
  rw [IntermediateField.adjoin.finrank hxQ] at h
  have hΦm : (minpoly (Polynomial ℤ) (jqN N)).Monic := minpoly.monic hx
  have hdeg : (minpoly (Polynomial ℤ) (jqN N)).natDegree = dedekindPsi N := by
    rw [← hΦm.natDegree_map (algebraMap (Polynomial ℤ) ℚ⟮jq⟯), ← hmin]
    exact h
  have heval : (minpoly (Polynomial ℤ) (jqN N)).eval₂ evalAtJ (jqN N) = 0 := by
    have ha := minpoly.aeval (Polynomial ℤ) (jqN N)
    rw [Polynomial.aeval_def] at ha
    exact ha
  refine ⟨⟨minpoly (Polynomial ℤ) (jqN N), hΦm, hdeg, heval⟩, ?_⟩
  show Irreducible (Polynomial.map evalAtJGen (minpoly (Polynomial ℤ) (jqN N)))
  have hmap : Polynomial.map evalAtJGen (minpoly (Polynomial ℤ) (jqN N)) =
      minpoly ℚ⟮jq⟯ (jqN N) := hmin.symm
  rw [hmap]
  exact minpoly.irreducible hxQ

/-- **An irreducible modular polynomial at every level**, the corollary the rest
of FLT consumes, from `exists_phiIrreducible_of_finrank_eq` and the degree count.
Verbatim from `Theorems/Thm_ModularCurve_exists_phiIrreducible.lean`. -/
theorem exists_phiIrreducible (N : ℕ) [NeZero N] :
    ∃ data : ModularPolynomialData N, PhiIrreducible data :=
  exists_phiIrreducible_of_finrank_eq N (finrank_adjoin_jqN_eq_dedekindPsi N)

end ModularCurve

end
