/-
  Layer 0b — the two function fields of `j`.

  `modularFunctionField N = ℚ(j(q), j(q ^ N))` is the field the theorem is about;
  `modularFunctionFieldFull N` is the larger field generated by every
  `j(q ^ d)` with `d ∣ N`. The module also records the degenerate cases
  (`N = 1`), the comparison `modularFunctionField N ≤ modularFunctionFieldFull N`,
  and the two degeneracy lemmas (`full_degeneracy_le`,
  `full_degeneracy_map_le`) that the strong induction consumes. Finally it
  transports the polynomial datum into the `jq`-adjoin ring via `toAdjoin`, and
  proves the relative-degree bridge `relfinrank_modularFunctionField`.

  FLT provenance, pinned `aa2d8b3`:
  `Definitions/Def_ModularCurve_X0.lean` lines 246–348, and (for
  `relfinrank_modularFunctionField`) `P2M/Sol/S_ModularCurve_relfinrank_modularFunctionField.lean`
  / `Theorems/Thm_ModularCurve_relfinrank_modularFunctionField.lean`.
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_X0.lean

  `IntermediateField`, `Subalgebra` and `Polynomial` are mathlib's; the
  declaration names are FLT's, verbatim. Assumes `qExpand`, `qExpandₐ` from
  `FLTForHuman.ModularCurve.Defs.Laurent`, `jq`/`jqN`/`evalAtJ` from
  `FLTForHuman.ModularCurve.Defs.Jq`, and `ModularPolynomialData` from
  `FLTForHuman.ModularCurve.Defs.Polynomial`.
-/
import Mathlib.FieldTheory.Relrank
import FLTForHuman.ModularCurve.Defs.Polynomial

set_option autoImplicit false

noncomputable section

open PowerSeries HahnSeries IntermediateField

namespace ModularCurve

section FunctionField

variable (N : ℕ) [NeZero N]

/-- The function field `ℚ(j(q), j(q ^ N))` of the theorem, as an intermediate
field of the Laurent series over `ℚ`. -/
def modularFunctionField : IntermediateField ℚ (LaurentSeries ℚ) :=
  IntermediateField.adjoin ℚ {jq, qExpand ℚ N jq}

theorem jq_mem : jq ∈ modularFunctionField N :=
  IntermediateField.subset_adjoin ℚ _ (Set.mem_insert _ _)

theorem jqN_mem : qExpand ℚ N jq ∈ modularFunctionField N :=
  IntermediateField.subset_adjoin ℚ _ (Set.mem_insert_of_mem _ rfl)

/-- At `N = 1` the two generators coincide, so the field is `ℚ(j(q))`. -/
theorem modularFunctionField_one : modularFunctionField 1 = ℚ⟮jq⟯ := by
  rw [modularFunctionField, qExpand_one_apply, Set.pair_eq_singleton]

/-- `ℚ(j(q))` sits inside `ℚ(j(q), j(q ^ N))`. -/
theorem adjoin_jq_le : ℚ⟮jq⟯ ≤ modularFunctionField N := by
  rw [IntermediateField.adjoin_le_iff]
  exact Set.singleton_subset_iff.mpr (jq_mem N)

end FunctionField

/-- The relative degree of `modularFunctionField N = ℚ(j(q), j(q ^ N))` over
`ℚ(j(q))` is the degree of `j(q ^ N)` over `ℚ(j(q))`: the two-generator field
generated inside the Laurent series is generated by the single element `jqN N`
over `ℚ⟮jq⟯`, so adjoining it and extending scalars agree.

This is `IntermediateField.relfinrank_eq_finrank_of_le` applied to
`adjoin_jq_le` together with `IntermediateField.extendScalars_adjoin`; the
remaining equality of the two adjoins is `qExpand ℚ N jq = jqN N` on the nose.
It is the bridge `Spine.lean`'s `relfinrank_full_of` uses to convert
`Gen + Tight` into a relative degree, and so was the third `cites = 0` field of
`Inputs`. -/
theorem relfinrank_modularFunctionField (N : ℕ) [NeZero N] :
    IntermediateField.relfinrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
      (modularFunctionField N) =
    Module.finrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
      (IntermediateField.adjoin (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
        ({jqN N} : Set (LaurentSeries ℚ))) := by
  have key : extendScalars (adjoin_jq_le N) =
      adjoin (adjoin ℚ ({jq} : Set (LaurentSeries ℚ))) ({jqN N} : Set (LaurentSeries ℚ)) := by
    have key0 := extendScalars_adjoin (adjoin_jq_le N)
    refine key0.trans (le_antisymm ?_ ?_)
    · rw [adjoin_le_iff, Set.insert_subset_iff]
      refine ⟨?_, Set.singleton_subset_iff.mpr (subset_adjoin _ _ rfl)⟩
      exact (adjoin _ _).algebraMap_mem
        (⟨jq, subset_adjoin ℚ _ rfl⟩ : ↥(adjoin ℚ ({jq} : Set (LaurentSeries ℚ))))
    · exact adjoin.mono _ _ _ (Set.subset_insert _ _)
  rw [IntermediateField.relfinrank_eq_finrank_of_le (adjoin_jq_le N), key]

/-- `j(q)` as an element of the simple extension `ℚ(j(q))`. -/
def jGen : ℚ⟮jq⟯ := ⟨jq, IntermediateField.mem_adjoin_simple_self ℚ jq⟩

/-- Evaluation of an integer polynomial at `jGen`, into `ℚ(j(q))`. -/
def evalAtJGen : Polynomial ℤ →+* ℚ⟮jq⟯ :=
  Polynomial.eval₂RingHom (Int.castRingHom ℚ⟮jq⟯) jGen

/-- `evalAtJGen` followed by the inclusion of `ℚ(j(q))` in the Laurent series
is `evalAtJ` — the bridge that lets the polynomial datum be moved into
`ℚ(j(q))`. -/
theorem algebraMap_comp_evalAtJGen :
    (algebraMap ℚ⟮jq⟯ (LaurentSeries ℚ)).comp evalAtJGen = evalAtJ := by
  refine Polynomial.ringHom_ext' (Subsingleton.elim _ _) ?_
  show algebraMap ℚ⟮jq⟯ (LaurentSeries ℚ) (evalAtJGen Polynomial.X) = evalAtJ Polynomial.X
  rw [evalAtJ_X]
  show algebraMap ℚ⟮jq⟯ (LaurentSeries ℚ)
    (Polynomial.eval₂ (Int.castRingHom ℚ⟮jq⟯) jGen Polynomial.X) = jq
  rw [Polynomial.eval₂_X]
  rfl

namespace ModularPolynomialData

variable {N : ℕ} [NeZero N] (data : ModularPolynomialData N)

/-- The modular polynomial, transported into `ℚ(j(q))[Y]` by evaluating its
integer coefficients at `jGen`. -/
def toAdjoin : Polynomial ℚ⟮jq⟯ := data.Φ.map evalAtJGen

theorem toAdjoin_monic : data.toAdjoin.Monic := data.monic.map _

end ModularPolynomialData

section AllDivisors

variable (N : ℕ) [NeZero N]

/-- The set of all `j(q ^ d)` with `d ∣ N` — the generators of the full field. -/
def divisorExpansions : Set (LaurentSeries ℚ) :=
  {x | ∃ (d : ℕ) (_ : NeZero d), d ∣ N ∧ x = qExpand ℚ d jq}

omit [NeZero N] in
theorem mem_divisorExpansions {d : ℕ} [NeZero d] (hd : d ∣ N) :
    qExpand ℚ d jq ∈ divisorExpansions N :=
  ⟨d, ‹_›, hd, rfl⟩

/-- The full field `ℚ(j(q ^ d) : d ∣ N)`, generated by all divisor
substitutions of `jq`. -/
def modularFunctionFieldFull : IntermediateField ℚ (LaurentSeries ℚ) :=
  IntermediateField.adjoin ℚ (divisorExpansions N)

omit [NeZero N] in
theorem jqd_mem_full {d : ℕ} [NeZero d] (hd : d ∣ N) :
    qExpand ℚ d jq ∈ modularFunctionFieldFull N :=
  subset_adjoin ℚ _ (mem_divisorExpansions N hd)

/-- The two-generator field is contained in the all-divisors field. -/
theorem modularFunctionField_le_full :
    modularFunctionField N ≤ modularFunctionFieldFull N := by
  rw [modularFunctionField, adjoin_le_iff]
  rintro x (rfl | rfl)
  · have h := jqd_mem_full N (one_dvd N)
    rwa [qExpand_one_apply] at h
  · exact jqd_mem_full N dvd_rfl

/-- Degeneracy in `N`: `N ∣ M` gives `ℚ(j(q ^ d) : d ∣ N) ≤ ℚ(j(q ^ d) : d ∣ M)`. -/
theorem full_degeneracy_le {N M : ℕ} [NeZero N] [NeZero M] (h : N ∣ M) :
    modularFunctionFieldFull N ≤ modularFunctionFieldFull M := by
  rw [modularFunctionFieldFull, adjoin_le_iff]
  rintro x ⟨d, _, hdvd, rfl⟩
  exact jqd_mem_full M (hdvd.trans h)

omit [NeZero N] in

theorem full_degeneracy_map_le (ℓ : ℕ) [NeZero ℓ] :
    (modularFunctionFieldFull N).map (qExpandₐ ℓ) ≤ modularFunctionFieldFull (N * ℓ) := by
  rw [modularFunctionFieldFull, adjoin_map, adjoin_le_iff]
  rintro x ⟨y, ⟨d, hne, hdvd, rfl⟩, rfl⟩
  show qExpandₐ ℓ (qExpand ℚ d jq) ∈ _
  rw [qExpandₐ_apply, qExpand_qExpand]
  exact jqd_mem_full (N * ℓ) ((mul_dvd_mul_left ℓ hdvd).trans (dvd_of_eq (mul_comm ℓ N)))

end AllDivisors

/-! ## T16 — the relative degree of adjoining one generator

`w1_relfinrank_insert` is Tier 1 of math/010 §6: adjoining a single element `α`
to `E` inside `ℚ(α, E)` has relative degree equal to `[E(α) : E]`. FLT repeats
it across three files; it already uses mathlib's relative-degree/tower API
(`relfinrank_eq_finrank_of_le`, `extendScalars_adjoin`), so there is nothing to
replace. Statement verbatim from
`S_ModularCurve_relfinrank_full_eq_mul.lean`. -/

section RelfinrankInsert

/-- The relative degree of `ℚ(α, E)` over `E` is the degree of `α` over `E`. -/
theorem w1_relfinrank_insert (E : IntermediateField ℚ (LaurentSeries ℚ))
    (α : LaurentSeries ℚ) :
    IntermediateField.relfinrank E
      (IntermediateField.adjoin ℚ (insert α (E : Set (LaurentSeries ℚ))))
      = Module.finrank E
          (IntermediateField.adjoin E ({α} : Set (LaurentSeries ℚ))) := by
  have h : E ≤ IntermediateField.adjoin ℚ (insert α (E : Set (LaurentSeries ℚ))) :=
    fun x hx => IntermediateField.subset_adjoin ℚ _ (Set.mem_insert_of_mem _ hx)
  have hEq : IntermediateField.adjoin E (insert α (E : Set (LaurentSeries ℚ)))
      = IntermediateField.adjoin E ({α} : Set (LaurentSeries ℚ)) := by
    refine le_antisymm ?_ ?_
    · rw [IntermediateField.adjoin_le_iff]
      rintro x (rfl | hxE)
      · exact IntermediateField.subset_adjoin _ _ rfl
      · exact (IntermediateField.adjoin E _).algebraMap_mem (⟨x, hxE⟩ : E)
    · exact IntermediateField.adjoin.mono _ _ _
        (Set.singleton_subset_iff.mpr (Set.mem_insert α _))
  rw [IntermediateField.relfinrank_eq_finrank_of_le h,
    IntermediateField.extendScalars_adjoin h, hEq]

end RelfinrankInsert

/-! ## T18 — the strong-induction invariants and the prime generator

`Tight`/`Gen`/`Hall` are FLT's own abbreviations for the strong induction of
math/010 §7; they were public in `FunctionFieldGeneration/Spine.lean` and T18
moves them here, beside the two fields they concern, so that `tight_one`/`gen_one`
and the T19 substitution `gen_prime` can be stated beside them.

`tight_one`/`gen_one` are FLT's (private in
`S_ModularCurve_functionFieldGeneration.lean`); `gen_prime` is the audit's
replacement (`TOPIC-t17-t19-route-audit.md` §1) for the pin's
`functionFieldGeneration_of_squarefree` detour at
`S_ModularCurve_jqN_prime_not_mem_full.lean:1638`. -/

section StrongInduction

/-- The two invariants of the strong induction, bundled. `Tight d` says the
relative degree of `ℚ⟮jq⟯(jqN d)` over `ℚ⟮jq⟯` is exactly `ψ(d)`. -/
abbrev Tight (d : ℕ) [NeZero d] : Prop :=
  Module.finrank ℚ⟮jq⟯ (IntermediateField.adjoin ℚ⟮jq⟯ ({jqN d} : Set (LaurentSeries ℚ))) =
    dedekindPsi d

/-- `Gen d` says the two-generator field already contains every `j(q ^ e)`, `e ∣ d`. -/
abbrev Gen (d : ℕ) [NeZero d] : Prop := modularFunctionField d = modularFunctionFieldFull d

/-- `Hall N` is the strong-induction hypothesis: `Tight` and `Gen` hold at every
divisor of `N`. -/
abbrev Hall (N : ℕ) : Prop := ∀ d : ℕ, d ∣ N → ∀ [NeZero d], Tight d ∧ Gen d

/-- The base of the strong induction: `Tight 1` is `[ℚ⟮jq⟯ : ℚ⟮jq⟯] = ψ(1) = 1`. -/
theorem tight_one : Tight 1 := by
  unfold Tight
  have h1 : jqN 1 = jq := by rw [jqN, qExpand_one_apply]
  rw [h1, dedekindPsi_one]
  have h2 : IntermediateField.adjoin ℚ⟮jq⟯ ({jq} : Set (LaurentSeries ℚ)) =
      (⊥ : IntermediateField ℚ⟮jq⟯ (LaurentSeries ℚ)) := by
    rw [IntermediateField.adjoin_simple_eq_bot_iff, IntermediateField.mem_bot]
    exact ⟨jGen, rfl⟩
  rw [h2]
  exact IntermediateField.finrank_bot

/-- The base of `Gen`: at `N = 1` the two-generator field is the full field. -/
theorem gen_one : Gen 1 := by
  unfold Gen
  refine le_antisymm (modularFunctionField_le_full 1) ?_
  rw [modularFunctionFieldFull, IntermediateField.adjoin_le_iff]
  rintro x ⟨d, hne, hdvd, rfl⟩
  have hd1 : d = 1 := Nat.dvd_one.mp hdvd
  subst hd1
  rw [qExpand_one_apply]
  exact jq_mem 1

/-- **`Gen` at a prime is definitional**: `modularFunctionField p =
modularFunctionFieldFull p = ℚ(j, j(q ^ p))`. This is T19's substitution: it
replaces the pin's `functionFieldGeneration_of_squarefree p` call at
`S_ModularCurve_jqN_prime_not_mem_full.lean:1638`
(`TOPIC-t17-t19-route-audit.md` §1), so T19 does not depend on the squarefree
generation/degree block. -/
theorem gen_prime (p : ℕ) [NeZero p] [hp : Fact (Nat.Prime p)] : Gen p := by
  unfold Gen
  refine le_antisymm (modularFunctionField_le_full p) ?_
  rw [modularFunctionField, modularFunctionFieldFull, divisorExpansions,
    IntermediateField.adjoin_le_iff]
  rintro x ⟨d, -, hdvd, rfl⟩
  rcases hp.out.eq_one_or_self_of_dvd d hdvd with h1 | h2
  · subst h1; rw [qExpand_one_apply]
    exact IntermediateField.subset_adjoin ℚ _ (Set.mem_insert _ _)
  · subst h2
    exact IntermediateField.subset_adjoin ℚ _ (Set.mem_insert_of_mem _ rfl)

end StrongInduction

end ModularCurve

end
