/-
  Layer 0b — the two function fields of `j`.

  `modularFunctionField N = ℚ(j(q), j(q ^ N))` is the field the theorem is about;
  `modularFunctionFieldFull N` is the larger field generated by every
  `j(q ^ d)` with `d ∣ N`. The module also records the degenerate cases
  (`N = 1`), the comparison `modularFunctionField N ≤ modularFunctionFieldFull N`,
  and the two degeneracy lemmas (`full_degeneracy_le`,
  `full_degeneracy_map_le`) that the strong induction consumes. Finally it
  transports the polynomial datum into the `jq`-adjoin ring via `toAdjoin`.

  FLT provenance, pinned `aa2d8b3`:
  `Definitions/Def_ModularCurve_X0.lean` lines 246–348.
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_X0.lean

  `IntermediateField`, `Subalgebra` and `Polynomial` are mathlib's; the
  declaration names are FLT's, verbatim. Assumes `qExpand`, `qExpandₐ` from
  `FLTForHuman.ModularCurve.Defs.Laurent`, `jq`/`jqN`/`evalAtJ` from
  `FLTForHuman.ModularCurve.Defs.Jq`, and `ModularPolynomialData` from
  `FLTForHuman.ModularCurve.Defs.Polynomial`.
-/
import FLTForHuman.ModularCurve.Defs.Polynomial

set_option autoImplicit false

noncomputable section

open PowerSeries HahnSeries IntermediateField

namespace ModularCurve

section FunctionField

variable (N : ℕ) [NeZero N]

/-- The function field `ℚ(j(q), j(q ^ N))` of the theorem, as an intermediate
field of the Laurent series over `ℚ`. -/
def modularFunctionField : IntermediateField ℚ (LaurentSeries ℚ) :=
  IntermediateField.adjoin ℚ {jq, qExpand ℚ N jq}

theorem jq_mem : jq ∈ modularFunctionField N :=
  IntermediateField.subset_adjoin ℚ _ (Set.mem_insert _ _)

theorem jqN_mem : qExpand ℚ N jq ∈ modularFunctionField N :=
  IntermediateField.subset_adjoin ℚ _ (Set.mem_insert_of_mem _ rfl)

/-- At `N = 1` the two generators coincide, so the field is `ℚ(j(q))`. -/
theorem modularFunctionField_one : modularFunctionField 1 = ℚ⟮jq⟯ := by
  rw [modularFunctionField, qExpand_one_apply, Set.pair_eq_singleton]

/-- `ℚ(j(q))` sits inside `ℚ(j(q), j(q ^ N))`. -/
theorem adjoin_jq_le : ℚ⟮jq⟯ ≤ modularFunctionField N := by
  rw [IntermediateField.adjoin_le_iff]
  exact Set.singleton_subset_iff.mpr (jq_mem N)

end FunctionField

/-- `j(q)` as an element of the simple extension `ℚ(j(q))`. -/
def jGen : ℚ⟮jq⟯ := ⟨jq, IntermediateField.mem_adjoin_simple_self ℚ jq⟩

/-- Evaluation of an integer polynomial at `jGen`, into `ℚ(j(q))`. -/
def evalAtJGen : Polynomial ℤ →+* ℚ⟮jq⟯ :=
  Polynomial.eval₂RingHom (Int.castRingHom ℚ⟮jq⟯) jGen

/-- `evalAtJGen` followed by the inclusion of `ℚ(j(q))` in the Laurent series
is `evalAtJ` — the bridge that lets the polynomial datum be moved into
`ℚ(j(q))`. -/
theorem algebraMap_comp_evalAtJGen :
    (algebraMap ℚ⟮jq⟯ (LaurentSeries ℚ)).comp evalAtJGen = evalAtJ := by
  refine Polynomial.ringHom_ext' (Subsingleton.elim _ _) ?_
  show algebraMap ℚ⟮jq⟯ (LaurentSeries ℚ) (evalAtJGen Polynomial.X) = evalAtJ Polynomial.X
  rw [evalAtJ_X]
  show algebraMap ℚ⟮jq⟯ (LaurentSeries ℚ)
    (Polynomial.eval₂ (Int.castRingHom ℚ⟮jq⟯) jGen Polynomial.X) = jq
  rw [Polynomial.eval₂_X]
  rfl

namespace ModularPolynomialData

variable {N : ℕ} [NeZero N] (data : ModularPolynomialData N)

/-- The modular polynomial, transported into `ℚ(j(q))[Y]` by evaluating its
integer coefficients at `jGen`. -/
def toAdjoin : Polynomial ℚ⟮jq⟯ := data.Φ.map evalAtJGen

theorem toAdjoin_monic : data.toAdjoin.Monic := data.monic.map _

end ModularPolynomialData

section AllDivisors

variable (N : ℕ) [NeZero N]

/-- The set of all `j(q ^ d)` with `d ∣ N` — the generators of the full field. -/
def divisorExpansions : Set (LaurentSeries ℚ) :=
  {x | ∃ (d : ℕ) (_ : NeZero d), d ∣ N ∧ x = qExpand ℚ d jq}

omit [NeZero N] in
theorem mem_divisorExpansions {d : ℕ} [NeZero d] (hd : d ∣ N) :
    qExpand ℚ d jq ∈ divisorExpansions N :=
  ⟨d, ‹_›, hd, rfl⟩

/-- The full field `ℚ(j(q ^ d) : d ∣ N)`, generated by all divisor
substitutions of `jq`. -/
def modularFunctionFieldFull : IntermediateField ℚ (LaurentSeries ℚ) :=
  IntermediateField.adjoin ℚ (divisorExpansions N)

omit [NeZero N] in
theorem jqd_mem_full {d : ℕ} [NeZero d] (hd : d ∣ N) :
    qExpand ℚ d jq ∈ modularFunctionFieldFull N :=
  subset_adjoin ℚ _ (mem_divisorExpansions N hd)

/-- The two-generator field is contained in the all-divisors field. -/
theorem modularFunctionField_le_full :
    modularFunctionField N ≤ modularFunctionFieldFull N := by
  rw [modularFunctionField, adjoin_le_iff]
  rintro x (rfl | rfl)
  · have h := jqd_mem_full N (one_dvd N)
    rwa [qExpand_one_apply] at h
  · exact jqd_mem_full N dvd_rfl

/-- Degeneracy in `N`: `N ∣ M` gives `ℚ(j(q ^ d) : d ∣ N) ≤ ℚ(j(q ^ d) : d ∣ M)`. -/
theorem full_degeneracy_le {N M : ℕ} [NeZero N] [NeZero M] (h : N ∣ M) :
    modularFunctionFieldFull N ≤ modularFunctionFieldFull M := by
  rw [modularFunctionFieldFull, adjoin_le_iff]
  rintro x ⟨d, _, hdvd, rfl⟩
  exact jqd_mem_full M (hdvd.trans h)

omit [NeZero N] in

theorem full_degeneracy_map_le (ℓ : ℕ) [NeZero ℓ] :
    (modularFunctionFieldFull N).map (qExpandₐ ℓ) ≤ modularFunctionFieldFull (N * ℓ) := by
  rw [modularFunctionFieldFull, adjoin_map, adjoin_le_iff]
  rintro x ⟨y, ⟨d, hne, hdvd, rfl⟩, rfl⟩
  show qExpandₐ ℓ (qExpand ℚ d jq) ∈ _
  rw [qExpandₐ_apply, qExpand_qExpand]
  exact jqd_mem_full (N * ℓ) ((mul_dvd_mul_left ℓ hdvd).trans (dvd_of_eq (mul_comm ℓ N)))

end AllDivisors

end ModularCurve

end
