/-
  Layer 0b — the slot vocabulary and the `Prop`s of the splitting input.

  Nothing here has a consumer yet. It is ported because it is the *vocabulary of
  math/010 §3*: a future effort that states the modular equation's splitting
  input cannot do so without these names. This is the first port's
  `Universal.lean` lesson in reverse — the statement layer must mention them, so
  they have to exist before the statement can be written.

  The module is in two halves:

  * `ModularCurve`-level objects: `cosetSubst` (the substitution
    `q ↦ ζ ^ (a * b) q ^ (a * a)`), `evalAtJqN`, the symmetry predicate
    `EvalSymm`, the pole predicates `PoleOrderLE`/`TPoleOrderLE`, the family
    predicate `ModularPolynomialFamily`, and the bivariate swap `swapBivar`.
  * `ModularCurve.PhiGen`: the coset indices `cosetA`/`cosetB`, the conjugate
    family `conj` built from them, the product `phiProd`, and the remaining
    `Prop`s (`JSimplePole`, `IntCoeffs`, `PhiGenDescends`).

  FLT provenance, pinned `aa2d8b3`:
  `Definitions/Def_ModularCurve_PhiGen.lean` lines 111–309.
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_PhiGen.lean

  `Polynomial`, `Subalgebra` and `IntermediateField` are mathlib's; the
  declaration names are FLT's, verbatim, and the `PhiGen` namespace is FLT's.
  Assumes `qExpand`/`coeffEmb` (`Defs/Laurent`), `qTwist` (`Defs/Twist`),
  `jq`/`jqN`/`evalAtJ` (`Defs/Jq`), and `ModularPolynomialData.toAdjoin`
  (`Defs/Fields`).
-/
import Mathlib.Algebra.Polynomial.BigOperators
import FLTForHuman.ModularCurve.Defs.Fields
import FLTForHuman.ModularCurve.Defs.Twist

set_option autoImplicit false

noncomputable section

open PowerSeries HahnSeries IntermediateField Polynomial

namespace ModularCurve

section CosetSubst

variable {K : Type*} [Field K]

/-- The coset substitution `q ↦ ζ ^ (a * b) q ^ (a * a)` used to build the
conjugates of `jq`: expand the exponent by `a * a`, then twist by
`ζ ^ (a * b)`. -/
def cosetSubst (ζ : Kˣ) (a b : ℕ) [NeZero a] : LaurentSeries K →+* LaurentSeries K :=
  haveI : NeZero (a * a) := ⟨Nat.mul_ne_zero (NeZero.ne a) (NeZero.ne a)⟩
  (qExpand K (a * a)).comp (qTwist (ζ ^ (a * b)))

end CosetSubst

section EvalAtJqN

variable (N : ℕ) [NeZero N]

/-- Evaluation of an integer polynomial at `j(q ^ N)`. -/
def evalAtJqN : Polynomial ℤ →+* LaurentSeries ℚ :=
  (Polynomial.aeval (R := ℤ) (jqN N)).toRingHom

@[simp]
theorem evalAtJqN_X : evalAtJqN N Polynomial.X = jqN N := by
  simp [evalAtJqN]

theorem evalAtJqN_def : evalAtJqN N = (Polynomial.aeval (R := ℤ) (jqN N)).toRingHom := rfl

theorem evalAtJ_def : evalAtJ = (Polynomial.aeval (R := ℤ) jq).toRingHom := rfl

theorem evalAtJqN_one : evalAtJqN 1 = evalAtJ := by
  rw [evalAtJqN_def, evalAtJ_def, jqN_one]

end EvalAtJqN

section Symmetry

/-- `Φ` is symmetric in its two variables when evaluating it at `(x, y)` and at
`(y, x)` agree. -/
def EvalSymm (Φ : Polynomial (Polynomial ℤ)) : Prop :=
  ∀ x y : LaurentSeries ℚ,
    Φ.eval₂ (Polynomial.aeval (R := ℤ) x).toRingHom y
      = Φ.eval₂ (Polynomial.aeval (R := ℤ) y).toRingHom x

@[simp]
theorem aeval_toRingHom_X (x : LaurentSeries ℚ) :
    (Polynomial.aeval (R := ℤ) x).toRingHom Polynomial.X = x := by
  simp

end Symmetry

/-- `f` has a pole of order at most `n` at `q = 0`: all coefficients below
`q ^ (-n)` vanish. -/
def PoleOrderLE (f : LaurentSeries ℚ) (n : ℕ) : Prop :=
  ∀ k : ℤ, k < -(n : ℤ) → f.coeff k = 0

/-- The splitting input as a family: for every prime `ℓ` there is a symmetric
modular polynomial datum at `ℓ`. -/
def ModularPolynomialFamily : Prop :=
  ∀ (ℓ : ℕ) [NeZero ℓ], ℓ.Prime → ∃ data : ModularPolynomialData ℓ, EvalSymm data.Φ

section Named

variable {N : ℕ} [NeZero N]

/-- The irreducibility half of the splitting input, transported into
`ℚ(j(q))[Y]`. -/
def PhiIrreducible (data : ModularPolynomialData N) : Prop :=
  Irreducible data.toAdjoin

end Named

section AdjoinRing

/-- The subalgebra `ℚ[j(q)]` (polynomial, not field) generated by `jq`. -/
abbrev adjoinJq : Subalgebra ℚ (LaurentSeries ℚ) := Algebra.adjoin ℚ {jq}

/-- `j(q)` as an element of the subalgebra `ℚ[j(q)]`. -/
def jAdj : adjoinJq := ⟨jq, Algebra.self_mem_adjoin_singleton ℚ jq⟩

/-- Evaluation of an integer polynomial at `jAdj`, into `ℚ[j(q)]`. -/
def evalAtJAdj : Polynomial ℤ →+* adjoinJq :=
  Polynomial.eval₂RingHom (Int.castRingHom adjoinJq) jAdj

end AdjoinRing

section SwapBivar

/-- The inner map `X ↦ Y` of `ℤ[X] → ℤ[X][Y]`. -/
def swapInner : Polynomial ℤ →+* Polynomial (Polynomial ℤ) :=
  (Polynomial.aeval (R := ℤ) (Polynomial.X : Polynomial (Polynomial ℤ))).toRingHom

/-- The bivariate swap `X ↔ Y` on `ℤ[X][Y]`. -/
def swapBivar : Polynomial (Polynomial ℤ) →+* Polynomial (Polynomial ℤ) :=
  Polynomial.eval₂RingHom swapInner (Polynomial.C Polynomial.X)

@[simp]
theorem swapBivar_X : swapBivar Polynomial.X = Polynomial.C Polynomial.X :=
  Polynomial.eval₂_X _ _

@[simp]
theorem swapBivar_C_X : swapBivar (Polynomial.C Polynomial.X) = Polynomial.X := by
  show Polynomial.eval₂ swapInner (Polynomial.C Polynomial.X) (Polynomial.C Polynomial.X)
    = Polynomial.X
  rw [Polynomial.eval₂_C]
  exact Polynomial.aeval_X _

end SwapBivar

namespace PhiGen

section CosetIndex

variable (ℓ : ℕ)

/-- The expansion index of the `i`-th conjugate: `ℓ` at `i = 0`, else `1`. -/
def cosetA (i : Fin (ℓ + 1)) : ℕ := if i = 0 then ℓ else 1

/-- The twist index of the `i`-th conjugate: `0` at `i = 0`, else `i - 1`. -/
def cosetB (i : Fin (ℓ + 1)) : ℕ := if i = 0 then 0 else (i : ℕ) - 1

@[simp]
theorem cosetA_zero : cosetA ℓ (0 : Fin (ℓ + 1)) = ℓ := ite_eq_left rfl

@[simp]
theorem cosetB_zero : cosetB ℓ (0 : Fin (ℓ + 1)) = 0 := ite_eq_left rfl

@[simp]
theorem cosetA_succ (b : Fin ℓ) : cosetA ℓ b.succ = 1 := ite_eq_right (Fin.succ_ne_zero b)

@[simp]
theorem cosetB_succ (b : Fin ℓ) : cosetB ℓ b.succ = (b : ℕ) := by
  rw [cosetB, ite_eq_right (Fin.succ_ne_zero b), Fin.val_succ, Nat.add_sub_cancel]

instance instNeZeroPhiGenCosetA [hℓ : Fact (Nat.Prime ℓ)] (i : Fin (ℓ + 1)) :
    NeZero (cosetA ℓ i) :=
  ⟨by unfold cosetA; split <;> simp [hℓ.out.ne_zero]⟩

end CosetIndex

section ConjugateFamily

variable {K : Type*} [Field K]

theorem cosetSubst_congr (ζ : Kˣ) {a a' b b' : ℕ} [NeZero a] [NeZero a'] (ha : a = a')
    (hb : b = b') (f : LaurentSeries K) : cosetSubst ζ a b f = cosetSubst ζ a' b' f := by
  subst ha; subst hb; rfl

variable [Algebra ℚ K] (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] (ζ : Kˣ)

/-- The conjugate family of `jq` at the prime `ℓ`: the `ℓ + 1` values
`j(ζ ^ b q ^ a)` for the coset representatives `(a, b)`. -/
def conj (i : Fin (ℓ + 1)) : LaurentSeries K :=
  cosetSubst ζ (cosetA ℓ i) (cosetB ℓ i) (coeffEmb K jq)

theorem conj_zero : conj ℓ ζ (0 : Fin (ℓ + 1)) = qExpand K (ℓ * ℓ) (coeffEmb K jq) := by
  have h1 : conj ℓ ζ (0 : Fin (ℓ + 1)) = cosetSubst ζ ℓ 0 (coeffEmb K jq) :=
    cosetSubst_congr ζ (cosetA_zero ℓ) (cosetB_zero ℓ) (coeffEmb K jq)
  rw [h1, cosetSubst, RingHom.comp_apply, mul_zero, pow_zero, qTwist_one_apply]

theorem conj_succ (b : Fin ℓ) : conj ℓ ζ b.succ = qTwist (ζ ^ (b : ℕ)) (coeffEmb K jq) := by
  have h1 : conj ℓ ζ b.succ = cosetSubst ζ 1 ((b : ℕ)) (coeffEmb K jq) :=
    cosetSubst_congr ζ (cosetA_succ ℓ b) (cosetB_succ ℓ b) (coeffEmb K jq)
  rw [h1, cosetSubst, RingHom.comp_apply,
    qExpand_congr (show 1 * 1 = 1 by norm_num), qExpand_one_apply, one_mul]

end ConjugateFamily

section Product

variable {K : Type*} [Field K] (ℓ : ℕ)

/-- The product `∏_i (Y - conj i)`, the polynomial whose roots are the
conjugates of `jq`. -/
def phiProd (conj : Fin (ℓ + 1) → LaurentSeries K) : Polynomial (LaurentSeries K) :=
  ∏ i : Fin (ℓ + 1), (Polynomial.X - Polynomial.C (conj i))

theorem phiProd_monic (conj : Fin (ℓ + 1) → LaurentSeries K) : (phiProd ℓ conj).Monic :=
  monic_prod_of_monic _ _ fun i _ => monic_X_sub_C (conj i)

theorem phiProd_natDegree (conj : Fin (ℓ + 1) → LaurentSeries K) :
    (phiProd ℓ conj).natDegree = ℓ + 1 := by
  rw [phiProd, natDegree_prod_of_monic _ _ fun i _ => monic_X_sub_C _]
  simp

theorem phiProd_ne_zero (conj : Fin (ℓ + 1) → LaurentSeries K) : phiProd ℓ conj ≠ 0 :=
  (phiProd_monic ℓ conj).ne_zero

theorem phiProd_eval_conj (conj : Fin (ℓ + 1) → LaurentSeries K) (i : Fin (ℓ + 1)) :
    (phiProd ℓ conj).eval (conj i) = 0 := by
  rw [phiProd, Polynomial.eval_prod]
  exact Finset.prod_eq_zero (Finset.mem_univ i) (by simp)

end Product

section PoleDefs

variable {K : Type*} [Field K]

/-- The `K`-coefficient version of `PoleOrderLE`. -/
def TPoleOrderLE (f : LaurentSeries K) (n : ℕ) : Prop :=
  ∀ m : ℤ, m < -(n : ℤ) → f.coeff m = 0

theorem tPoleOrderLE_iff_poleOrderLE (f : LaurentSeries ℚ) (n : ℕ) :
    TPoleOrderLE f n ↔ PoleOrderLE f n :=
  Iff.rfl

variable (J : LaurentSeries K)

/-- `J` has at most a simple pole at `q = 0`. -/
def JSimplePole : Prop := ∀ m : ℤ, m < -1 → J.coeff m = 0

end PoleDefs

/-- `f` has integer coefficients, as rationals. -/
def IntCoeffs (f : LaurentSeries ℚ) : Prop :=
  ∀ m : ℤ, ∃ z : ℤ, f.coeff m = (z : ℚ)

section Descends

variable {K : Type*} [Field K] [Algebra ℚ K] (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] (ζ : Kˣ)

/-- `phiProd` descends to `ℚ`: its coefficients are the `coeffEmb` images of the
series `c k` after the `ℓ`-substitution. -/
def PhiGenDescends (c : ℕ → LaurentSeries ℚ) : Prop :=
  ∀ k : ℕ, (phiProd ℓ (conj ℓ ζ)).coeff k = coeffEmb K (qExpand ℚ ℓ (c k))

end Descends

end PhiGen

end ModularCurve

end
