/-
  Layer 0b — the slot vocabulary and the `Prop`s of the splitting input.

  Nothing here has a consumer yet. It is ported because it is the *vocabulary of
  math/010 §3*: a future effort that states the modular equation's splitting
  input cannot do so without these names. This is the first port's
  `Universal.lean` lesson in reverse — the statement layer must mention them, so
  they have to exist before the statement can be written.

  The module is in two halves:

  * `ModularCurve`-level objects: `cosetSubst` (the substitution
    `q ↦ ζ ^ (a * b) q ^ (a * a)`), `evalAtJqN`, the symmetry predicate
    `EvalSymm`, the pole predicates `PoleOrderLE`/`TPoleOrderLE`, the family
    predicate `ModularPolynomialFamily`, and the bivariate swap `swapBivar`.
  * `ModularCurve.PhiGen`: the coset indices `cosetA`/`cosetB`, the conjugate
    family `conj` built from them, the product `phiProd`, and the remaining
    `Prop`s (`JSimplePole`, `IntCoeffs`, `PhiGenDescends`).

  FLT provenance, pinned `aa2d8b3`:
  `Definitions/Def_ModularCurve_PhiGen.lean` lines 111–309.
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_PhiGen.lean

  `Polynomial`, `Subalgebra` and `IntermediateField` are mathlib's; the
  declaration names are FLT's, verbatim, and the `PhiGen` namespace is FLT's.
  Assumes `qExpand`/`coeffEmb` (`Defs/Laurent`), `qTwist` (`Defs/Twist`),
  `jq`/`jqN`/`evalAtJ` (`Defs/Jq`), and `ModularPolynomialData.toAdjoin`
  (`Defs/Fields`).
-/
import Mathlib.Algebra.Polynomial.BigOperators
import FLTForHuman.ModularCurve.Defs.Fields
import FLTForHuman.ModularCurve.Defs.Twist

set_option autoImplicit false

noncomputable section

open PowerSeries HahnSeries IntermediateField Polynomial

namespace ModularCurve

section CosetSubst

variable {K : Type*} [Field K]

/-- The coset substitution `q ↦ ζ ^ (a * b) q ^ (a * a)` used to build the
conjugates of `jq`: expand the exponent by `a * a`, then twist by
`ζ ^ (a * b)`. -/
def cosetSubst (ζ : Kˣ) (a b : ℕ) [NeZero a] : LaurentSeries K →+* LaurentSeries K :=
  haveI : NeZero (a * a) := ⟨Nat.mul_ne_zero (NeZero.ne a) (NeZero.ne a)⟩
  (qExpand K (a * a)).comp (qTwist (ζ ^ (a * b)))

end CosetSubst

section EvalAtJqN

variable (N : ℕ) [NeZero N]

/-- Evaluation of an integer polynomial at `j(q ^ N)`. -/
def evalAtJqN : Polynomial ℤ →+* LaurentSeries ℚ :=
  (Polynomial.aeval (R := ℤ) (jqN N)).toRingHom

@[simp]
theorem evalAtJqN_X : evalAtJqN N Polynomial.X = jqN N := by
  simp [evalAtJqN]

theorem evalAtJqN_def : evalAtJqN N = (Polynomial.aeval (R := ℤ) (jqN N)).toRingHom := rfl

theorem evalAtJ_def : evalAtJ = (Polynomial.aeval (R := ℤ) jq).toRingHom := rfl

theorem evalAtJqN_one : evalAtJqN 1 = evalAtJ := by
  rw [evalAtJqN_def, evalAtJ_def, jqN_one]

end EvalAtJqN

section Symmetry

/-- `Φ` is symmetric in its two variables when evaluating it at `(x, y)` and at
`(y, x)` agree. -/
def EvalSymm (Φ : Polynomial (Polynomial ℤ)) : Prop :=
  ∀ x y : LaurentSeries ℚ,
    Φ.eval₂ (Polynomial.aeval (R := ℤ) x).toRingHom y
      = Φ.eval₂ (Polynomial.aeval (R := ℤ) y).toRingHom x

@[simp]
theorem aeval_toRingHom_X (x : LaurentSeries ℚ) :
    (Polynomial.aeval (R := ℤ) x).toRingHom Polynomial.X = x := by
  simp

end Symmetry

/-- `f` has a pole of order at most `n` at `q = 0`: all coefficients below
`q ^ (-n)` vanish. -/
def PoleOrderLE (f : LaurentSeries ℚ) (n : ℕ) : Prop :=
  ∀ k : ℤ, k < -(n : ℤ) → f.coeff k = 0

/-- Triangularity of `jq`'s pole: a polynomial in `jq` of degree `n` has pole
order at most `n`. Promoted from T7's private copy (`Hauptmodul.lean`) so that the
cone's pole-bound topics share it; FLT keeps it private in
`S_ModularCurve_exists_aeval_jq_sub_holomorphicAtInfty.lean`. -/
theorem poleOrderLE_aeval_jq (P : Polynomial ℚ) :
    PoleOrderLE (Polynomial.aeval jq P) P.natDegree := by
  intro k hk
  rw [Polynomial.aeval_def, Polynomial.eval₂_eq_sum_range, HahnSeries.coeff_sum]
  refine Finset.sum_eq_zero fun i hi => ?_
  have hile : i ≤ P.natDegree := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
  rw [algebraMap_apply_eq_single, HahnSeries.coeff_single_zero_mul,
    coeff_jq_pow_of_lt (by omega), mul_zero]

/-- The splitting input as a family: for every prime `ℓ` there is a symmetric
modular polynomial datum at `ℓ`. -/
def ModularPolynomialFamily : Prop :=
  ∀ (ℓ : ℕ) [NeZero ℓ], ℓ.Prime → ∃ data : ModularPolynomialData ℓ, EvalSymm data.Φ

section Named

variable {N : ℕ} [NeZero N]

/-- The irreducibility half of the splitting input, transported into
`ℚ(j(q))[Y]`. -/
def PhiIrreducible (data : ModularPolynomialData N) : Prop :=
  Irreducible data.toAdjoin

end Named

section AdjoinRing

/-- The subalgebra `ℚ[j(q)]` (polynomial, not field) generated by `jq`. -/
abbrev adjoinJq : Subalgebra ℚ (LaurentSeries ℚ) := Algebra.adjoin ℚ {jq}

/-- `j(q)` as an element of the subalgebra `ℚ[j(q)]`. -/
def jAdj : adjoinJq := ⟨jq, Algebra.self_mem_adjoin_singleton ℚ jq⟩

/-- Evaluation of an integer polynomial at `jAdj`, into `ℚ[j(q)]`. -/
def evalAtJAdj : Polynomial ℤ →+* adjoinJq :=
  Polynomial.eval₂RingHom (Int.castRingHom adjoinJq) jAdj

end AdjoinRing

section SwapBivar

/-- The inner map `X ↦ Y` of `ℤ[X] → ℤ[X][Y]`. -/
def swapInner : Polynomial ℤ →+* Polynomial (Polynomial ℤ) :=
  (Polynomial.aeval (R := ℤ) (Polynomial.X : Polynomial (Polynomial ℤ))).toRingHom

/-- The bivariate swap `X ↔ Y` on `ℤ[X][Y]`. -/
def swapBivar : Polynomial (Polynomial ℤ) →+* Polynomial (Polynomial ℤ) :=
  Polynomial.eval₂RingHom swapInner (Polynomial.C Polynomial.X)

@[simp]
theorem swapBivar_X : swapBivar Polynomial.X = Polynomial.C Polynomial.X :=
  Polynomial.eval₂_X _ _

@[simp]
theorem swapBivar_C_X : swapBivar (Polynomial.C Polynomial.X) = Polynomial.X := by
  show Polynomial.eval₂ swapInner (Polynomial.C Polynomial.X) (Polynomial.C Polynomial.X)
    = Polynomial.X
  rw [Polynomial.eval₂_C]
  exact Polynomial.aeval_X _

end SwapBivar

namespace PhiGen

section CosetIndex

variable (ℓ : ℕ)

/-- The expansion index of the `i`-th conjugate: `ℓ` at `i = 0`, else `1`. -/
def cosetA (i : Fin (ℓ + 1)) : ℕ := if i = 0 then ℓ else 1

/-- The twist index of the `i`-th conjugate: `0` at `i = 0`, else `i - 1`. -/
def cosetB (i : Fin (ℓ + 1)) : ℕ := if i = 0 then 0 else (i : ℕ) - 1

@[simp]
theorem cosetA_zero : cosetA ℓ (0 : Fin (ℓ + 1)) = ℓ := ite_eq_left rfl

@[simp]
theorem cosetB_zero : cosetB ℓ (0 : Fin (ℓ + 1)) = 0 := ite_eq_left rfl

@[simp]
theorem cosetA_succ (b : Fin ℓ) : cosetA ℓ b.succ = 1 := ite_eq_right (Fin.succ_ne_zero b)

@[simp]
theorem cosetB_succ (b : Fin ℓ) : cosetB ℓ b.succ = (b : ℕ) := by
  rw [cosetB, ite_eq_right (Fin.succ_ne_zero b), Fin.val_succ, Nat.add_sub_cancel]

instance instNeZeroPhiGenCosetA [hℓ : Fact (Nat.Prime ℓ)] (i : Fin (ℓ + 1)) :
    NeZero (cosetA ℓ i) :=
  ⟨by unfold cosetA; split <;> simp [hℓ.out.ne_zero]⟩

end CosetIndex

section ConjugateFamily

variable {K : Type*} [Field K]

theorem cosetSubst_congr (ζ : Kˣ) {a a' b b' : ℕ} [NeZero a] [NeZero a'] (ha : a = a')
    (hb : b = b') (f : LaurentSeries K) : cosetSubst ζ a b f = cosetSubst ζ a' b' f := by
  subst ha; subst hb; rfl

variable [Algebra ℚ K] (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] (ζ : Kˣ)

/-- The conjugate family of `jq` at the prime `ℓ`: the `ℓ + 1` values
`j(ζ ^ b q ^ a)` for the coset representatives `(a, b)`. -/
def conj (i : Fin (ℓ + 1)) : LaurentSeries K :=
  cosetSubst ζ (cosetA ℓ i) (cosetB ℓ i) (coeffEmb K jq)

theorem conj_zero : conj ℓ ζ (0 : Fin (ℓ + 1)) = qExpand K (ℓ * ℓ) (coeffEmb K jq) := by
  have h1 : conj ℓ ζ (0 : Fin (ℓ + 1)) = cosetSubst ζ ℓ 0 (coeffEmb K jq) :=
    cosetSubst_congr ζ (cosetA_zero ℓ) (cosetB_zero ℓ) (coeffEmb K jq)
  rw [h1, cosetSubst, RingHom.comp_apply, mul_zero, pow_zero, qTwist_one_apply]

theorem conj_succ (b : Fin ℓ) : conj ℓ ζ b.succ = qTwist (ζ ^ (b : ℕ)) (coeffEmb K jq) := by
  have h1 : conj ℓ ζ b.succ = cosetSubst ζ 1 ((b : ℕ)) (coeffEmb K jq) :=
    cosetSubst_congr ζ (cosetA_succ ℓ b) (cosetB_succ ℓ b) (coeffEmb K jq)
  rw [h1, cosetSubst, RingHom.comp_apply,
    qExpand_congr (show 1 * 1 = 1 by norm_num), qExpand_one_apply, one_mul]

end ConjugateFamily

section Product

variable {K : Type*} [Field K] (ℓ : ℕ)

/-- The product `∏_i (Y - conj i)`, the polynomial whose roots are the
conjugates of `jq`. -/
def phiProd (conj : Fin (ℓ + 1) → LaurentSeries K) : Polynomial (LaurentSeries K) :=
  ∏ i : Fin (ℓ + 1), (Polynomial.X - Polynomial.C (conj i))

theorem phiProd_monic (conj : Fin (ℓ + 1) → LaurentSeries K) : (phiProd ℓ conj).Monic :=
  monic_prod_of_monic _ _ fun i _ => monic_X_sub_C (conj i)

theorem phiProd_natDegree (conj : Fin (ℓ + 1) → LaurentSeries K) :
    (phiProd ℓ conj).natDegree = ℓ + 1 := by
  rw [phiProd, natDegree_prod_of_monic _ _ fun i _ => monic_X_sub_C _]
  simp

theorem phiProd_ne_zero (conj : Fin (ℓ + 1) → LaurentSeries K) : phiProd ℓ conj ≠ 0 :=
  (phiProd_monic ℓ conj).ne_zero

theorem phiProd_eval_conj (conj : Fin (ℓ + 1) → LaurentSeries K) (i : Fin (ℓ + 1)) :
    (phiProd ℓ conj).eval (conj i) = 0 := by
  rw [phiProd, Polynomial.eval_prod]
  exact Finset.prod_eq_zero (Finset.mem_univ i) (by simp)

end Product

section PoleDefs

variable {K : Type*} [Field K]

/-- The `K`-coefficient version of `PoleOrderLE`. -/
def TPoleOrderLE (f : LaurentSeries K) (n : ℕ) : Prop :=
  ∀ m : ℤ, m < -(n : ℤ) → f.coeff m = 0

theorem tPoleOrderLE_iff_poleOrderLE (f : LaurentSeries ℚ) (n : ℕ) :
    TPoleOrderLE f n ↔ PoleOrderLE f n :=
  Iff.rfl

variable (J : LaurentSeries K)

/-- `J` has at most a simple pole at `q = 0`. -/
def JSimplePole : Prop := ∀ m : ℤ, m < -1 → J.coeff m = 0

end PoleDefs

section TPoleOrderLEBlock

/-! ## The shared `TPoleOrderLE` prelude

FLT repeats the following block across **six** developments (the `phiProd_conj`
development — itself shipped twice — and all five copies of the 328-line
`PhiGenDescends` block), physically in **twelve** `S_` files. The port writes it
once here, public. **T11 (the 328 block and the assembly) imports it from this
file**, and T10's pole bounds
(`FLTForHuman/ModularCurve/PhiGenPoleBounds.lean`) does too. The statements are
FLT's verbatim; where the pin keeps a declaration `private` (or exposes it only
through its `p2m_export` alias), the port still promotes it, because a later
module has to name it. -/

theorem TPoleOrderLE.mono {K : Type*} [Field K] {f : LaurentSeries K} {m n : ℕ}
    (hf : TPoleOrderLE f m) (hmn : m ≤ n) : TPoleOrderLE f n :=
  fun k hk => hf k (by omega)

theorem tPoleOrderLE_zero {K : Type*} [Field K] (n : ℕ) :
    TPoleOrderLE (0 : LaurentSeries K) n :=
  fun _ _ => rfl

theorem tPoleOrderLE_one {K : Type*} [Field K] :
    TPoleOrderLE (1 : LaurentSeries K) 0 := by
  intro m hm
  rw [HahnSeries.coeff_one, ite_eq_right (by omega)]

theorem TPoleOrderLE.neg {K : Type*} [Field K] {f : LaurentSeries K} {n : ℕ}
    (hf : TPoleOrderLE f n) : TPoleOrderLE (-f) n := by
  intro m hm
  rw [HahnSeries.coeff_neg, hf m hm, neg_zero]

theorem TPoleOrderLE.add {K : Type*} [Field K] {f g : LaurentSeries K} {n : ℕ}
    (hf : TPoleOrderLE f n) (hg : TPoleOrderLE g n) : TPoleOrderLE (f + g) n := by
  intro m hm
  rw [HahnSeries.coeff_add, hf m hm, hg m hm, add_zero]

theorem TPoleOrderLE.mul {K : Type*} [Field K] {f g : LaurentSeries K} {m n : ℕ}
    (hf : TPoleOrderLE f m) (hg : TPoleOrderLE g n) : TPoleOrderLE (f * g) (m + n) := by
  intro k hk
  rw [HahnSeries.coeff_mul]
  refine Finset.sum_eq_zero fun ij hij => ?_
  obtain ⟨-, -, hsum⟩ := Finset.mem_antidiagonal.mp hij
  by_cases hi : ij.1 < -(m : ℤ)
  · rw [hf ij.1 hi, zero_mul]
  · refine mul_eq_zero_of_right _ (hg ij.2 ?_)
    push_cast at hk
    omega

theorem TPoleOrderLE.qTwist {K : Type*} [Field K] {f : LaurentSeries K} {n : ℕ}
    (hf : TPoleOrderLE f n) (u : Kˣ) : TPoleOrderLE (qTwist u f) n := by
  intro m hm
  rw [qTwist_coeff, hf m hm, mul_zero]

theorem TPoleOrderLE.qExpand {K : Type*} [Field K] {f : LaurentSeries K} {n : ℕ}
    (hf : TPoleOrderLE f n) (N : ℕ) [NeZero N] :
    TPoleOrderLE (qExpand K N f) (N * n) := by
  intro m hm
  by_cases hdvd : (N : ℤ) ∣ m
  · obtain ⟨c, rfl⟩ := hdvd
    rw [qExpand_coeff_mul]
    refine hf c ?_
    have hN : 0 < (N : ℤ) := by exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne N)
    push_cast at hm
    nlinarith
  · exact qExpand_coeff_of_not_dvd N f hdvd

theorem tPoleOrderLE_of_jSimplePole {K : Type*} [Field K] (J : LaurentSeries K)
    (hJ : JSimplePole J) : TPoleOrderLE J 1 := by
  intro m hm
  exact hJ m (by push_cast at hm; omega)

private theorem coeff_coeffEmb_jq_of_lt {K : Type*} [Field K] [Algebra ℚ K] {k : ℤ}
    (hk : k < -1) : (coeffEmb K jq).coeff k = 0 := by
  rw [coeffEmb_coeff, coeff_jq_of_lt hk, map_zero]

theorem jSimplePole_jqK {K : Type*} [Field K] [Algebra ℚ K] :
    JSimplePole (coeffEmb K jq) :=
  fun _ hm => coeff_coeffEmb_jq_of_lt hm

theorem tPoleOrderLE_coeffEmb_iff {K : Type*} [Field K] [Algebra ℚ K]
    (f : LaurentSeries ℚ) (n : ℕ) :
    TPoleOrderLE (coeffEmb K f) n ↔ TPoleOrderLE f n := by
  constructor
  · intro h m hm
    have h0 := h m hm
    rw [coeffEmb_coeff] at h0
    exact FaithfulSMul.algebraMap_injective ℚ K (by rw [h0, map_zero])
  · intro h m hm
    rw [coeffEmb_coeff, h m hm, map_zero]

theorem tPoleOrderLE_of_qExpand {K : Type*} [Field K] {f : LaurentSeries K} {N n : ℕ}
    [NeZero N] (h : TPoleOrderLE (qExpand K N f) (N * n)) : TPoleOrderLE f n := by
  intro m hm
  rw [← qExpand_coeff_mul N f m]
  refine h _ ?_
  push_cast
  have hN : 0 < (N : ℤ) := by exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne N)
  nlinarith

/-- The pole bound of the `i`-th conjugate: `ℓ ^ 2` at `i = 0`, else `1`. -/
def conjPoleBound (ℓ : ℕ) : Fin (ℓ + 1) → ℕ :=
  fun i => if i = 0 then ℓ * ℓ else 1

theorem conjPoleBound_zero (ℓ : ℕ) : conjPoleBound ℓ 0 = ℓ * ℓ := ite_eq_left rfl

theorem conjPoleBound_succ (ℓ : ℕ) (b : Fin ℓ) : conjPoleBound ℓ b.succ = 1 :=
  ite_eq_right (Fin.succ_ne_zero b)

theorem sum_conjPoleBound (ℓ : ℕ) :
    ∑ i : Fin (ℓ + 1), conjPoleBound ℓ i = ℓ * ℓ + ℓ := by
  rw [Fin.sum_univ_succ, conjPoleBound_zero]
  congr 1
  simp only [conjPoleBound_succ]
  simp

theorem tPoleOrderLE_conj_zero {K : Type*} [Field K] {ℓ : ℕ}
    [hℓ : Fact (Nat.Prime ℓ)] {J : LaurentSeries K}
    {conj : Fin (ℓ + 1) → LaurentSeries K} (hconj0 : conj 0 = qExpand K (ℓ * ℓ) J)
    (hJ : JSimplePole J) : TPoleOrderLE (conj 0) (ℓ * ℓ) := by
  rw [hconj0]
  have h := (tPoleOrderLE_of_jSimplePole J hJ).qExpand (ℓ * ℓ)
  simpa using h

theorem tPoleOrderLE_conj_succ {K : Type*} [Field K] {ℓ : ℕ} {ζ : Kˣ}
    {J : LaurentSeries K} {conj : Fin (ℓ + 1) → LaurentSeries K}
    (hconjS : ∀ b : Fin ℓ, conj b.succ = qTwist (ζ ^ (b : ℕ)) J)
    (hJ : JSimplePole J) (b : Fin ℓ) : TPoleOrderLE (conj b.succ) 1 := by
  rw [hconjS b]
  exact (tPoleOrderLE_of_jSimplePole J hJ).qTwist _

theorem tPoleOrderLE_conj {K : Type*} [Field K] {ℓ : ℕ} [hℓ : Fact (Nat.Prime ℓ)]
    {ζ : Kˣ} {J : LaurentSeries K} {conj : Fin (ℓ + 1) → LaurentSeries K}
    (hconj0 : conj 0 = qExpand K (ℓ * ℓ) J)
    (hconjS : ∀ b : Fin ℓ, conj b.succ = qTwist (ζ ^ (b : ℕ)) J)
    (hJ : JSimplePole J) (i : Fin (ℓ + 1)) :
    TPoleOrderLE (conj i) (conjPoleBound ℓ i) := by
  rcases Fin.eq_zero_or_eq_succ i with rfl | ⟨b, rfl⟩
  · rw [conjPoleBound_zero]
    exact tPoleOrderLE_conj_zero hconj0 hJ
  · rw [conjPoleBound_succ]
    exact tPoleOrderLE_conj_succ hconjS hJ b

theorem tPoleOrderLE_coeff_X_sub_C {K : Type*} [Field K] {a : LaurentSeries K}
    {n : ℕ} (ha : TPoleOrderLE a n) (k : ℕ) :
    TPoleOrderLE ((Polynomial.X - Polynomial.C a).coeff k) n := by
  match k with
  | 0 =>
    simp only [Polynomial.coeff_sub, Polynomial.coeff_X_zero, Polynomial.coeff_C_zero,
      zero_sub]
    exact ha.neg
  | 1 =>
    simp only [Polynomial.coeff_sub, Polynomial.coeff_X_one, Polynomial.coeff_C,
      ite_eq_right (one_ne_zero), sub_zero]
    exact tPoleOrderLE_one.mono (Nat.zero_le _)
  | (k + 2) =>
    simp only [Polynomial.coeff_sub, Polynomial.coeff_X, Polynomial.coeff_C]
    rw [ite_eq_right (by omega), ite_eq_right (by omega), sub_zero]
    exact tPoleOrderLE_zero _

private theorem phiProd_def {K : Type*} [Field K] (ℓ : ℕ)
    (conj : Fin (ℓ + 1) → LaurentSeries K) :
    phiProd ℓ conj = ∏ i : Fin (ℓ + 1), (Polynomial.X - Polynomial.C (conj i)) := rfl

theorem tPoleOrderLE_coeff_mul {K : Type*} [Field K] {p q : Polynomial (LaurentSeries K)}
    {m n : ℕ} (hp : ∀ k, TPoleOrderLE (p.coeff k) m) (hq : ∀ k, TPoleOrderLE (q.coeff k) n)
    (k : ℕ) : TPoleOrderLE ((p * q).coeff k) (m + n) := by
  rw [Polynomial.coeff_mul]
  intro a ha
  rw [HahnSeries.coeff_sum]
  exact Finset.sum_eq_zero fun ij _ => (hp ij.1).mul (hq ij.2) a ha

theorem tPoleOrderLE_coeff_prod {K : Type*} [Field K] {ι : Type*} (s : Finset ι)
    (p : ι → Polynomial (LaurentSeries K)) (n : ι → ℕ)
    (hp : ∀ i ∈ s, ∀ k, TPoleOrderLE ((p i).coeff k) (n i)) :
    ∀ k, TPoleOrderLE ((∏ i ∈ s, p i).coeff k) (∑ i ∈ s, n i) := by
  induction s using Finset.cons_induction with
  | empty =>
    intro k
    simp only [Finset.prod_empty, Finset.sum_empty]
    rcases Nat.eq_zero_or_pos k with rfl | hk
    · simpa using tPoleOrderLE_one
    · rw [Polynomial.coeff_one, ite_eq_right (by omega)]
      exact tPoleOrderLE_zero 0
  | cons a s ha ih =>
    intro k
    rw [Finset.prod_cons, Finset.sum_cons]
    exact tPoleOrderLE_coeff_mul (hp a (Finset.mem_cons_self a s))
      (ih fun i hi k => hp i (Finset.mem_cons_of_mem hi) k) k

theorem tPoleOrderLE_phiProd_coeff {K : Type*} [Field K] (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)]
    (ζ : Kˣ) (J : LaurentSeries K) (conj : Fin (ℓ + 1) → LaurentSeries K)
    (hconj0 : conj 0 = qExpand K (ℓ * ℓ) J)
    (hconjS : ∀ b : Fin ℓ, conj b.succ = qTwist (ζ ^ (b : ℕ)) J)
    (hJ : JSimplePole J) (k : ℕ) :
    TPoleOrderLE ((phiProd ℓ conj).coeff k) (ℓ * ℓ + ℓ) := by
  rw [phiProd_def, ← sum_conjPoleBound ℓ]
  exact tPoleOrderLE_coeff_prod Finset.univ _ (conjPoleBound ℓ)
    (fun i _ k => tPoleOrderLE_coeff_X_sub_C (tPoleOrderLE_conj hconj0 hconjS hJ i) k) k

end TPoleOrderLEBlock

/-- `f` has integer coefficients, as rationals. -/
def IntCoeffs (f : LaurentSeries ℚ) : Prop :=
  ∀ m : ℤ, ∃ z : ℤ, f.coeff m = (z : ℚ)

section Descends

variable {K : Type*} [Field K] [Algebra ℚ K] (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] (ζ : Kˣ)

/-- `phiProd` descends to `ℚ`: its coefficients are the `coeffEmb` images of the
series `c k` after the `ℓ`-substitution. -/
def PhiGenDescends (c : ℕ → LaurentSeries ℚ) : Prop :=
  ∀ k : ℕ, (phiProd ℓ (conj ℓ ζ)).coeff k = coeffEmb K (qExpand ℚ ℓ (c k))

end Descends

end PhiGen

end ModularCurve

end
