/-
  Layer 0a — the target statement's definition, and the one case it can prove.

  `FunctionFieldGeneration M` says that for every `d ∣ M`, the `q ^ d`-substitute
  `j(q ^ d)` lies in `ℚ(j(q), j(q ^ M))`. That is the content of the capstone
  `ModularCurve.functionFieldGeneration`; here it is only *stated*, as a `def`,
  together with its degenerate case `M = 1`, which 0a proves outright.

  FLT provenance, pinned `aa2d8b3`:
  `Definitions/Def_ModularCurve_X0.lean` lines 233–242.
  https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b3/Definitions/Def_ModularCurve_X0.lean

  `IntermediateField` is mathlib's; the two names below are FLT's, verbatim.
  Assumes `qExpand` from `FLTForHuman.ModularCurve.Defs.Laurent` and `jq` from
  `FLTForHuman.ModularCurve.Defs.Jq`; it mentions nothing from Layer 0b, which is why the
  target is statable already.
-/
import FLTForHuman.ModularCurve.Defs.Jq

set_option autoImplicit false

noncomputable section

open HahnSeries IntermediateField

namespace ModularCurve

/-- The theorem's content, as a `def`: for every divisor `d` of `M`, the
substitution `j(q ^ d)` lies in the field generated by `j(q)` and `j(q ^ M)`
over `ℚ`. -/
def FunctionFieldGeneration (M : ℕ) [NeZero M] : Prop :=
  ∀ d : ℕ, d ∣ M → ∀ (_ : NeZero d), qExpand ℚ d jq ∈
    IntermediateField.adjoin ℚ {jq, qExpand ℚ M jq}

/-- The `M = 1` case: the only divisor is `1`, and `j(q)` generates
`ℚ(j(q))`. -/
theorem functionFieldGeneration_one : FunctionFieldGeneration 1 := by
  intro d hd _
  rw [Nat.dvd_one] at hd
  subst hd
  exact subset_adjoin ℚ _ (Set.mem_insert_of_mem _ rfl)

end ModularCurve

end
